### ISSUE TITLE
Mono assert while deallocating and exiting app

### ISSUE THREAD

**Issue by captainjono** [xamarin/xamarin-macios#10019]
I am attempting to run [CEF](http://opensource.spotify.com/cefbuilds/index.html#macosx64:83) in [Xamarin mac via Chromely](https://github.com/captainjono/Chromely/) and CefGlue. 

### Steps to Reproduce

1. Clone [repo](https://github.com/captainjono/Chromely/tree/xammac-fix-shutdown)
2. Open `Chromely.XamMac/Chromely.XamMac.sln`
3. Build `DemoApp`. 
4. Run it, and after 5 seconds it will exit. _Observe the log messages._ 

### Expected Behavior

Finishes execution with with the `"Exiting gracefully"` log message

### Actual Behavior
* `"CEF ShutdownCallback ended"` message observed 

followed by (occasionally)

``` * Assertion at /Users/builder/jenkins/workspace/archive-mono/2020-02/mac/release/mono/metadata/exception.c:162, condition is_ok (error)' not met, function:mono_exception_from_token, Unknown type token 73000000```

the OS reports

<img src=https://raw.githubusercontent.com/captainjono/Chromely/xammac-fix-shutdown/crash1.PNG>

### Environment

* Statistically, the app crashes on exit 30-50% of the time on my test machines. Different failure rates on different hardware with different levels of GC pressure. 

### Build Logs

* Look at the checkin history of the main [xammac](https://github.com/captainjono/Chromely/tree/xammac) / [xammac-fix-shutdown](https://github.com/captainjono/Chromely/tree/xammac-fix-shutdown) branches for details all the components used and why.
* Details of my debugging process and the nature of the bindings can be found in the [linked issue](https://github.com/captainjono/Chromely/issues/1#issuecomment-720553218). 

This app is potentially going too over 100k+ in the coming months... This issue is blocking the release and threatening to derail the project. I have been debugging various shutdown issues over the last 6+weeks now, and have fixed multiple issues... but this one persists! 

Any help on diagnosing the failure, guidance on debugging, is appreciated. I had not used macos much before this project and I am basically poking around in the dark with log-statements and reading as much as i can about all the systems to comphrehend what needs to be done and when to satisfy the deallocation process.

**Comment by chamons** [comment]
Hmm, it looks like you are hitting this:

https://github.com/mono/mono/blob/master/mono/metadata/exception.c#L162

But I'm rather sure that's a red herring, we're just trying to look up information on a crash that already occurred and failing. 

One way to sometimes get additional information is to enable [AOT](https://docs.microsoft.com/en-us/xamarin/mac/internals/aot), which I did and then ran in LLDB.

I first saw this:

```
[1103/121745.949259:FATAL:shutdown_checker.cc(52)] Check failed: !IsCefShutdown(). Object reference incorrectly held at CefShutdown
Process 2745 stopped
```

and this is the backtrace:

https://gist.github.com/chamons/fa7e9e2c3107e8d61daaedd885704110

The most interesting part to me is:

```
    frame #9: 0x000000011bfb8f6a Chromely.CefGlue.dll.dylib`Xilium_CefGlue_CefRuntime_Shutdown + 106
    frame #10: 0x000000011be56801 Chromely.dll.dylib`Chromely_Native_MacCocoaHost_QuitCallback(this=0x0000000106c867d0) + 49
    frame #11: 0x000000011e4d32b3
    frame #12: 0x00000001330e73a4 libchromely.dylib`-[RootWindowDelegate cleanup] + 228
    frame #13: 0x00000001330e72a6 libchromely.dylib`-[RootWindowDelegate windowShouldClose:] + 118
    frame #14: 0x00007fff2fe33d51 AppKit`__19-[NSWindow __close]_block_invoke + 181
    frame #15: 0x00007fff2fe33c8f AppKit`-[NSWindow __close] + 292
    frame #16: 0x00007fff2fcaf7a7 AppKit`-[NSApplication(NSResponder) sendAction:to:from:] + 299
    frame #17: 0x00007fff2fcaf642 AppKit`-[NSControl sendAction:to:] + 86
    frame #18: 0x00007fff2fcaf574 AppKit`__26-[NSCell _sendActionFrom:]_block_invo
```

We close the window, that calls RootWindowDelegate cleanup, which tries to call a quit callback and that invokes this from what I can tell:

```
        public static void Shutdown()
        {
            if (!_initialized) return;

            GC.Collect(GC.MaxGeneration, GCCollectionMode.Forced);
            GC.WaitForPendingFinalizers();

            libcef.shutdown();  // HERE
        }
```

and inside libcef.shutdown (that p/invoke) we die, or shortly after.

We don't have debug symbols for libcef, so I can only make guesses here:

It seems like a common CEF integration problem of crashing due to on shutdown.

- https://stackoverflow.com/questions/38716266/cef-crash-when-app-exit-qt5cef3-2526
- https://magpcss.org/ceforum/viewtopic.php?f=6&t=17525

I strongly suspect you have some chrome object with a lifetime later than shutdown, which matches the chrome assertion I saw:

```
[1103/121745.949259:FATAL:shutdown_checker.cc(52)] Check failed: !IsCefShutdown(). Object reference incorrectly held at CefShutdown
```

You could try getting a debug version of CEF, setting a breakpoint inside shutdown_checker.cc and seeing what object is triggering that check, then walking back to figure out who implemented it (and what part of your app isn't cleaning it up before calling shutdown).

It turns out that marrying the lifetime of native objects with garbage collected ones is really difficult. While I appreciate the difficulty of integrating CEF, I do not believe this is a Xamarin.Mac bug at this time. 

You are welcome to join the [.NET community discord](https://aka.ms/dotnet-discord) and see others might have insights as well. Though at this point I suspect it'll just be debugging the native API you are attempting to bind to figure out your lifetime issues.
