### ISSUE TITLE
xCode continuously crashes when connected to PC as build host

### ISSUE THREAD

**Issue by gitKRM** [xamarin/xamarin-macios#10052]
### Description
as per above, xCode continuously crashes when connected to a PC as a build host.

### Steps to Reproduce

1. Connect PC to mac over wifi to use the mac as a build host --> on the mac turn on VS and xCode.
2. xCode crashes generally after a few minutes -- This can be bit of a pain as if not noticed, an app being built will take a very long time before the build fails.

### Expected Behavior
To use a stable tool for iOS app development

### Actual Behavior
a lot of fire fighting and time wasted not developing

### Basic Information

- Version with issue:
VS for mac version 8.7.8 & xCode 12.1
mac OS version 10.15.7
[xCode crash log.txt](https://github.com/xamarin/Xamarin.Forms/files/5490691/xCode.crash.log.txt)

- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by chamons** [comment]
Thanks for the feedback.

The crash is in a private framework inside Xcode, so I don't believe this is due to a Xamarin bug. We shouldn't be able to crash CoreSimulator. You may want to contact Apple for assistance, but a few thing you can consider doing first include:

- Run the [Apple Hardware Diagnostics](https://support.apple.com/en-us/HT202731) to make sure there isn't an issue with the specific macOS build host.
- If you happen to have access to more that one machine, try swapping macOS machine to see if there is an issue.
- If you are running any 3rd party security software such as antivirus, consider disabling it and seeing if you can reproduce the issue with it disabled.
