### ISSUE TITLE
[Bug] Invalid Service Error (error: 0xe8000022).

### ISSUE THREAD

**Issue by solomonfried** [xamarin/xamarin-macios#10075]
### Description

Trying to Debug my app on an iPad I get the following error

Error		error MT1007: Failed to launch the application '/Users/solomonfried/Library/Caches/Xamarin/mtbs/builds/Classtars.iOS/c98d0a0aeae...4f29/bin/iPhone/Debug/device-builds/ipad6.11-14.2/Classtars.iOS.app' on the device 'My???s iPad': Failed to launch the application 'com.pnqsys.classtars' on the device 'My???s iPad': Invalid Service Error (error: 0xe8000022). You can still launch the application manually by tapping on it.		 	0	

I have tried everything that used to resolve this issue in the past.
My Mac has the latest XCode. (12.1)
On my mac I removed the ~/Library/Developer/Xcode/DerivedData directory
I restarted my iPad and Mac.
Cleaned the project on VS2019 (Windows)

I am at a loss.
Any suggestions would be appreciated.

### Steps to Reproduce

1.  Try to debug the app

### Expected Behavior

App should start in Debug on iPad

### Actual Behavior

App Terminates, but I can start the app on the iPad by starting it manually. Though there is no debug session.

### Basic Information

- Version with issue: Xamarin 4.8.0.1560
- Last known good version:
- IDE: VS2019 Version 16.7.7
- Platform Target Frameworks: 
  - iOS:  14.2

**Comment by jgold6** [comment]
I believe this issue is do to XCode 12.1 not supporting iOS devices updated to iOS 14.2. 

I am downloading and testing the RC for XCode 12.2 to see if it fixes this issue. I will report my findings when done.

See this SO thread for more info: https://stackoverflow.com/questions/64736953/iphone-is-not-available-please-reconnect-the-device-ios-14-2-xcode-12-1

**Comment by spouliot** [comment]
> You can still launch the application manually by tapping on it.

@jgold6 you're right.

In order to start an application on device it needs to be loaded with a developer disk image. Those are OS version spefici and ships with Xcode.

So if you have a 14.2 device and Xcode 12.1 (shipping only the 14.1 image) then we cannot load it (and neither can Xcode). In such case we fall back to asking the developer to start the application manually. Once started the debugging session will work normally (we don't need the image for nothing else).

> I was able to deploy to an iOS 14.2 device even using XCode 12.1.

Yes, that will work if that device has been used with Xcode 12.2. The image would have been loaded into memory and the previous Xcode (or Xamarin SDK) will be able to use it.

It might stop to work if something unloads the developer disk image... we don't do that but updating the OS (or maybe just a reboot) will do that.

**Comment by FlxGen** [comment]
It would be nice if VS could tell us this instead of a the cryptic message we currently receive.
