### ISSUE TITLE
List`1[T].get_Item (System.Int32 index) SIGABRT: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by amy-perelberg-self** [xamarin/xamarin-macios#10096]
### Steps to Reproduce

1. Seems to happen when View is updated with StackLayout.Children.Clear and StackLayout.Children.Add
2. 
3. 

### Expected Behavior
The app doesn't crash

### Actual Behavior
The app crashes

### Environment
Visual Studio 2019 Windows
Xamarin.Forms latest version

```
```

### Build Logs

List`1[T].get_Item (System.Int32 index)
SIGABRT: Index was outside the bounds of the array.
Launched at
Nov 15, 12:35 PM
Country
N/A
Device
iPhone XR
Network
N/A
Crashed after
4m 8s
Language
English
OS
iOS 13.5.1
User ID
N/A
Main thread
List`1[T].get_Item (System.Int32 index)
Collection`1[T].get_Item (System.Int32 index)
ReadOnlyCollection`1[T].get_Item (System.Int32 index)
Element+<Descendants>d__88.MoveNext ()
Enumerable+<OfTypeIterator>d__32`1[TResult].MoveNext ()
EnumerableExtensions.ForEach[T] (System.Collections.Generic.IEnumerable`1[T] enumeration, System.Action`1[T] action)
ToolbarTracker.UntrackTarget (Xamarin.Forms.Page page)
ToolbarTracker.set_Target (Xamarin.Forms.Page value)
NavigationRenderer+ParentingViewController.Dispose (System.Boolean disposing)
NSObject.Dispose ()
NavigationRenderer.OnPopViewAsync (Xamarin.Forms.Page page, System.Boolean animated)
INavigationPageController.RemoveAsyncInner (Xamarin.Forms.Page page, System.Boolean animated, System.Boolean fast)
NavigationPage.PopAsyncInner (System.Boolean animated, System.Boolean fast)
NavigationPage.PopAsync (System.Boolean animated)
ContentPageEx.PopAsync (System.Boolean animated, System.Int32 levels)
DisplayListingView.<AssignControlEvents>b__45_0 ()
AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state)
NSAsyncSynchronizationContextDispatcher.Apply ()
(wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate)
UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName)
Application.Main (System.String[] args)

**Comment by tj-devel709** [comment]
Thank you for your feedback!

Some more information about your issue would help us figure out what is going wrong. If you could include your project so that we could try to reproduce this issue on our end, that would be very helpful. Also providing full build logs and version information would also help pinpoint the issue.

To get full build logs just set the log verbosity to diagnostic at the following locations:

- On Visual Studio for Windows: Tools > Options > Projects and Solutions > Build and Run

On Visual Studio for Windows you also want to add `-v -v -v -v` to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting `Properties`.

The easiest way to get exact version information:

- On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.

Then copy/paste the version information (you can use the "Copy Information" button).

We look forward to hearing from you!

**Comment by rolfbjarne** [comment]
We have not received the requested information.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!
