### ISSUE TITLE
Xamarin binding C library params not working (variadic functions)

### ISSUE THREAD

**Issue by Toine-db** [xamarin/xamarin-macios#10285]
Binding a C library with variadic functions on the emulator works easily, but on an arm64 device only with some strange trickery. The issue is that C functions with … (variadic functions) do not pass values correctly from C# to the library.

### Steps to Reproduce

1. Create a iOS .a library binding project
2. Reference an .a library with a variadic function : meaning the ...(3 dots) at the end
`cmd_ln_init(cmd_ln_t *inout_cmdln, const arg_t *defn, int32 strict, ...)
 {`
3. Use binding expressions in the binding project like: (
` [DllImport("__Internal")]
 public static extern unsafe cmd_ln_t* cmd_ln_init(cmd_ln_t* inout_cmdln, arg_t* defn, int strict, string arg1, string arg2);`
4. Use this from a Xamarin.iOS project and run on an Emulator > this works good
5. Use this from a Xamarin.iOS project and run on a real device > this doesnt work

### Expected Behavior
Xamarin.iOS binding project must work the same as on an emulator.

### Actual Behavior
Now the variadic function (parameter) needs a lot of 'null' prefixes to get all values from the Xamarin.iOS project to the .a library

### Environment
VS2019 community for MAC (8.8.1, build 37)
Xamarin.iOS 14.6.0.15
xcode 12.2
real device: iPhone 6s
emulator: iPhone 12 Pro Max (and many others)

### Detailed explanation
This is the C function I work with

```
cmd_ln_t *
cmd_ln_init(cmd_ln_t *inout_cmdln, const arg_t *defn, int32 strict, ...)
{
va_list args;
const char *arg, *val;
char **f_argv;
int32 f_argc;

va_start(args, strict);
f_argc = 0;
while ((arg = va_arg(args, const char *))) {
    ++f_argc;
    E_INFO("name: %s   ", arg);
    E_INFO(" retrieving value...");
    val = va_arg(args, const char*);
    E_INFO("value retrieved. \n");
    E_INFO("value: %s \n", val);
    if (val == NULL) {
        E_ERROR("Number of arguments must be even!\n");
        return NULL;
    }
    ++f_argc;
}
va_end(args);
```

FYI: E_INFO() is used to show incomming values in the .a library

**Approach 1 - The default PARAMS doesn't work:**

When I use the following default params expression approuch for c bindings, the ‘arg’ printed in the function shows unknown characters and when ‘val’ is used the function crashes.

```
[DllImport("__Internal")] public static extern unsafe cmd_ln_t*
cmd_ln_init(cmd_ln_t* inout_cmdln, arg_t* defn, int strict, params string[] arguments);
```

**Approach 2 - a more elaborate approach works:**

When I use the a more elaborate approach everything works, on x86_64 architecture normally but for arm64 with a strange work-around. the binding expression in a more elaborate approach.

```
        [DllImport("__Internal")]
        public static extern unsafe cmd_ln_t* cmd_ln_init(cmd_ln_t* inout_cmdln, arg_t* defn, int strict, string arg1, string arg2);

        [DllImport("__Internal")]
        public static extern unsafe cmd_ln_t* cmd_ln_init(cmd_ln_t* inout_cmdln, arg_t* defn, int strict, string arg1, string arg2, string arg3);

        [DllImport("__Internal")]
        public static extern unsafe cmd_ln_t* cmd_ln_init(cmd_ln_t* inout_cmdln, arg_t* defn, int strict, string arg1, string arg2, string arg3, string arg4);
        //etc etc… for x numbers of arguments
```
The binding works works the following code

            // works for x86_64
            var cmdPointer = MyBindingLib.cmd_ln_init(null, psArgsPointer, 1,
            "-hmm", hmmFolder,
                "-dict", dictFile,
                "-mmap", "no",
                "-kws_threshold", "1e-80", 
                "-lw", "2.0", 
                null);

            // works for arm64
            var cmdPointer = MyBindingLib.cmd_ln_init(null, psArgsPointer, 1,
                null, null,
                null, null, null,
                "-hmm", hmmFolder,
                "-dict", dictFile,
                "-mmap", "no",
                "-kws_threshold", "1e-80",
                "-lw", "2.0", 
                null);
As you see, the x86_64 works normally to get the values to the C library. But the arm64 version needs to have 5 null values, others half of the values won't make it to the C library (I can check that with the E_INFO function in the C function).

Anyone any idea how to get this Xamarin C binding correct with params or without the 5 prefix null values?

Source is on [github ](https://github.com/Toine-db/pocketsphinx-xamarin-ios-demo/tree/sharpie-tryout) uses c library at [sphinxbase](https://github.com/cmusphinx/sphinxbase)

**Comment by rolfbjarne** [comment]
This isn't a bug in Xamarin.iOS, it's a difference in the C calling convention between x86_64 and ARM64.

This P/Invoke:

```csharp
[DllImport("__Internal")]
public static extern unsafe cmd_ln_t* cmd_ln_init(cmd_ln_t* inout_cmdln, arg_t* defn, int strict, string arg1, string arg2);
```

would work for this C function:

```c
cmd_ln_t *cmd_ln_init (cmd_ln_t* inout_cmdln, arg_t* defn, int strict, const char *arg1, const char *arg2);
```

which is *not* the same as a variadic function. However, due to how variadic functions are implemented in C, it turns out it works the same on all architectures except on ARM64.

Briefly explained (but you should read arms' document about the ARM64 calling convention (https://developer.arm.com/documentation/ihi0055/b/), and then also Apple's changes to it (https://developer.apple.com/library/ios/documentation/Xcode/Conceptual/iPhoneOSABIReference/Articles/ARM64FunctionCallingConventions.html):

* For a non-variadic function, the 8 first arguments are passed in registers, and the rest on the stack.
* For a variadic function, only non-variadic arguments are passed in registers (up to 8); any variadic arguments are always passed on the stack.

The end result is that if you want to create a P/Invoke that passes variadic arguments that works on ARM64, you'll have to pass the variadic arguments as the 9th+ arguments.

**Comment by Toine-db** [comment]
Thanks, this makes sense.
Great to have an explanation.

**Comment by rolfbjarne** [comment]
@Toine-db the correct solution would be to implement support for `__arglist` on ARM64 (http://community.bartdesmet.net/blogs/bart/archive/2006/09/28/4473.aspx), but that's quite difficult and a lot of work to complete (and difficult to use properly as well), and since the workaround is quite simple, this hasn't been prioritized (but we know about it).

**Comment by Toine-db** [comment]
@rolfbjarne 
Thanks, using the fillup method for the first 8 arguments works good enough for me.
I will just try to detect arm64 runtimes and invoke the method different in that case.
