### ISSUE TITLE
actionSheetAlert.PopoverPresentationController returns null

### ISSUE THREAD

**Issue by hungnguyenepiserver** [xamarin/xamarin-macios#10329]
1. Create an UIAlertController but display as Popover Menu on iPad follow xamarin doc:
https://docs.microsoft.com/en-us/xamarin/ios/user-interface/controls/alerts
2.  actionSheetAlert.PopoverPresentationController return null

### Expected Behavior
actionSheetAlert.PopoverPresentationController not null
### Actual Behavior
actionSheetAlert.PopoverPresentationController is null

### Environment
Xamarin 7.0
Build on Emulator any iPad ios 14.3

### Example Project (If Possible)
https://github.com/xamarin/docs-archive/blob/master/Recipes/ios/standard_controls/alertcontroller/AlertControllerSample/AlertControllerSampleViewController.cs

**Comment by tj-devel709** [comment]
Hello! Thank you very much for your feedback.

It appears that UIActionSheet has been deprecated since iOS 8. 
Try using UIAlertController which has replaced UIAlertController. You can find the documentation [here](https://docs.microsoft.com/en-us/dotnet/api/uikit.uialertcontroller?view=xamarin-ios-sdk-12#remarks).

If this does not work for you, feel free to reopen this issue. Thank you!

**Comment by hungnguyenepiserver** [comment]
> Hello! Thank you very much for your feedback.
> 
> It appears that UIActionSheet has been deprecated since iOS 8.
> Try using UIAlertController which has replaced UIAlertController. You can find the documentation [here](https://docs.microsoft.com/en-us/dotnet/api/uikit.uialertcontroller?view=xamarin-ios-sdk-12#remarks).
> 
> If this does not work for you, feel free to reopen this issue. Thank you!

Hello TJ,
I've edited the description for more detail. I'm using UIAlertController as your comment but the UIPopoverPresentationController .PopoverPresentationController  from is null
