### ISSUE TITLE
UIApplicationDelegate.ReceiveMemoryWarning throws You_Should_Not_Call_base_In_This_Method which is not obvious

### ISSUE THREAD

**Issue by thisisthekap** [xamarin/xamarin-macios#10454]
### Steps to Reproduce

1. Go to UIApplicationDelegate.ReceiveMemoryWarning
![image](https://user-images.githubusercontent.com/9071974/104905041-1f426e80-5982-11eb-9d88-3c2266e4c68e.png)
2. The implementation is empty
3. When the method is called, `You_Should_Not_Call_base_In_This_Method` is thrown at runtime

### Expected Behavior

The `You_Should_Not_Call_base_In_This_Method`, which is thrown during runtime is shown in the decompiler.

### Actual Behavior

The Implementation of `UIApplicationDelegate.ReceiveMemoryWarning` is empty.

**Comment by spouliot** [comment]
What's happening is that VSfM has a loaded the **reference** assembly for `Xamarin.iOS.dll`. Reference assemblies are "empty" of any code (no implementation) and VS disassembler won't display any code (since there's no IL).

Reference assemblies are useful at build-time. In this case there are different versions for 32bits and 64bits OS, something that the IDE does not known. Both references assemblies are identical (which is why it's used at build time) but the code inside each differs (e..g different ABI, some API will throw if not available...).

Either (or both) version(s) of the assembly will be used at runtime, depending on which architectures are supported by your application.

You can load still the complete (w/IL) version of `Xamarin.iOS.dll`. For example, to load the 64bits version of the assembly do:

```bash
open /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/64bits/
```

and drag  the`Xamarin.iOS.dll` file into VSfM.

This will load the 64bits version of `Xamarin.iOS.dll` and, when you select `ReceiveMemoryWarning `, it will show the decompiled source.

```csharp
using Foundation;
using ObjCRuntime;

[Export ("applicationDidReceiveMemoryWarning:")]
[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
public virtual void ReceiveMemoryWarning (UIApplication application)
{
	throw new You_Should_Not_Call_base_In_This_Method ();
}
```

**Comment by thisisthekap** [comment]
@spouliot Ok, understand the reason, thanks for clarification.

To my opinion, adding You_Should_Not_Call_base_In_This_Method to the reference assembly would be very much appreciated for documentation purpose.
