### ISSUE TITLE
Consider using (generated) UTF8 for selectors

### ISSUE THREAD

**Issue by spouliot** [xamarin/xamarin-macios#10462]
Once upon a time there was some experimental work to have UFT8 strings into .net...

Now we have [source generators](https://github.com/ufcpp/StringLiteralGenerator) that provide a similar service.

Our own binding generator predates the new source generator but they share a lot and we could do the same (or similar) as the one linked above. IOW generating bindings for

`[Export ("selectorWithOne:andTwo:")]`

could output an UTF8 field (or local variable), which would reduce the size (if/when we can get away with the `[Export]`) and remove the need for unicode to uft8 conversion when p/invoking.

Bunch of measurements needed...

**Comment by jonathanpeppers** [comment]
The Android/Java version of this one is filed here: https://github.com/xamarin/java.interop/issues/950

**Comment by akoeplinger** [comment]
Note that C#11 will add UTF8 literals so that could reduce the need for a source generator:  https://github.com/dotnet/csharplang/blob/main/proposals/csharp-11.0/utf8-string-literals.md

**Comment by stephen-hawley** [comment]
It turns out that this will not especially help for a couple of reasons:
1. The AOT compiler special cases calls to `GetSelector` and there is absolutely no run-time conversion being done. I did some measurements and a million invocations to `GetSelector` takes 6 milliseconds total. That's effectively 0 on a call per call bases. Without the special casing, if you work with a byte array with UTF8, 1M invocations takes 120 milliseconds, which is small on a per call basis, but it's still 20 times slower. Of course the same optimization could be done with UTF8 arrays, but it won't make and improvement in performance. At the same time, it will degrade readability of the code until a point when UFT8 literals are available.
2. In terms of savings in the dll version of the assembly, we get nothing. This is because the initializers for the `ExportAttribute` are already in UTF8 or something similar. Here's an example from the compiled code:
```
.custom instance void [mscorlib]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 )
.custom instance void Foundation.ExportAttribute::.ctor(string) = ( 01 00 23 64 69 73 6D 69 73 73 4E 6F 74 69 66 69   // ..#dismissNotifi
                                                                        63 61 74 69 6F 6E 43 6F 6E 74 65 6E 74 45 78 74   // cationContentExt
                                                                        65 6E 73 69 6F 6E 00 00 )
```
There are no interspersed 0's so this is clearly not UTF16 and that sure looks like something akin to ASCII.

The only difference at this point is the runtime memory space. We can investigate that. But we can also calculate the theoretical gain for doing this. In Xamarin.Mac, there are 50,882 attributes. Assuming roughly 48 bytes (20 characters + 8 bytes overhead for the pointer to the string) for a typical string, the memory use is 2.42M. If we kept the string initializer and used a byte array to store it, assuming roughly 28 bytes, the memory use is 1.42M.

So the savings is roughly 1M. That's not nothing, but it's not a huge win. It's about the same as a single 400x200 32 bit image.

**Comment by spouliot** [comment]
Good points! I definitively did not check them when I wrote the issue :-)

However not all platforms use the mono full-AOT compiler, e.g. net6.0-macos uses CoreCLR and this optimization does (or did) not exist (at least not for AOT which state is rather unknown in this case).

Did you get numbers for net6.0-macos ? If not then this might still be quite helpful for macOS applications (which includes VSfM).

Finally the optimization was (still is?) disabled for tvOS and/or watchOS. That's worth checking too at least for tvOS :)

**Comment by stephen-hawley** [comment]
For some reason GitHub cut this off: of course marshaling UTF16 strings will be O(n) where n is the string size. The cost doesn't start to show until the string gets > 70 characters. Up until then, the overhead dwarfs the conversion.

**Comment by jonathanpeppers** [comment]
Can you put the above code sample in a [BenchmarkDotNet](https://benchmarkdotnet.org/articles/overview.html) project? That would make the comparison testable in both Mono & CoreCLR. It also does the math & measuring in a much smarter way, that I would even know how to do.

**Comment by rolfbjarne** [comment]
> A difference of 22 milliseconds over 1M iterations is effectively nothing.

That would mean this kind of optimization is quite useless:

https://github.com/xamarin/xamarin-macios/blob/599ae5a931d0d2d0c06e8a7e222acd39e1852be2/src/Foundation/NSObject2.cs#L686-L690

(it's also be counter-productive if we ever implemented an AOT compiler for macOS with the GetHandle optimization)

**Comment by stephen-hawley** [comment]
@jonathanpeppers - I was unable to get a mono run, but I did get a CoreClr run. I tested using a typical selector and a longer selector than we'll ever see.
The tl;dr is that the results more or less match up to what I saw - about 20ns difference per call for a typical string and a 24ns difference per call for a string longer than we'll ever see.

Here's the results:
``` ini

BenchmarkDotNet=v0.13.2, OS=macOS Monterey 12.6 (21G115) [Darwin 21.6.0]
Intel Core i9-9880H CPU 2.30GHz, 1 CPU, 16 logical and 8 physical cores
.NET SDK=6.0.401
  [Host]     : .NET 6.0.9 (6.0.922.41905), X64 RyuJIT AVX2
  Job-LMCWND : .NET 6.0.9 (6.0.922.41905), X64 RyuJIT AVX2

Runtime=.NET 6.0  

```
|           Method |      Mean |     Error |    StdDev |
|----------------- |----------:|----------:|----------:|
| TypicalByteArray |  9.254 ns | 0.1707 ns | 0.2097 ns |
|    LongByteArray |  9.219 ns | 0.1567 ns | 0.1466 ns |
|    TypicalString | 29.060 ns | 0.5774 ns | 0.5119 ns |
|       LongString | 33.074 ns | 0.5672 ns | 0.5305 ns |
