### ISSUE TITLE
Mono.framework MDK is missing. Please install the MDK for your Mono.framework

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-macios#10652]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Monoframework-MDK-is-missing-Please-in/1340478)._

---
After Update VS4Mac 8.8.9 and Mono to 6.12.0.122 
Xamarin.Mac is failing to build the application with the error 

/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/bin/mmp @/Users/viniciusjarina/projects/test_mac/test_mac/obj/Debug/response-file.rsp 
    MMP : error MM5202: Mono.framework MDK is missing. Please install the MDK for your Mono.framework version from https://www.mono-project.com/download/

Steps to repro:

- Create a new Xamarin.Mac, try to build.

---
### Original Comments
(no comments)

---
### Original Solutions
(no solutions)

**Comment by rolfbjarne** [comment]
This is because Mono stopped shipping `libmonosgen-2.0.a`.

Workaround: install the previous version of Mono ([monoframework-mdk-6.12.0.113.macos10.xamarin.universal.pkg](https://download.visualstudio.microsoft.com/download/pr/98cec39a-ed8a-4d97-971d-48beb00aafb3/e3b4355c6b24db604c655ccdb3daf083/monoframework-mdk-6.12.0.113.macos10.xamarin.universal.pkg))

**Comment by rolfbjarne** [comment]
Due to a bug in Xamarin.Mac, this seems to affect every project, not only those using the system mono. This other bug is already fixed in the xcode12.5/d16-9 branches, but not in the xcode12.4 branch (PR: https://github.com/xamarin/xamarin-macios/pull/10653), which is where the current stable version is coming from.

**Comment by filipnavara** [comment]
FWIW, the second bug is fixed in the already shipped preview, so switching to the Preview channel is also an option.

**Comment by dalexsoto** [comment]
This should be fixed in the latest stable release [Xamarin.Mac 7.4.0.10](https://bosstoragemirror.blob.core.windows.net/wrench/xcode12.4/a4c70e7d04e3904d17aa60f6d640eb048081c757/4477741/package/notarized/xamarin.mac-7.4.0.10.pkg)

**Comment by nor0x** [comment]
hi all 👋 
i have to bring attention to this issue again - i'm running into this issue in an Azure Pipeline. It seems that 7.4.0.10 isn't on the hosted agents yet?

**Comment by Butternubs** [comment]
> hi all 👋
> i have to bring attention to this issue again - i'm running into this issue in an Azure Pipeline. It seems that 7.4.0.10 isn't on the hosted agents yet?

Can also confirm I'm also getting this via an Azure pipeline now. This  didn't occur yesterday evening (23/02/21), and only started occurring this morning (24/02/21).

**Comment by nor0x** [comment]
@Butternubs  here is the workaround i'm using right now:

```
curl -o xamarinmac.pkg 'https://bosstoragemirror.blob.core.windows.net/wrench/xcode12.4/a4c70e7d04e3904d17aa60f6d640eb048081c757/4477741/package/notarized/xamarin.mac-7.4.0.10.pkg'

sudo installer -pkg xamarinmac.pkg -target /
```

just add a bash script step with this code to your pipeline agent - and it should work as a temporary workaround until this is fixed in the agent image.
what this script does is actually just downloading and installing this version of Xamarin.Mac 

> This should be fixed in the latest stable release [Xamarin.Mac 7.4.0.10](https://bosstoragemirror.blob.core.windows.net/wrench/xcode12.4/a4c70e7d04e3904d17aa60f6d640eb048081c757/4477741/package/notarized/xamarin.mac-7.4.0.10.pkg)

**Comment by Butternubs** [comment]
> @Butternubs here is the workaround i'm using right now:
> 
> ```
> curl -o xamarinmac.pkg 'https://bosstoragemirror.blob.core.windows.net/wrench/xcode12.4/a4c70e7d04e3904d17aa60f6d640eb048081c757/4477741/package/notarized/xamarin.mac-7.4.0.10.pkg'
> 
> sudo installer -pkg xamarinmac.pkg -target /
> ```
> 
> just add a bash script step with this code to your pipeline agent - and it should work as a temporary workaround until this is fixed in the agent image.
> what this script does is actually just downloading and installing this version of Xamarin.Mac
> 
> > This should be fixed in the latest stable release [Xamarin.Mac 7.4.0.10](https://bosstoragemirror.blob.core.windows.net/wrench/xcode12.4/a4c70e7d04e3904d17aa60f6d640eb048081c757/4477741/package/notarized/xamarin.mac-7.4.0.10.pkg)

Beautiful - that has worked and we can get builds out again. Thank you nor0x. Hopefully they fix the issue soon!
