### ISSUE TITLE
Add OpenTK-1.0.dll to OpenTK nuget

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#10736]
Xamarin.Android is going to ship a NuGet with their OpenTK assembly for .NET.

We might want to add our OpenTK assembly to the same NuGet.

Ref: https://github.com/mono/opentk/pull/26

**Comment by rolfbjarne** [comment]
CC @dellis1972

**Comment by leonluc-dev** [comment]
I'm currently experimenting with migrating my current Xamarin.iOS projects to .NET 6.
I'm encountering the following error whenever I try to use a Xamarin.iOS NuGet package that depends on the OpenTK-1.0 assembly, since it was removed in .NET 6
`CS0012	The type 'Color' is defined in an assembly that is not referenced. You must add a reference to assembly 'OpenTK-1.0, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065`

Should the assembly be added to the NuGet package, would that solve this issue as well?

**Comment by rolfbjarne** [comment]
Due to #13087, we've decided that we're not going to do this.
