### ISSUE TITLE
Rejected App due to HealthKit (HealthKit is not referenced)

### ISSUE THREAD

**Issue by srinivas56** [xamarin/xamarin-macios#10735]
The problem is that most of the solutions suggest to link framework SDK's only which would in fact solve the issue. However, my app crashes with this linker behaviour. Therefore, I have to use the "Don't Link" behaviour.

I have used additional mtouch arguments **--linkskip=HealthKit** and **--xml=_File.xml_**, but I could still see HealthKit Functionalities when checked with
strings <> | grep Health,

```
<?xml version="1.0" encoding="UTF-8" ?>
 <linker>
     <assembly fullname="Xamarin.iOS">
         <type fullname="HealthKit" preserve="none"/>
     </assembly>
 </linker>
```

and even in the simple Sample application, without even referencing any HealthKit, all the HealthKit functionalities has been linked, I have attached the same sample application and screenshot as well. Kindly provide any solution for this issue ASAP, as my iOS app is getting delayed.
.
.

<img width="451" alt="Screenshot 2021-02-20 at 5 10 03 PM" src="https://user-images.githubusercontent.com/74173137/109288396-d0260e00-784a-11eb-8ea6-42d1838251ad.png">

[Sample 2.zip](https://github.com/xamarin/xamarin-macios/files/6048963/Sample.2.zip)

**Comment by rolfbjarne** [comment]
The solution is to use `Link SDK`, and if that doesn't work, then you need to figure out why and fix that.

`Don't link` will not link anything away, and this includes all the binding code for HealthKit in Xamarin.iOS.dll.

Creating a linker xml file and setting `preserve="none"` won't work, because linker xml files can only be used to make the managed linker keep code, not make it remove code.

`--linkskip=HealthKit` won't work, because the `---linkskip` argument takes the name of an assembly the linker should not remove code from (so you're asking the linker to keep `HealthKit.dll` - and there's no such assembly, nor is it the behavior you want).

However, you might be able to use `--linkskip=...` to make Link SDK work: try passing different `--linkskip=SDKAssembly1 --linksdkip=SdkAssembly2 ...` to figure out which assembly/assemblies must not be linked for your app to keep working.
