### ISSUE TITLE
Rejected App due to HealthKit (HealthKit is not referenced)

### ISSUE THREAD

**Issue by srinivas56** [xamarin/xamarin-macios#10743]
The problem is that most of the solutions suggest to link framework SDK's only which would in fact solve the issue. However, my app crashes with this linker behaviour. Therefore, I have to use the "Don't Link" behaviour.

I have used additional mtouch arguments --linkskip=HealthKit and --xml=File.xml, but I could still see HealthKit Functionalities when checked with
strings <> | grep Health,

```
<?xml version="1.0" encoding="UTF-8" ?>
 <linker>
     <assembly fullname="Xamarin.iOS">
         <type fullname="HealthKit" preserve="none"/>
     </assembly>
 </linker>
```

and even in the simple Sample application, without even referencing any HealthKit, all the HealthKit functionalities has been linked, I have attached the same sample application and screenshot as well. Kindly provide any solution for this issue ASAP, as my iOS app is getting delayed.
.
.

<img width="451" alt="Screenshot 2021-02-20 at 5 10 03 PM" src="https://user-images.githubusercontent.com/74173137/109457530-0d73e100-7a81-11eb-9132-4139ca45805b.png">
[Sample 2.zip](https://github.com/xamarin/xamarin-macios/files/6059410/Sample.2.zip)

**Comment by srinivas56** [comment]
@rolfbjarne : --linkskip=HealthKit won't work, because the ---linkskip argument takes the name of an assembly **the linker should not remove code** from (so you're asking the linker to keep HealthKit.dll - and there's no such assembly, nor is it the behavior you want).

However, you might be able to use --linkskip=... to make Link SDK work: try passing different --linkskip=SDKAssembly1 --linksdkip=SdkAssembly2 ... to figure out which **assembly/assemblies must not be linked** for your app to keep working.

These two statements of yours are contradicting to each other, kindly please check this issue.

**Comment by rolfbjarne** [comment]
> @rolfbjarne : --linkskip=HealthKit won't work, because the ---linkskip argument takes the name of an assembly **the linker should not remove code** from (so you're asking the linker to keep HealthKit.dll - and there's no such assembly, nor is it the behavior you want).
> 
> However, you might be able to use --linkskip=... to make Link SDK work: try passing different --linkskip=SDKAssembly1 --linksdkip=SdkAssembly2 ... to figure out which **assembly/assemblies must not be linked** for your app to keep working.
> 
> These two statements of yours are contradicting to each other, kindly please check this issue.

You say this:

> The problem is that most of the solutions suggest to link framework SDK's only which would in fact solve the issue. However, my app crashes with this linker behaviour.

"Link Framework SDKs" will link all framework assemblies, and that causes problems for you. However, it's reasonable to assume that _some_ framework SDK assemblies can still be linked without making your app crash. The problem is then to figure out which assemblies you can and which assemblies you can't link, and that's what you can use `--linkskip` for: enable "Link Framework SDKs only", and then try different `--linkskip=...` arguments until your app starts working again. At that point your app should also pass Apple's HealthKit check [1].

[1]: As long as you didn't have to `--linkskip=Xamarin.iOS`, because that would prevent the linker from removing any of the HealthKit support code, which is in the Xamarin.iOS.dll assembly.

**Comment by mandel-macaque** [comment]
We have not received the requested information.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!
