### ISSUE TITLE
SetupBlock is not optimised to SetupBlockImpl

### ISSUE THREAD

**Issue by tipa** [xamarin/xamarin-macios#10770]
### Steps to Reproduce

1. Set `Linker behavior` to `Link All`
2. Execute `OverrideSetText` (see code example)

```
[DllImport("/usr/lib/libobjc.dylib")] static extern IntPtr class_getInstanceMethod(IntPtr classHandle, IntPtr Selector);
[DllImport("/usr/lib/libobjc.dylib")] static extern OriginalDelegate method_setImplementation(IntPtr method, IntPtr imp);
[DllImport("/usr/lib/libobjc.dylib")] static extern IntPtr imp_implementationWithBlock(ref BlockLiteral block);

static OriginalDelegate original_setText_impl;
static IntPtr setTextSelectorHandle = new Selector("setText:").Handle;
delegate void CaptureDelegate(IntPtr block, IntPtr self, IntPtr paramOne);

[MonoNativeFunctionWrapper]
public delegate void OriginalDelegate(IntPtr one, IntPtr selector, IntPtr three);

[BindingImpl(BindingImplOptions.Optimizable)]
public static void OverrideSetText()
{
     var originalMethod = class_getInstanceMethod(Class.GetHandle(nameof(UILabel)), setTextSelectorHandle);
     var block_value = new BlockLiteral();
     CaptureDelegate d = NewSetText;
     block_value.SetupBlock(d, null);
     var impl = imp_implementationWithBlock(ref block_value);
     original_setText_impl = method_setImplementation(originalMethod, impl);
}

[MonoPInvokeCallback(typeof(CaptureDelegate))]
static void NewSetText(IntPtr block, IntPtr self, IntPtr stringParam)
{
    original_setText_impl(self, setTextSelectorHandle, stringParam);
}
```

### Expected Behavior
App does not crash

### Actual Behavior
App crashes at `SetupBlock` with `BlockLiteral.SetupBlock is not supported when the dynamic registrar has been linked away.`

The exception can be prevented by passing `--optimize=-blockliteral-setupblock` to mtouch/mmp but I'd like to keep that optimization enabled as it can `speed up calling a block by a factor of 10 to 15`  as noted [here](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/macios/optimizations.md#optimize-calls-to-blockliteralsetupblock). Or are all the `SetupBlock` calls in Xamarin.iOS already optimised (= replaced with SetupBlockImpl) so disabling that optimisation would only impact that single `SetupBlock` call in my code?

The docs also mentions that:
`This optimization requires the linker to be enabled, and is only applied to methods with the [BindingImpl (BindingImplOptions.Optimizable)] attribute.`
As you can see in my code snippet, I added that attribute however the method call isn't optimised - why?

### Environment
```
=== Visual Studio Community 2019 for Mac ===

Version 8.9 (build 1651)
Installation UUID: c377b96c-535d-442b-bb76-8a03d414adf3
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000122

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.122 (2020-02/c621c35ffa0) (64-bit)
	Package version: 612000122

=== Roslyn (Language Service) ===

3.9.0-5.21112.8+f3ff04378c972d435826e6181de364b3c0db8d14

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: Not installed
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: Not installed

=== .NET Core 3.1 SDK ===

SDK: Not installed

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.4 (17801)
Build 12D4e

=== Xamarin.Mac ===

Version: 7.8.2.5 (Visual Studio Community)
Hash: 3836759d4
Branch: d16-9
Build date: 2021-02-10 17:56:43-0500

=== Xamarin.iOS ===

Version: 14.14.2.5 (Visual Studio Community)
Hash: 3836759d4
Branch: d16-9
Build date: 2021-02-10 17:56:44-0500

=== Xamarin Designer ===

Version: 16.9.0.316
Hash: bd2705417
Branch: remotes/origin/d16-9
Build date: 2021-02-24 00:16:08 UTC

=== Xamarin.Android ===

Not Installed

=== Microsoft OpenJDK for Mobile ===

Java SDK: Not Found

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.9.0.22
Hash: a391de2
Branch: remotes/origin/d16-9
Build date: 2021-02-18 03:14:56 UTC

=== Android Device Manager ===

Version: 16.9.0.17
Hash: fc2b3db
Branch: remotes/origin/d16-9
Build date: 2021-02-18 03:15:18 UTC

=== Build Information ===

Release ID: 809001651
Git revision: c05b1dec4362b5956d47624a437e900ffdc9aa0a
Build date: 2021-02-25 11:27:51-05
Build branch: release-8.9
Xamarin extensions: c05b1dec4362b5956d47624a437e900ffdc9aa0a

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.3.0 Darwin Kernel Version 20.3.0
    Thu Jan 21 00:06:51 PST 2021
    root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 x86_64

```

**Comment by mandel-macaque** [comment]
Does look like an issue. Do you have a full sample to look into it further?

**Comment by tipa** [comment]
Friendly ping @mandel-macaque :)

**Comment by spouliot** [comment]
> Or are all the SetupBlock calls in Xamarin.iOS already optimised (= replaced with SetupBlockImpl) so disabling that optimisation would only impact that single SetupBlock call in my code?

No, the code is not optimized by default as it would require the static registrar to be build (each time). That runtime optimization can be quite costly (at build time) as it also requires the linker to run. 

In most use cases the simulator is, without linking, the fastest way to edit/deploy/run(debug) your code. In order for that too remain true we do not force the managed linker to run and we do not re-create a new static registrar for each build.

> As you can see in my code snippet, I added that attribute however the method call isn't optimised - why?

The linker has several code optimization steps. Many of them are not general purpose optimizations. They are meant to optimize very specific code pattern, ones that are, usually [1], generated.

To avoid breaking normal user code those special optimization are only applied to code "known to be safe" to optimize. This is the goal of `[BindingImpl(BindingImplOptions.Optimizable)]`, it tells the optimizers that the method can be optimized.

IOW adding `[BindingImpl(BindingImplOptions.Optimizable)]` means you, as the author, are vouching that the code **is** optimizable. It does **not** mean _please optimize this code_. 

What happens if it's misused ? then
* it won't be optimized (best case) or 
* it will fail to build (not so bad) or
* it will crash at runtime (worse case)

If you cannot use the generator for your code then your best _bet_ is to copy-paste similar generated code. Keep in mind that this might break in the future. Example: the generated code might have to change and the optimizer will be updated to match (and so would your _now manually written_ code need to be updated too).

[1] if not `bgen`-generated code then **great** care must be used to ensure the code is optimizable. That responsibility is on the code's author (not the optimizer).

**Comment by tipa** [comment]
Thanks for the explanation @spouliot.
I must admit that I am still in the process of learning how all this optimizing and calling native APIs works.
Coming back to my initial question, what would you recommend to prevent the crash?
Would I need to use `--optimize=-blockliteral-setupblock` and just accept the additional performance costs that it introduces?
Or is there another way to prevent the crash from happening when using `Link All`?

**Comment by spouliot** [comment]
> Coming back to my initial question, what would you recommend to prevent the crash?

Method Swizzling is fun but evil. It's not hard to do (work) but it's very hard to get it right (so it will keep working).

I strongly suggest not depending on swizzling for apps you intend to release. It's only a matter of time before things breaks up and future-you will be angry with past-you.

If you really want to do method swizzling then you either:

* avoid using our runtime code for doing it: that will allow our optimization to continue working;
* you disable our optimizations (and you pray the next Xcode/OS update does not break your app).

**Comment by tipa** [comment]
Thanks for the recommendation. Even though it would have been cool to let my users choose a custom font for the whole app, I will not implement it and hope for Apple to offer a native option to do so in the future.
