### ISSUE TITLE
Mtouch errors

### ISSUE THREAD

**Issue by rahul3m** [xamarin/xamarin-macios#11067]
### Steps to Reproduce

1. Add scanbot.xamarin 2.0.4 package 
2. Build Xamarin IOS

### Expected Behavior

Smooth Build

### Actual Behavior

**/iOnHealing.iOS/MTOUCH: Error MT2101: Can't resolve the reference 'System.IntPtr ObjCRuntime.NativeObjectExtensions::GetHandle(ObjCRuntime.INativeObject)', referenced from the method 'System.Void ScanbotSDK.iOS.SBSDKBaseCameraViewController::.ctor(UIKit.UIViewController,UIKit.UIView,ScanbotSDK.iOS.dooFeature)' in 'Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'. (MT2101) (iOnHealing2.iOS)

### Environment

```
```

**Comment by mandel-macaque** [comment]
Hello,
 
Can you please add more information, like full build logs, versions and a small sample product.  Also add a pointer to scanbot.xamarin  since I do not know what that is.

To get full build logs just set the log verbosity to diagnostic at the following locations:

- On Visual Studio for Mac: Preferences > Projects > Build
- On Visual Studio for Windows: Tools > Options > Projects and Solutions > Build and Run

On Visual Studio for Windows you also want to add `-v -v -v -v` to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting `Properties`.

Note: this is done automatically on Visual Studio for Mac when the log verbosity is set to diagnostic.

The easiest way to get exact version information:

- On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
- On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.

Then copy/paste the version information (you can use the "Copy Information" button).

**Comment by spouliot** [comment]
We have not received the requested information.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!

**Comment by spouliot** [comment]
No replies, closing
