### ISSUE TITLE
[maccatalyst] UICollectionViewSource is missing methods

### ISSUE THREAD

**Issue by jeromelaban** [xamarin/xamarin-macios#11236]
### Description

The following methods are present in `xamarinios10` and `net6.0-ios` but are not present in `net6.0-maccatalyst`:
- `UICollectionViewSource.Scolled`
- `UICollectionViewSource.DraggingStarted`
- `UICollectionViewSource.DraggingEnded`
- `UICollectionViewSource.DidZoom`
- `UICollectionViewSource.WillEndDragging`
- `UICollectionViewSource.DecelerationEnded`
- `UICollectionViewSource.ScrollAnimationEmded`

### Environment

`6.0.100-preview.3.21202.5`

**Comment by spouliot** [comment]
Keep in mind that MacCatalyst support, even for the current (soon legacy) SDK is a preview and incomplete. YMMV.

The API surface for iOS and Catalyst are not totally identical. We're trying to solve this by shipping a `Xamarin.iOS.dll` along with `Xamarin.MacCatalyst.dll`.

This _special_ `Xamarin.iOS.dll` contains:
* type forwarders to `Xamarin.MacCatalyst.dll` when an API is available on Catalyst;
* empty stubs that will throw a `PlatformNotSupportedException` for other, non available, API

The above trick was not generating a perfect/total coverage for P3 (it was incomplete at P3 release time).
This _should_ be accurate for P4 (or it will be a bug in our tooling).

Note that we're still missing some API annotations for Catalyst so it's still possible something will throw (while it should be supported) or crash (because it should be throwing). However it should _build_ fine when `Xamarin.iOS.dll` is used.

Now if you're referencing `Xamarin.MacCatalyst.dll` directly then some missing (or incorrect) annotations might be excluding some API. We have tools to report those errors - but there's quite a backlog to process until completion. If you're blocked by something then feel free to open bugs and we'll prioritize those API (over others) for the next release(s).


Q: What assembly are you referencing ? (any build logs?)

**Comment by jeromelaban** [comment]
Thanks for the very detailed answer! No worries about the preview state, that's to be expected for sure.

I'm not referencing anything specific, aside from `net6.0-maccatalyst`, and looking at the IL disassembly of `UICollectionViewSource` in `Xamarin.MacCatalyst.dll` I see that those members are also effectively missing.

The sources basically doing something like this:

```csharp
public partial class MySource : UICollectionViewSource
{
	public override void Scrolled(UIScrollView scrollView)
	{
		InvokeOnScroll();
	}
}
```

**Comment by spouliot** [comment]
This seems to be because `XAMCORE_3_0` is defined, like tvOS and watchOS. This does remove a few mistakes (on both our and Apple sides) but reduce compatibility in those corner cases.

```
src/Makefile:MACCATALYST_GENERATED_DEFINES= -d:__MACCATALYST__ -d:XAMCORE_3_0 -d:IOS
```

**Comment by spouliot** [comment]
You can see the API in the (just merged) API diff
https://gist.github.com/vs-mobiletools-engineering-service2/3329d5705cffab4bb74f418414111b77
