### ISSUE TITLE
FileProviderReplicatedExtension implementation support for MacOS

### ISSUE THREAD

**Issue by AndirNotes** [xamarin/xamarin-macios#11290]
Hi,

Do you have any plans to support implementation of FileProviderReplicatedExtension for MacOS? (https://developer.apple.com/documentation/fileprovider/nsfileproviderreplicatedextension)
Currently it's possible to implement it with XCode, so would be nice to have support in Xamarin Mac.
Sample Swift implementation: https://github.com/peterthomashorn/macosfileproviderexample 

In the latest release I found only interface FileProvider.INSFileProviderReplicatedExtension that looks a bit awkward and I'm not sure whether it possible to implement it with Xamarin?

![image](https://user-images.githubusercontent.com/1484293/115715107-82c4a980-a380-11eb-973d-63a66b014ab3.png)

**Comment by mandel-macaque** [comment]
We do provide the binding: https://github.com/xamarin/xamarin-macios/blob/main/src/fileprovider.cs#L943 

Is there anything wrong with the current implementation: https://github.com/xamarin/xamarin-macios/blob/main/src/fileprovider.cs#L973 You have to implement the protocol (https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/delegates-protocols-and-events#protocols) and then pass the implementation to the required registration. 

I'm closing because I thing it is not an issue, but please re-open if you think I am wrong (and I can perfectly be :) )

**Comment by AndirNotes** [comment]
Great! Thank you for the kicking me in the proper direction. Yep with those interface definitions and proper registration I was able to implement it successfully (at least a prototype).
