### ISSUE TITLE
xamarin ipa size increased from Xamarin.iOS 14.14

### ISSUE THREAD

**Issue by anish1984** [xamarin/xamarin-macios#11574]
iOS mobile app is developed using xamarin native. We are building mobile app using GitHub actions, msbuild command and executing on latest macOS runner. We have observed ipa size of development and enterprise build increased from Xamarin.iOS 14.14. iOS app for submission to the App Store is almost 10 MB less in size than development and enterprise build.

Prior to this xamarin.ios version development and enterprise build was almost 10 mb less.

Is there any changes in latest xamarin SDK which increase ipa size?

**Comment by spouliot** [comment]
> iOS app for submission to the App Store is almost 10 MB less in size than development and enterprise build.

That's not clear. It sounds like it's a decrease.

> Is there any changes in latest xamarin SDK which increase ipa size?

No. There are always little changes between releases. Huge ones (like 10MB) are generally due to different options being used (linker, debug, architectures...) for builds and/or updates to 3rd party libraries.

Things to try:

1. The compare both `.app` sizes, not the compressed `.ipa`. You can add a single, incompressible file to your `.app` and get a very different `.ipa` size. However it has no impact on the final `.app` size deployed to your end-users iOS devices.

2. Try building your app again with the previous version of XI you were using. That will eliminate code changes (like updates to yours or 3rd party updates) and changes made to your project (options) that could affect the build.

3. Compare your build logs for both old and 14.14. There might be extra (or missing) steps in the build that could explain this.

4. Attach the build logs to this report. We can check for a few things (but we can't try any with building it ourselves).

**Comment by spouliot** [comment]
Close / inactivity

**Comment by rolfbjarne** [comment]
Due to inactivity, we will be closing this issue. Please feel free to re-open this issue if the issue persists. For enhanced visibility, if over 7 days have passed, please open a new issue and link this issue there. Thank you.
