### ISSUE TITLE
[xamarin-ios 14.20.0.1] App icon(Asset Catalogs) issue on archive

### ISSUE THREAD

**Issue by tree1891** [xamarin/xamarin-macios#11722]
Does not package AppIcons.appiconset  in ipa properly.
When distribute on app store, it fails with missing app icon issue

### Steps to Reproduce

1. Archive and Save as ipa

### Actual Behavior

It package default app icon.

### Environment

```
Microsoft Visual Studio Enterprise 2019
Version 16.10.0
VisualStudio.16.Release/16.10.0+31321.278
Microsoft .NET Framework
Version 4.8.04084

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.10.000.228 (d16-10@1c8354c)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.10.0.115 (remotes/origin/c750fbf1bde3c720d077f51640fe197c6dac7cbe@c750fbf1b)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.10.5 (355b57a)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.3.0.1 (d16-10/22fc2b3)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: b4a3858
    Java.Interop: xamarin/java.interop/d16-10@f39db25
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.35.4@85460d3
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0


Xamarin.iOS and Xamarin.Mac SDK   14.20.0.1 (fe0e2c518)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

### Example Project (If Possible)
create new xamarin ios project

**Comment by cschwarz** [comment]
I've the same issue since the update to VS 16.10.0:

ERROR ITMS-90022: "Missing required icon file. The bundle does not contain an app icon for iPhone / iPod Touch of exactly '120x120' pixels, in .png format for iOS versions >= 7.0. To support older versions of iOS, the icon may be required in the bundle outside of an asset catalog. Make sure the Info.plist file includes appropriate entries referencing the file. See https://developer.apple.com/documentation/bundleresources/information_property_list/user_interface"

ERROR ITMS-90023: "Missing required icon file. The bundle does not contain an app icon for iPad of exactly '152x152' pixels, in .png format for iOS versions >= 7.0. To support older operating systems, the icon may be required in the bundle outside of an asset catalog. Make sure the Info.plist file includes appropriate entries referencing the file. See https://developer.apple.com/documentation/bundleresources/information_property_list/user_interface"

ERROR ITMS-90023: "Missing required icon file. The bundle does not contain an app icon for iPad of exactly '76x76' pixels, in .png format for iOS versions >= 7.0. To support older operating systems, the icon may be required in the bundle outside of an asset catalog. Make sure the Info.plist file includes appropriate entries referencing the file. See https://developer.apple.com/documentation/bundleresources/information_property_list/user_interface"

**Comment by spouliot** [comment]
Our own submission tests are working fine. Could you attach the build / archive logs to this issue so we can see what's happening ? thanks!

Also can you try doing the build and archive on the Mac (only) to see if that works for you ?

**Comment by tree1891** [comment]
Sorry, I have reverted to xamarin.ios 14.16.0.5 and vs 2019 16.9.6.

**Comment by spouliot** [comment]
This seems Windows-only (so far) and based on [logs](https://github.com/xamarin/xamarin-macios/issues/11728#issuecomment-850572543) are likely related to SSH issues w/XMA.

**Comment by SKeehnen** [comment]
I think I have a related issue after installing the update to vs 2019 16.10.
After distributing the archive to Apple I get an error message back: "ITMS-90546: Missing Asset Catalog - Your app is missing the asset catalog file". 
The building shows no error and debug works also without problems.

**Comment by spouliot** [comment]
@SKeehnen please provide your version information (like the original description) so we can determine if this is the same issue (or a similar one). Thanks!

**Comment by SKeehnen** [comment]
Sorry I did the same as @tree1891 by removing Visual Studio and install version 16.9.6. 
I did find out that with 16.10 there is no assets.car in the archive, which explains the error I'm getting back from Apple. 16.9.6 works without problems, so I will stay with that version for now.

**Comment by spouliot** [comment]
We received more information about this issue inside issue https://github.com/xamarin/xamarin-macios/issues/11786
I'm closing this issue as a duplicate. If you have more information to share please use the link above.
