### ISSUE TITLE
I have the same problem with VS for windows  16.10.1 and Xcode on Macincloud 14.20.0.1,

### ISSUE THREAD

**Issue by pedromramalho** [xamarin/xamarin-macios#11926]
I have the same problem with VS for windows  16.10.1 and Xcode on Macincloud 14.20.0.1,
How can I publish ? I need it urgently because have a launch. Some one have a soluction?

_Originally posted by @pedromramalho in https://github.com/xamarin/xamarin-macios/issues/11786#issuecomment-857213360_

**Comment by pedromramalho** [comment]
Some know when this bug is resolve? Please, one week without work, is very bad.

**Comment by rolfbjarne** [comment]
@pedromramalho someone answered you here:

https://github.com/xamarin/xamarin-macios/issues/11786#issuecomment-857396572

Also please add any comments [here](https://developercommunity.visualstudio.com/t/Cant-deliver-to-the-appstore-since-last/1436223#T-N1445242) instead, that way it reaches the correct team.
