### ISSUE TITLE
[net6][Catalyst] Uppercase `CFBundleIdentifier` fails to deploy with `The application cannot be opened for an unexpected reason`

### ISSUE THREAD

**Issue by jeromelaban** [xamarin/xamarin-macios#12132]
### Steps to Reproduce

1. Create a net6.0-catalyst project
2. Use an uppercase name in `CFBundleIdentifier`
3. Build and run

### Expected Behavior
The build should fail because of the uppercase name

### Actual Behavior
The app fails to deploy and raises this error:

```
The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10661 "(null)" UserInfo={_LSLine=3762, _LSFunction=_LSOpenStuffCallLocal}
```

### Environment

```
.NET 6 Preview 6, 6.0.100-preview.6.21355.2
```

**Comment by jeromelaban** [comment]
I'm opening this issue just in case, as I'm not sure if it's the reponsibility for .NET to validate this... but it's an annoying gotcha :)

**Comment by rolfbjarne** [comment]
Can you give a specific value that doesn't work? I setting CFBundleIdentifier to `COM.XAMARIN.MONOTOUCHTEST` and that worked just fine.

**Comment by jeromelaban** [comment]
I've tested with `<string>com.microsoft.net6.App151Net6</string>` which failed, and `<string>com.microsoft.net6.app151net6</string>` which did not. But now, it may be completely something else and the name was not the issue...

**Comment by rolfbjarne** [comment]
> ```
> The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10661 "(null)" UserInfo={_LSLine=3762, _LSFunction=_LSOpenStuffCallLocal}
> ```

Error -10661 is kLSExecutableIncorrectFormat: https://www.osstatus.com/search/results?platform=all&framework=all&search=10661, so it doesn't sound like this is a problem with the bundle identifier.

On the other hand it might be a rebuild issue, where we didn't rebuild the app correctly for some reason. In order to track this down, we'll need a binary build log (when building from the command line, add `/bl` to the "dotnet build" command). Also try to launch the executable directly from the command line (it's usually something like `path/to/project/bin/Debug/net6.0-maccatalyst/maccatalyst-x64/myapp.app/Contents/MacOS/myapp`) - and then you'll usually get a better error written to the terminal, or a crash report with more information.

**Comment by spouliot** [comment]
We have not received any further information.

If you are still experiencing this issue please provide all the information inside a new issue.

Thanks!

**Comment by jeromelaban** [comment]
I was not able to confirm it in recent builds. Thanks!
