### ISSUE TITLE
Allow Mmp Release to preserve embedded Pdbs

### ISSUE THREAD

**Issue by KirillOsenkov** [xamarin/xamarin-macios#12263]
When building a macOS app in Release mode, if an assembly used by the app contains embedded .pdbs they will be stripped by Mmp.

Switching to Debug preserves the embedded pdb.

LinkSymbols should not be conflated with EnableDebug:
https://github.com/xamarin/xamarin-macios/blob/ebf6c13bd1e419c20112a4702c10876b21c0ba75/tools/mmp/driver.cs#L1099

This forces VSMac to choose either to ship pdbs so we can have line numbers in crashes and stack traces, or to have optimizations.

@Therzok

**Comment by KirillOsenkov** [comment]
You can view whether a .dll has embedded pdb by using ILSpy or this little tool:
https://github.com/KirillOsenkov/MetadataTools/tree/main/src/Pdb

**Comment by Therzok** [comment]
Probably part of this issue, if not, maybe worth splitting in a different one.

Stripping assemblies shouldn't be tied to `MmpDebug`, especially if `LinkMode=none` is set by the application.

MmpDebug seems to generate the `#DEBUG` define in the native code and also seems to add some more codegen to the application. This seems to be probably what MmpDebug is intended for?

The few things we definitely need is: embedded PDBs, mono_pmip and optimized code.

**Comment by rolfbjarne** [comment]
If you want to bundle symbols for release builds, you can pass `--package-debug-symbols=true` to mmp.

This line:

https://github.com/xamarin/xamarin-macios/blob/ebf6c13bd1e419c20112a4702c10876b21c0ba75/tools/mmp/driver.cs#L1099

means: "update the debug symbols to match the linked code", it does *not* mean "remove the debug symbols."

However, the logic is still incorrect, because it's possible to ship symbols for a release build, and in that case you may end up with broken symbols (if the linker is also enabled).

In fact, mtouch will always link symbols:

https://github.com/xamarin/xamarin-macios/blob/405441f544149677e420c9c0f8a8788f7bcbbeb3/tools/mtouch/Target.mtouch.cs#L505

and that's the safer option (the symbols will never be out of date with regards to the actual code).

Another issue is that the embedded symbols are removed from the assembly, I'll have a look and see what that's happening.
