### ISSUE TITLE
Mac Catalyst failed to code sign after runtime crash

### ISSUE THREAD

**Issue by davidortinau** [xamarin/xamarin-macios#12320]
### Steps to Reproduce

1.  Run the project for catalyst and hit the Grid samples until it crashes. Works from VSM and CLI
2. After crash, rerun/debug without a clean 

### Expected Behavior

Should run again just as before.

### Actual Behavior

Won't code sign. Error:

```
/usr/local/share/dotnet/packs/Microsoft.MacCatalyst.Sdk/15.0.100-preview.7221/tools/msbuild/iOS/Xamarin.iOS.Common.targets(3,3): Error: Failed to codesign 'bin/Debug/net6.0-maccatalyst/maccatalyst-x64/ControlGallery.app': /Users/dmo/work/ControlGallery/src/ControlGallery/bin/Debug/net6.0-maccatalyst/maccatalyst-x64/ControlGallery.app: replacing existing signature
/Users/dmo/work/ControlGallery/src/ControlGallery/bin/Debug/net6.0-maccatalyst/maccatalyst-x64/ControlGallery.app: unsealed contents present in the bundle root
```

### Environment

https://gist.github.com/davidortinau/3a56f5a22cb779f7fd148fac4831bf16

### Build Logs

[msbuild.binlog.zip](https://github.com/xamarin/xamarin-macios/files/6917620/msbuild.binlog.zip)

### Example Project (If Possible)

https://github.com/davidortinau/ControlGallery

**Comment by rolfbjarne** [comment]
This is what happens:

1. Mono will write crash dumps in the current directory: https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/mono/mono/utils/mono-state.c#L302-L322
2. The current directory is by default the root of the app bundle.
3. If there are any files in the root of the app bundle for macOS or Mac Catalyst, 'codesign' will fail ("unsealed contents present in the bundle root").

This leads to the following sequence of events:

1. App developer builds & runs a Mac Catalyst app.
2. The app crashes for some reason.
3. Mono creates a crash dump (in the root directory of the app bundle).
4. The app developer changes something in the project and tries again.
5. The build fails, because 'codesign' fails.

A few ideas how to fix this comes to mind:

1. Make the built .app read-only.
    * Con: This can make rebuilds even more complicated, because we might have to make the .app read-write every time we want to write to it. 
2. Delete any crash dumps before signing the app.
    * Con: This just feels like a hack.
3. Disable crash dumps in Mono (by setting the "MONO_CRASH_NOFILE" environment variable).
    * Con: The developer should be the one in charge whether crash dumps should be created or not.
4. Make Mono add support for a directory where to put crash dumps (for instance an environment variable called `MONO_CRASH_DIRECTORY`), and then we could set it to a temporary directory (`/tmp` for instance).
    * Con: A bit more complex, would involve another team.

I don't particularly like any of these options, but option 2 seems like the simplest and fastest to implement.
