### ISSUE TITLE
ITMS-90338 Non-public API usage - determineAppInstallationAttributionWithCompletionHandler initWithMIDIEntity:dataReadyHandler

### ISSUE THREAD

**Issue by ackava** [xamarin/xamarin-macios#12382]
### Steps to Reproduce

1.  Create new Xamarin Forms App
2.  Set `<MtouchExtraArgs>--registrar:static</MtouchExtraArgs>`, `<MtouchLink>None</MtouchLink>`
2.  Submit to app store

### Expected Behavior
No Error

### Actual Behavior
App Store rejects with following message,
ITMS-90338: Non-public API usage - The app references non-public selectors in XXXXXXXX.iOS: advertisingSection, cancelAction, cancelBannerViewAction, cancelPreroll, currentContentSizeIdentifier, determineAppInstallationAttributionWithCompletionHandler:, firstName, initForInterstitialAd:, initWithAdType:, initWithMIDIEntity:dataReadyHandler:, isActionInProgress, isBannerLoaded, isBannerViewActionInProgress, lastName, lookupAdConversionDetails:, playPrerollAdWithCompletionHandler:, prepareInterstitialAds, preparePrerollAds, presentFromViewController:, presentInView:, requestInterstitialAdPresentation, requiredContentSizeIdentifiers, setAdvertisingSection:, setAlignmentTransform:, setCurrentContentSizeIdentifier:, setOptimizerData:, setRequiredContentSizeIdentifiers:, setSocketFamily:, setWarpTransform:, shouldTestVisibilityAtPoint:, sizeFromBannerContentSizeIdentifier:, temporalAntialiasingEnabled.

If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed.

My App is pretty basic, and same app was updated 30 days back in the past, with exactly same set of nuget packages.

I do not use any of these methods in my app, And I have only referenced `Microsoft.AppCenter.Crashes` package to setup crash logs. But there is no library used which may have anything to do with advertising.

I have following NuGet Packages,

```
    <PackageReference Include="Xamarin.Forms" Version="5.0.0.2083" />
    <PackageReference Include="Xamarin.CommunityToolkit" Version="1.2.0" />
    <PackageReference Include="Microsoft.AppCenter.Analytics">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AppCenter.Crashes">
      <Version>4.3.0</Version>
    </PackageReference>

```

And iOS Platform version is 14.14

As per https://developer.apple.com/documentation/iad

`ADClient` is deprecated so static references in the library results in given error.

Is there  a way to conditionally remove class from linking?

For large apps, `PreserveAttribute` is complex, and Apple can deprecate any API anytime, waiting for new version of Xamarin.iOS will cause delay in deployment.

If there is a script to exclude something from the linked app, it would be of great help.

**Comment by spouliot** [comment]
Please include the full version of every tools you're using. From the issue template

```
1.
Visual Studio: Help > About Microsoft Visual Studio > Copy Info [button]
Visual Studio for Mac: Visual Studio > About Visual Studio > Show Details > Copy Information [button]
2. Paste into the code block below (between ```)
```

> And iOS Platform version is 14.14
> waiting for new version of Xamarin.iOS will cause delay in deployment.

If you're using Xamarin.iOS 14.14 then you are several versions away from the current stable, which is Xamarin.iOS 14.20.

> Apple can deprecate any API anytime,

Yes. There was recently a change where Apple submission process started to reject some old API. Those were removed in a service release of Xamarin.iOS. Using the latest stable would solve this (unless those are very new). We run submission tests every (business) day to spot such policy change from Apple. Unless this one happened over the weekend (or late on Friday) then using the current stable should fix your problem.

> If there is a script to exclude something from the linked app, it would be of great help.

This is not how it works. You can preserve extra code so it's **not** removed, but you cannot exclude any additional code.

_If the linker is enabled_ then it removes what's not required. Removing more code would break your app or make it impossible to AOT it (since the link assemblies would be invalid due to missing references).

However the **high** number of selectors from the original description makes me think you are **not** linking your application. If you are linking then please attach your build logs for further analysis. Thanks!

**Comment by ackava** [comment]
[logs_92.zip](https://github.com/xamarin/xamarin-macios/files/6955342/logs_92.zip)

@spouliot 

I am using AppCenter.ms , and previous build 30 days ago with same NuGet Packages went successfully. I have attached the build of yesterday which failed with given error. However, build and submission goes successfully, but I received an error from Apple and my build was marked as invalid binary.

**Comment by spouliot** [comment]
> I am using AppCenter.ms

You should be able to set the XI version you want to use. From your logs

```
2021-08-08T15:36:32.8365270Z   Xamarin.iOS 14.14.2.5 (d16-9: 3836759d4 using framework: /Applications/Xcode_12.4.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.4.sdk
```

The last time Apple changed its rules was after Xcode 12.4 (and XI 14.14) was released. Please try to re-build/submit with the latest stable.

Sadly the verbosity of the logs does not show any details about the `mtouch` part of the build and I can't tell you if the linker was enabled or not.  Please double-check that your `AppStore` configuration is set to "Link SDK frameworks" (or "Link all).

Not linking your application means a very large executable binary is produced. It's large because it will have the bindings for all of Apple's API - and that makes it much more likely to be affected if/when Apple starts to reject the use of any API.

IOW if you don't link (to remove unused API) and you're not using the latest stable then your app is very likely to be rejected when Apple change their rules (at least the API usage ones).


> and previous build 30 days ago with same NuGet Packages went successfully.

Apple change its rules whenever they want. An older build, that was accepted 30 days, might not be accepted today.


>  submission goes successfully, but I received an error from Apple and my build was marked as invalid binary.

If Apple reject the binary then "submission (to the App Store)" has failed.

**Comment by ackava** [comment]
Same result,

The API specifically mentions `ADClient` class and it's selector which was deprecated but it is still present in `Xamarin.iOS` package. Though it is marked as obsolete, presence of selector in the app is an issue.

https://docs.microsoft.com/en-us/dotnet/api/iad.adclient.determineappinstallationattribution?view=xamarin-ios-sdk-12

This is the API which should not be present in linked app.

I had set linker to Off as we are using JavaScript to call the respective APIs so the binary isn't very large, but including Preserve attribute to very large set of APIs is very time consuming.

**Comment by spouliot** [comment]
> The API specifically mentions ADClient class and it's selector which was deprecated but it is still present in Xamarin.iOS package.

The _managed_ type is still present, because removing it is a binary breaking change. However, in the latest stable release, the selectors (not to be confused with the _managed_ type or methods) are **not** present anymore.

I confirmed that today's test results are positive. Apple rules have not changed over the weekend and, even without linking, using the current (XI 14.20) stable release can be used to submit a non-linked app successfully.

> This is the API which should not be present in linked app.

It won't be include inside a linked application unless the application or 3rd party code have references to the API. The linker can only remove that is **not** used (referenced) by the application.

> I had set linker to Off as we are using JavaScript to call the respective APIs so the binary isn't very large, but including Preserve attribute to very large set of APIs is very time consuming.

It does not have to be time consuming. You can use an XML file to tell the linker to preserve only a subset of API, e.g. by namespace.
https://docs.microsoft.com/en-us/xamarin/cross-platform/deploy-test/linker

If you can't enable the linker then you must update to the latest XI stable (where the symbols are removed).

**Comment by ackava** [comment]
@spouliot 

I have managed to fix this issue by enabling Linking SDK. But there are still issues and we have to manually add classes with Preserve attributes.

Would it be possible to know who is using this particular API? I checked source code of all dependencies such as `Microsoft.AppCenter`, `Xamarin.Essentials` and `Xamarin.CommunityToolkit`, but none of them are referencing this particular selector.

Would it be possible if someone has created a class with same selector name but not for `ADClient`? Would it still give this error?

**Comment by spouliot** [comment]
> Would it be possible to know who is using this particular API?

If you are not linking then `Xamarin.iOS.dll` has all the symbols.

If you're using an older version of the SDK, like `14.14.2.5` which predates the latest Apple changes wrt submissions, then this is the source of your problem.

The solution is to update to a newer SDK (where we have removed the symbols) and/or enable the linker (which will remove unused symbols).

> I have managed to fix this issue by enabling Linking SDK.

Enabling the linker is the best solution. This reduce your app size and allow us to do further optimizations that makes your app faster and require less memory at runtime.

> But there are still issues and we have to manually add classes with Preserve attributes.

It depends on your application and its use of reflection as the linker uses static analysis to determine what is needed at runtime.

When using `Link SDK` we take care that the framework itself can be linked (if dynamic is required internally). However you need to preserve anything else your app (your code and 3rd party) requires.

> Would it be possible if someone has created a class with same selector name but not for ADClient? Would it still give this error?

It's possible but it's very unlikely - even more since your list of selectors is quite long and some of them seems unlikely to be present by coincidence.
