### ISSUE TITLE
net6.0-macos with UseMonoRuntime=false swallow exceptions thrown in UI code

### ISSUE THREAD

**Issue by kdubau** [xamarin/xamarin-macios#12406]
Add a button and throw an exception from a `NSButton` handler in a net6.0-macos project. When you click the button it will crash. Now add `<UseMonoRuntime>false</UseMonoRuntime>` and rebuild. When you click the button it does _not_ crash.

Mono -> crash
CoreCLR -> no crash

### Steps to Reproduce

1. `dotnet new macos`
2.  Add `<UseMonoRuntime>false</UseMonoRuntime>` to the .csproj
2.  Open `ViewController.cs` and add a button to `ViewDidLoad()`
```csharp
var btn = new NSButton(new CGRect((20, 20, 120, 30));
btn.Title = "throw exception";
btn.Activated += (sender, e) => {
	throw new Exception();
};
View.AddSubview(btn);
```

3.  build it 
4.  run it
5.  click the button

### Expected Behavior
Crash

### Actual Behavior
No crash

### Environment

```
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.1.21408.2
 Commit:    db9e71c7f6

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.100-rc.1.21408.2/

Host (useful for support):
  Version: 6.0.0-rc.1.21406.5
  Commit:  58efa4b797
```

**Comment by kdubau** [comment]
This is a breaking change

**Comment by rolfbjarne** [comment]
What happens (with CoreCLR) is this:

* The managed exception is thrown.
* We convert the managed exception to an Objective-C exception, and throw that in native code.
* AppKit handles the Objective-C exception, and ignores it (I haven't found a way to make AppKit do something else).

With Mono it's like this:

* The managed exception is thrown.
* Mono unwinds the stack (including native frames), and doesn't find any managed exception handlers.
* The unhandled managed exception logic is executed, which crashes the process.

CoreCLR doesn't support the same exception unwinding behavior as Mono (unwinding native frames), so that's not an option (this is documented here: https://github.com/xamarin/xamarin-macios/issues/10795, which will be put into the release notes). The options are: convert to an Objective-C exception (the default) or abort the process.

You can choose to abort the process instead by adding the `<MonoBundlingExtraArgs>--marshal-managed-exceptions=abort</MonoBundlingExtraArgs>` property to the csproj.
