### ISSUE TITLE
.NET: Setting MtouchFloat32 (or not) in the project file does nothing

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#12524]
Ref: https://github.com/dotnet/runtime/issues/57689#issuecomment-904431984

We need to replicate this for .NET:

https://github.com/xamarin/xamarin-macios/blob/aad913db8673637150af01b13e76605966b8f14a/msbuild/Xamarin.iOS.Tasks.Core/Tasks/MTouchTaskBase.cs#L169-L172

**Comment by spouliot** [comment]
One of the problem we had with this (and other runtime) options is that they were taken as boolean values, just like the code above. 

That sounded right at the beginning but then the runtime wanted to change the default... but there was no default inside project files because the UI would be a checkbox. This meant we could never knew if a customer opt'ed in (or out) an option because of a specific need (that we would break by not honouring the value) or if what was written in the project file was simply the default value (basically not caring).

Ideally we can avoid that with net6 :), e.g. 

```
if (MtouchFloat32 is present) {
   if (MtouchFloat32.Value)
      args.AddLine ("--aot-options=-O=float32");
   else
      args.AddLine ("--aot-options=-O=-float32");
} else {
   // use the runtime default value, which might change over time
}
```

Of course that works only if the UI does not write the default value back into projects...
