### ISSUE TITLE
Fonts (*.ttf) under the `Resources` folder in an iOS app are not automatically included

### ISSUE THREAD

**Issue by mattleibow** [xamarin/xamarin-macios#12536]
### Steps to Reproduce

1. `dotnet new ios`
2. Copy a set of .ttf files into Resources
3. `dotnet build`
4. Check that the resources were not copied into the resulting .app

### Expected Behavior

Everything under Resources is copied.

### Actual Behavior

Fonts are not copied. I did not test anything else tbh.

### Environment

```
dotnet 6.0.100-rc.1.21418.8
ios 15.0.100-rc.1.516
```

### Build Logs

[msbuild.binlog.zip](https://github.com/xamarin/xamarin-macios/files/7042625/msbuild.binlog.zip)

### Example Project (If Possible)

[TestFontsNet6.zip](https://github.com/xamarin/xamarin-macios/files/7042622/TestFontsNet6.zip)

**Comment by filipnavara** [comment]
Copying my response from the other issue:

> Everything under Resources is copied.

That was not [specified](https://github.com/xamarin/xamarin-macios/blob/main/dotnet/DefaultCompilationIncludes.md) to happen or [implemented](https://github.com/xamarin/xamarin-macios/blob/main/dotnet/targets/Microsoft.Sdk.DefaultItems.template.props). It would not even make sense to include everything since it's always been the default directory for managed .resx/.cs files.

I am not necessarily objecting to changing the implementation to be more broad, just adjusting expectations about the current behavior.

**Comment by rolfbjarne** [comment]
This is what Android includes by default:

https://github.com/xamarin/xamarin-android/blob/681887ebdbd192ce7ce1cd02221d4939599ba762/src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/Sdk/AutoImport.props#L26-L34

They don't all make sense for us, but something like this might work:

```xml
    <BundleResource Include="$(IPhoneResourcePrefix)\**\*.png" />
    <BundleResource Include="$(IPhoneResourcePrefix)\**\*.jpg" />
    <BundleResource Include="$(IPhoneResourcePrefix)\**\*.gif" />
    <BundleResource Include="$(IPhoneResourcePrefix)\font\*.ttf" />
    <BundleResource Include="$(IPhoneResourcePrefix)\font\*.otf" />
    <BundleResource Include="$(IPhoneResourcePrefix)\font\*.ttc" />
```

There are a few differences with regards to Android:

* Includes all `*.png`, `*.jpg` and `*.git` files, even from the root resource prefix directory (I believe Android's implementation only includes image files from any immediate subdirectories).
* Does not include any `*.xml` or `*.axml` files
* Does not include any `raw/*` files

Any other thoughts? Does this make sense?

CC @jonathanpeppers @Redth

**Comment by rolfbjarne** [comment]
One thing that complicates this a bit is that fonts [must be added to the Info.plist](https://developer.apple.com/documentation/uikit/text_display_and_fonts/adding_a_custom_font_to_your_app?language=objc) in order to be usable.

We could do the addition to the Info.plist automatically by adding support for metadata on the BundleResource items that asks for this:

```xml
    <BundleResource Include="$(IPhoneResourcePrefix)\font\*.ttf" RegisterFont="true" />
    <BundleResource Include="$(IPhoneResourcePrefix)\font\*.otf" RegisterFont="true" />
    <BundleResource Include="$(IPhoneResourcePrefix)\font\*.ttc" RegisterFont="true" />
```

CC @Redth you mentioned that we'll want to sync this with the rest of MAUI; do you have any input here?

**Comment by Redth** [comment]
Yes, currently we have a custom build task which adds font registration to a partial info.plist we generate (it includes other things too): 

https://github.com/dotnet/maui/blob/main/src/SingleProject/Resizetizer/src/CreatePartialInfoPlistTask.cs#L43-L56

If this functionality is added to the macios build tasks I would like to remove our code which generates this so that we aren't duplicating the same type of implementation.

We could then adjust our targets to just set the `RegisterFont` metadata for the fonts we already identify from the `MauiFont` item group: https://github.com/dotnet/maui/blob/main/.nuspec/Microsoft.Maui.Resizetizer.targets#L360-L365

Mostly I just want to make sure we stay in sync with the changes, know what they are, when they are made, so we can adjust (simplify) our targets afterwards.

**Comment by Redth** [comment]
Also images might not be desired here for iOS by default (unless we disable that default glob for MAUI Single Project) since we do further processing to included images in MAUI to generate various density versions of them.

**Comment by rolfbjarne** [comment]
@Redth 

> Also images might not be desired here for iOS by default (unless we disable that default glob for MAUI Single Project) since we do further processing to included images in MAUI to generate various density versions of them.

You don't end up including the original image in the .app, just the generated variations of them?

**Comment by rolfbjarne** [comment]
Since we're already including some resources from anywhere inside the project's Resources directory, I think it makes sense to include fonts in the same way.

This means something like this:

```xml
<BundleResource Include="$(IPhoneResourcePrefix)\**\*.ttf" />
<BundleResource Include="$(IPhoneResourcePrefix)\**\*.otf" />
<BundleResource Include="$(IPhoneResourcePrefix)\**\*.ttc" />
```

and then also add support for a `RegisterFont` metadata on the `BundleResource` items, that will add the font(s) to the `UIAppFonts` Info.plist entry.

I'll implement this unless someone complains :smile:

**Comment by rolfbjarne** [comment]
@Redth just an FYI that the default font inclusion has been implemented now, I believe this would need changes in MAUI as well according to our conversations.
