### ISSUE TITLE
Cyber security issues - IPA Binary Analysis in Xamarin forms app

### ISSUE THREAD

**Issue by vallial** [xamarin/xamarin-macios#12612]
Hi All,

Recently our Xamarin.forms application has gone through a Cyber Security Analysis Certification(CSAC) and we got issues in Xamarin.iOS part in IPA Binary Analysis.

![image](https://user-images.githubusercontent.com/89967681/131809000-08d3d38f-ea33-40ee-b466-c7da3ea098b4.png)

Please help us to find the solution for above mentioned issues.

Thanks,
Valli.

**Comment by spouliot** [comment]
> Please help us to find the solution for above mentioned issues.

TL&DR: There's no _solution_ and there's likely no issue to solve.

Long Story:

We had a few similar questions in the past. Those tools are not very useful since they inspect the output (singular, the application binary) and not the inputs (plural) of the build process.

I can **not** tell you about everything that's inside the application that was verified. IOW you might be using several 3rd party libraries that include those symbols and those might be used correctly (or not).

As @filipnavara mentioned the mono runtime is scanned with coverity. This tool looks, among other things, for the proper usage of _risky_ API, including those you mention.

The iOS SDK is also scanned [here](https://scan.coverity.com/projects/xamarin-macios). It's not up-to-date since the coverity tools had issues with newer Xcode (it's been fixed recently), however our unmanaged libraries are quite small and does not change a lot over time.

If needed you can look at the coverity results (or even use coverity to scan the repos yourself) [1].

WRT #1, #2 and #4 it is not possible (at least for mono) to completely avoid the uses those API. Sadly your tool only detect if the API is referenced, so
* it cannot tell you if it's ever executed - notice the use of "_may_ use/contain" in the wording;
* it cannot tell you how many times it's used (that's why tools like coverity are much more useful);

WRT #3 `NSLog` this is _normal_ as we map `Console.WriteLine` (and similar API) to `NSLog` and it's also used internally to display crash-related (or very important debugging information). Since the SDK is open source (and mono is too) you can audit the use cases to satisfy [1] that no sensitive information is leaked thru logs.

[1] but you need to do the same for any other unmanaged libraries your application might include thru 3rd party dependencies.
