### ISSUE TITLE
Make dotnet publish more consistent 

### ISSUE THREAD

**Issue by Redth** [xamarin/xamarin-macios#12997]
This is the equivalent of the android issue I filed: https://github.com/xamarin/xamarin-android/issues/6393

Goal: Make dotnet publish relatively consistent and relatively free of platform specific arguments required...

Consider the following scenario for building in CI:

`dotnet publish -f net6.0-ios -c Release -o ./artifacts`

This currently does not automatically produce a .ipa file, though there are some files output there so it seems the output setting is used in some capacity.

I'm not sure how to currently produce a .ipa with this command.  I've tried `dotnet publish -f net6.0-ios -c Release -o ./artifacts -p:BuildIpa=True -p:IpaPackagePath=./artifacts/com.app.id.ipa` which says it created the package but the package does not exist.

Ideally I would expect the output from the first publish command mentioned above to look like:
- ./artifacts/com.app.id.app
- ./artifacts/com.app.id.ipa

This makes it a simple command, consistent with other platforms, to produce a reasonably expected set of binaries created.

**Comment by rolfbjarne** [comment]
> This currently does not automatically produce a .ipa file, though there are some files output there so it seems the output setting is used in some capacity.

The reason it doesn't work is because no RuntimeIdentifier was specified, and it defaulted to iossimulator-x64, which can't be used to create an ipa.

Unfortunately I'm not sure we can fix this, because by the time we know we're publishing, it's too late to set the default runtime identifier (i.e. it's not possible to have a different default runtime identifier between "dotnet build" and "dotnet publish").

At most it looks like I'll be able to show an error if trying to publish without specifying the runtime identifier.

> Ideally I would expect the output from the first publish command mentioned above to look like:
> 
> * ./artifacts/com.app.id.app
> * ./artifacts/com.app.id.ipa

I'll fix it so that the .ipa ends up in the specified output directory (once a runtime identifier has been specified).

**Comment by rolfbjarne** [comment]
> I'll fix it so that the .ipa ends up in the specified output directory (once a runtime identifier has been specified).

This part is done now.

**Comment by rolfbjarne** [comment]
> At most it looks like I'll be able to show an error if trying to publish without specifying the runtime identifier.

This has been implemented too now.

@Redth I'm not sure what else we can do now?

**Comment by rolfbjarne** [comment]
Closing, I don't think we can do anything else here.
