### ISSUE TITLE
[Announcement] Breaking changes in .NET 6 for iOS, tvOS and macOS

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#13087]
In order to fully support the new native types in C# (nint, nuint), we’ve unfortunately realized that we can’t keep compatibility with existing code or assemblies built for Xamarin.iOS or Xamarin.Mac. 

The consequences are as follows when upgrading a project to .NET 6: 
 
1. All code must be recompiled to support .NET 6. Existing assemblies (such as NuGets built for the old TargetFrameworkIdentifier xamarinios10) won’t work and won’t be supported. Non-xamarin specific assets for net4.x, netstandard, netcoreapp, net5.0+, etc. will work fine however. 
2. Existing code might need to be modified. We’ll post a more detailed document with examples of code changes that might be required at a later point. 

In addition, we’re taking the opportunity to fix a few mistakes we’ve made in the past, that we’ve been unable able to address because they were breaking changes. 

These are the main changes: 

1. Removal of the [System.nint](https://docs.microsoft.com/en-us/dotnet/api/system.nint?view=xamarin-ios-sdk-12) and [System.nuint](https://docs.microsoft.com/en-us/dotnet/api/system.nuint?view=xamarin-ios-sdk-12) types. We’re going to use the `nint` and `nuint` types [as defined by C#](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nint-nuint) (they are [System.IntPtr](https://docs.microsoft.com/en-us/dotnet/api/system.intptr?view=net-5.0) and [System.UIntPtr](https://docs.microsoft.com/en-us/dotnet/api/system.uintptr?view=net-5.0) under the hood). 
2. Removal of the [System.nfloat](https://docs.microsoft.com/en-us/dotnet/api/system.nfloat?view=xamarin-ios-sdk-12) type. We're going to use the [System.Runtime.InteropServices.NFloat](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.nfloat?view=net-6.0) type instead. ~For the [System.nfloat](https://docs.microsoft.com/en-us/dotnet/api/system.nfloat?view=xamarin-ios-sdk-12) type we’re probably going to keep the type [1], but move it to a different namespace.~
3. Use a different type than System.IntPtr for handles (the [NSObject.Handle](https://docs.microsoft.com/es-es/dotnet/api/foundation.nsobject.handle?view=xamarin-ios-sdk-12) property): [ObjCRuntime.NativeHandle](https://github.com/xamarin/xamarin-macios/blob/main/src/ObjCRuntime/NativeHandle.cs). This is to avoid confusion between nint/nuint and handles. 
4. Move all the types in the OpenTK namespace elsewhere. 

We also have a list of minor changes we’ve wanted to do for a long time: https://github.com/xamarin/xamarin-macios/issues/5107. We’ll be going through this list and implement the ones that make sense and that we have time to complete. 

The first preview with these breaking changes will be Preview 11.

Reference: https://github.com/xamarin/xamarin-macios/issues/10508 
Reference: https://github.com/dotnet/designs/pull/252
Reference: https://github.com/NuGet/Home/issues/11338

[1]: ~[System.Runtime.InteropServices.NFloat](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.nfloat?view=net-6.0)  is not a good replacement for [System.nfloat](https://docs.microsoft.com/en-us/dotnet/api/system.nfloat?view=xamarin-ios-sdk-12), because it’s a very basic type intended only for interop scenarios. For instance, it does not have any operators, so code like “NFloat + NFloat” does not compile.~ The operators were implemented and back ported to .NET 6, so the concerns with System.Runtime.InteropServices.NFloat went away.

**Comment by commonsensesoftware** [comment]
@rolfbjarne with respect to:

>[1]: System.Runtime.InteropServices.NFloat is not a good replacement for System.nfloat, because it’s a very basic type intended only for interop scenarios. For instance, it does not have any operators, so code like “NFloat + NFloat” does not compile.

I completely understand and agree with this value judgement - today. Does that still make sense with the advent of [Generic Math](https://devblogs.microsoft.com/dotnet/preview-features-in-net-6-generic-math) on the horizon? Granted, it is in _preview_ at the moment, but if it were fully flushed out, it would seem pretty trivial to have `NFloat` implement all the necessary interfaces to make it a fully functional drop-in for `nfloat` by implementing it through to the underlying native implementation (e.g. `Single` or `Double`). There  might be one or two other gaps, but it would seem those are addressable by way of extension methods or simply asking to have it added to `NFloat`.

Ultimately, it _feels_ like `NFloat` and `nfloat` serve the same purpose, but have different features and capabilities. Wouldn't converging to one be preferable? `NFloat` would seem to be the long-term winner. I concede that `nfloat` _might_ have to stay around for the short term. Backing `nfloat` with `NFloat` under the hood or, at least, making it convertible to and from `NFloat` may set up an easier transition in the future. As an example, have interop APIs only use `NFloat`, but expose `nfloat` where manipulation in managed code may be necessary. That also _feels_ like it has parity with the approach to using `SafeHandle`.

_"Why have one when you can have two at twice the cost?"_

**Comment by Perksey** [comment]
I think IS.NFloat not implementing any arithmetic operators was by design (@tannergooding?), so even if generic math comes along it likely will not implement those interfaces. But I could be wrong, and if that is the case then yes IS.NFloat would theoretically be a suitable replacement given we're already down the rabbit hole of ABI breaks.

**Comment by commonsensesoftware** [comment]
@Perksey I get that it was _by design_ - of `NFloat` anyway. Clearly, it exists for the purposes of providing interop, but nothing more. By name and description, `NFloat` and `nfloat` are _meant_ to do the same thing, even they have different features. Adding stuff to a core library requires a lot of thought and consideration. Once you add it, it's pretty much there forever. To that end, it's not that hard to rationalize why `NFloat` is currently so _feature incomplete_ for general usage. Creating a completely separate `nfloat` that does everything `NFloat` does and more seems _wrong_ and is definitely confusing (to use).

While it may have been _by design_, the design of `NFloat` _should_ be revisited. If I'm way off the mark and these two types do completely different things, then the documentation - at minimum - should call out those differences (aside from obvious feature differences). The existence and use `nfloat` validates there is a clear and strong use case for a fully-featured `NFloat` (IMO). There could very well be other scenarios where it could be useful in constrained systems such as some IoT applications.

Ultimately, this probably isn't the right forum to discuss the historical design of `NFloat`. If we agree that `NFloat` _should_ be the correct replacement for `nfloat`, regardless of what its original design was, then this issue should be the catalyst to support changing/enhancing the design of `NFloat` to provide the necessary capabilities. A formal discussion in the runtime repo would establish a path forward that either sees `nfloat` get sunset once and for all or squash the conversation that `NFloat` should be enhanced. I don't know that I'm the best person to champion to do that, but I'm more than willing to lead the charge.

At least for me, I find the answer _"Well, that's just how NFloat works and it's by design"_ extremely unsatisfactory. If we agree that `NFloat` should be the _right_ thing, then I'm of the opinion we should push in that direction, even if it doesn't meet all the needs of today. The design of `NFloat` is what it is - for the moment, but it doesn't necessarily _have_ to stay that way.

**Comment by Perksey** [comment]
> While it may have been by design, the design of `NFloat` should be revisited.

For .NET 6 it's too late already, the API is already finalized. So in any case Xamarin will need their `nfloat` on .NET 6. And I suspect even if in .NET 7 `NFloat` gets matching features, Xamarin will want to keep their `nfloat` to avoid API differences between framework versions (as that would be extremely confusing).

**Comment by tannergooding** [comment]
> Use a different type than System.IntPtr for handles (the NSObject.Handle property). Exactly which type(s) has not been decided yet. This is to avoid confusion between nint/nuint and handles.

@rolfbjarne, sorry for the late comment on this, I had missed the original issue.

I don't think this one is a good idea. The rest of .NET uses `IntPtr` to represent handles and will continue doing so moving forward. As it stands "right now", `IntPtr` and `nint` have slightly different semantics. Even if that were to change, I still don't think it would be problematic as there are already operators/methods exposed on `IntPtr` that you wouldn't want to use in the face of true opaque handles.

> I think IS.NFloat not implementing any arithmetic operators was by design (@tannergooding?)

@Perksey, The reviewed design was indeed that it be purely an interchange type (this was partially influenced based on input from @jkotas, as my initial design did include basic operators, etc).

Given that `nfloat` is the "ABI primitive", if it having operators or not was the deciding factor of `Xamarin` using it or continuing to use their own custom version of `nfloat`, then we should probably revisit this. Adding the operators wouldn't be overly complex and would be "inline" with a lot of the "generic math" changes already being done for .NET 7.

If, however, `Xamarin` decided to use `double` in the public surface area and `NFloat` on the "backend", I think it would be fine to continue being purely an interchange type.

**Comment by commonsensesoftware** [comment]
@Perksey You are right and I agree. @tannergooding more or less confirmed what I suspected. Here's my thoughts as to how this would play out as it relates to the breaking changes and future evolution here.

### Option 1
1. Only use or publicly expose `NFloat` on API surfaces
    a. This assumes that `NFloat` could _some_ day replace `nfloat`
    b. This would largely mitigate future breaking changes when/if `NFloat` becomes a formal replacement
2. Keep `nfloat` for Xamarin because `NFloat` is not ready to completely replace it
3. Refactor `nfloat` and/or provide extension methods to easily convert between `NFloat` and `nfloat`
    a. Implicit conversions should be a safe like-for-like, but I'd be just as happy with explicit conversions
4. _Some_ day (.NET 7, 8, 9...) `nfloat` is marked `[Obsolete]` and _perhaps_ even removed

Using this approach would stabilize APIs themselves to `NFloat`, but provides easy-to-use conversions to `nfloat` when math operations are necessary.

### Option 2
Having thought about it a little more, this would be my preferred and suggested approach:

1. Only use or publicly expose `NFloat` on API surfaces
2. Provide a _math_ class (ex: `MathNF` like there's `MathF`) that provides all of the operations, functions, and constants currently exposed by `nfloat`.
    a. For example: `public static NFloat Add(NFloat x, NFloat y)`
    b. This type need not, and probably should not, live under the `System` namespace
3. _Some_ day (.NET 7, 8, 9...) the provided _math_ class will no longer be necessary because `NFloat` provides intrinsic features that make it natural to use.
    a. While the _math_ class is no longer _necessary_ it's still fully valid and doesn't need to be necessarily deprecated or removed

A _Math_ class doesn't represent the "ABI Primitive", it just provides the operations you'd do on the primitive. This path means you'd never have to worry about confusing `NFloat` with `nfloat` or having to deprecate/remove `nfloat` at some future point in time.

This approach is a bit _less than desirable_ for how it would be used in the short-term, but that can be mitigated in a couple of ways:

#### User-Defined Extension Methods
If devs care enough, they can add extension methods to make things _feel_ more natural. For example:

```c#
internal static class NFloatExtensions
{
    public static NFloat Add(this NFloat x, NFloat y) => MathNF.Add(x, y);
    // ... and so
}
```
Not quite `x + y`, but `x.Add(y)` is close.

#### Provide Scaffolding
A scaffolding template can be provided that would produce a substitute `NFloat` user-defined type that can be freely swapped out for `IS.NFloat` at some point in the future if a developer so chooses. This is purely only if a developer wants the usage to feel natural and is probably only _convenient_ if you're doing a lot of `NFloat` math. Something like:

```c#
namespace MyProject;

using nfloat = System.Runtime.InteropServices.NFloat;

internal readonly struct NFloat : IEquatable<NFloat>
{
    private readonly nfloat value;
    public NFloat(nfloat value) => this.value = value;
    public static implicit operator nfloat(NFloat x) => x.value;
    public static implicit operator NFloat(nfloat x) => new(x);
    public static NFloat operator +(NFloat x, NFloat y) => new(MathNF.Add(x.value, y.value));
    public static NFloat operator -(NFloat x, NFloat y) => new(MathNF.Substract(x.value, y.value));
    // ... and so on
    public bool Equals(NFloat other) => value.Equals(other.value);
    public override bool Equals(object? obj) => obj is NFloat other && Equals(other);
    public override int GetHashCode() => value.GetHashCode();
    public override string ToString() => value.ToString();
}
```

With the exception of the namespace, this produces source compatibility with `IS.NFloat` the way we expect it to work in the future (e.g. `x + y` is now supported). When it's no longer needed, you'd simply delete the file. If you never delete it, it happily lives on side-by-side - forever. Again, this would be a _choice_, not a requirement. This might only be something the community provides as opposed to the platform team. Regardless, this can be used to make using `NFloat` today easier, while mitigating the breaking changes or obsolescence of the future.

**Comment by rolfbjarne** [comment]
@tannergooding 

> > Use a different type than System.IntPtr for handles (the NSObject.Handle property). Exactly which type(s) has not been decided yet. This is to avoid confusion between nint/nuint and handles.
> 
> @rolfbjarne, sorry for the late comment on this, I had missed the original issue.
> 
> I don't think this one is a good idea.

I don't quite understand your explanation:

> The rest of .NET uses `IntPtr` to represent handles and will continue doing so moving forward.

`SafeHandle` (and friends) is used in a lot of places.

> As it stands "right now", `IntPtr` and `nint` have slightly different semantics.

To me that's a reason to use a different type than `IntPtr` (which is what `nint` really is) for opaque handles.

> Even if that were to change, I still don't think it would be problematic as there are already operators/methods exposed on `IntPtr` that you wouldn't want to use in the face of true opaque handles.

Once again, this seems to be an argument for using a different type than `IntPtr` for opaque handles.

In any case, the problem we're running into is that we're binding native API that do something like this:

```objective-c
void SetValue (NSInteger number);
void SetValue (NSObject* object);
```

when mapping this to C#, we'd end up with something like this (if using `IntPtr` to represent opaque handles):

```csharp
void SetValue (nint number);
void SetValue (IntPtr number);
```

and that won't compile, since `nint` and `IntPtr` are the same type.

**Comment by rolfbjarne** [comment]
## nfloat -> NFloat

The only remotely feasible solution to removing our `ObjCRuntime.nfloat` type in favor of `System.Runtime.InteropServices.NFloat` would be to if `NFloat`'s API was improved in .NET 7 to actually be usable.

In that case we could remove our `ObjCRuntime.nfloat` type now, and app developers could either heavily adapt their existing code to use the .NET 6 version of `System.Runtime.InteropServices.NFloat`, or wait until .NET 7 when the API would become a lot better.

The code adaptation in the .NET 6 time frame would be extensive and ugly...

Examples:

* There are no `NFloat` constants, nor conversion to `NFloat` from constants:

```csharp
// before
var color = new CGColor (0.5, 0.25, 0.75);
// .NET 6
var color = new CGColor (new NFloat (0.5), new NFloat (0.25), new NFloat (0.75));
// .NET 7 (would work unmodified)
var color = new CGColor (0.5, 0.25, 0.75);
```

* There are no `NFloat` math operators

```csharp
// before
nfloat a = 1;
nfloat b = 2;
var c = a + b;
// .NET 6
var a = new NFloat (1);
var b = new NFloat (2);
var c = MathHelper.Add (a, b);
// .NET 7 (slight modifications still required)
NFloat a = 1;
NFloat b = 2;
var c = a + b;
```

The (eventual) upside is that we won't have two types doing pretty much the same thing, and (🔮) we won't run into any compatibility problems if C# decides to add a `nfloat` keyword.

@tannergooding: you seem to think that improving NFloat's API is feasible for .NET 7, who can I contact to get a commitment on this? Our deadline for removing `nfloat` on our side is approaching fast, and we need some sort of commitment that these changes will come in .NET 7 before even starting to do any work on our side.

**Comment by tannergooding** [comment]
> @tannergooding: you seem to think that improving NFloat's API is feasible for .NET 7, who can I contact to get a commitment on this? 

I could likely get an commitment on Tuesday for the next API review. I'd need to write up a proposal and take it through as a "blocking" request (which isn't a big deal, it just ensures it gets reviewed "first", in relation to other blocking reviews of which we currently have none).

Based on the examples you gave above, this basically just needs operators and implicit conversions support.

One interesting thing is that you allow `implicit conversion from double` in that sample. However, that is "potentially lossy" which goes against the "normal" implicit conversion rules. The safe thing would be:
* implicit to `double`
* explicit from `double`
* explicit to `float`
* implicit from `float`

That is:
```
// Implicit
NFloat x = 0.5f;
double y = x;

// Explicit
NFloat z = (NFloat)0.5;
float w = (float)z;
```

I'd also note that `There are no NFloat constants,` isn't possible unless you modified the C# lang. That is, `const NFloat x = 5` won't be possible because constants for user-defined structs aren't possible today. This extends to their usage in attributes, parameters (although with the right implicit conversions and attributes parameters can work, its just more verbose), etc. The implicit conversions would work, given where there is no silent truncation.

If maintaining the silent truncation support is important, I can raise that in API review, but it is "lossy" behavior.

**Comment by rolfbjarne** [comment]
@tannergooding 

> I could likely get an commitment (or not) on Tuesday for the next API review. I'd need to write up a proposal and take it through as a "blocking" request (which isn't a big deal, it just ensures it gets reviewed "first", in relation to other blocking reviews of which we currently have none).

That sounds great!

Here's our current nfloat API: https://gist.github.com/rolfbjarne/573f32cf015e0adcab3600894e2de1a2, the closer `NFloat` can be the better :)

> One interesting thing is that you allow `implicit conversion from double` in that sample.

That was a mistake in the sample code (which I've now changed to use `float` constants), we don't support lossy conversion in our `nfloat`. The `double` -> `nfloat` conversion is explicit:

https://gist.github.com/rolfbjarne/573f32cf015e0adcab3600894e2de1a2#file-nfloat-cs-L64

> I'd also note that `There are no NFloat constants,` isn't possible unless you modified the C# lang.

Another mistake on my part, I was only thinking about conversion from constants to `NFloat`. `nfloat` as it stands today is in the same situation (it's not possible to have `nfloat` constants).

**Comment by tannergooding** [comment]
> That was a mistake in the sample code

Awesome and I did notice that when looking at the existing surface area.

I've opened https://github.com/dotnet/runtime/issues/63801 to track this and left a couple annotations. Notably there were just conversions missing to/from `nuint` (`UIntPtr`), we've previously opted to not extend new types with `System.IConvertible`, and Xamarin is currently using `static readonly` where-as `static properties` likely provide better perf and is the general "goto".

I also called out that we should likely make them inline with `Half`/`Double`/`Single` and have it extend the `generic math` interfaces that will be moving to "stable" for .NET 7. This would also expose all the math APIs like `Sqrt`, `Min`, `Max`, etc (what looks to be currently covered by `NMath` in Xamarin).

**Comment by bgavrilMS** [comment]
@rolfbjarne - what does this change imply for SDKs which currently target `Xamarin.iOS10` ? Will you have any guidance on how to fix compatibility issues?

**Comment by rolfbjarne** [comment]
@bgavrilMS that will continue to work as-is, there are no breaking changes if you want to target `Xamarin.iOS10`. The only breaking changes are if you upgrade to .NET.

**Comment by rolfbjarne** [comment]
@bgavrilMS it's possible to target both at the same time, and ship a single NuGet that supports both.

**Comment by bgavrilMS** [comment]
I understand that, and we already target android9.0 and android10.0; I was hoping that there will be a guide that shows us what breaking changes there are and how to mitigate them. I am sure many SDKs will require this.

**Comment by rolfbjarne** [comment]
@bgavrilMS yes, we're working on a document to explain the changes and how to migrate existing code.

**Comment by tannergooding** [comment]
@rolfbjarne, I still have to write tests but https://github.com/dotnet/runtime/pull/64234 implements the necessary surface area and can be pulled down/built locally if you want to do any prototyping.

**Comment by mattleibow** [comment]
@rolfbjarne due to the changes in the type used for handles, I now get this error: https://github.com/xamarin/xamarin-macios/issues/13867

**Comment by rolfbjarne** [comment]
> @rolfbjarne, I still have to write tests but [dotnet/runtime#64234](https://github.com/dotnet/runtime/pull/64234) implements the necessary surface area and can be pulled down/built locally if you want to do any prototyping.

Thanks!

**Comment by rolfbjarne** [comment]
All the changes we wanted to do have been implemented, so I'm closing this.

The upcoming preview 14 will have all these changes.

Barring extreme circumstances, we won't be doing any more breaking changes for subsequent preview/rc releases.

Regarding nfloat, we were able to add the operators that were missing in `System.Runtime.InteropServices.NFloat` into .NET 6, so we're going to remove our `System.nfloat` in favor of `System.Runtime.InteropServices.NFloat`. Most code will compile without changes, because we're automatically adding a global using to make `nfloat` mean `System.Runtime.InteropServices.NFloat` (the most common piece of code that won't compile would be any code that references `nfloat` using the full typename with namespace, such as: `System.nfloat number = 123;`)
