### ISSUE TITLE
Our app breaks after upgrading to Xamarin.iOS 15.2

### ISSUE THREAD

**Issue by SaqibS** [xamarin/xamarin-macios#13347]
### Steps to Reproduce

1. Build our not-open-source app. Use our Azure DevOps pipeline to avoid machine-specific issues.
2. Run app.

### Expected Behavior

The app should continue to run as it was before upgrading to Xamarin.iOS 15.2.

### Actual Behavior

When built with Xamarin.iOS 15.2, the app hangs for several seconds on the splash screen, and then eventually crashes.

We have found 3 different, independent, ways to fix the problem, and go back to a normally-working app:

* Install Xamarin.iOS 15.0.0.6 on the build machine.
* Or, keep 15.2, but disable linker.
* Or, keep 15.2 with linker enabled, but disable LLVM.

So I conclude that the problem is related to the combination of having all 3 of these criteria. Removing any one will remove the problem.

### Environment

* Using Azure DevOps pipeline, with the `macOS-11` VM image.
* Manually specify DotNet 5.x and Nuget >=5.0.

**Comment by rachelkang** [comment]
Hi, @SaqibS - thanks for opening this issue. However, we currently don't have enough information to investigate this further.

The next time you experience this issue, please share a [crash report](https://help.apple.com/xcode/mac/current/#/dev7b20475ba) as well as [the build logs](https://docs.microsoft.com/visualstudio/msbuild/obtaining-build-logs-with-msbuild?view=vs-2019#save-a-binary-log) so that we can take a closer look.

It would also be helpful to know:
* Are you getting any output when you run from the IDE on device?
* Does his ever happen in the simulator?
* Is this only happening from AppCenter builds?

**Comment by ShadowOfPhantom** [comment]
Same here, app is installing... installing... and then crashes after start (on debug)

**Comment by chamons** [comment]
As @rachelkang noted, we need more detailed information to be able to investigate this. Our test applications are not showing this behavior at all.

Please provide crash logs, ideally a sample project, any output when run from the IDE, etc.

**Comment by ShadowOfPhantom** [comment]
> As @rachelkang noted, we need more detailed information to be able to investigate this. Our test applications are not showing this behavior at all.
> 
> Please provide crash logs, ideally a sample project, any output when run from the IDE, etc.

I'll collect more info and get back with a feedback
I upgraded to the latest xamarin iOS on mac / deleted bin obj and it works but it doesn't works if I connect to Mac from VS 2022: it prompts to install previous version of Xamarin iOS on Mac and then crashes on debug. Do I also have to install VS 2022 for Mac if I use VS 2022 on my Windows PC? Seems like it's not compatible or so and that's what I'm going to check a little later
