### ISSUE TITLE
Terminating app due to uncaught exception 'System.ArgumentException', reason: 'Object of type 'Foundation.NSUrlSessionTask' cannot be converted to type 'Foundation.NSUrlSessionDataTask'.'

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#13531]
There seems to be a random test failure that goes like this:

    MonoTests.System.Net.Http.MessageHandlerTest.AcceptSslCertificatesServicePointManager
        [PASS] AcceptSslCertificatesServicePointManager(System.Net.Http.HttpClientHandler)
        2021-12-09 13:40:07.861 monotouchtest[83307:12887188] *** Terminating app due to uncaught exception 'System.ArgumentException', reason: 'Object of type 'Foundation.NSUrlSessionTask' cannot be converted to type 'Foundation.NSUrlSessionDataTask'.'
        *** First throw call stack:
        (
        	0   CoreFoundation                      0x00007fff2064a1db __exceptionPreprocess + 242
        	1   libobjc.A.dylib                     0x00007fff20383d92 objc_exception_throw + 48
        	2   monotouchtest                       0x00000001092b12c2 xamarin_process_managed_exception + 866
        	3   monotouchtest                       0x000000010943e335 _ZL32native_to_managed_trampoline_637P11objc_objectP13objc_selectorPP11_MonoObjectS0_S0_S0_S0_j + 1621
        	4   monotouchtest                       0x000000010943dcd0 -[Foundation_NSUrlSessionHandler_NSUrlSessionHandlerDelegate URLSession:dataTask:willCacheResponse:completionHandler:] + 80
        	5   CFNetwork                           0x00007fff24a23c22 CFHTTPCookieStorageUnscheduleFromRunLoop + 162223
        	6   libdispatch.dylib                   0x00007fff2032d623 _dispatch_call_block_and_release + 12
        	7   libdispatch.dylib                   0x00007fff2032e806 _dispatch_client_callout + 8
        	8   libdispatch.dylib                   0x00007fff203345ea _dispatch_lane_serial_drain + 606
        	9   libdispatch.dylib                   0x00007fff203350e0 _dispatch_lane_invoke + 417
        	10  libdispatch.dylib                   0x00007fff2033ec0d _dispatch_workloop_worker_thread + 811
        	11  libsystem_pthread.dylib             0x00007fff204d545d _pthread_wqthread + 314
        	12  libsystem_pthread.dylib             0x00007fff204d442f start_wqthread + 15
        )

Ref: https://github.com/xamarin/xamarin-macios/pull/13523#issuecomment-990440273

**Comment by rolfbjarne** [comment]
Duplicate of #13921.

**Comment by rolfbjarne** [comment]
Reopening, since this is not a duplicate of #13921 in the end (or #13921 ended up with two distinct problems, and only one was fixed).

**Comment by rolfbjarne** [comment]
See: https://github.com/xamarin/xamarin-macios/issues/13921#issuecomment-1083520157

Repro: https://github.com/xamarin/xamarin-macios/files/8383411/Archive.zip

**Comment by filipnavara** [comment]
Part of the problem is that #14070 did not really fix the interaction between the object map, GC and finalization properly. It rightly identified the underlying problem (`InFinalizerQueue` flag not being set when objects enter finalization queue on CoreCLR) but it only reduced the race condition window instead of eliminating it entirely. The reason the fix doesn't work is my misunderstanding of how `GCHandle` works when used with the `WeakTrackResurrection` type.

There's still a window between the GC collection and setting the `InFinalizerQueue` flag in the finalizer where the `GCHandle.Target` returns the object that has no references and is already on the finalization queue. In this small time window any other thread can get a reference to the object and incorrectly assume that it's not on the finalization queue. Any later use of that object can encounter `Disposed` flag or null `Handle` once the delayed finalization code is run on the UI thread.

I mistakenly assumed that `GCHandle.Target` would be `null` during this window (analogous to the `Weak` GCHandle) but that's [not the case](https://devblogs.microsoft.com/dotnet/finalization-implementation-details/). `Weak` GC handles are invalidated when objects are placed on the finalization queue, ie. have no further references at GC time. `WeakTrackResurrection` GC handles are invalidated after the finalizer runs and there are no resurrected references.

That's basically the explanation for the `ObjectDisposedException` in https://github.com/xamarin/xamarin-macios/issues/13921#issuecomment-1083441632.

**Comment by filipnavara** [comment]
I don't have full explanation for the `NSUrlSessionTask` and `NSUrlSessionDataTask` type mismatch. However, my observations seem to imply that there are two different objects of the respective types at different points in time with the same handle value. The object map just happens to be "poisoned" with the managed instance of `NSUrlSessionTask` that doesn't exist any more and that was finalized. I guess this theory could be either verified or debunked by asserting the native object type in `Runtime.GetNSObject` in the `TryGetNSObject(...) is not null` case.

**Comment by rolfbjarne** [comment]
> That's basically the explanation for the `ObjectDisposedException` in [#13921 (comment)](https://github.com/xamarin/xamarin-macios/issues/13921#issuecomment-1083441632).

I don't see how that explains the `ObjectDisposedException`s.

The disposed objects shouldn't be on the finalizer queue anywhere, they're reachable from the stack.

The ODE happens when iterating here:

https://github.com/xamarin/xamarin-macios/blob/e387cce6dea6fcc20877490fb344b238dbf4aaca/src/Foundation/NSUrlSessionHandler.cs#L699

for some reason a key from the `Keys` array ends up disposed, while iterating over the array: https://github.com/xamarin/xamarin-macios/blob/635ce68452ac23405475ee44f71586e3d35d6481/src/Foundation/NSDictionary.cs#L397-L399

**Comment by rolfbjarne** [comment]
Actually, I have a few ideas. Maybe I'll just need to think about this early in the morning with a fresh brain...

**Comment by filipnavara** [comment]
> I don't see how that explains the ObjectDisposedExceptions.
>
> The disposed objects shouldn't be on the finalizer queue anywhere, they're reachable from the stack.

The NSMutableStrings are reused on the native side. Here's the flow that leads to the exception:
- Enumeration of `AllHeaderFields` creates managed objects wrapping the strings
- Managed counterparts get unreachable right after the `AllHeaderFields` enumeration and they become eligible for garbage collection. 
- Garbage collection happens and places the managed `NSMutableString` instances on the finalization queue.
- Different thread runs into the same code path with `AllHeaderFields` on a different request. The native objects are still the same with the same handles.
- Each of the keys is retrieved from object map through `Runtime.GetNSObject` which returns the objects that are now on the finalization queue (or in the middle of running finalizer).
- The finalizer runs on its thread, sets the `Disposed` flag and proceeds to hand the object to `NSObject_Disposer`.
- On the previous thread the key object is now marked as disposed (verified in LLDB with SOS) and if the UI thread is fast enough it even gets the handle released by `NSObject_Disposer` before it's used.

**Comment by filipnavara** [comment]
So far I didn't find any reasonable fix for the `GCHandle` problem above. Workaround that I tried is [here]( https://github.com/xamarin/xamarin-macios/commit/e69822083c1bc4539838a11b981026c33fc866ae), it seems to work but it's expensive.

**Comment by filipnavara** [comment]
> So far I didn't find any reasonable fix for the `GCHandle` problem above. Workaround that I tried is [here](https://github.com/xamarin/xamarin-macios/commit/e69822083c1bc4539838a11b981026c33fc866ae), it seems to work but it's expensive (the second `GCHandle` can be avoided for `IsDirectBinding && !IsRegisteredToggleRef` objects).

I gave it one more thought I think it may be possible to get rid of the overhead.

Suppose we would use `GCHandleType.Weak` instead of `GCHandleType.WeakTrackResurrection` by default:
- Custom types should not be affected. If they are referenced by native code they should have a GCHandle preventing them from being collected, right?
- Direct bindings with `!IsRegisteredToggleRef` are [not returned from TryGetNSObject](https://github.com/xamarin/xamarin-macios/blob/d48b0eb42e3531465b6119688c04439cf6eae6f8/src/ObjCRuntime/Runtime.cs#L1364-L1373) if they are already on the finalizer queue, irrespective of the `evenInFinalizerQueue` option.
- Direct bindings with `IsRegisteredToggleRef` have to undergo the toggle ref transition. That enables the necessary tracking that sets the `InFinalizerQueue` flag. It can just as well replace the handle in `object_map` with one that has the `GCHandleType.WeakTrackResurrection` type.

I'm almost certain that I missed some important case but for the sake of discussion [here's implementation of that idea](https://github.com/xamarin/xamarin-macios/commit/19f91e1084a3f3d530bad3c3f6b7515c12a52011).

**Comment by rolfbjarne** [comment]
I think we can use the CoreCLR support for toggle-ref objects. It will also call us whenever an object enters the finalization queue, so we could just use it for all NSObject-based objects, and not just toggle-ref objects.

**Comment by filipnavara** [comment]
> I think we can use the CoreCLR support for toggle-ref objects. It will also call us whenever an object enters the finalization queue, so we could just use it for all NSObject-based objects, and not just toggle-ref objects.

I assume that would work.

**Comment by filipnavara** [comment]
> I assume that would work.

On second thought, that allocates extra GC handle so that basically boils down to equivalent overhead as keeping both `Weak` and `WeakTrackResurrection` GC handles. Unless you remove that second handle, of course, which looks quite doable.

**Comment by rolfbjarne** [comment]
> > I assume that would work.
> 
> On second thought, that allocates extra GC handle so that basically boils down to equivalent overhead as keeping both `Weak` and `WeakTrackResurrection` GC handles. Unless you remove that second handle, of course, which looks quite doable.

Yes, the idea would be to remove the second (WeakTrackResurrection) GCHandle. It'll be interesting to see if that actually works... 🤞

**Comment by Nyta7419** [comment]
thank you very much))) I haven't really figured it out on this platform yet))
I'll go find where to delete it, and delete it (WeakTrackResurrection) I think you should believe you are clearly longer on this platform)))
thanks again very much))



Отправлено из мобильной Почты Mail.ru


понедельник, 4 апреля 2022 г., 18:34 +0300 от ***@***.***  ***@***.***>:

**Comment by rolfbjarne** [comment]
These three PRs should fix it:

* https://github.com/xamarin/xamarin-macios/pull/14783
* https://github.com/xamarin/xamarin-macios/pull/14784
* https://github.com/xamarin/xamarin-macios/pull/14785

**Comment by rolfbjarne** [comment]
All three PRs have been merged, so closing this.
