### ISSUE TITLE
2 binding libraries that have different framework versions?

### ISSUE THREAD

**Issue by motoko89** [xamarin/xamarin-macios#13701]
I created a binding library for Google REST API, which has dependency on `GTMSessionFetcher.framework` and `GTMAppAuth`. I also use `Xamarin.Firebase.iOS.Analytics`, last updated over a year ago. It also has dependency on the above 2 frameworks, but older version.

I notice that VS extract these frameworks to the same location. They seem to overwrite each other? Is the extraction order deterministic?

Is there any risk of crashing if I use mismatch framework version like this? Mitigation?

**Comment by dalexsoto** [comment]
Hello, 

This could potentially be bad for your application, the keyword is "potentially" that really depends on what `Xamarin.Firebase.iOS.Analytics` and `Google REST API` use from `GTMSessionFetcher.framework` and `GTMAppAuth`. To be on the "safer" side I would try to run these with the same version of both frameworks and see if the app doesn't crash but there be dragons if you decide to run your own combinations. That said we cannot link against two versions of the same library since we would run into duplicated symbols so you will need to decide which version to bring in via your own binding project.
