### ISSUE TITLE
[net6/Xamarin.iOS] `NSObject.ConformsToProtocol` is very costly and invoked very often

### ISSUE THREAD

**Issue by jeromelaban** [xamarin/xamarin-macios#14065]
### Steps to Reproduce

No specific step to reproduce, but it seems that UIView.AddSubview / UIView.RemoveFromSuperview with custom types inheriting from UIView seems to trigger this from time to time.

### Expected Behavior
`ConformsToProtocol` does not appear prominently in performance traces.

### Actual Behavior

![image](https://user-images.githubusercontent.com/5839577/152430495-03addb9e-a9ca-4142-8f6e-53827a51a395.png)

Most of the time is spent here:
https://github.com/xamarin/xamarin-macios/blob/d78aa6712b15659b0fed259952364c060ffedcea/src/Foundation/NSObject2.cs#L407

A lot of the time is spent invoking this method at regular times, seemingly in batch, but there's no direct stack trace leading to invocation from managed code.

### Environment

VS 2022 17.1 Preview 5

### Example Project (If Possible)

I do not have an available project yet.

**Comment by spouliot** [comment]
I do not think this would be a specific issue to net6 - but I might have missed some changes so take this with a grain of salt.

> but there's no direct stack trace leading to invocation from managed code.

That's Apple's ObjC code calling `conformsToProtocol:` [1] and since it happens when add/removing views there won't be an _interesting_ managed stack trace.

[1] so there's
* the associated native->managed->native cost for each call;
* the number of calls can vary (and likely grows) with each version of iOS (since more protocols are added)

Caching would help some cases but it would help in every cases (at least versus its cost). I doubt it's a good thing to implement caching inside the platform assemblies.

Still you could cache the specific cases that affects you.

* Set a breakpoint in `NSObject.ConformsToProtocol` to see which types are queried.
* Next override `ConformsToProtocol` and cache the results (IntPtr -> bool).

Or do your own hardcoded logic to return `true` (or `false`) without running the heavy weight reflection (and cache that or not).

**Comment by jeromelaban** [comment]
Thanks for the detailed update! Indeed, I do know which types are queried there, and caching should be simple enough for sure. 

I wonder, is this a lookup that could be statically generated, or is the pointer passed opaque enough to be useless for caching?

**Comment by spouliot** [comment]
> I wonder, is this a lookup that could be statically generated

It is, in some cases. However if your app/config is allowing dynamic registration [1] then the querying happens (even if a single `GetCustomAttributes` will be called anyway).

See `src/Foundation/NSObject2.cs` around line 477 for details.

[1] and that could be what differ from _legacy_ and net6 profiles in your case.

**Comment by jeromelaban** [comment]
It's actually very curious, and likely something that started happening with iOS 15 (seemingly in relation to `_isTransparentFocusItem`). Also, caching `ConformsToProtocol` only marginally improves the overall performance.

Here's a snippet from what I see in instruments:

![image](https://user-images.githubusercontent.com/5839577/152562889-566d8a26-17fd-4501-99c9-71cf6dd65293.png)

This happens with very large trees.

**Comment by spouliot** [comment]
It might not be the exact same case but inside **Dope** for `net6.0-macos` the time spent inside `ConformsToProtocol` (and reflection) happens when removing subviews [1]. That's 2.82 seconds out of a 2m05s benchmark run (so more than 2%).

<img width="962" alt="Screen Shot 2022-06-05 at 2 59 16 PM" src="https://user-images.githubusercontent.com/260465/172066220-ea115326-892e-4a6d-b6da-18046a1e9655.png">

The static registrar is not enabled by default for `net6.0-macos` (which it should be for `net6.0-ios` applications) and that should make a cache helpful... but there might be a different way (for macOS) to handle this. I can file an issue on Uno for it - but it would best to understand how this affects iOS (with the static registrar) first, so that a fix is beneficial to both platforms.


[1] that subviews removal is somewhat (maybe not everywhere yet) optimized for macOS (using an API not available on iOS) so it could be worse on iOS (at least when the static registrar was not enabled).

**Comment by rolfbjarne** [comment]
One point to have in mind is that it's possible to add protocols to an existing class at runtime... so we might only be able to cache parts of the ConformsToProtocol logic (the part where we use reflection to check if a managed class implements a certain interface / has a certain attribute).

**Comment by spouliot** [comment]
Good point, there's a `class_addProtocol` API, but AFAIK there's no matching removal API.

There's two parts that does reflection inside `ConformsToProtocol`

* `is_wrapper` for 3rd party types (640ms in the graph above)
* calls to `IsProtocol` (2.05s in the graph above)

So if we can cache only the reflection part we still win back 2/3 of the time.

Or, since the protocols conformance can't be removed, use the cache and fall back to native/selectors when it returns `false`. That would cache the `true` that came from the selector call.

**Comment by Therzok** [comment]
@spouliot I remember the protocol checks pop up on mono/xammac, but not that often in net6 - but when using dotnet trace (on release builds) I don't see it. It's possible it's inlined?

I guess it's the frame right under RemoveFromSuperview - this is a short trace taken after playing around in the IDE for a bit, 

<img width="1536" alt="image" src="https://user-images.githubusercontent.com/109974/173104421-93a7d822-5b92-4575-95cf-24b092859fda.png">

**Comment by Therzok** [comment]
Is the managed RemoveFromSuperview method called for direct bindings as well?

**Comment by spouliot** [comment]
@Therzok thanks for looking at it 😄 

> It's possible it's inlined?

No, it could be removed (by the linker/trimmer) if the dynamic registrar is removed. I thought it was not for VSfM but I'm not 💯% sure about it...

Also it's possible that `ConformsToProtocol` might not be called from `RemoveFromSuperview`. It's not clear under which circumstances it is (or not) called and, even if we knew, it could change between OS versions.

> Is the managed RemoveFromSuperview method called for direct bindings as well?

Yes, unless the linker/trimmer was able to remove it: like no `override` and only called from native code. Since we see it inside the trace then it will be called, even for direct bindings.

**Comment by Therzok** [comment]
I need to look into why I'm missing so many symbols, these stacks should all have had symbols in them.
