### ISSUE TITLE
error MSB4044: The "ComputeBundleResourceOutputPaths" task was not given a value for the required parameter "BundleIdentifier".

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-macios#14283]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/error-MSB4044:-The-ComputeBundleResourc/1677888)._

---
/usr/local/share/dotnet/packs/Microsoft.macOS.Sdk/12.1.301-preview.13.7/tools/msbuild/macOS/Xamarin.Shared.targets(1078,3): error MSB4044: The &quot;ComputeBundleResourceOutputPaths&quot; task was not given a value for the required parameter &quot;BundleIdentifier&quot;.

Project is a multi target application targetting net6.0, net6.0-macos, and net6.0-windows.

Source is available here: https://github.com/biltongza/CardIngestor/tree/msb4044

Steps to reproduce: dotnet build

2021 Macbook Pro M1 Pro
MacOS 12.2.1

The same project builds fine on Windows.

---
#### Feedback Bot on 2/27/2022, 11:21 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by rolfbjarne** [comment]
The problem is that no bundle identifier has been specified.

A bundle identifier can be specified in two ways:

1. Add the `ApplicationId` property to your csproj (Ingestor.Deamon.csproj in this case):

```xml
<PropertyGroup>
    <ApplicationId>com.mycompany.mybundleidentifier</ApplicationId>
</PropertyGroup>
```

2. Add an `Info.plist` file (to the same project), and add a `CFBundleIdentifier` entry.

That said, I'm keeping this open, because we should definitively show a better error message.
