### ISSUE TITLE
Objective C with Xamarin Binding not returning values

### ISSUE THREAD

**Issue by SaravananWipro** [xamarin/xamarin-macios#14763]
### Steps to Reproduce

1. Created Objective C static library with simple static methods.
2. Included static lib in Xamarin.iOS binding wrapper project and generated .dll
3. Created sample test project and added .dll reference then built app.

### Expected Behavior
Static library API should be called in Xamarin Test application and return correct values

### Actual Behavior
Static library called via Xamarin binding but outputs are not displayed, Not returning any values.

### Environment

```
=== Visual Studio Community 2019 for Mac ===

Version 8.7 (build 2037)
Installation UUID: 6df0ab54-6b35-4b65-b2b3-6418b729595f
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000122

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.122 (2020-02/c621c35ffa0) (64-bit)
	Package version: 612000122

=== Roslyn (Language Service) ===

3.7.0-6.20371.12+917b9dfae12e3b6cb266a3c062fb20a1e9d5fb06

=== NuGet ===

Version: 5.7.0.6702

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/2.1.505/Sdks
SDK Versions:
	2.1.505
	2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.0.0
	2.1.20
	2.1.13
	2.1.9
	2.0.5

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 13.0 (19234)
Build 13A233

=== Xamarin.Mac ===

Version: 6.20.2.2 (Visual Studio Community)
Hash: 817b6f72a
Branch: d16-7
Build date: 2020-07-18 18:44:59-0400

=== Xamarin.iOS ===

Version: 15.0.0.6 (Visual Studio Community)
Hash: 2771277e0
Branch: xcode13-ios
Build date: 2021-09-23 10:36:08-0400

=== Xamarin Designer ===

Version: 16.7.0.492
Hash: f5afe667d
Branch: remotes/origin/d16-7-vsmac
Build date: 2020-07-10 18:42:54 UTC

=== Xamarin.Android ===

Not Installed

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/wipro/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.7.0.13
Hash: 8380518
Branch: remotes/origin/dev/jmt/d16-7readconfig~2
Build date: 2020-07-23 22:38:02 UTC

=== Android Device Manager ===

Version: 16.7.0.18
Hash: 4b44bc1
Branch: remotes/origin/d16-7
Build date: 2020-07-23 22:38:26 UTC

=== Build Information ===

Release ID: 807002037
Git revision: b7706774ff5a1b761a7eb7f2d116d0d2c29ad87c
Build date: 2020-07-31 04:14:15-04
Build branch: release-8.7
Xamarin extensions: b7706774ff5a1b761a7eb7f2d116d0d2c29ad87c

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.4.0 Darwin Kernel Version 20.4.0
    Thu Apr 22 21:46:47 PDT 2021
    root:xnu-7195.101.2~1/RELEASE_X86_64 x86_64
```

**Comment by SaravananWipro** [comment]
Example Project
[StaticBinding.zip](https://github.com/xamarin/xamarin-macios/files/8506373/StaticBinding.zip)
[StaticLib.zip](https://github.com/xamarin/xamarin-macios/files/8506376/StaticLib.zip)
[StaticTest.zip](https://github.com/xamarin/xamarin-macios/files/8506377/StaticTest.zip)

**Comment by chamons** [comment]
Given the fact that the last issue you filed was due to an incorrect binding:

https://github.com/xamarin/xamarin-macios/issues/14693

the safe assumption is that your binding is incorrect. Reviewing your definition:

```
@interface StaticLib : NSObject
+(NSString *)consoleString:(NSString *)identifier;
+(BOOL) isTrue;
@end
```
and binding
```
    [BaseType(typeof(NSObject))]
    [Protocol]
    interface StaticLib {
        [Static, Export("consoleString:")]
        string ConsoleString(string key);

        [Static, Export("isTrue")]
        bool IsTrue();
    }
```

The first issue is that you are defining this as a protocol, while there are no protocols at all in your header file. 

Consider reviewing [Apple's documentation on protocols](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/WorkingwithProtocols/WorkingwithProtocols.html) and Xamarin's iOS [binding documentation](https://docs.microsoft.com/en-us/xamarin/cross-platform/macios/binding/). 

In this case, an invalid binding gave incorrect results, and your last error a build error. Incorrect bindings however can corrupt your stack, causing crashes far from the point of error.

Github issues are also not a valid place to discuss 3rd party bindings. Consider the [DotNetEvolution](https://aka.ms/dotnet-discord) discord server, stack overflow, or other communities for assistance.
