### ISSUE TITLE
Unable to get Forms app with extension uploaded into store

### ISSUE THREAD

**Issue by Matti-Koopa** [xamarin/xamarin-macios#14774]
### Steps to Reproduce
I'm not able to get a functioning build of my Xamarin Forms app into the Apple app store. My app contains a "share"-extension as well. It also uses the NuGet "Esri ArgGis Runtime", which does contain native libraries.
I can build the app fine in Release mode and have it run on an actual device. When uploading to the store though, I get a bunch of `ITMS-90171` errors though.
I believe the issue is with the included libraries not beeing correctly liked away. My IPA-file contains a `Frameworks` folder, which it probably shouldn't accoring to some internet threads.

I have tried making my own `.targets`-file and removing the files the Store complains about like so:
```
<Delete SessionId="$(BuildSessionId)" Files="$(_AppBundlePath)Frameworks/Runtimecore.framework/Runtimecore" />
<Delete SessionId="$(BuildSessionId)" Files="$(_AppBundlePath)Frameworks/libSkiaSharp.framework/libSkiaSharp" />
<Delete SessionId="$(BuildSessionId)" Files="$(_AppBundlePath)Frameworks/ArcGIS-arm64.framework/ArcGIS-arm64" />
```

While this does result in a successful upload, the app will just crash on startup due to missing frameworks.
Different linker settings also don't do much. My best guess is, that it's some wort of problem with apps containing native libraries and extensions.

### Expected Behavior
Successful upload to the store.

### Actual Behavior
Invalid bundle structure errors.

### Environment
Building and uploading on appcenter.ms. But the same happens on Visual Studio for Mac locally.
Appcenter settings: Xamarin.iOS 15.4, Xcode version 13.2.1

### Build Logs
[uploadlog](https://github.com/xamarin/xamarin-macios/files/8514366/uploadlog_censored.txt)
[ipacontenttree](https://github.com/xamarin/xamarin-macios/files/8514367/ipacontenttree_censored.txt)

I can share the solution code in private if needed.

**Comment by rolfbjarne** [comment]
The problem is that some files aren't signed correctly (the content in the Frameworks directory is correct, and must be there, otherwise the app will crash (as you've found out)).

Please build the .IPA from the command line as described here: https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/app-distribution/ipa-support?tabs=macos#building-via-the-command-line-on-mac, and then append "/bl:msbuild.binlog" to the msbuild command, and finally attach the resulting binlog.

If you want to keep information private, you can create a ticket here: https://developercommunity.visualstudio.com/report?space=41&entry=problem, and you should be able to add private attachments after creating the ticket. Please remember to add links between this issue and any new issue you create there so that we're aware they're the same issue (and that the developer community issue is just to provide private information).

**Comment by Matti-Koopa** [comment]
@rolfbjarne here is the linked ticket: https://developercommunity.visualstudio.com/t/Linked-ticket-for-Unable-to-get-Forms-a/10017592?space=41&entry=myfeedback
I uploaded the logfile there. Should I zip & upload the source code there as well?

**Comment by chamons** [comment]
@Matti-Koopa - Sorry for the trouble but multiple of us are unable to download the biglog or zip you added to that issue. 

Could you please e-mail the binlog to chhamo at microsoft dot com?

**Comment by rolfbjarne** [comment]
We ended up handling this in the developer community issue.
