### ISSUE TITLE
6.0.2xx workload manifest was not updated on nuget.org

### ISSUE THREAD

**Issue by filipnavara** [xamarin/xamarin-macios#14907]
The latest changes on the [6.0.2xx-preview14](https://github.com/xamarin/xamarin-macios/tree/release/6.0.2xx-preview14) branch were not published on the [NuGet workload manifest feed](https://www.nuget.org/packages/Microsoft.NET.Sdk.macOS.Manifest-6.0.200/12.1.302-preview.14.122).

**Comment by dalexsoto** [comment]
Hello, yeah this expected everyone should be using https://www.nuget.org/packages/Microsoft.NET.Sdk.macOS.Manifest-6.0.300 instead, we had to do a [preview13](https://www.nuget.org/packages/Microsoft.NET.Sdk.macOS.Manifest-6.0.200/12.1.301-preview.13.15) exception to this due to special circumstances but no one else should be using it. 

Is there any reason you want P14 bits?

**Comment by filipnavara** [comment]
> Is there any reason you want P14 bits?

Yes, the last released *non-preview* SDK is 6.0.200 and hence I should be getting bits from P14 for the workloads. Upgrading to 6.0.3xx *preview* is problematic in CI scenarios.

**Comment by dalexsoto** [comment]
> > Is there any reason you want P14 bits?
> 
> Yes, the last released _non-preview_ SDK is 6.0.2xx and hence I should be getting bits from P14 for the workloads. Upgrading to 6.0.3xx _preview_ is problematic in CI scenarios. For the same reason that VS4Mac is locked to P13 we are locked to P14 which is the latest workload on the 6.0.2xx SDK.

Fair enough :) On it.

**Comment by filipnavara** [comment]
6.0.300 SDK RTMed, so this is moot.
