### ISSUE TITLE
DatePicker mirror display in arabic 

### ISSUE THREAD

**Issue by ramziqoura** [xamarin/xamarin-macios#15057]
### Steps to Reproduce

1.  Run App
2. Select  DatePicker, error in display days mirrors
3. Move left to right, day names not linked with day number
4. Move again right to left month is not the first look month when open it 

### Environment

<details>
<summary>Version information</summary>
```
```
</details>

### Build Logs

[DatePickerDemo.zip](https://github.com/xamarin/xamarin-macios/files/8717561/DatePickerDemo.zip)

**Comment by chamons** [comment]
I believe this is behavior from Apple. I recreated almost all of your sample in Obj-C:

[DatePickerNative.zip](https://github.com/xamarin/xamarin-macios/files/8719312/DatePickerNative.zip)

and I believe I see the same behavior, though it is difficult to tell exactly due to the short description in the issue.

Please review, and if I'm missing something feel free to reopen with details.
