### ISSUE TITLE
AVAudioEngine InputNode available only on TvOS

### ISSUE THREAD

**Issue by vadd98** [xamarin/xamarin-macios#15093]
I'm trying to develop a mobile app for iPhone which needs to record audio from microphone. I'm trying to use AVAudioEngine but it seems I can't use the InputNode

### Steps to Reproduce

1. Create a Xamarin.iOS project targeting iOS 15
2. Try to get InputNode from AVAudioEngine

### Expected Behavior
Get InputNode from AVAudioEngine

### Actual Behavior
Returns null and warning that it is only supported on TvOS

### Environment
Xamarin.iOS version 15.8.0.3

<details>
<summary>Version information</summary>
```
```
</details>

**Comment by vadd98** [comment]
The warnings I'm getting while building are:

> "This call site is reachable on: 'iOS' 15.0 and later, 'maccatalyst' 15.0 and later. 'AVAudioEngine.InputNode' is only supported on: 'tvos' 11.0 and later."

> This call site is reachable on: 'iOS' 15.0 and later, 'maccatalyst' 15.0 and later. 'AVAudioEngine.InputNode.get' is only supported on: 'tvos' 11.0 and later.

When I try to debug the code in the simulator, when I try to use the InputNode I get null but no error is thrown. I don't know if entitlements can resolve the issue, by the way I already get warnings in the IDE and at build time, so I think that even with entitlements those warnings will remain.

If needed I can provide sample code, by the way I can assure that in order to get the warning is enough to create a Xamarin.iOS project, instantiate an AVAudioEngine and try to get the InputNode from it

**Comment by chamons** [comment]
Ok, those warnings are from https://github.com/xamarin/xamarin-macios/issues/10170 which is fixed in the very latest MAUI bits, which should now be stable (or will be in a few hours).

The fact that you are getting null from that API suggests that it is an API usage issue, not a bug. Here is a sample project that I believe is using that API:

https://github.com/xamarin/ios-samples/blob/main/ios10/SpeakToMe/SpeakToMe/ViewController.cs#L84

And it has a number of Info.plist keys set:

https://github.com/xamarin/ios-samples/blob/main/ios10/SpeakToMe/SpeakToMe/Info.plist#L22-L25

**Comment by vadd98** [comment]
Ok thanks, so for now I'll ignore those warnings and I'll give a look to the sample project you linked and I'll let you know if this solved the issue

**Comment by vadd98** [comment]
I updated to the latest version and warnings disappeared.
 It also works in the simulator (I have no physical devices at the moment to test), so I think the problem is solved
