### ISSUE TITLE
System.Void ObjCRuntime.DisposableObject::Dispose() GetEmptyBackIndicatorImage

### ISSUE THREAD

**Issue by seedunk** [xamarin/xamarin-macios#15157]
`Can't resolve the reference 'System.Void ObjCRuntime.DisposableObject::Dispose()', referenced from the method 'UIKit.UIImage Xamarin.Forms.Platform.iOS.NavigationRenderer/ParentingViewController::GetEmptyBackIndicatorImage()' in 'Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'. (MT2101) `
when I build iOS app to App Store use release iPhone link action is link all

**Comment by rolfbjarne** [comment]
You didn't include your version information, but I believe the problem is that you need to update Xamarin.iOS to the latest version.

If that's already the case, please provide:

1. Full version information: https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#version-information
2. A binary build log: https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#build-logs

and reopen this issue.
