### ISSUE TITLE
MKTileOverlay passing erroneous values to MKTileOverlayPath

### ISSUE THREAD

**Issue by albielee** [xamarin/xamarin-macios#15247]
I am unable to load custom tiles on iOS because the tile data is incorrect.
Originally posted the problem on StackOverflow:
https://stackoverflow.com/questions/72532769/why-does-mktileoverlaypath-contain-these-values

### Steps to Reproduce

1.  Install Xamarin.Forms.Maps
2.  Create a custom Map Renderer
3.  Create a custom MKTileOverlay
4.  Use the MKTileOverlay in the custom Map Renderer
5.  Inside the Custom MKTileOverlay, override the URLForTilePath method
6.  Inspect the values being passed to MKTileOverlayPath in the URLForTilePath method

### Expected Behavior

MKTileOverlayPath contains valid data.
For example ContentScaleFactor should be 1 or 2. Not what it is below.

### Actual Behavior

MKTileOverlayPath contains incorrect data.

Example:
X = 4355653632
Y = 40
Z = 6143813312
ContentScaleFactor = 3.34872044616471E-314

### Environment

<details>
<summary>Version information</summary>

```
Microsoft Visual Studio Enterprise 2022
Version 17.2.0
VisualStudio.17.Release/17.2.0+32505.173
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

Azure App Service Tools v3.0.0   17.2.388.21846
Azure App Service Tools v3.0.0

C# Tools   4.2.0-4.22252.24+47cdc16a21bbb8a4aadfb666b011e2059e1be5d2
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.2.20 (482eb2a)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.2.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Visual Basic Tools   4.2.0-4.22252.24+47cdc16a21bbb8a4aadfb666b011e2059e1be5d2
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.1.0-beta.22178.3+6da0245a7ce4bb8483b8d1f2993c8ecaea967ad9
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.2.0.174 (d17-2@fb414d4)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.2.0.244 (remotes/origin/d17-2@197e1a0b7)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.2.15 (2e3b60e)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   12.3.0.3 (d17-2/bbba5a2)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: adf1bc4
    Java.Interop: xamarin/java.interop/d17-2@9760f0a9
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.38.2@7b1e016
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-2@fc3c2ac


Xamarin.iOS and Xamarin.Mac SDK   15.10.0.1 (568bdb24e)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

</details>

### Build Logs
[msbuild.zip](https://github.com/xamarin/xamarin-macios/files/8881106/msbuild.zip)

### Example Project (If Possible)

[ios-tiles-test.zip](https://github.com/xamarin/xamarin-macios/files/8881112/ios-tiles-test.zip)

**Comment by dalexsoto** [comment]
Hello,

I had a look at this and I do not think I can reproduce this:
![image](https://user-images.githubusercontent.com/204671/176672372-aeacb141-f7c8-45cb-9675-25a45c607edf.png)

And from the image below the tile seems correctly positioned to me:
![image](https://user-images.githubusercontent.com/204671/176670929-4993a107-0b76-4197-8c30-8eaee3099471.png)

> For example ContentScaleFactor should be 1 or 2. Not what it is below.

While Apple in their [docs](https://developer.apple.com/documentation/mapkit/mkoverlayrenderer/1451931-contentscalefactor?language=objc) state that, I think the guidance is not up to date since you can definitely get a [3x scale factor](https://developer.apple.com/design/human-interface-guidelines/foundations/images/#scale-factors).

I also played around a little bit with the sample by avoiding `LocalTilesOverlayRenderer` by using `MKTileOverlay` directly using a templated url and compared both results and they match visually.

```csharp
protected override void OnElementChanged(ElementChangedEventArgs<View> e)
{
    base.OnElementChanged(e);

    if (e.OldElement != null)
    {
        nativeMap = Control as MKMapView;
    }

    if (e.NewElement != null)
    {
        nativeMap = Control as MKMapView;

        //var ol = new LocalTilesOverlayRenderer();
        //nativeMap.AddOverlay(ol, MKOverlayLevel.AboveLabels);

        // Using native MKTileOverlay
        var template = "https://tile.openstreetmap.org/{z}/{x}/{y}.png";
        var ol = new MKTileOverlay(template);

        nativeMap.AddOverlay(ol, MKOverlayLevel.AboveLabels);

        nativeMap.OverlayRenderer = (mv, o) => GetOverlayRenderer(mv, o);
    }
}
```

and finally I double checked the bindings just in case and they are correct.

```objective-c
typedef struct {
    NSInteger x;
    NSInteger y;
    NSInteger z;
    CGFloat contentScaleFactor; // The screen scale that the tile will be shown on. Either 1.0 or 2.0.
} MKTileOverlayPath;
```

```csharp
[StructLayout (LayoutKind.Sequential)]
public struct MKTileOverlayPath
{
	public /* NSInteger */ nint X;
	public /* NSInteger */ nint Y;
	public /* NSInteger */ nint Z;
	public /* CGFloat */ nfloat ContentScaleFactor;
}
```

Xamarin.iOS is just a thin layer on top of the Objective-C iOS SDKs and while it is possible to have a bad bindings it is a rarely occurrence specially in these heavy usage areas like Maps were something like this should have been caught a long time ago, my guess is that you may have been unlucky and hit a bug in the native Apple SDK object.

If you continue to experience this I would recommend firing up Xcode and do a line by line sample on both C# and Objective-c/swift this usually lets you spot what you may be missing. Please feel free to reopen if you have further information.
