### ISSUE TITLE
Xamarin.Mac with included OpenTK package crippled to an ancient OpenGL Shading Language version - v1.20 (released 2006)

### ISSUE THREAD

**Issue by smlehbleh** [xamarin/xamarin-macios#15251]
Steps to reproduce:
Follow the official Xamarin.Mac OpenTK example (https://docs.microsoft.com/en-us/xamarin/mac/platform/opentk - updated only a month ago in May 2022) 
Call GL.GetString(StringName.ShadingLanguageVersion)
Alternatively, attempt to compile a GLSL shader with the preprocessor define: ‘#version 150’ or higher.

Expected behaviour:
Support for the OpenGL version which the macOS software supports, i.e. Core 3.2 or 4.1 depending on macOS version (and accompanying GLSL version, i.e. 3.30).

Actual behaviour:
GL.GetString(StringName.ShadingLanguageVersion) returns 1.20 and shaders with ‘#version 150’ or higher will fail to compile.
There doesn’t appear to be any way to create a newer GL/GLSL version context.

Environment:
Visual Studio for Mac 17.0.2
macOS 12.4, Apple M1 Pro 

Example Project:
Follow official example: https://docs.microsoft.com/en-us/xamarin/mac/platform/opentk and retrieve GLSL version with:
GL.GetString(StringName.ShadingLanguageVersion)

**Comment by rolfbjarne** [comment]
In .NET 6 we're not shipping OpenTK ourselves anymore, instead you'll use the (much more up-to-date) upstream version from https://www.nuget.org/packages/OpenTK / https://github.com/opentk/opentk.

I'm not sure if the OpenTK package will work with Xamarin.Mac, but it might be worth a try.

Closing as won't fix, since we're not going to update our own OpenTK package.
