### ISSUE TITLE
native reference error on ios in xamarin forms

### ISSUE THREAD

**Issue by llzz19851985** [xamarin/xamarin-macios#15573]
detail as here ,donnot know why is closed!! https://github.com/xamarin/xamarin-macios/issues/15394

**Comment by KuzonCode** [comment]
@llzz19851985 It appears it was closed because of the following
![image](https://user-images.githubusercontent.com/8284579/180906910-58f2acf8-3eeb-4719-8327-15b33a016be6.png)

**Comment by dalexsoto** [comment]
Hello, the problem seems to be with the Visual Studio on Windows integration, unfortunately that team is not accesible via GitHub. You will need to file an issue using Visual Studio itself so please file an issue via [these instructions](https://developercommunity.visualstudio.com/report?space=8&entry=problem), by doing so VS will collect the necessary logs and you can provide the info to the team that can assist you with your issue.
