### ISSUE TITLE
[Meta] Xcode 14.0 Support for .NET 6/7 and MAUI

### ISSUE THREAD

**Issue by dalexsoto** [xamarin/xamarin-macios#16164]
⚠️ Update 🚨

Please use Visual Studio 2022 Version 17.3.6, this brings Xcode 14.0 support to .NET 6. 

Thank you for your patience!

The macios team!

-------

<details>
  <summary>Click me</summary>

Apple released Xcode 14.0 on September 12, 2022 we are working to get our Xcode 14 support release out in the meantime if you use MAUI .NET 6/7 **we recommend you to not upgrade to Xcode 14 just yet** and keep using Xcode 13.4.1.

If you updated to Xcode 14 please revert back to Xcode 13.4.1 from the [downloads](https://developer.apple.com/download/all/) page in the Apple Developer Portal and continue to use it.

We will keep this issue updated as we go to have the final builds declared.

If you are using Xamarin.iOS on Visual Studio or VS for Mac update to the latest stable to get Xcode 14 support.

Thank you for your patience!

The macios team!

</details>

**Comment by Martinedo** [comment]
for Xcode 13.4.1 follow [these steps](https://stackoverflow.com/a/73714263/3495516). You can have both versions 14 and 13.4.1 installed at the same time and switcht between them.

**Comment by J-Swift** [comment]
Is there any way to get an early preview of this effort similar to what was provided in https://github.com/xamarin/xamarin-macios/issues/15954? Its been nearly 3 weeks at this point and I haven't been able to get any builds out to testers (or even test ios 16 support on my machine) yet.

**Comment by mlancione** [comment]
Any update on XCode 14 support for .NET 6? Going forward can we expect same day support for new XCode releases as was the case for Xamarin releases in the past?

Did anything change in the XCode 14 final build that was not present in the multiple Beta releases that have been released for months now? Ideally Apple's early beta process can allow for the required changes to be made up front.

**Comment by stcmz** [comment]
Even with Xcode 13.4.1, when I connect from Visual Studio Version 17.3.5 on my PC it says
> The Xcode version installed on the Mac (13.4) is not compatible with this version of Visual Studio. This may cause unexpected warnings or errors when building and deploying iOS projects. Please install Xcode '13.0'. To download a specific version of Xcode, visit: https://developer.apple.com/downloads.

Should I just ignore the warning?

**Comment by AndreasReitberger** [comment]
@dalexsoto 
Is there any ETA for this? 
I'm not able to run a MAUI app on iOS, even with Xcode 13.4 using the latest version of VS 2022 Preview.
Thank you!

**Comment by g4mb10r** [comment]
@dalexsoto MAUI devlopment has been broken since September 12.  Any ETA?

**Comment by J-Swift** [comment]
I understand the lack of resources on the team, and the workload the team is under, but the lack of communication for such a high priority / high impact issue is _extremely_ concerning for me and my company. It is very hard to continue to advocate for Maui as a solution when these sorts of things are left to linger and my only recourse is to hope its fixed the next day I come into the office. It also leaves me looking extremely incompetent as the team lead when my only answer is for when its going to come out is "I dont know, I hope sometime soon".

SIDENOTE: Because of the signaling that Xamarin Forms was EOL basically as soon as Maui hit GA, we did our greenfield app in Maui. Now we are stuck in a very tough position of Maui definitely not being GA, and legacy being unsupported. We aren't live yet with the app so its not "showstopping" bad right now, but what is ios 17 going to look like? What is the issue here, and what can we do to remedy it in the future when we _know_ we will come up against this issue again?

My gut says that the workload system is an overall liability, otherwise you would cut a preview nuget and let people continue on their way with the prerelease-bits.

**Comment by dalexsoto** [comment]
Sorry folks we are still ironing out all the details that Xcode 14.0 brought to the table, it broke some assumptions that we had regarding our CI infrastructure and how we build the SDKs. In a nutshell Xcode 14 is shipping iOS and tvOS 16.0 and MacCat 15.4 and macOS 12.4 SDKs if you see this from the MAUI standpoint is kind of complicated since it means some code needs 16.0 but MacCat SDK is not there. For the old Xamarin SDKs this was not much of a problem since all of it shipped in a single package iOS and macOS support but for .NET 6+ this is a different story NuGet packages, .NET workloads, VS releases, etc. 

As a team we are definitely working out so something like this does not happen in the future, because we are OpenSource you can see all of the work happening on our different branches like:

* main
* release/6.0.4xx-xcode14
* release/6.0.4xx
* release/7.0.1xx-rc2
* release/7.0.1xx-xcode14-rc2
* xcode14.1

This time around we could not have a public .NET preview with Xcode 14.0 because multiple factors but as I mentioned before we are working out these issues so we do not end up in the same situation next year or in a future Xcode release.

That said Visual Studio 2022 version 17.3.6 is now live and this brings Xcode 14 support to .NET 6 and MAUI. Sorry for all the inconveniences! Please let us know if you run into any issues!
