### ISSUE TITLE
UIViewController setNeedsUpdateOfSupportedInterface

### ISSUE THREAD

**Issue by mollea3** [xamarin/xamarin-macios#16292]
As per the apple Beta Release [notes](https://developer.apple.com/documentation/ios-ipados-release-notes/ipados-16-release-notes), UIKIt has some deprecations :
**UIKit**
**Deprecations**
[UIViewController shouldAutorotate] has been deprecated is no longer supported. [UIViewController attemptRotationToDeviceOrientation] has been deprecated and replaced with [UIViewController setNeedsUpdateOfSupportedInterfaceOrientations].

**Workaround**: Apps relying on shouldAutorotate should reflect their preferences using the view controllers supportedInterfaceOrientations. If the supported orientations change, use `-[UIViewController setNeedsUpdateOfSupportedInterface

Latest Xamarin-ios-16.0.0.72  doesn't have the Support to **UIViewController setNeedsUpdateOfSupportedInterface** 

Can we get support for this, As we are utilising the UIViewController.

**Comment by tj-devel709** [comment]
Thank you for the feedback @mollea3. We will look into this.

Note to self: setNeedsUpdateOfSupportedInterface seems to be coming from the Xcode14.1 Beta 3 release notes but was not in our xcode 14.1 beta 3 diff.

**Comment by tj-devel709** [comment]
@mollea3, it appears to me that in the workaround suggested by Apple, they may be referring to "setNeedsUpdateOfSupportedInterfaceOrientations" instead of "setNeedsUpdateOfSupportedInterface". I do not see any web documentation by Apple with "setNeedsUpdateOfSupportedInterface" and inside the header files, "shouldAutorotate" mentions using "setNeedsUpdateOfSupportedInterfaceOrientations". 
```
// New Autorotation support.
@property(nonatomic, readonly) BOOL shouldAutorotate API_DEPRECATED("Update supported interface orientations and call setNeedsUpdateOfSupportedInterfaceOrientations to indicate a change.", ios(6.0, 16.0)) API_UNAVAILABLE(tvos);
```

I believe that setNeedsUpdateOfSupportedInterfaceOrientations should be working in your version of Xamarin.iOS. Please let us know if this helps!

**Comment by dalexsoto** [comment]
As @tj-devel709 mentioned the API is there for the Xamarin.iOS version you are using 

https://github.com/xamarin/xamarin-macios/blob/12aaa79efd7aefb65a3875e8c42da75e473077c6/src/uikit.cs#L16566-L16568

Hope this helps, feel free to re-open or file a new issue if you run into other issues.
