### ISSUE TITLE
Apple Watch support completely broken in all versions - ITMS-90398: Invalid WatchKit Support

### ISSUE THREAD

**Issue by jahmai-ca** [xamarin/xamarin-macios#16499]
PLEASE DO NOT CLOSE THIS AS DUPLICATE UNLESS #16120 IS RE-OPENED.

### Steps to Reproduce

Build any project that contains a watchOS extension and submit it to the App Store (I have provided the sample but it is just a slightly modified default template so that it can pass other upload tests).

### Expected Behavior

This should work.

### Actual Behavior

You get an email like this:

> Dear Developer,
> 
> We identified one or more issues with a recent delivery for your app, "labsiitest" 1.0 (1.0). Please correct the following issues, then upload again.
> 
> ITMS-90398: Invalid WatchKit Support - The bundle contains an invalid implementation of WatchKit. The app may have been built or signed with non-compliant or pre-release tools. Visit developer.apple.com for more information.
> 
> Best regards,
> 
> The App Store Team
> 

### Environment

<details>
<summary>Version information</summary>

```
Visual Studio Community 2022 for Mac
Version 17.3.4 (build 4)
Installation UUID: dec5c782-26e3-4e09-9017-2e6a936b7e2e

Runtime
.NET 6.0.5 (64-bit)
Architecture: X64

Roslyn (Language Service)
4.3.0-3.22312.2+52adfb8b2dc71ed4278debcf13960f2116868608

NuGet
Version: 6.2.1.2

.NET SDK (x64)
SDK: /usr/local/share/dotnet/sdk/6.0.400/Sdks
SDK Versions:
	6.0.400
	6.0.302
	6.0.301
	5.0.408
	5.0.407
	5.0.406
	5.0.405
	5.0.404
	5.0.403
	5.0.402
	5.0.401
	5.0.400
	5.0.302
	5.0.301
	5.0.203
	5.0.202
	5.0.201
	5.0.103
	5.0.102
	5.0.101
	5.0.100
	3.1.423
	3.1.422
	3.1.421
	3.1.420
	3.1.419
	3.1.418
	3.1.417
	3.1.416
	3.1.415
	3.1.414
	3.1.413
	3.1.412
	3.1.411
	3.1.410
	3.1.409
	3.1.408
	3.1.407
	3.1.406
	3.1.405
	3.1.404
	3.1.403
	3.1.402
	3.1.401
	3.1.302
	3.1.301
	3.1.300
	3.1.202
	3.1.200
	3.1.102
	3.1.101
	3.1.100
	3.0.101
	3.0.100
	2.1.701
	2.1.700
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.8
	6.0.7
	6.0.6
	5.0.17
	5.0.16
	5.0.15
	5.0.14
	5.0.13
	5.0.12
	5.0.11
	5.0.10
	5.0.9
	5.0.8
	5.0.7
	5.0.6
	5.0.5
	5.0.4
	5.0.3
	5.0.2
	5.0.1
	5.0.0
	3.1.29
	3.1.28
	3.1.27
	3.1.26
	3.1.25
	3.1.24
	3.1.23
	3.1.22
	3.1.21
	3.1.20
	3.1.19
	3.1.18
	3.1.17
	3.1.16
	3.1.15
	3.1.14
	3.1.13
	3.1.12
	3.1.11
	3.1.10
	3.1.9
	3.1.8
	3.1.7
	3.1.6
	3.1.5
	3.1.4
	3.1.2
	3.1.1
	3.1.0
	3.0.1
	3.0.0
	2.1.23
	2.1.22
	2.1.21
	2.1.20
	2.1.19
	2.1.18
	2.1.17
	2.1.16
	2.1.15
	2.1.14
	2.1.13
	2.1.12
	2.1.11

Xamarin.Profiler
Version: 1.8.0.19
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 14.0 (21335)
Build 14A309

Xamarin.Mac
Version: 8.12.0.2 (Visual Studio Community)
Hash: 87f98a75e
Branch: d17-3
Build date: 2022-07-25 20:18:54-0400

Xamarin.iOS
Version: 16.0.0.72 (Visual Studio Community)
Hash: 6756a1146
Branch: release/6.0.4xx-xcode14
Build date: 2022-09-21 08:51:06-0400

Xamarin Designer
Version: 17.3.0.208
Hash: 0de472ea0
Branch: remotes/origin/d17-3
Build date: 2022-09-01 17:18:13 UTC

Xamarin.Android
Version: 13.0.0.0 (Visual Studio Community)
Commit: xamarin-android/d17-3/030cd63
Android SDK: /Users/ivanicin/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		12.0 (API level 31)
		11.0 (API level 30)
		10.0 (API level 29)
		9.0  (API level 28)

SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 33.0.2
SDK Build Tools Version: 33.0.0

Build Information: 
Mono: dffa5ab
Java.Interop: xamarin/java.interop/d17-3@7716ae53
SQLite: xamarin/sqlite/3.38.5@df4deab
Xamarin.Android Tools: xamarin/xamarin-android-tools/main@14076a6

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.12
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.3.0.23
Hash: 965bf40
Branch: remotes/origin/d17-3
Build date: 2022-09-01 17:18:18 UTC

Android Device Manager
Version: 0.0.0.1169
Hash: fafb1d5
Branch: fafb1d5
Build date: 2022-09-01 17:18:18 UTC

Build Information
Release ID: 1703040004
Git revision: 5ec72d3a5e7c84e88be448c0ff9e58839e0913e9
Build date: 2022-09-01 17:16:20+00
Build branch: release-17.3
Build lane: release-17.3

Operating System
Mac OS X 12.6.0
Darwin 21.6.0 Darwin Kernel Version 21.6.0
    Mon Aug 22 20:17:10 PDT 2022
    root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64

```

</details>

### Build Logs

[Log.txt](https://github.com/xamarin/xamarin-macios/files/9883783/Log.txt)

### Example Project (If Possible)

[WatchTest.zip](https://github.com/xamarin/xamarin-macios/files/9883784/WatchTest.zip)

**Comment by jahmai-ca** [comment]
I have cloned #16120 because the author doesn't believe Microsoft will fix this, but I disagree, and at the very least I want to aggitate more for them to do so.

**Comment by jahmai-ca** [comment]
@dalexsoto The author of the linked issue said you might have some input on this one? If I am wrong maybe you can indicate who at Microsoft is best positioned to comment?

Microsofts support policy states that WatchOS is EOL but support is ongoing until next year. To me that means that I should be able to continue to ship Xamarin.watchOS products until then.

**Comment by bigDave1357** [comment]
It would also be useful to get a steer from Microsoft that specifically explains their plans for WatchOS support with Xamarin. If that's really going to be ended, what is going to replace it? Anything? Will MAUI be developed to include it? Developers need a roadmap and I don't see one.

**Comment by beeradmoore** [comment]
@bigDave1357 , MS staff in the past have said watchOS was used minimally by developers and therefor support was not added in .NET 6 or 7. Unless there is proposals/requests to have it in .NET 8 it won't be added. If MS don't hear that people use this then why would they bother putting effort into it?

WearOS works with .net6-android (heck I even [accidentally deployed the MAUI sample app](https://twitter.com/beeradmoore/status/1529276251030298624) onto my watch) but I think that is mostly on accident of how closely tied tooling and SDKs for WearOS and Android are. Considering MS staff seemed surprised that this worked I assume they didn't either. Because of that I don't think I'll be rolling with WearOS apps with .net6 as it seems like support and (potentially required?) optimisation for wearable device is non-existant.

Both of those points should be made into a discussion thread rather than on this issue as it sidetracks from the problem that this issue is about.

Regarding watchOS TestFlight, just hit the same thing right now. My TestFlight expires in 4 hours so I guess I am releasing a beta app with no watchOS component.

**Comment by ivanicin** [comment]
> @bigDave1357 , MS staff in the past have said watchOS was used minimally by developers and therefor support was not added in .NET 6 or 7. Unless there is proposals/requests to have it in .NET 8 it won't be added. If MS don't hear that people use this then why would they bother putting effort into it?

@beeradmoore This is not correct. Currently the most upvoted issue is the one that asks for support for independent watchOS apps. And I am quite sure that interest for watchOS is miles ahead of tvOS and probably very close to macOS (which is also very far from iOS and Android).

Even worse, this should not be the reason if Xamarin is Xamarin, but it is not anymore. Xamarin was made with idea that you have 100% of capabilities of native developers, while you can share some code and save costs. I was sold on that and I am definitely looking for my way out now (at least for Apple platforms). But Xamarin is not about mobile developers anymore, it is about Microsoft and its internal goals. If you think that I am not relevant, then the man who started Xamarin Miguel de Icaza has said that Xamarin doesn't live up to its vision anymore and that he is sorry that he can't use his own product for his own projects.

So that is not the reason why watchOS is not supported. You can find reasons among those things:

- bitcode requirement made this project a bit more complicated than other projects (ironically Apple has pulled this requirement few weeks ago)
- Xamarin.Forms has never been developed for watchOS and current management is only interested in MAUI and is tight on budget
- Apple shows clear signs that watchOS will work only with SwiftUI in the future and Xamarin can't support this without big investments that Microsoft is not willing to make

**Comment by beeradmoore** [comment]
The second most upvoted issue is for "independent watchOS" apps. Meaning distributed without the parent app. It has 16 👍 over 3 years. I don't think this is a reflection of the second most important issue to iOS developers, but a failing in how Xamarin team wish people to upvote issues. Where are all the people tripping over themselves requesting for net6.0-watchOS, net7.0-watchOS, net8.0-watchOS? 

tvOS happens because tvOS is [basically iOS](https://twitter.com/davidortinau/status/1519483825629368321), so binding it is super easy. Sounds like very similar thing to what I said above about WearOS and how its basically Android. From that independent watchOS issue you can see XamDevs saying it would require a major toolchain change (possibly what you were mentioning with bitcode being dropped?)

But watchOS being so different also lines up with what was said [here](https://twitter.com/davidortinau/status/1519303524726849536), "high cost, low usage". Not having watchOS would not make me not choose the platform, but it certainly doesn't help.
 
 Don't get me wrong, I want it. I have apps that I need it, and now have to make major workarounds on and learn new languages to continue to support. It sucks. I have said several times myself that I need to make the request for .NET 8 support but I assume like others they have given up because they acknowledge they are in a very low minority of people who want this and a team too small to deliver it.
 
 I don't get what you are saying about XF and watchOS. You can use watchOS in XF apps, I exclusively use watchOS in XF apps. I don't think XF (+MAUI) should be developed for watch/WearOS. The implied usage there is that you can slap down a Gird and a button and boom, now you have a wearable app that runs on both major platforms. This is such a moonshot and would lack so many features. BUT, there should be native support for watch/WearOS in .NET. To quote what you said 
 
 > Xamarin was made with idea that you have 100% of capabilities of native developers
 
 Yes. watch/WearOS should be supported in .NET 6/7/8 with 100% of capabilities of native. watchOS independent apps should be supported in .NET 6/7/8. But what the team can accomplish seems to have been nerfed, not sure on the exact reason but that doesn't matter. We can't have everything we want and it sucks.

**Comment by jahmai-ca** [comment]
Regardless of the future of watchOS for net6 or MAUI, I would very much like Microsoft to respond to the question of support for the current Xamarin.iOS _product_ (not the TFM) that is experiencing this issue. My reading of the Xamarin.iOS support document is that it should be supported until May 2024. The Xamarin.iOS _product_ includes watchOS support as a feature.

https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin

This, to me, is a bug in the currently supported product, and it's not acceptable to point to the future obsolence as a reason to not address the issue.

**Comment by bigDave1357** [comment]
> "it's not acceptable to point to the future obsolence as a reason to not address the issue."

I actually think it can be acceptable, but only when an issue has arisen at a point in time very close to the end of the support window. That's not the case here, and so Microsoft should absolutely be fixing this problem.

We all clearly have to consider the future of our apps regarding Microsoft's support statement for Xamarin, but right now that should not be on the table. Fix it, please, Microsoft.

**Comment by ivanicin** [comment]
> This, to me, is a bug in the currently supported product, and it's not acceptable to point to the future obsolence as a reason to not address the issue.

I’ve subscribed to this issue to give you some support and then I have received some comments that I felt like replying. 

Anyway in theory you are right. But the project got into the situation where it is hard to say what is wrong and what is right. 

I wanted to find that tweet of Miguel that I quoted but it is likely he has deleted that. There he also says that Microsoft has cut the budget for Xamarin. But here is the newer tweet: https://twitter.com/migueldeicaza/status/1584613254990790656?s=46&t=__ROTVYKk2l8q7ZyfQvVLQ

So it is a double edged sword - budget was cut and Microsoft imposed over ambitious goals and incompetent young managers that will support them. 

The only solution is that Microsoft accepts its errors, pours as much money as needed to fix the situation and go ahead. But that is Ballmer’s style, Satya will more likely further cut the costs. 

The other possible solution is to spin off Xamarin like it happened before when one company failed to maintain Mono. 

In the absence of good solutions you have to play with bad solutions. Honestly not fixing this is very bad. But it doesn’t mean that there aren’t worse outcomes than that in this situation. 

Just for the record the share extension for the Mac doesn’t work for more than full two years now. It is recognized as the bug, but that’s all.

**Comment by dalexsoto** [comment]
Hello everyone!

I see you had a great discussion over the weekend, we have a [fix in progress](https://github.com/xamarin/xamarin-macios/pull/16526) for this issue that will come along when we push Xcode 14.1 to stable if all goes well. 

The other thing I wanted to point out is that currently there a no plans to support watchOS on .NET 8+.

**Comment by jahmai-ca** [comment]
> Hello everyone!
> 
> I see you had a great discussion over the weekend, we have a [fix in progress](https://github.com/xamarin/xamarin-macios/pull/16526) for this issue that will come along when we push Xcode 14.1 to stable if all goes well.
> 
> The other thing I wanted to point out is that currently there a no plans to support watchOS on .NET 8+.

Thank you Alex for response and the bug fix. It is disappointing that watchOS won't be supported in any current/future NET release, but with this fix it gives me time to come up with a strategy to work around that.

**Comment by jahmai-ca** [comment]
@dalexsoto 

Unfortunately the fix for this issue just unlocks a new issue... I used the .targets snippet from the PR locally and built and distributed to AppStore Connect, and how get this email:


```Dear Developer,

We identified one or more issues with a recent delivery for your app, <snip>. Please correct the following issues, then upload again.

ITMS-90482: Invalid Executable - The executable '<snip>' contains bitcode.

Best regards,

The App Store Team
```

So I tried to set this in the project file:

`<MtouchEnableBitcode>False</MtouchEnableBitcode>`

But then building fails with:

`MTOUCH : error MT0145: Please use device specific builds on WatchOS when building for Debug.`

I assume MtouchEnableBitcode is somehow tightly connected to Release builds in Xamarin?

Any workaround possible?

**Comment by jahmai-ca** [comment]
I expect the bitcode issue is caused by this line:

https://github.com/xamarin/xamarin-macios/blob/f28c7f8d3ec165eb3b8a381422fd9477f004b5ee/tools/mtouch/Application.mtouch.cs#L648

This check can possibly just be removed?

**Comment by jahmai-ca** [comment]
Ok, I am pleased to update that the fix in the related PR does actually work, and my problem was not using the latest Xamarin.iOS build.

Here's what I did to get it working:

1. Add the PR MSBuild target to `MyApp.Watch` project _after_ `<Import Project="$(MSBuildExtensionsPath)\Xamarin\WatchOS\Xamarin.WatchOS.App.CSharp.targets" />`. Note that this is the MS fix and this step isn't required once the fix is released.

```
	<Target Name="_CompileToNative" DependsOnTargets="$(_CompileToNativeDependsOn)"
		Inputs="$(_NativeWatchApp)"
		Outputs="$(_NativeExecutable);$(_AppBundlePath)_WatchKitStub\WK">

		<PropertyGroup>
			<!-- Remove any arm64e slices -->
			<WKDittoArchitectures Condition="'$(WKDittoArchitectures)' == ''">--arch arm64_32 --arch arm64 --arch armv7k</WKDittoArchitectures>
		</PropertyGroup>

		<Ditto
			SessionId="$(BuildSessionId)"
			Condition="'$(IsMacEnabled)'"
			AdditionalArguments="$(WKDittoArchitectures)"
			ToolExe="$(DittoExe)"
			ToolPath="$(DittoPath)"
			Source="$(_NativeWatchApp)"
			Destination="$(_AppBundlePath)$(AssemblyName)"
		/>
		<MakeDir SessionId="$(BuildSessionId)" Condition="'$(IsMacEnabled)' == 'true'" Directories="$(_AppBundlePath)_WatchKitStub" />
		<Ditto
			SessionId="$(BuildSessionId)"
			Condition="'$(IsMacEnabled)'"
			AdditionalArguments="$(WKDittoArchitectures)"
			ToolExe="$(DittoExe)"
			ToolPath="$(DittoPath)"
			Source="$(_NativeWatchApp)"
			Destination="$(_AppBundlePath)_WatchKitStub\WK"
		/>
		<RemoveDir SessionId="$(BuildSessionId)" Condition="'$(IsMacEnabled)' == 'true'" Directories="$(AppBundleDir).dSYM" />
	</Target>
```

2. In the same project in 1., add the `WKDittoArchitectures` to each of my build configurations that matches the target architectures, e.g. for simulator `<WKDittoArchitectures>--arch i386</WKDittoArchitectures>` and for device `<WKDittoArchitectures>--arch arm64_32 --arch armv7k</WKDittoArchitectures>`. Leaving this as default caused a compile failure.

3. Ensure that `Xamarin.iOS 16.0` and `XCode 14.0.1` are being used. In Azure Devops I used the `macos-12` image which had these as default.

4. Deployed to AppStore Connect successfully (no emails).

5. Installed on device from Testflight successfully.

I still haven't submitted for view yet, so I'll report back on that.
