### ISSUE TITLE
Exception `Could not initialize an instance of the type 'CoreGraphics.CGGradient': handle is null in IOS 15 version

### ISSUE THREAD

**Issue by HemalathaDuraisamy** [xamarin/xamarin-macios#16497]
I have just upgraded to the latest Xcode and am testing my app on iOS 15.2. I am receiving the exception `Could not initialize an instance of the type 'CoreGraphics.CGGradient': the handle is null.

I have passed nfloat[] object value in CGGradient. I have passed the negative offset value its will be thrown the exception. 

**Note:** It is not working in iOS 15 version, but It's working fine in the iOS 14 version.

**Steps to Reproduce:**
Run the attached sample and it will be thrown the exception. 

please find the sample link:
https://www.syncfusion.com/downloads/support/directtrac/general/ze/App20728130047

Regards,
Hemalatha D.

**Comment by Soap-141** [comment]
I've got the same issue, hope we can have a fix or workaround soon.

**Comment by rolfbjarne** [comment]
Apple's [documentation](https://developer.apple.com/documentation/coregraphics/1398454-cggradientcreatewithcolorcompone) says: "Each location must be a CGFloat value in the range of 0 to 1, inclusive."

You're passing -7, which is clearly not valid according to the documentation, and most likely this fails in iOS 15 because Apple added validation somewhere.

As such, this does not look like a bug in Xamarin.iOS, so I'm closing this issue. If you still think it's a bug in Xamarin.iOS, please provide a working Xcode sample with the code you expect to work, and we'll gladly reopen this issue and investigate.
