### ISSUE TITLE
[net7] Creating a cross-targeted `net7.0-ios` + `net6.0-ios` packages forces consumers to build with net7 workloads

### ISSUE THREAD

**Issue by jeromelaban** [xamarin/xamarin-macios#16524]
Creating a cross-targeted `net7.0-ios` + `net6.0-ios` packages forces consumers to build with net7 workloads, causing dependents on net6.0 to fail building with the following message:

```
CSC : error CS1705: Assembly 'Uno.UI' with identity 'Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null'
uses 'Microsoft.iOS, Version=16.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' which 
has a higher version than referenced assembly 'Microsoft.iOS' with identity 'Microsoft.iOS, Version=15.4.300.0, 
Culture=neutral, PublicKeyToken=84e04ff9cfb79065'
```

This means that any library author currently cannot build packages for net6.0 and net7.0 without resorting to manual package authoring and multi-builds with `global.json` modifications.

### Steps to Reproduce

1. Install .NET 6.0.40x with ios workload
1. Install .NET 7 RC2 with ios workload
2. Create an empty library
3. Pack for `<TargetFrameworks>net6.0-ios;net7.0-ios</TargetFramework>`

### Expected Behavior

`net6.0-ios` binaries reference `Microsoft.iOS` 15.4.300.x

### Actual Behavior

The `net6.0-ios` binaries reference `Microsoft.iOS` 16.0.x

### Environment

.NET 7.0 RC2 with workloads (VS 17.4 Preview 5)

### Build Logs

I can provide those as needed.

As needed.

**Comment by rolfbjarne** [comment]
@jonathanpeppers is this something you've seen for Android too?

**Comment by jeromelaban** [comment]
Android does not seem to exhibit this problem at this point, maybe the binaries did not change versions enough to cause this?

**Comment by jonathanpeppers** [comment]
I think we've always kept `Mono.Android.dll` at version 0.0.0.0 to avoid this...

I don't know if that is the *right* approach, but it's been that way for a long time, maybe since beginning of Xamarin.Android?

**Comment by rolfbjarne** [comment]
> `net6.0-ios` binaries reference `Microsoft.iOS` 15.4.300.x

We've released iOS 16 support for `net6.0-ios`, so it's expected that `net6.0-ios` assemblies built with the latest .NET 6 workloads reference `Microsoft.iOS` 16.0.*.

> CSC : error CS1705: Assembly 'Uno.UI' with identity 'Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null'
> uses 'Microsoft.iOS, Version=16.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' which 
> has a higher version than referenced assembly 'Microsoft.iOS' with identity 'Microsoft.iOS, Version=15.4.300.0, 
> Culture=neutral, PublicKeyToken=84e04ff9cfb79065'

This error seems to indicate that the consumer isn't using the latest version of the .NET 6 workloads (with .iOS 16 support).

Can you include a [binlog](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs) of a build that fails like this?

**Comment by filipnavara** [comment]
> This error seems to indicate that the consumer isn't using the latest version of the .NET 6 workloads (with .iOS 16 support).

So, funny story... I keep trying to explain to the SDK team that I need to update workloads for different SDK version (https://github.com/dotnet/sdk/issues/27109). This is yet another use case for that. The suggestion to use "global.json" to force specific SDK version doesn't work if you want to multi-target.

**Comment by rolfbjarne** [comment]
Ok, so to recap, what's needed is a way to build with the _earliest_ version (or a specific version) of a workload for a given .NET version (the project doesn't really have to be multi-targetting, that just makes the problem more complicated to solve), to ensure maximum compatibility with your customers.

The use-case would be to compile a library that uses the earliest managed API for the workload (to maximize compatibility with that .NET version, since consumers of that library can then use any workload version when consuming said library).

And ideally this would be specified in the csproj somehow.

It seems that specifying the OS version in the TargetFramework could be a way to express this:

```xml
<TargetFrameworks>net6.0-ios15.4;net7.0-ios16.0</TargetFrameworks>
```

but that doesn't work (the `net6.0-ios15.4` target framework still builds with newer reference assembly from the workload for iOS 16.0, and not the older for iOS 15.4).

Moving to dotnet/runtime, since I don't think we can do this today with how workloads are designed and implemented.

**Comment by rolfbjarne** [comment]
This issue was moved to dotnet/runtime#81057
