### ISSUE TITLE
Xamarin.IOS is not generating the dSYMs for frameworks

### ISSUE THREAD

**Issue by ankasani** [xamarin/xamarin-macios#17160]
### Steps to Reproduce

1. Its a simple Xamarin forms app, when you generate the ipa it was not generating the dSYMs for frameworks
Sample project: https://github.com/ankasani/symbolsTesting

### Expected Behavior
Need to generate the dSYMs for frameworks also

### Actual Behavior
dSYMs for frameworks are not getting generated.

### Environment
Xamarin.IOS version 16.0, tested on other versions also it has same issue.
Xcode 14.2, used other versions also.

I use azure devops pipeline mac 12
https://github.com/actions/runner-images/blob/macOS-12/20221215.1/images/macos/macos-12-Readme.md

### Build Logs
Build logs: https://github.com/ankasani/symbolsTesting/blob/main/BuildLogs.txt

**Comment by ankasani** [comment]
@rolfbjarne As requested created a new issue!

**Comment by rolfbjarne** [comment]
@ankasani I'm assuming you want a dSYM for libSkiaSharp.framework.

The problem here is two-fold:

* libSkiaSharp.framework should really be published with a corresponding .dSYM. That would solve the issue (and Xamarin.iOS wouldn't have to create it).
* Technically anyone can create the dSYM for a .framework (using the dsymutil tool), but unfortunately libSkiaSharp.framework does not contain debug symbols (as explained here: https://github.com/mono/SkiaSharp/issues/271#issuecomment-290534921) - incidentally that also means that if Xamarin.iOS were to create a dSYM, it wouldn't anything useful.

This means that I think this is an issue for the https://github.com/mono/SkiaSharp repository, unless I misunderstood your request?

**Comment by ankasani** [comment]
@rolfbjarne , Thanks for the detail.

For the same sample i have shared, If we use xamarin.ios 15.4, then the symbols are getting generated. so i am no sure, if its issue with libSkiaSharp.

The same thing to the one of my customer, where there frameworks are not generating the dsyms files.
Earlier it was working fine with xamarin.ios 15.4, once they upgraded there project to the latest version of the xamarin.ios, issue started.

So, its not specific to the libSkiaSharp, other frameworks also not getting generated the dsym files.

**Comment by rolfbjarne** [comment]
This is in fact by design, we won't be creating dSYMs for user frameworks anymore, because it doesn't make sense for us to do so (as explained here: https://github.com/xamarin/xamarin-macios/issues/17318#issuecomment-1398077919).

If you really need to create a .dSYM, you can create them yourself by using `dsymutil`:

> dsymutil /path/to/libSkiaSharp.framework -o /path/to/libSkiaSharp.framework.dSYM
