### ISSUE TITLE
Building A net6.0-macos Executable on a Windows Machine Fails Silently

### ISSUE THREAD

**Issue by timo352** [xamarin/xamarin-macios#17542]
I say this all with the least amount of confidence that allows me to submit an issue. Please direct me to the right place or point me at documentation.

### Steps to Reproduce

1. Create a new console executable on a Windows machine
2. Switch the TargetFramework to be `net6.0-macos`
3. Switch the RuntimeIdentifier to be `osx-x64` or set that on the command line when you build. Not needed since it defaults to this if you target `net6.0-macos`
4. Run `dotnet build` or `dotnet publish`

### Expected Behavior
This is where I'm a little confused. I think I expected the behavior to generate output similar to a normal Linux/Mac executable when I'm building with the `net6.0` TFM. Output usually looks like this.
- MacExe
- MacExe.dll
- MacExe.runtimeconfig.json
- MacExe.deps.json
- MacExe.pdb

For a windows runtime the extension-less file is replaced with a `.exe`

If I was building on a Mac, I'd expect the next steps to generate the App Bundle and then create the .pkg and sign it with XCode's help. 
I understand that some of that behavior isn't possible on a windows machine, but I think I'd expect that we'd at least get similar output we can copy to Mac to run the executable without the bundling and packaging.

### Actual Behavior

Instead, it seems like the build silently fails earlier than this. In my output I only have:
- MacExe.dll
- MacExe.pdb
- MacExe.runtimeconfig.json
- A MacExe.app "bundle" folder that is empty except for a runtimeconfig.bin file in a MonoBundle subfolder.

The console output looks identical to a working build, saying that the MacExe.dll file is output to the correct folder. A few days ago [haven't been able to reproduce this], I was getting it to say "Package Built: " or something like that but the path after the colon was blank.

My conclusion is that it's impossible to build an executable targeting the `-macos` TargetPlatformIdentifier on a Windows machine. Building libraries works fine and building exes for other TFMs [android and windows, obviously]

Without going into details on why it's necessary we do it this way, but my team builds all of our source code from one integrated stream on one machine in the same process. If my conclusion is accurate, anything targeting macos needs to be compiled on a separate machine. It doesn't entirely defeat the purpose of "multi-targeting", but it is a little inconvenient you can't just build once and get working exes for every target framework.

Again, I wouldn't expect everything to work. At best, I'd expect output like the other Target Frameworks with additional steps that can't run/fail since we aren't on a Mac. At the very least I'd expect an error saying what I'm doing is impossible. 

<details>
<summary>Version information</summary>

```
Microsoft Visual Studio Professional 2022
Version 17.3.6
VisualStudio.17.Release/17.3.6+32929.385
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Professional

ASP.NET and Web Tools   17.3.376.3011
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.3.376.3011
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.3.376.3011
Azure Functions and Web Jobs Tools

C# Tools   4.3.0-3.22470.13+80a8ce8d5fdb9ceda4101e2acb8e8eb7be4ebcea
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.3.20 (3f4cb00)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.0.0.2232702+e1d654e792aa2fe6646a6935bcca80ff0aff4387
Provides languages services for ASP.NET Core Razor.

Solution Colors   1.1.44
Allows you to associate a color with a solution and display it in various locations within Visual Studio. Inspired by the Peacock extension for VS Code.

SQL Server Data Tools   17.0.62207.04100
Microsoft SQL Server Data Tools

TypeScript Tools   17.0.10701.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.3.0-3.22470.13+80a8ce8d5fdb9ceda4101e2acb8e8eb7be4ebcea
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.1.0-beta.22363.4+1b94f89d4d1f41f20f9be73c76f4b229d4e49078
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

Visual Studio Spell Check Everywhere   VSSpellCheckEverywhere
An extension that enables spell checking within any Visual Studio file editor or tool window that uses WPF text boxes.
https://GitHub.com/EWSoftware/VSSpellChecker

Visual Studio Spell Checker   VSSpellChecker
An editor extension that checks the spelling of comments, strings, and plain text as you type or interactively with tool windows.
https://GitHub.com/EWSoftware/VSSpellChecker

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

WiX Toolset Visual Studio Extension   1.0.0.18
WiX Toolset Visual Studio Extension version 1.0.0.18
Copyright (c) .NET Foundation and contributors. All rights reserved.

Xamarin   17.3.0.308 (d17-3@56b9f7e)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.3.0.217 (remotes/origin/d17-3@b81db1dcc0)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.2.28 (9b3d244)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   13.0.0.0 (d17-3/030cd63)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: dffa5ab
    Java.Interop: xamarin/java.interop/d17-3@7716ae53
    SQLite: xamarin/sqlite/3.38.5@df4deab
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@14076a6


Xamarin.iOS and Xamarin.Mac SDK   16.0.0.75 (e4f48bed7)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

</details>

### Build Logs
[msbuild.zip](https://github.com/xamarin/xamarin-macios/files/10737736/msbuild.zip)

### Example Project (If Possible)
The project is just a Hello World console app. I know that App Bundles don't really work with console applications without creating some separate scripts to call the exe, so maybe my problem is there?
```
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net6.0-macos</TargetFramework>
		<RuntimeIdentifier>osx-x64</RuntimeIdentifier>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<CreatePackage>false</CreatePackage>
		 <UseAppHost>true</UseAppHost>
		<EnableDefaultItems>false</EnableDefaultItems>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Include="Program.cs" />
	</ItemGroup>
</Project>

```

**Comment by rolfbjarne** [comment]
> My conclusion is that it's impossible to build an executable targeting the `-macos` TargetPlatformIdentifier on a Windows machine.

That is correct, and there's a bit of history to the reasons for what you've discovered.

Generally, in order to build a macOS (Mach-O) executable, it's necessary to have a macOS toolchain capable of compiling and linking Mach-O executables. Currently there's no such toolchain that can execute on a Windows machine, it requires a macOS machine (we use the toolchain shipped with Xcode). In theory it would be possible to make it work on Windows, but in practice it would require a lot of resources to keep the toolchain up-to-date, so this is unlikely to happen. There are some ways around this - we could ship a prebuilt executable, and somehow make that work - but it would have limitations (no support for using static third-party native libraries for instance, and there would be optimizations we couldn't do, etc.). Incidentally this is how [Hot Restart](https://learn.microsoft.com/en-us/xamarin/xamarin-forms/deploy-test/hot-restart) works for iOS projects for instance - but one major caveat is that Hot Restart is for development (debugging and writing code), not for publishing an iOS app (in which case we require you to have a Mac for an unrestricted build), and it requires developing on the iOS device (no simulator support). A similar solution for macOS projects would likely have the same restrictions - but if a Mac is required for debugging, then you'd also have a Mac to do the build, and it doesn't make much sense to spend a considerable amount of resources being able to build on Windows if you need a Mac later on anyway.

> At the very least I'd expect an error saying what I'm doing is impossible.

Yes, that's what we thought too, and how we initially implemented it.

But it turned out customers didn't like it, because very often they had projects targeting multiple platforms, and during development they wanted to know _does my new business logic (in C#) compile on all platforms_? And our errors saying "you can't build this type of project on Windows" were not very welcome, so we ended up silently succeeding any such builds as long as the C# code built successfully.
