### ISSUE TITLE
Incorrect .app bundle when build with '-p:RuntimeIdentifier' option and <RuntimeIdentifiers> property

### ISSUE THREAD

**Issue by JaneySprings** [xamarin/xamarin-macios#17707]
### Steps to Reproduce

1. Create maccatalyst project
2. Add 'RuntimeIdentifiers' property:
```xml
<RuntimeIdentifiers>maccatalyst-arm64;maccatalyst-x64</RuntimeIdentifiers>
```
3. Try to build the project with following command:
```
dotnet build -f:net7.0-maccatalyst -p:RuntimeIdentifier=maccatalyst-arm64
```
4. The application will be built, but it is empty (there are no dll and dylib libraries).
5. Run the application:
<img width="255" alt="image" src="https://user-images.githubusercontent.com/48021947/222921483-38ced0b1-e4fc-4e11-8cd8-8a1dd2367a6e.png">

### Expected Behavior
I think the behavior should be like the `<TargetFrameworks>` option:

I have multiple frameworks in my project
```xml
<TargetFrameworks>net7.0-android;net7.0-ios;net7.0-maccatalyst</TargetFrameworks>
```
if I build the application using `dotnet build -p:TargetFramework=net7.0-android` then I will have only `net7.0-android` application assembled.

### Actual Behavior
incorrect (empty) app bundle

### Environment
dotnet 7.0.200
latest iOS workload
MacBook Pro (M1)

### Build Logs
[msbuild-binlog.txt](https://github.com/xamarin/xamarin-macios/files/10889321/msbuild-binlog.txt) - rename to .binlog

**Comment by JaneySprings** [comment]
Build was skipped...?
<img width="720" alt="image" src="https://user-images.githubusercontent.com/48021947/222922624-3d4e57bf-64cc-414f-996b-45b9c463aea6.png">

**Comment by rolfbjarne** [comment]
I can reproduce this.

The workaround is to use the plural variable in the command:

> dotnet build -f:net7.0-maccatalyst -p:RuntimeIdentifiers=maccatalyst-arm64

The problem is that when detect that both `RuntimeIdentifier` and  `RuntimeIdentifiers` are set, we clear `RuntimeIdentifier`, so that `RuntimeIdentifiers` takes precedence - except that when `RuntimeIdentifier` is set on the command line, we can't clear the property (an MSBuild property set on the command line can't be changed later), and then the rest of our build logic gets confused because it assumes/depends on the fact that just one of the two variables are set:

https://github.com/xamarin/xamarin-macios/blob/028efe3a7c23548063d7be5f03d074b860ef2549/dotnet/targets/Xamarin.Shared.Sdk.DefaultItems.targets#L33-L39

The fix is likely to detect if `RuntimeIdentifier` was indeed cleared successfully, and if not, try to clear `RuntimeIdentifiers` instead:

```xml
<!-- Clear RuntimeIdentifier -->
<RuntimeIdentifier />
<!-- Check if RuntimeIdentifier was cleared. If it wasn't it was set on the command line, and in that case, try to clear RuntimeIdentifiers instead -->
<_RuntimeIdentifiersClashMessage Condition="'$(RuntimeIdentifier)' != ''">RuntimeIdentifier was set on the command line, and will override the value for  RuntimeIdentifiers set in the project file.</_RuntimeIdentifiersClashMessage>
<RuntimeIdentifiers Condition="'$(RuntimeIdentifier)' != ''" />
<!-- If we couldn't clear RuntimeIdentifiers either, then both were set on the command line. This is an error -->
<_RuntimeIdentifiersClashErrorMessage  Condition="'$(RuntimeIdentifier)' != '' And '$(RuntimeIdentifiers)' != ''">Both RuntimeIdentifier and RuntimeIdentifiers were passed on the command line, but only one of them can be set at a time.</_RuntimeIdentifiersClashErrorMessage>
```
