### ISSUE TITLE
An SSL error when sending request to server using mac to deploy but successful when using windows and pair mac

### ISSUE THREAD

**Issue by steveisok** [xamarin/xamarin-macios#18580]
### Description

Moved from https://github.com/dotnet/runtime/issues/87850

I created sample maui app in VS 2022 with .NET 7.0 for both Android and iOS. 
In that application, I used the api provided here https://sqa.stackexchange.com/questions/47097/free-sites-for-testing-post-rest-api-calls to test Http post request. 
When i deploy this app using mac, the following ssl exception is thrown after certificate validation. Running the same app using windows and pair mac works fine and gives back a 200 response.

2023-06-20 14:53:00.807797-0700 MauiApp3[20694:3562905] System.Net.Http.HttpRequestException: An SSL error has occurred and a secure connection to the server cannot be made.
2023-06-20 14:53:00.808028-0700 MauiApp3[20694:3562905]  ---> Foundation.NSErrorException: Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, NSErrorPeerCertificateChainKey=(
[MauiApp3.zip](https://github.com/dotnet/runtime/files/11808602/MauiApp3.zip)

### Steps to Reproduce

1. Download the attached zip
2. unzip and open in Visual Studio on mac
3. build and run the app
4. ssl exception is thrown
5. open the same app on windows visual studio
6. pair to mac
7. build and run the app 
8. request is successful with a 200 response

### Expected Behavior

The http request should return 200 response

### Actual Behavior

SSL exception is thrown

### Environment

<details>
<summary>Version information</summary>

```
VS 2022
.NET 7.0
```

</details>

**Comment by rolfbjarne** [comment]
You're getting the error because you return false from the `ValidateServerCertificate` callback.

You return false from the `ValidateServerCertificate` callback because you compute the hash for given certificate, and it does not match the expected hash in the code.

I don't know why the hash is different (different - but still valid - certificate? incorrect hash computation?), but in any case this is unlikely to be an issue in the SDK, so I'm closing this.

Feel free to reopen if you think I'm wrong
