### ISSUE TITLE
simctl returned exit code 3

### ISSUE THREAD

**Issue by Connect-and-Exchange** [xamarin/xamarin-macios#18602]
### Steps to Reproduce

1.  run the app on the iOS simulator (fails)
2. Do the same on Android and the app starts without issue in the simulator
3. deploy the app to a physical iOS device and it deploys and debugging works

### Expected Behavior

Simulator starts
- app gets deployed 
- app starts connected to the debugger

### Actual Behavior
Simulator starts
- app gets deployed 
- app does not start and an exit code is shown in visual studio for Mac

xcrun simctl launch --stdout=/dev/ttys000 --stderr=/dev/ttys001 --terminate-running-process 47CB8525-E348-4334-8E9C-AD9A2890884D pl.com.ex.pei.iPrescriptions -monodevelop-port 10000
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=3):
Simulator device returned an error for the requested operation.
No such process
Underlying error (domain=NSPOSIXErrorDomain, code=3):
	Application launch for 'pl.com.ex.pei.iPrescriptions' did not return a valid pid nor a launch error.
	No such process
error HE0042: Could not launch the app 'pl.com.ex.pei.iPrescriptions' on the device 'iOS 16.4 (20E247) - iPhone 14': simctl returned exit code 3

### Environment

<details>
<summary>Version information</summary>

```
Visual Studio Community 2022 for Mac
Version 17.6.1 (build 452)
Installation UUID: afc8f866-e5a5-46d0-8634-8359f24e82f5

Runtime
.NET 7.0.3 (64-bit)
Architecture: Arm64
Microsoft.macOS.Sdk 13.1.1007; git-rev-head:8afca776a0a96613dfb7200e0917bb57f9ed5583; git-branch:release/7.0.1xx-xcode14.2

Roslyn (Language Service)
4.6.0-3.23180.6+99e956e42697a6dd886d1e12478ea2b27cceacfa

NuGet
Version: 6.4.0.117

.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/7.0.306/Sdks
SDK Versions:
	7.0.306
	7.0.304
	7.0.302
	7.0.203
	7.0.202
	7.0.201
	7.0.200
	7.0.103
	7.0.102
	7.0.101
	7.0.100
	6.0.412
	6.0.410
	6.0.408
	6.0.407
	6.0.406
	6.0.405
	6.0.404
	6.0.403
	6.0.401
	6.0.302
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET SDK (x64)
SDK Versions:
	3.1.426
	3.1.425
	3.1.423
	3.1.421

.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	7.0.9
	7.0.7
	7.0.5
	7.0.4
	7.0.3
	7.0.2
	7.0.1
	7.0.0
	6.0.20
	6.0.18
	6.0.16
	6.0.15
	6.0.14
	6.0.13
	6.0.12
	6.0.11
	6.0.9
	6.0.7

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/x64/dotnet
Runtime Versions:
	3.1.32
	3.1.31
	3.1.29
	3.1.27

Xamarin.Profiler
Version: 1.8.0.49
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode: 14.3 21812
Build: 14E222b

Xamarin.Mac
Version: 9.3.0.6 Visual Studio Community
Hash: 97731c92c
Branch: xcode14.3
Build date: 2023-04-11 22:38:35-0400

Xamarin.iOS
Version: 16.4.0.6 Visual Studio Community
Hash: 97731c92c
Branch: xcode14.3
Build date: 2023-04-11 22:38:36-0400

Xamarin.Android
Version: 13.2.0.6 (Visual Studio Community)
Commit: xamarin-android/d17-5/a200af1
Android SDK: /Users/m.meuwese/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0  (API level 23)
		12.0 (API level 31)
		10.0 (API level 29)
		13.0 (API level 33)

SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 33.0.3
SDK Build Tools Version: 33.0.0

Build Information: 
Mono: 6dd9def
Java.Interop: xamarin/java.interop/d17-5@149d70fe
SQLite: xamarin/sqlite/3.40.1@68c69d8
Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@9f02d77

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.16.1
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.6.0.50
Hash: a715dca
Branch: HEAD
Build date: 2023-07-06 12:51:55 UTC

Android Device Manager
Version: 0.0.0.1309
Hash: 06e3e77
Branch: HEAD
Build date: 2023-07-06 12:51:55 UTC

Xamarin Designer
Version: 17.6.3.9
Hash: 2648399ae8
Branch: remotes/origin/d17-6
Build date: 2023-07-06 12:51:51 UTC

Build Information
Release ID: 1706010452
Git revision: 9c61cec4d4c4498378f5878b08459d6fd258659d
Build date: 2023-07-06 12:50:14+00
Build branch: release-17.6
Build lane: release-17.6

Operating System
Mac OS X 13.4.1
Darwin 22.5.0 Darwin Kernel Version 22.5.0
    Thu Jun  8 22:22:20 PDT 2023
    root:xnu-8796.121.3~7/RELEASE_ARM64_T6000 arm64


```

</details>

### Build Logs

[msbuild.binlog.zip](https://github.com/xamarin/xamarin-macios/files/12207566/msbuild.binlog.zip)

**Comment by rolfbjarne** [comment]
> ###
> [msbuild.binlog.zip](https://github.com/xamarin/xamarin-macios/files/12207566/msbuild.binlog.zip)

The build log seems to be for a netstandard2.0 project (`Rx-WhizzV2.csproj`), not an iOS project - did you upload the wrong build log?

**Comment by borrmann** [comment]
I also run into this issue with either exit code 3 (currently) or exit code 1 usually after updates of xcode or Visual Studio.
I am using a M1 machine.
What is a general process to kind of reset the setup, as this seems to fix this issue normally?

I already cleared the bin and obj folders of my project and the XCode caches with no luck.
No issues running on a physical device.

**Comment by borrmann** [comment]
Here is a log report with `xcrun simctl logverbose enable`, although I am not quite sure if I used it correctly 
[simctl_diagnose_2023_11_30.11-04-11+0000.tar.gz](https://github.com/xamarin/xamarin-macios/files/13512088/simctl_diagnose_2023_11_30.11-04-11%2B0000.tar.gz)

**Comment by borrmann** [comment]
@rolfbjarne 

[meitiMaui.zip](https://github.com/xamarin/xamarin-macios/files/13545708/meitiMaui.zip)

Some more background info:

I am using .NET 7, because my app is already in production and .NET 8 introduced several new issues that I have to wait for being fixed as well as some third party dependencies that are not quite ready, etc..
 
Currently I am getting an exit code 149 (the application does not even install on the simulator), but the app is still running fine on physical devices. I do not have an iossimulator-arm64 folder. I only have the ios-arm64 folder (That is where the zip is from). Does that indicate something is wrong with my project file? Previously I was able to run my app just fine on simulators (or lets say, sometimes)..

On another note, I am still using VS for Mac to build my project, because VS code won't find the MAUI SDK if I open my rather large project and I don't really want to use a preview tool for my production development. And as I understood the news, VS Mac is still in support for .NET 7 until next year. I guess I should probably switch to CLI at this time as it seems no IDE is currently really ready anymore/ yet for production on a Mac. Or what is your suggestion here?

When I run my project from my Windows with my Mac host and a simulator, the simulator launches but I only get a black screen.

**Comment by rolfbjarne** [comment]
> I do not have an iossimulator-arm64 folder. I only have the ios-arm64 folder

Then you have a device build, not a simulator build.

If you're using VSMac, I'm guessing you're selecting the simulator you want to target in the device selector and then running the project? If so, do you have a RuntimeIdentifier property in your csproj?

**Comment by borrmann** [comment]
> If you're using VSMac, I'm guessing you're selecting the simulator you want to target in the device selector and then running the project?

Yes!

>If so, do you have a RuntimeIdentifier property in your csproj?

Yes, it was set to ios-arm64. Thanks so much! It is indeed working with RID set to `iossimulator-arm64` (on iOS 17 simulators)
I understand this is totally my fault, but maybe it could be possible to give an error that points to the runtimeidentifier or so? I wasnt aware I would have to change my project file. There is no hint in the docs [here](https://learn.microsoft.com/en-us/dotnet/maui/ios/remote-simulator?view=net-maui-8.0) 
And the catalog for [RID](https://learn.microsoft.com/en-us/dotnet/core/rid-catalog) does not list the iossimulator.

Now, running on simulators with iOS 17 works fine, iOS 15 still gives an error code 149. Not sure if those arent supported anymore, but I am trying to reproduce a bug a user reported to us on an iOS 15 device, and unfortunately I dont have a device with iOS 15 installed anymore. Because our customers (handymen) deliberately use older phones on construction sites, unfortunately this is not as uncommon as we wished..

**Comment by borrmann** [comment]
> > iOS 15 still gives an error code 149.
> 
> Can you show the complete output?

This is all I get:

```
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=405):
Unable to lookup in current state: Shutdown
error HE0046: Failed to install the app 'com.meitihandwerk.meiti' on the device 'iOS 15.0 (19A339) - iPhone 13': simctl returned exit code 149
```

but I think this has actually nothing to do with Xamarin, as I receive an error notification from Xcode when I try to boot the simulator. I will try to reinstall the simulators but I assume this will fix the issues.
Thanks again for your help!
