### ISSUE TITLE
.NET6.0+: Multi-targetting project help

### ISSUE THREAD

**Issue by projectgoav** [xamarin/xamarin-macios#18634]
I have the following csproj

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net6.0;net6.0-ios</TargetFrameworks>
  </PropertyGroup>

</Project>
```

When I execute the following command on Windows or Linux:
```
dotnet build <csproj> --framework net6.0
```
the build errors due to missing iOS workload. 

On windows, this is easily solved by installing the ios workload. 

On Linux, it recommends I install the macos workload. Doing so then results in:
```
error NETSDK1178: The project depends on the following workload packs that do not exist in any of the workloads available in this installation: Microsoft.iOS.Sdk.net6
error NETSDK1178: You may need to build the project on another operating system or architecture, or update the .NET SDK.
```

Why it this? I had assumed a multi-target project would only need the iOS workload installed when you specifcy `--framework net6.0-ios`? 

Is there a solution without having 2 csproj files defining the 2 runtimes?

**Comment by rolfbjarne** [comment]
There are several things at play here:

* We don't ship packages for net6.0-ios on Linux (it could be possible, but would take time to implement, and time is not something we have an abundance of). See also https://github.com/xamarin/xamarin-macios/issues/17289.
* .NET seems to require all target frameworks to be available when building, even when building for a single target framework. I don't know why this is, and it's probably an issue for .NET itself (my recommendation would be to file an issue in https://github.com/dotnet/sdk).

> Is there a solution without having 2 csproj files defining the 2 runtimes?

This might work:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks Condition="!$([MSBuild]::IsOSPlatform('Linux'))">net6.0;net6.0-ios</TargetFrameworks>
    <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('Linux'))">net6.0</TargetFrameworks>
  </PropertyGroup>
</Project>
```

I'm closing this, since I don't think there's anything actionable on our side.

**Comment by projectgoav** [comment]
Thanks - the above solution you mentioned was the solution I came up with.

Will raise a ticket on the dotnet SDK like you suggested.
