### ISSUE TITLE
Emulator list not showing iOS devices/emulators

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-macios#19141]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Emulator-list-not-showing-iOS-devicesem/10481430)._

---
After following the steps suggested by YanFang Wang:
For the issue that non-displaying of iOS emulators:
What is your Xcode version? Xcode 14.3.1? or Xcode 15.0?
If Xcode version is 15.0, have you downloaded the 17.0 iOS simulator?
If not, you need to download the 17.0 iOS simulator:
Click Xcode and select settings
Click platforms, you can see if you have a 17.0 iOS simulator
If not, click get iOS 17.0 simulator.
If you already have 17.0 iOS simulator, please execute the command line in Terminal:
sudo xcode-select –reset
Then open VS to check if Simulators show out.

There’s no iOS list yet, besides I have xcode 15 and iOS 17 installed.
And now, when I build the solution for Android, I get these warnings:

Warning MT4178: The class 'NewsstandKit.NKAssetDownload' will not be registered because the NewsstandKit framework has been removed from the iOS SDK. (MT4178)
Warning MT4178: The class 'NewsstandKit.NKLibrary' will not be registered because the NewsstandKit framework has been removed from the iOS SDK. (MT4178)
Warning MT4189: The class 'PassKit.PKDisbursementAuthorizationControllerDelegate' will not be registered it has been removed from the iOS SDK. (MT4189)
Warning MT4178: The class 'NewsstandKit.NKIssue' will not be registered because the NewsstandKit framework has been removed from the iOS SDK. (MT4178) Warning MT4189: The class 'PassKit.PKDisbursementAuthorizationController' will not be registered it has been removed from the iOS SDK. (MT4189)

---
#### Feedback Bot on 10/1/2023, 08:21 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by rolfbjarne** [comment]
Can you open "Xcode -> Settings -> Platforms" and make sure the iOS 17 platform is downloaded?

![Screenshot 2023-10-12 at 12 14 58](https://github.com/xamarin/xamarin-macios/assets/249268/233b4b30-dba0-46f3-a952-67a0a81a44e2)

Once you have the iOS 17 platform, also open "Xcode -> Window -> Devices and Simulators" and check whether you have any iOS 17 simulators:

![Screenshot 2023-10-12 at 12 16 29](https://github.com/xamarin/xamarin-macios/assets/249268/dc8995a6-5aac-4bd2-9404-e38a40f9a75a)

**Comment by appdevcanada** [comment]
So @rolfbjarne, it's yes for both questions...
I do have iOS 17 installed (+ 16.4)...
![image](https://github.com/xamarin/xamarin-macios/assets/43067488/9d5bb761-7234-4cbd-b493-336cf3b1ca27)

And I do have Simulators with iOS 17...
![image](https://github.com/xamarin/xamarin-macios/assets/43067488/857d98a0-5d7a-4af7-a8f8-4120963dcb11)

**Comment by rolfbjarne** [comment]
@appdevcanada is this a .NET project or a legacy Xamarin project? Can you also get the version information from the IDE (https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#version-information)?

**Comment by appdevcanada** [comment]
Hello,

Here's the requested info:

It's a .NET MAUI project intended to run on Android and iOS.
![image](https://github.com/xamarin/xamarin-macios/assets/43067488/d7a9e3cb-99d8-4914-8b13-8e5919a9b859)

Detailed information from About:

Visual Studio Community 2022 for Mac
Version 17.6.5 (build 417)
Installation UUID: cd36e2a7-68f4-499e-8a5c-4eacc6d99c7f

Runtime
.NET 7.0.3 (64-bit)
Architecture: Arm64
Microsoft.macOS.Sdk 13.1.1007; git-rev-head:8afca776a0a96613dfb7200e0917bb57f9ed5583; git-branch:release/7.0.1xx-xcode14.2

Roslyn (Language Service)
4.6.0-3.23180.6+99e956e42697a6dd886d1e12478ea2b27cceacfa

NuGet
Version: 6.4.0.117

.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/7.0.401/Sdks
SDK Versions:
	7.0.401
	7.0.308
	7.0.307
	7.0.306
	7.0.304
	7.0.302
	7.0.105
	7.0.101
	6.0.415
	6.0.414
MSBuild SDKs: /Volumes/Mac SSD II/Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET SDK (x64)
SDK Versions:
	7.0.401
	7.0.308
	7.0.307
	7.0.306
	7.0.304
	7.0.302
	7.0.105
	7.0.101

.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	7.0.11
	7.0.10
	7.0.9
	7.0.7
	7.0.5
	7.0.1
	6.0.23
	6.0.22

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/x64/dotnet
Runtime Versions:
	7.0.11
	7.0.10
	7.0.9
	7.0.7
	7.0.5
	7.0.1

Xamarin.Profiler
Version: 1.8.0.49
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Version: 13.2.2.0 (Visual Studio Community)
Commit: xamarin-android/d17-5/45b0e14
Android SDK: /Users/luishmsouza/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		11.0 (API level 30)
		13.0 (API level 33)

SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 34.0.5
SDK Build Tools Version: 34.0.0 rc3

Build Information: 
Mono: d9a6e87
Java.Interop: xamarin/java.interop/d17-5@149d70fe
SQLite: xamarin/sqlite/3.40.1@68c69d8
Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@ca1552d

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.16.1
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.6.0.50
Hash: a715dca
Branch: HEAD
Build date: 2023-10-04 18:09:18 UTC

Android Device Manager
Version: 0.0.0.1309
Hash: 06e3e77
Branch: HEAD
Build date: 2023-10-04 18:09:18 UTC

Xamarin Designer
Version: 17.6.3.9
Hash: 2648399ae8
Branch: remotes/origin/d17-6
Build date: 2023-10-04 18:09:13 UTC

Apple Developer Tools
Xcode: 15.0 22265
Build: 15A240d

Xamarin.Mac
Version: 9.3.0.18 Visual Studio Community
Hash: 9d266025e
Branch: xcode14.3
Build date: 2023-09-06 19:52:26-0400

Xamarin.iOS
Version: 16.4.0.18 Visual Studio Community
Hash: 9d266025e
Branch: xcode14.3
Build date: 2023-09-06 19:52:27-0400

Build Information
Release ID: 1706050417
Git revision: 6d6585a706becbd4a5be3b0e99ace260dfdf5748
Build date: 2023-10-04 18:07:26+00
Build branch: release-17.6
Build lane: release-17.6

Operating System
Mac OS X 14.0.0
Darwin 23.0.0 Darwin Kernel Version 23.0.0
    Fri Sep 15 14:41:34 PDT 2023
    root:xnu-10002.1.13~1/RELEASE_ARM64_T8103 arm64

Enabled user installed extensions
.NET Core Extensions 0.7

**Comment by rolfbjarne** [comment]
Thanks, here's a few other things/questions:

* Do you get the same lack of simulators and devices in VSMac if you create a new project from a template?
* I'm assuming this worked at some point - but do you know what triggered the change?
* Can you launch a new Xcode project in a simulator / on device?
* What happens if you try to launch the app from the command line (in a terminal window, do "dotnet run" in the project's directory)?

**Comment by rolfbjarne** [comment]
```
... % dotnet run --framework net7.0-ios16.4
The launch profile "(Default)" could not be applied.
A usable launch profile could not be located.
MSBuild version 17.7.3+8ec440e68 for .NET
Determining projects to restore...
All projects are up-to-date for restore.
xxx.csproj : error MSB4057: The target "Run" does not exist in the project.
```

I've never seen that before... can you try this:

```
% dotnet build -t:Run --framework net7.0-ios16.4 -bl:msbuild.binlog
```

and if that fails, upload the msbuild.binlog file?

**Comment by appdevcanada** [comment]
It failed complaining about the device, then after plugging in, it failed for another reason...
File attached
[msbuild.binlog.zip](https://github.com/xamarin/xamarin-macios/files/13031716/msbuild.binlog.zip)

**Comment by rolfbjarne** [comment]
In your csproj, can you try changing this:

```xml
<RuntimeIdentifiers>ios-arm64</RuntimeIdentifiers>
```

to:

```xml
<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
```

and see if that makes a difference?

**Comment by appdevcanada** [comment]
So, some progress now...
At least, after setting all the trusting and setting dev mode in this new iPhone, the app was installed, with the right icon, but doesn't run, quitting immediately after the splash screen.
File attached again...
[msbuild.binlog.zip](https://github.com/xamarin/xamarin-macios/files/13032018/msbuild.binlog.zip)

**Comment by rolfbjarne** [comment]
> So, some progress now... At least, after setting all the trusting and setting dev mode in this new iPhone, the app was installed, with the right icon, but doesn't run, quitting immediately after the splash screen. File attached again... [msbuild.binlog.zip](https://github.com/xamarin/xamarin-macios/files/13032018/msbuild.binlog.zip)
> 
> *Btw, still no device/simulator selection on VS

Ah, that last issue is because you've updated your device to iOS 17, and Apple changed a lot of internal logic to deploy/launch on device in iOS 17, so we have to catch up before things are working fully again (it's already fixed, and we're trying to get the fix released asap right now).

>  *Btw, still no device/simulator selection on VS

First you need to remove this line:

```xml
<MtouchArch>ARMv7</MtouchArch>
```

Then try changing this line in your csproj:

```xml
<TargetFrameworks>net7.0-android;net7.0-ios16.4</TargetFrameworks>
```

to:

```xml
<TargetFrameworks>net7.0-android;net7.0-ios</TargetFrameworks>
```

and if that doesn't work, try this:

```xml
<TargetFramework>net7.0-ios</TargetFramework>
```

**Comment by appdevcanada** [comment]
Hey,

I was really really sad and hopeless to have my app back on track on iOS, but **you nailed it**!

I could have it installed and running fine on my device (that's great!), but on any simulator, I get the splash and closes, like stopping the execution on VS:
xcrun simctl launch --stdout=/dev/ttys001 --stderr=/dev/ttys002 --terminate-running-process EDDA9147-A8CE-4511-A189-A42DC86C5B62 com.xxx.yyy -monodevelop-port 10000
An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=1):
Simulator device returned an error for the requested operation.
The request was denied by service delegate (SBMainWorkspace).
Underlying error (domain=FBSOpenApplicationServiceErrorDomain, code=1):
	The request to open "com.xxx.yyy" failed.
	The request was denied by service delegate (SBMainWorkspace).
error HE0042: Could not launch the app 'com.xxx.yyy' on the device 'iOS 17.0 (21A328) - iPhone 15 Pro': simctl returned exit code 1


Also, but less importantly, I get these warnings:
ILLINK : warning MT4178: The class 'NewsstandKit.NKAssetDownload' will not be registered because the NewsstandKit framework has been removed from the iOS SDK.
ILLINK : warning MT4178: The class 'NewsstandKit.NKLibrary' will not be registered because the NewsstandKit framework has been removed from the iOS SDK.
ILLINK : warning MT4189: The class 'PassKit.IPKDisbursementAuthorizationControllerDelegate' will not be registered it has been removed from the iOS SDK.
ILLINK : warning MT4189: The class 'PassKit.PKDisbursementAuthorizationControllerDelegate' will not be registered it has been removed from the iOS SDK.
ILLINK : warning MT4178: The class 'NewsstandKit.NKIssue' will not be registered because the NewsstandKit framework has been removed from the iOS SDK.
ILLINK : warning MT4189: The class 'PassKit.PKDisbursementAuthorizationController' will not be registered it has been removed from the iOS SDK.

**Comment by rolfbjarne** [comment]
@appdevcanada I didn't quite understand your last comment: is it all working for you now? Or do you still have a problem in the simulator?

**Comment by appdevcanada** [comment]
On my device it’s ok, but on any simulator that error occurs, stopping me from using it.

**Comment by rolfbjarne** [comment]
Can you try removing this line in your csproj and see if it works in both the simulator and device afterwards?

```xml
<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
```

**Comment by appdevcanada** [comment]
Hey @rolfbjarne , you rule!

It's working on both now... Thank you so much for your help and effort on this!

**Comment by rolfbjarne** [comment]
That's great! I'll close this then.

**Comment by RamyaKannan19** [comment]
Hi @rolfbjarne 

The Xcode Simulator 16.2 is not showing in Visual Studio 2022.


<img width="1427" alt="Image" src="https://github.com/user-attachments/assets/049b6515-40ac-4064-8c6c-721de01367e6" />

<img width="1076" alt="Image" src="https://github.com/user-attachments/assets/402108bc-29dd-4d3b-9b65-9a6902ea8b17" />

<img width="942" alt="Image" src="https://github.com/user-attachments/assets/d11900e6-7ae7-4be4-aca4-cc48f8439f0b" />

<img width="1359" alt="Image" src="https://github.com/user-attachments/assets/51cd7930-b0a9-4f10-af5c-ca3304ca85ae" />

**Comment by rolfbjarne** [comment]
@RamyaKannan19 Visual Studio for Mac has been retired for a few months now, so this is not something we'll look into. Please switch to VSCode, and if you still have problems, we'll investigate.
