### ISSUE TITLE
[regression/8.0.0] SkiaSharp signature check fails for deployment (Visual Studio local iOS device)

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#19278]
_From @espenrl on Tue, 10 Oct 2023 13:52:22 GMT_

### Description

This happens when deploying a `dotnet new maui` app with package refrences to `SkiaSharp`. It works on .NET 7 and is a regression for .NET 8.

```
Xamarin.Messaging.IDB.Local.DeployAppMessageHandler Error: 0 : An error occurred while trying to deploy the app 'net8test.app'. Details: Could not install the application '<redacted>\AppData\Local\Temp\Xamarin\HotRestart\Signing\net8test.app\out\net8test.ipa' on the device <redacted>. Details: ApplicationVerificationFailed|0xE8008014 - Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.Pc97q0/extracted/Payload/net8test.app/Frameworks/libSkiaSharp.framework : 0xe8008014 (The executable contains an invalid signature.)
Xamarin.iOS.Windows.WindowsiOSException: Could not install the application '<redacted>\AppData\Local\Temp\Xamarin\HotRestart\Signing\net8test.app\out\net8test.ipa' on the device <redacted>. Details: ApplicationVerificationFailed|0xE8008014 - Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.Pc97q0/extracted/Payload/net8test.app/Frameworks/libSkiaSharp.framework : 0xe8008014 (The executable contains an invalid signature.)
   at Xamarin.iOS.Windows.Installer.ApplicationSession.InstallApp(String appPath, String appBundleId) in D:\a\_work\1\s\src\Tools\Xamarin.iOS.Windows.Client\Installer\ApplicationSession.cs:line 276
   at Xamarin.iOS.Windows.Installer.ApplicationSession.Deploy(String appRootFolder, String appBundleId, String appName) in D:\a\_work\1\s\src\Tools\Xamarin.iOS.Windows.Client\Installer\ApplicationSession.cs:line 95
   at Xamarin.iOS.Windows.HotRestartClient.Deploy(AppleDevice nativeDevice, String appBundleId, String appBundleName, Boolean& incremental) in D:\a\_work\1\s\src\Tools\Xamarin.iOS.Windows.Client\HotRestartClient.cs:line 250
   at Xamarin.Messaging.IDB.Local.DeployAppMessageHandler.<ExecuteAsync>d__5.MoveNext() in D:\a\_work\1\s\src\Messaging\Xamarin.Messaging.IDB.Local\Handlers\DeployAppMessageHandler.cs:line 43: 10.10.2023 13:40:53Z
    DateTime=2023-10-10T13:40:53.6841338Z: 10.10.2023 13:40:53Z
```

### Link to public reproduction project repository

https://github.com/espenrl/issue-repro/tree/main/net8-skiasharp

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.49

### Affected platforms

iOS

### Affected platform versions

iOS 16

_Copied from original issue dotnet/maui#17930_

**Comment by rolfbjarne** [comment]
_From @mattleibow on Wed, 11 Oct 2023 21:49:20 GMT_

@rolfbjarne thoughts?

**Comment by rolfbjarne** [comment]
_From @rolfbjarne on Thu, 12 Oct 2023 09:49:34 GMT_

The sample project works fine for me.

@espenrl can you try running the project directly from the mac using Visual Studio for Mac to see if that works?

**Comment by rolfbjarne** [comment]
_From @drasticactions on Thu, 12 Oct 2023 09:52:02 GMT_

Going by the error in the stack trace, they are using Hot Restart, so it could be specific to that app bundle.

**Comment by rolfbjarne** [comment]
_From @espenrl on Thu, 12 Oct 2023 10:44:41 GMT_

> The sample project works fine for me.
> 
> @espenrl can you try running the project directly from the mac using Visual Studio for Mac to see if that works?

I don't use or have a Mac in my development. I use Windows and Github Actions CI to publish the app. Sorry.

**Comment by rolfbjarne** [comment]
_From @espenrl on Thu, 12 Oct 2023 10:46:40 GMT_

I've also been sure to delete obj/bin and anything in `C:\Users\erl0\AppData\Local\Temp\Xamarin\HotRestart` so it shouldn't be a cache issue.

**Comment by rolfbjarne** [comment]
_From @rkone on Thu, 12 Oct 2023 14:26:02 GMT_

Also happening for me.  Also in 8.0.0.rc.2.9373 and Visual Studio 17.8.0 Preview 3.0

**Comment by rolfbjarne** [comment]
_From @espenrl on Thu, 12 Oct 2023 22:16:41 GMT_

> Also happening for me. Also in 8.0.0.rc.2.9373 and Visual Studio 17.8.0 Preview 3.0

Same software versions in my case.

**Comment by rolfbjarne** [comment]
_From @rolfbjarne on Fri, 13 Oct 2023 13:36:27 GMT_

Can you get a binlog as described here: https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs?

**Comment by rolfbjarne** [comment]
_From @msftbot[bot] on Mon, 16 Oct 2023 19:20:58 GMT_

Hi @espenrl. We have added the "s/needs-info" label to this issue, which indicates that we have an open question for you before we can take further action. This issue will be closed automatically in 7 days if we do not hear back from you by then - please feel free to re-open it if you come back to this issue after that time.

**Comment by rolfbjarne** [comment]
_From @espenrl on Tue, 17 Oct 2023 10:53:15 GMT_

[net8test_Debug_AnyCPU_net8.0-ios_Build_2023-10-17T12_49_57.7879151+02_00.zip](https://github.com/dotnet/maui/files/12927751/net8test_Debug_AnyCPU_net8.0-ios_Build_2023-10-17T12_49_57.7879151%2B02_00.zip)

@rolfbjarne here you go

PS: The app gets installed on the phone, but if I try to start it (without debugging) I get a system message from the phone saying `could not install because integrity could not be verified`.

**Comment by rolfbjarne** [comment]
_From @rolfbjarne on Thu, 19 Oct 2023 10:55:22 GMT_

I can reproduce, and I'm looking at it to see what needs to be done.

**Comment by rolfbjarne** [comment]
Fix is in progress, trying to get this into .NET 8 GA.

**Comment by rolfbjarne** [comment]
> Do you know if the fix will be coming soon or should I just forget Skia and lovely lottie files for now? 😄

The fix will be in .NET 8.

**Comment by gabsamples6** [comment]
Hi is this related to what we are experiencing when launching the app in debug  **using .net 8.0.0-rc.2.9511**

We cannot debug an iOS app (WinPC using iphone hot restart)
When deployed the app we get "the app cannot be installed because its integrity could not be verified"



Xamarin.Messaging.IDB.Local.**DeployAppMessageHandler** Error: 0 :
 An error occurred while trying to deploy the app 'MyApp.app'. Details: Could not install the application 'C:\Users\user\AppData\Local\Temp\Xamarin\HotRestart\Signing\MyApp.app\out\MyApp.ipa' on the device Mark’s iPhone. 
 Details: ApplicationVerificationFailed|0xE8008014 - Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.fVnlmq/extracted/Payload/MyApp.app/Frameworks/libSkiaSharp.framework : 0xe8008014 (**The executable contains an invalid signature**.)

Xamarin.iOS.Windows.WindowsiOSException: Could not install the application 'C:\Users\user\AppData\Local\Temp\Xamarin\HotRestart\Signing\MyApp.app\out\MyApp.ipa' on the device User’s iPhone. 
Details: ApplicationVerificationFailed|0xE8008014 - Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.fVnlmq/extracted/Payload/MyApp.app/Frameworks/libSkiaSharp.framework : 0xe8008014 (The executable contains an invalid signature.)
   at Xamarin.iOS.Windows.Installer.ApplicationSession.InstallApp(String appPath, String appBundleId) in D:\a\_work\1\s\src\Tools\Xamarin.iOS.Windows.Client\Installer\ApplicationSession.cs:line 276

**Comment by rolfbjarne** [comment]
@gabsamples6 yes, that looks related.

**Comment by espenrl** [comment]
Tested it now on latest MAUI .NET 8 RC2 release and it deploys smoothly. Good work @rolfbjarne
