### ISSUE TITLE
Xamarin.Shared.Sdk.targets MessagingException The post for client ... on topic ... GetFileSystemEntries has been cancelled

### ISSUE THREAD

**Issue by tranb3r** [xamarin/xamarin-macios#20183]
### Steps to Reproduce

Error when building my maui app for ios.

```
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.2.8022\targets\Xamarin.Shared.Sdk.targets(2266,3): error : MessagingException: The post for client build2914829148bertr on topic xvs/build/1.11.0.2/execute-task/OuiBank.Maui/13bfbaa002fGetFileSystemEntries has been cancelled [D:\Dev\Zitch\ouibank\OuiBank.Maui\OuiBank.Maui.csproj::TargetFramework=net8.0-ios17.2]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.2.8022\targets\Xamarin.Shared.Sdk.targets(2266,3): error : OperationCanceledException: The operation was canceled. [D:\Dev\Zitch\ouibank\OuiBank.Maui\OuiBank.Maui.csproj::TargetFramework=net8.0-ios17.2]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.2.8022\targets\Xamarin.Shared.Sdk.targets(2266,3): error :  [D:\Dev\Zitch\ouibank\OuiBank.Maui\OuiBank.Maui.csproj::TargetFramework=net8.0-ios17.2]
```

What can I do?

### Environment

Windows 10
Visual studio 2022 17.9.0
ios SDK 17.2.8022
xcode 15.2 on remote mac 
macOS Sonoma 14.1.1

### Build Logs

binlog: [msbuild.zip](https://github.com/xamarin/xamarin-macios/files/14375521/msbuild.zip)

**Comment by rolfbjarne** [comment]
Does this happen all the time, or just once in a while?

**Comment by tranb3r** [comment]
@rolfbjarne It happens all the time.

**Comment by rolfbjarne** [comment]
The build is trying to find all files in a given directory when it gets stuck and is eventually cancelled. I suspect something is wrong when iterating over files, where the build is finding too many files for some reason (maybe it's looking in the root directory due to a bug, maybe something else is going on).

So to start diagnosing, can you delete the following directory, try again and see if something changes?

> ~/Library/Caches/Xamarin/mtbs/builds

This is where the builds are stored on the Mac, removing this directory makes sure the build starts from a clean state (on the Mac).

If that doesn't work, try creating a new project, adding the Firebase NuGets (looks like these trigger the problem somehow), and see if you can reproduce in the new project as well.

**Comment by tranb3r** [comment]
@rolfbjarne 
I've deleted the `~/Library/Caches/Xamarin/mtbs/builds` folder, but I still get the same error.
I can build a new project successfully. 
However when adding Firebase Nuget, I get the build error.

**Comment by rolfbjarne** [comment]
> I can build a new project successfully.
> However when adding Plugin.Firebase Nugets, I get the build error.

Can you attach that new project that fails?

**Comment by tranb3r** [comment]
@rolfbjarne 
The project is available [here](https://github.com/tranb3r/Issues/tree/main/MauiAppIOsBuildIssue)

**Comment by rolfbjarne** [comment]
I tried your project, and works fine for me, so since I'm not sure what's going on, I'm recommending filing an issue with the IDE, which is the team responsible for this.

**Comment by tranb3r** [comment]
@rolfbjarne 
The error happens when building from the command line.
How could this be related to Visual Studio?
Could you please confirm you used the build command from the scripts folder in the repro project?

**Comment by tranb3r** [comment]
Yes, it also happens when building from Visual Studio.
New ticket here: https://developercommunity.visualstudio.com/t/iOS:-XamarinSharedSdktargets-Messagin/10609446
