### ISSUE TITLE
[macOS] Exception in NSControl.Activated event handler doesn't crash the app

### ISSUE THREAD

**Issue by tipa** [xamarin/xamarin-macios#20400]
I just encountered a situation where my app got in a weird, undefined state that shouldn't have happened. After more investigation I found that my code was throwing an exception in the middle of a button click event handler, but it did not crash my app, as I would have expected. Why is that?

### Steps to Reproduce

1. create `NSButton`
2. subscribe to `Activated` event, throw exception in event handler
3. click button

### Expected Behavior
Exception crashes the app, as it isn't handled by my code

### Actual Behavior
The app does not crash

### Environment
.NET 8

### Example Project (If Possible)
[crash_test.zip](https://github.com/xamarin/xamarin-macios/files/14885690/crash_test.zip)

**Comment by rolfbjarne** [comment]
> Why is that?

This is what happens:

1. The managed exception occur in the button click event handler.
2. Upon returning to native code, we convert the managed exception into an Objective-C exception, and throw that.
3. Cocoa handles the Objective-C exception, _and ignores it completely_.

You can configure the behavior when a managed exception has to be marshalled to native code: https://learn.microsoft.com/en-us/xamarin/ios/platform/exception-marshaling (the default in .NET is to convert it to an Objective-C exception, while the default in Xamarin.iOS/Xamarin.Mac was to let Mono unwind the stack trace - which had its own set of problems, as that document explains).

My recommendation is to add event handlers when exceptions are marshalled (https://learn.microsoft.com/en-us/xamarin/ios/platform/exception-marshaling#events), and then log those, preferrably fixing them somehow so that they don't occur in the first place.

FWIW on iOS UIKit does *not* ignore Objective-C exceptions like this, and the app crashes (as expected) - one area where UIKit is an improvement over AppKit/Cocoa.

**Comment by tipa** [comment]
There's always something new to learn... Thanks a lot for taking the time to explain what's going on!
