### ISSUE TITLE
Missing VNBarcodeObservation properties

### ISSUE THREAD

**Issue by afriscic** [xamarin/xamarin-macios#20744]
Hello.

I don't really know if it is a bug or am I missing something but on MAUI 8.0.40/8.0.100 SDK 8.0.300 and Microsoft.iOS.Ref 17.2.8053 I'm unable to access VNBarcodeObservation properties that require iOS and MacCatalyst >= 17.0 (PayloadData, IsGS1DataCarrier, IsColorInverted, SupplementalCompositeType, SupplementalPayloadString and SupplementalPayloadData).

Link: [vision.cs](https://github.com/xamarin/xamarin-macios/blob/6c2a7a9eac6168910e59134fc5e452b758675f2c/src/vision.cs#L2262)

Is this released on .NET 8?

**Comment by rolfbjarne** [comment]
As you can see from the vision.cs file, we've already implemented these properties.

The plan was to release them together with new APIs released in Xcode 15.3, but that release has unfortunately been rather delayed due to unforeseen circumstances.

The current plan is technically the same: release the VNBarcodeObservation properties with our Xcode 15.3, but I don't know when that might be. In the meantime, I created a few extensions methods that should make it possible to fetch these properties: https://gist.github.com/rolfbjarne/41bb92baf79a006d5ebf59457d5ce3aa (it's untested, but shouldn't be too far from a working version).
