### ISSUE TITLE
.NET MAUI XCFramework error clang++ exited with code 1: Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by jerodmotley** [xamarin/xamarin-macios#20809]
### Steps to Reproduce

1. Created MAUI iOS class library Project & added native frameworks on M1 and Intel Mac
2. Create MAUI app and added the reference of MAUI iOS class Library created in step 1
3. Compile MAUI app

### Expected Behavior
MAUI app created in step 2 should compile

### Actual Behavior
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(3,3): Error: clang++ exited with code 1:
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_MiSnapSDKOverlayView", referenced from:
      objc-class-ref in registrar.o
  "_OBJC_CLASS_$_MiSnapSDKOverlayViewUX1", referenced from:
      objc-class-ref in registrar.o
  "_OBJC_CLASS_$_MiSnapSDKOverlayViewUX2", referenced from:
      objc-class-ref in registrar.o
  "_OBJC_CLASS_$_MiSnapSDKTutorialViewController", referenced from:
      objc-class-ref in registrar.o
  "_OBJC_CLASS_$_MiSnapSDKViewController", referenced from:
      objc-class-ref in registrar.o
  "_OBJC_CLASS_$_MiSnapSDKViewControllerUX1", referenced from:
      objc-class-ref in registrar.o
  "_OBJC_CLASS_$_MiSnapSDKViewControllerUX2", referenced from:
      objc-class-ref in registrar.o
  "_OBJC_CLASS_$_MiSnapTutorialViewControllerDelegate", referenced from:
      objc-class-ref in registrar.o
  "_OBJC_CLASS_$_MiSnapViewControllerDelegate", referenced from:
      objc-class-ref in registrar.o
  "_OBJC_CLASS_$_ShowResultsViewController", referenced from:
      objc-class-ref in reg

### Environment
Visual Studio for Mac 17.6.12 (build 410)
.NET SDK (Arm64) 8.0.302
.NET Runtime (Arm64) 8.0.6

I have checked other posts about similar issues and none are working.

<details>
<summary>Version information</summary>

```
```

</details>

**Comment by rolfbjarne** [comment]
If you're building for the iOS Simulator, the problem is likely that the native framework in question does not contain native bits for arm64 in the simulator.

If you provide a binary build log (binlog) - https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs - I can check if this is the case.

**Comment by jerodmotley** [comment]
I tried building on the device and simulator, on both an Intel and M1 Mac. It's still the same error.

**Comment by rolfbjarne** [comment]
Please provide a complete test project we can use to reproduce the problem then.

**Comment by jerodmotley** [comment]
[msbuild.binlog.zip](https://github.com/user-attachments/files/16091023/msbuild.binlog.zip)
binlog attached.

**Comment by rolfbjarne** [comment]
The EntrustIdentityiOS.csproj project is referencing a native library:

```xml
<NativeReference Include="libEntrustIGMobileSDK.a">
```

and this won't work, because a native library can only contain a single slice of native code for each architecture - historically arm64 for device and x64 for the simulator. The problem is that there's now arm64 for the simulator, and if there's an arm64 slice in the native library, it won't apply to the simulator.

The solution is to create an xcframework, which can contain multiple native libraries, one for the simulator and one for device. Then you reference the xcframework in the binding project instead:

```xml
<NativeReference Include="libEntrustIGMobileSDK.xcframework">
```

Typically the vendor of the native library can also provide the xcframework version (Xcode projects need it too). If this is your own library, there are plenty of tutorials online on how to create xcframeworks.

Can you try that and see if it works for you?

**Comment by jerodmotley** [comment]
> The EntrustIdentityiOS.csproj project is referencing a native library:
> 
> ```
> <NativeReference Include="libEntrustIGMobileSDK.a">
> ```
> 
> and this won't work, because a native library can only contain a single slice of native code for each architecture - historically arm64 for device and x64 for the simulator. The problem is that there's now arm64 for the simulator, and if there's an arm64 slice in the native library, it won't apply to the simulator.
> 
> The solution is to create an xcframework, which can contain multiple native libraries, one for the simulator and one for device. Then you reference the xcframework in the binding project instead:
> 
> ```
> <NativeReference Include="libEntrustIGMobileSDK.xcframework">
> ```
> 
> Typically the vendor of the native library can also provide the xcframework version (Xcode projects need it too). If this is your own library, there are plenty of tutorials online on how to create xcframeworks.
> 
> Can you try that and see if it works for you?

The ".a" project reference works fine. We're only having isses with the xcframework used in the other binding library. If we remove any reference to the Mitek library (xcframeworks) the project works fine. The behavior is the same on both intel and M series Macs.

<NativeReference Include="libEntrustIGMobileSDK.a">

**Comment by rolfbjarne** [comment]
Could you try to create a test project we can use to reproduce the problem then?

**Comment by jerodmotley** [comment]
[XCFrameworkTest.zip](https://github.com/user-attachments/files/16110309/XCFrameworkTest.zip)
Here is a sample project with those same xcframeworks.

**Comment by jerodmotley** [comment]
Here is a log where we referenced a project instead of a dll.
[Archive.zip](https://github.com/user-attachments/files/16147319/Archive.zip)

**Comment by rolfbjarne** [comment]
> [XCFrameworkTest.zip](https://github.com/user-attachments/files/16110309/XCFrameworkTest.zip) Here is a sample project with those same xcframeworks.

The frameworks for a binding assembly can be in two different locations:

1. As resources in the binding assembly.
2. Inside a `*.resources` directory next to the binding assembly.

In this sample, the frameworks are *next* to the binding assembly (XCFrameworkTest/dlls/MiSnapSDK_original/MitekiOSBindingNew.dll), so they're not found during the build.

Can you attach the binding project as well?

**Comment by jerodmotley** [comment]
Binding project is attached.
[Archive 2.zip](https://github.com/user-attachments/files/16147550/Archive.2.zip)

**Comment by rolfbjarne** [comment]
You have to add the xcframework itself as the NativeReference in the binding project.

So instead of:

```xml
<NativeReference Include="..\MiSnapSDK_original\MiSnapSDKCamera.xcframework\ios-arm64_armv7\MiSnapSDKCamera.framework">
  <Kind>Framework</Kind>
  <SmartLink>False</SmartLink>
  <ForceLoad>True</ForceLoad>
</NativeReference>
```

do:

```xml
<NativeReference Include="..\MiSnapSDK_original\MiSnapSDKCamera.xcframework">
  <Kind>Framework</Kind>
  <SmartLink>False</SmartLink>
  <ForceLoad>True</ForceLoad>
</NativeReference>
```

That said, your zip file doesn't include the xcframeworks, so I can't test this.

Also note that the binding project doesn't compile, because you're trying to add a constructor to a category:

```cs
[Category]
[BaseType(typeof(MiSnapSDKViewController))]
interface MiSnapSDKViewController_MiSnapPrivate
{
    // -(id)initWithParameters:(NSDictionary *)parametersDictionary;
    [Export("initWithParameters:")]
    IntPtr Constructor(NSDictionary parametersDictionary);
}
```

That's not supported (admittedly we should give a better error message here). You can either remove the constructor, or move it into the `MiSnapSDKViewController` type.

**Comment by jerodmotley** [comment]
I thought the frameworks were included. They are now.
[MiSnapSDK_original.zip](https://github.com/user-attachments/files/16168015/MiSnapSDK_original.zip)

**Comment by jerodmotley** [comment]
We have updated the references as you mentioned and made sure the reference project compiles. We got the error attached. Also attaching the updated logs.
![image](https://github.com/xamarin/xamarin-macios/assets/164416599/208ccf7e-e74d-4e80-b0ed-3f33b086ffdc)
[Archive.zip](https://github.com/user-attachments/files/16170094/Archive.zip)

**Comment by rolfbjarne** [comment]
> I thought the frameworks were included. They are now. [MiSnapSDK_original.zip](https://github.com/user-attachments/files/16168015/MiSnapSDK_original.zip)

There are no .xcframework directories in his zip, only .framework directories.

**Comment by jerodmotley** [comment]
My apologies for missing the extension difference. Here are the xc extensions.
[MiSnapSDK.zip](https://github.com/user-attachments/files/16178953/MiSnapSDK.zip)
[MyFramework.xcframework.zip](https://github.com/user-attachments/files/16178962/MyFramework.xcframework.zip)

**Comment by rolfbjarne** [comment]
OK, I made that work.

In the binding project, you need to:

* Uncomment the `[Protocol, Model]` attributes to MiSnapViewControllerDelegate and MiSnapTutorialViewControllerDelegate
* Remove the constructor in the MiSnapSDKViewController_MiSnapPrivate.
* Adjust the NativeReference items to reference the corresponding .xcframework instead of .framework.

In the executable project, you need to:

* Remove the dlls subdirectory. All files in the project directory are included in the project (recursively), and you have frameworks in the dlls directory, which means they end up included in the build, which ends up wrong. Regarding the .strings resources, you can keep those, but not inside a .framework directory, you'll have to move them to a different parent directory.

Zipped versions that work for me:

* [XCFrameworkTest.zip](https://github.com/user-attachments/files/16181411/XCFrameworkTest.zip)
* [MitekiOSBindingNew.zip](https://github.com/user-attachments/files/16181412/MitekiOSBindingNew.zip)

You'll have to adjust paths in the project files to the location on your hard drive.

**Comment by jerodmotley** [comment]
I am working on your suggested changes right now. One thing that isn't working is referring specific project to their respective platforms. For example, the project that you assisted with is iOS only. However when I specify that, nothing works at all. The only thing that works is making the whole app specific to the platform you want to build for, and then changing it to a different platform as needed.
