### ISSUE TITLE
MtouchInterpreter is disabled in Debug iOS configuration after the latest update 

### ISSUE THREAD

**Issue by AlexanderEgorov** [xamarin/xamarin-macios#20869]
Hello, 

**After the latest update**, we noticed that **Reflection.Emit** is not allowed in **Debug** iOS configuration.

### Example Project

[_DXMauiApp-MtouchInterpreter.zip](https://github.com/user-attachments/files/16175886/_DXMauiApp-MtouchInterpreter.zip)

### Steps to Reproduce

1. Build the attached project under Debug configuration
2. Run the project on iPhone 15 simulator (iOS 17.5)
3. Click the Test button.

The **PlatformNotSupportedException** error is shown (Dynamic code generation is not supported on this platform).  
**In the previous version, there was no such errors.**

Then, open the **DXMauiApp.csproj** file and uncomment this line: `<MtouchInterpreter>all</MtouchInterpreter>`.  
Repeat the test again and notice that there is no errors anymore.

### Investigation

I have tried to add the following block to the csproj file:

```xml
<Target Name="PrintInfo" BeforeTargets="BeforeBuild">
   <Error Text="MtouchUseLlvm=$(MtouchUseLlvm), UseInterpreter=$(UseInterpreter), MtouchInterpreter=$(MtouchInterpreter)"/>
</Target>
```
This task prints the following info:

```
error : MtouchUseLlvm=, UseInterpreter=true, MtouchInterpreter= [TargetFramework=net8.0-android]
error : MtouchUseLlvm=False, UseInterpreter=True, MtouchInterpreter=all [TargetFramework=net8.0-ios]
```

So, all variables have the same values as in previous versions.
 
### Environment

```
Xcode 15.4
iPhone 15 Simulator (iOS 17.5)
dotnet version:
  8.0.303
dotnet workload:
  maui-ios:
    Manifest Version: 8.0.61/8.0.100
    Installation Source: SDK 8.0.300
```

**Comment by rolfbjarne** [comment]
This is a consequence of a [bug fix](https://github.com/xamarin/xamarin-macios/pull/20732), and is in fact the expected behavior:

System.Reflection.Emit (dynamic code support in general) is only supported when the interpreter is enabled, and the interpreter is not enabled by default (in either Debug or Release) for plain iOS projects [1].

In your particular scenario, your code might have worked even without the interpreter, but that would have been mostly by accident.

The fix is to enable the interpreter, as you've already found out.

[1]: it's enabled by default for Debug builds in MAUI projects.
