### ISSUE TITLE
clang++ exited with code 1: Undefined symbols for architecture arm64 when using the XCFramework for .NET MAUI iOS binding library 

### ISSUE THREAD

**Issue by Bagya921230** [xamarin/xamarin-macios#20992]
### Steps to Reproduce

1. Updated existing iOS binding library project by adding SDK's XCFramework and built iOS binding dll successfully. (Previously worked with .a file( Native static library))
2. Updated the .NET MAUI class library which included Android and iOS binding libraries and built dlls. (Only added the newly created iOS binding)
3. Built the existing sample project with the new iOS & Android binding dlls and class library dll. 

### Expected Behavior

Existing sample project should be working perfectly as the only update was using the XCFramework instead of the native static library file.

### Actual Behavior
When building sample project it produces below error.
Note: The sample project is working fine with the binding created with .a file but not with XCFramework file. And when the framework(ios-arm64/ios-arm64_x86_64-simulator) files are included separately in the binding project file, everything works.
[
<img width="690" alt="Screenshot 2024-08-07 at 2 08 12 PM" src="https://github.com/user-attachments/assets/8cb4b982-a649-4cf2-afe1-c66599b8db3f">
](url)

### Environment

<details>
<summary>Version information</summary>

```
Visual Studio Community 2022 for Mac
Version 17.6.13 (build 424)
Installation UUID: 9245bfd5-8d81-457f-9314-96c56a76c0c8

Runtime
.NET 7.0.3 (64-bit)
Architecture: Arm64
Microsoft.macOS.Sdk 13.1.1007; git-rev-head:8afca776a0a96613dfb7200e0917bb57f9ed5583; git-branch:release/7.0.1xx-xcode14.2

Roslyn (Language Service)
4.6.0-3.23180.6+99e956e42697a6dd886d1e12478ea2b27cceacfa

NuGet
Version: 6.4.0.117

.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/8.0.303/Sdks
SDK Versions:
	8.0.303
	8.0.201
	8.0.200
	8.0.102
	7.0.317
	7.0.316
	7.0.315
	7.0.314
	7.0.313
	7.0.311
	7.0.310
	7.0.309
	7.0.308
	7.0.307
	7.0.302
	6.0.424
	6.0.422
	6.0.421
	6.0.420
	6.0.419
	6.0.417
	6.0.416
	6.0.415
	6.0.414
	6.0.413
	6.0.408
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET SDK (x64)
SDK Versions:
	8.0.201
	8.0.200
	8.0.102

.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	8.0.7
	8.0.2
	7.0.20
	7.0.19
	7.0.18
	7.0.17
	7.0.16
	7.0.14
	7.0.13
	7.0.12
	7.0.11
	7.0.10
	7.0.5
	6.0.32
	6.0.30
	6.0.29
	6.0.28
	6.0.27
	6.0.25
	6.0.24
	6.0.23
	6.0.22
	6.0.21
	6.0.16

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/x64/dotnet
Runtime Version: 8.0.2

Xamarin.Profiler
Version: 1.8.0.49
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin Designer
Version: 17.6.3.9
Hash: 2648399ae8
Branch: remotes/origin/d17-6
Build date: 2024-07-09 00:12:23 UTC

Xamarin.Android
Version: 13.2.2.0 (Visual Studio Community)
Commit: xamarin-android/d17-5/45b0e14
Android SDK: /Users/bg7115/Library/Android/sdk
	Supported Android versions:
		12.1 (API level 32)
		12.0 (API level 31)
		11.0 (API level 30)
		13.0 (API level 33)

SDK Command-line Tools Version: 13.0
SDK Platform Tools Version: 35.0.2
SDK Build Tools Version: 35.0.0

Build Information: 
Mono: d9a6e87
Java.Interop: xamarin/java.interop/d17-5@149d70fe
SQLite: xamarin/sqlite/3.40.1@68c69d8
Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@ca1552d

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.16.1
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.6.0.50
Hash: a715dca
Branch: HEAD
Build date: 2024-07-09 00:12:30 UTC

Android Device Manager
Version: 0.0.0.1309
Hash: 06e3e77
Branch: HEAD
Build date: 2024-07-09 00:12:30 UTC

Apple Developer Tools
Xcode: 15.4 22622
Build: 15F31d

Xamarin.Mac
Not Installed

Xamarin.iOS
Version: 16.4.0.23 Visual Studio Community
Hash: 9defd91b3
Branch: xcode14.3
Build date: 2023-10-23 16:15:00-0400

Build Information
Release ID: 1706130424
Git revision: acd381f8e8bd7deca64bdf93287dc0849a0e73f5
Build date: 2024-07-09 00:10:15+00
Build branch: release-17.6
Build lane: release-17.6

Operating System
Mac OS X 14.5.0
Darwin 23.5.0 Darwin Kernel Version 23.5.0
    Wed May  1 20:12:58 PDT 2024
    root:xnu-10063.121.3~5/RELEASE_ARM64_T6000 arm64

Enabled user installed extensions
.NET Core Extensions 0.7
```

</details>

### Build Logs

[msbuild.binlog.zip](https://github.com/user-attachments/files/16521082/msbuild.binlog.zip)

**Comment by rolfbjarne** [comment]
You don't show a binlog for the binding project, but I suspect you're setting `NoBindingEmbedding=false` in your binding project.

Try removing that line and see if that works.

If you don't have that line, or it doesn't work, please provide a binlog when building the binding project as well.

**Comment by Bagya921230** [comment]
[msbuild.binlog.zip](https://github.com/user-attachments/files/16537642/msbuild.binlog.zip)

Attaching the binding file and NoBindingEmbedding=false is not there in the binding project file.
Below is the binding project file format we are using.
[ScannerSDKiOSBinding.csproj.zip](https://github.com/user-attachments/files/16537656/ScannerSDKiOSBinding.csproj.zip)

**Comment by rolfbjarne** [comment]
We're looking for the xcframework inside this directory (next to the `/Users/bg7115/Documents/Xamarin Workspace/DCS-Unified-Scanner-SDK-For-Xamarin/src/MAUI Support/NET 8 Support/ZebraBarcodeScannerSDK/ZebraBarcodeScannerSDK/bin/Debug/net8.0-ios/ScannerSDKiOSBinding.dll` assembly referenced in your main project file):

> /Users/bg7115/Documents/Xamarin Workspace/DCS-Unified-Scanner-SDK-For-Xamarin/src/MAUI Support/NET 8 Support/ZebraBarcodeScannerSDK/ZebraBarcodeScannerSDK/bin/Debug/net8.0-ios/ScannerSDKiOSBinding.resources

but that directory doesn't seem to exist.

I'm guessing you have a `ZebraBarcodeScannerSDK` project, which references the `ScannerSDKiOSBinding` project, which you build and then reference the assemblies from the bin directory of the `ZebraBarcodeScannerSDK`.

Unfortunately this won't work, because when building the `ZebraBarcodeScannerSDK` project, the additional `ScannerSDKiOSBinding.resources` directory isn't copied to `ZebraBarcodeScannerSDK`'s bin directory together with the `ScannerSDKiOSBinding.dll` assembly.

There are a couple of options:

1. Reference the `ZebraBarcodeScannerSDK` project from your main project (and `ScannerSDKiOSBinding` project from your `ZebraBarcodeScannerSDK` project, if you're not already doing that).
2. Create a NuGet for the `ZebraBarcodeScannerSDK` and `ScannerSDKiOSBinding` projects and reference those in your main project.
3. Reference the `ScannerSDKiOSBinding.dll` assembly from the `ScannerSDKiOSBinding` project's bin directory instead of the one from the `ZebraBarcodeScannerSDK` project.

Can you try and see if that works?

**Comment by Bagya921230** [comment]
Referencing the binding dll from binding project's bin worked fine. 

Just for information we need to clarify why previous way of including the dlls worked with iOS static library (.a) but not with XCFramework. Previously we made the MAUI sample app work well without the resources file linking and only including the dlls from ZebraBarcodeScannerSDK project's bin.

**Comment by rolfbjarne** [comment]
> Just for information we need to clarify why previous way of including the dlls worked with iOS static library (.a) but not with XCFramework.

In Xamarin we would default to embedding the native libraries (such as your .a file) as a resource inside the binding assembly, so there wouldn't be a problem of not copying it around.

In .NET, we default to putting native libraries in a separate directory next to the binding assembly (this has a rather big performance impact for big native libraries: we've seen multi-GB native libraries, and reading them as a resource from the binding assembly and writing them to disk takes quite a while, and disk space also becomes an issue because the native library is essentially duplicated, inside the assembly and then extracted on disk).
