### ISSUE TITLE
C# Wrapper fails to load framework library

### ISSUE THREAD

**Issue by afcsoft** [xamarin/xamarin-macios#21200]
### Apple platform

iOS

### Framework version

net8.0-*

### Affected platform version

.NET 8.0.100

### Description

C# wrapper throws DllNotFoundException when trying to use framework dynamic library. 
Here is the [sample code](https://github.com/afcsoft/FrameworkTest) which includes native library compilation and wrapper.

### Steps to Reproduce

1. Open solution folder
2. Navigate to "native"
3. Make sure to use valid development team name in CMakeLists.txt
4. Run "cmake -S . --preset ios-arm64"
5. Run "cmake --build out/ios-arm64"
6. Navigate to TestLibWrapper
7. Run "dotnet build"
8. Run "nuget pack TestLibWrapper.nuspec"
9. Consume TestLibWrapper in sample .NET MAUI App "TestLib.CallTestFunc()"
10. Run on iOS Device
11. It will throw DllNotFoundException (TestLib)

**Comment by rolfbjarne** [comment]
The problem is that the library name in the P/Invoke is wrong.

I can either be `"@rpath/TestLib.framework/TestLib"`, or you can use the NativeLibrary API to find and load the desired native library at runtime: https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.nativelibrary?view=netcore-3.1

Can you try that and see if it works for you?

**Comment by afcsoft** [comment]
It works for me but It causes trouble more than a solution. Since I am trying to create a single nuget package that covers multiple platforms. Why can't we have framework dir in the search path for DllImport? Now I need to create multiple packages for each platform, I guess.

**Comment by rolfbjarne** [comment]
> Why can't we have framework dir in the search path for DllImport?

It's because we pass the library name directly to the native OS function to load a library (`dlopen`), so the string needs to be something the OS understands, and this is how it's done for frameworks on Apple platforms.

> Now I need to create multiple packages for each platform, I guess.

You could create one package that uses the NativeLibrary API as mentioned above, and only use the API on iOS.
