### ISSUE TITLE
[MacCatalyst] OperatingSystem is currently not working 

### ISSUE THREAD

**Issue by PureWeen** [xamarin/xamarin-macios#21390]
### Description

It looks like on MacCatalyst the Build on the `Environment.OSVersion.Version` is set to "-1" so when you call 

`if (OperatingSystem.IsMacCatalystVersionAtLeast(18,0))`

it resolves to false. 
This works fine on iOS just not MacCatalyst

### Reproduction
[aoperatingsystem.zip](https://github.com/user-attachments/files/17298855/aoperatingsystem.zip)

Just run the app and I've set a label on the screen to output the value of `OSVersion.Version`. I've also included some if statements in the main page you can break point

#### Catalyst
![image](https://github.com/user-attachments/assets/e69cc7c1-d447-4a70-b444-682cfcf28d97)

#### iOS

![image](https://github.com/user-attachments/assets/f68e99f7-c867-4e17-b788-5e9b75093d08)

**Comment by drasticactions** [comment]
https://github.com/drasticactions/MauiRepoRedux/tree/MacCatalystVersion

https://github.com/dotnet/runtime/blob/abde3f9498f09b5016a7a0d7d2e1b81ce5c1b614/src/libraries/System.Private.CoreLib/src/System/OperatingSystem.cs#L227

<img width="759" alt="スクリーンショット 2024-10-09 14 19 32" src="https://github.com/user-attachments/assets/2a4f267f-b66c-4252-9022-750687810fb9">

https://github.com/dotnet/runtime/blob/abde3f9498f09b5016a7a0d7d2e1b81ce5c1b614/src/libraries/Common/src/Interop/OSX/System.Native/Interop.iOSSupportVersion.cs#L11

https://github.com/dotnet/runtime/blob/abde3f9498f09b5016a7a0d7d2e1b81ce5c1b614/src/libraries/System.Private.CoreLib/src/System/OperatingSystem.cs#L328-L341

https://github.com/xamarin/xamarin-macios/blob/0db186c75896a516b409274b45136714230d60ab/tests/common/PlatformInfo.cs#L95-L107

<img width="277" alt="image" src="https://github.com/user-attachments/assets/1ddc7f49-c2f4-4610-b8a1-649f06ec359b">

https://github.com/xamarin/xamarin-macios/blob/0db186c75896a516b409274b45136714230d60ab/tests/common/PlatformInfo.cs#L82

That value is coming from `SystemVersion.plist`, which is `18.0`, hence why it would get `-1`, since it's `Version.Parse`ed and it doesn't have the Build number that it may have had in the past.

https://github.com/dotnet/runtime/blob/abde3f9498f09b5016a7a0d7d2e1b81ce5c1b614/src/libraries/System.Private.CoreLib/src/System/OperatingSystem.cs#L344

It may be that this needed that the `-1` check needs to also be added to build for the same reason as revision, since it can't be assumed that build will be there. Or the SDK code above that fetches the version should always include the build even if the system doesn't provide it.

To work around it, checking against`18` `0` `-1` should work

**Comment by rolfbjarne** [comment]
This issue was moved to dotnet/runtime#108694
