### ISSUE TITLE
[.NET 9] iOS notification app extensions

### ISSUE THREAD

**Issue by dottam** [xamarin/xamarin-macios#21606]
### Apple platform

iOS

### Framework version

net9.0-*

### Affected platform version

.NET 9.0.100 / iOS MAUI 18.0.9617/9.0.100

### Description

The iOS notification extensions does not work as expected in .NET 9, tested on iPhone 12 iOS 18.0.1

**Sample project**
[notification.zip](https://github.com/user-attachments/files/17725820/notification.zip)

**.NET information**

.NET SDK:
 Version:           9.0.100
 Commit:            59db016f11
 Workload version:  9.0.100-manifests.c6f19616
 MSBuild version:   17.12.7+5b8665660

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  15.1
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/9.0.100/

.NET workloads installed:
 [maui-ios]
   Installation Source: SDK 9.0.100
   Manifest Version:    9.0.0/9.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/9.0.100/microsoft.net.sdk.maui/9.0.0/WorkloadManifest.json
   Install Type:        FileBased

 [ios]
   Installation Source: SDK 9.0.100
   Manifest Version:    18.0.9617/9.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/9.0.100/microsoft.net.sdk.ios/18.0.9617/WorkloadManifest.json
   Install Type:        FileBased

 [maui]
   Installation Source: SDK 9.0.100
   Manifest Version:    9.0.0/9.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/9.0.100/microsoft.net.sdk.maui/9.0.0/WorkloadManifest.json
   Install Type:        FileBased

### Steps to Reproduce

1. Change the bundle identifier in the Info.plist for the notificationTest, notificationService and notificationContent sample projects to match your provisioning profile
3. Build the project
    `dotnet build notificationTest/notificationTest.csproj -c Debug -p:Platform="iPhone" -p:RuntimeIdentifier="ios-arm64"`
4. Install and launch the app on device
5. Tap "Send Local Notification" button
6. Long pressed the notification to show details

Observe logs from Console app

### Did you find any workaround?

Sets the `TargetFramework` to `net8.0-ios` in the following projects

- notificationContent/notificationContent.csproj 
- notificationService/notificationService.csproj

### Relevant logs

Logs from Console app:

*** Terminating app due to uncaught exception 'ObjCRuntime.RuntimeException', reason: 'Could not find the type 'ObjCRuntime.__Registrar__' in the assembly 'NotificationTest.NotificationContent'. (ObjCRuntime.RuntimeException)
   at ObjCRuntime.RegistrarHelper.GetMapEntry(String assemblyName)
   at ObjCRuntime.RegistrarHelper.GetMapEntry(Assembly assembly)
   at ObjCRuntime.RegistrarHelper.LookupRegisteredType(Assembly assembly, UInt32 id)
   at ObjCRuntime.Class.ResolveToken(Assembly assembly, Module module, UInt32 token)
   at ObjCRuntime.Class.ResolveFullTokenReference(UInt32 token_reference)
   at ObjCRuntime.Class.ResolveTokenReference(UInt32 token_reference, UInt32 implicit_token_type)
   at ObjCRuntime.Class.ResolveTypeTokenReference(UInt32 token_reference)
   at ObjCRuntime.Class.FindType(NativeHandle class, Boolean& is_custom_type)
   at ObjCRuntime.Class.Lookup(IntPtr klass, Boolean throw_on_error)
   at ObjCRuntime.Class.Lookup(IntPtr klass)
   at ObjCRuntime.Runtime.ConstructNSObject(IntPt<…>

Received unhandled Objective-C exception that was marshalled from a managed exception: Could not find the type 'ObjCRuntime.__Registrar__' in the assembly 'NotificationTest.NotificationContent'. (ObjCRuntime.RuntimeException)
   at ObjCRuntime.RegistrarHelper.GetMapEntry(String assemblyName)
   at ObjCRuntime.RegistrarHelper.GetMapEntry(Assembly assembly)
   at ObjCRuntime.RegistrarHelper.LookupRegisteredType(Assembly assembly, UInt32 id)
   at ObjCRuntime.Class.ResolveToken(Assembly assembly, Module module, UInt32 token)
   at ObjCRuntime.Class.ResolveFullTokenReference(UInt32 token_reference)
   at ObjCRuntime.Class.ResolveTokenReference(UInt32 token_reference, UInt32 implicit_token_type)
   at ObjCRuntime.Class.ResolveTypeTokenReference(UInt32 token_reference)
   at ObjCRuntime.Class.FindType(NativeHandle class, Boolean& is_custom_type)
   at ObjCRuntime.Class.Lookup(IntPtr klass, Boolean throw_on_error)
   at ObjCRuntime.Class.Lookup(IntPtr klass)
   at ObjCRuntime.Runtime.ConstructNSObject(IntPt<…>

**Comment by rolfbjarne** [comment]
Can you try adding this to the csproj to see if that works around it?

```xml
<PropertyGroup>
    <Registrar>static</Registrar>
</PropertyGroup>
```

**Comment by dottam** [comment]
setting `Registrar` property works. Is it a workaround or we need to add this property moving forward?

**Comment by rolfbjarne** [comment]
It's a workaround, we'll fix it so that it works without it (although I'm not sure right now when that might be).

**Comment by ivanpovazan** [comment]
Just for reference and to not lose the track of it.
The linked issue: https://github.com/roubachof/NukeProxy/issues/23 which a potential duplicate, also has a repro project posted here: https://github.com/Cheesebaron/NukeProxyObjCRuntimeRegistrar
/cc: @Cheesebaron

**Comment by rolfbjarne** [comment]
I can reproduce the problem, and a fix is in progress.

**Comment by bnSonic** [comment]
As this one is almost a year old i like to ask: Is this (or should this) be fixed in the .net9 / maui9.0.110 or something?

I'm asking because i have a strange and serious problem with my ShareExtension:
- When i Debug (on real device - iPad and iPhone) the ShareExtension just works: Select a file, "share…", choose my App, then my (empty) View is animated open and then closed because i just send that file over to my app which is opened via URI … it works

- But when i build a release and install it via Testflight, it DOESN'T work anymore! When i choose my App in the Share-Sheet of iOS, The iOS-ShareSheet shortly animates to make room for my Extension-View - but my view is never shown and does nothing. My app is not started and on the Console-Log i cannot even see the Extension reaching any of my code (if trace should work in release build…)


Should i still add this `<Registrar>static</Registrar>` workaround? 
And if so: in which project? The .iOS-project or the extension-project
(it's a migrated Xamarin App, so i have 4 .csproj files: The main .csproj, the main.ios.csproj, the main.droid.csproj and the main.shareextension.csproj)

_I really need a solution as we are in a hurry to publish our migrated apps until November because of googles rules for whatever compatibility they say we need to implement :(_

**Comment by rolfbjarne** [comment]
@bnSonic please file a new issue and we'll have a look to see if we can figure out what's happening

**Comment by bnSonic** [comment]
Meanwhile I found out what is going wrong: The Compiler is removing essential things of the ShareExtension, so it crashes right at the start because the function that should be called isn't there anymore!

To test this I compiled the ShareExtension with `<MtouchLink>None</MtouchLink>` and - voilá - it runs as Release-Build! 

now I'm trying to use `<MtouchLink>SdkOnly</MtouchLink>` again and see where I need to add some attributes to tell the compiler/linker that the one and only View/Class needs to be there even if it's not called inside the code itself …
