### ISSUE TITLE
.NET iOS 9 Build issue

### ISSUE THREAD

**Issue by ArunaYarra** [xamarin/xamarin-macios#21622]
### Apple platform

iOS

### Framework version

net9.0-*

### Affected platform version

.NET 9.0

### Description

Getting the Linker error when building MAUI application with Mac OS Sequoia and Xcode 16 

 clang++ exited with code 1:
      ld: building for 'iOS-simulator', but linking in object file (/Users/***/**/obj/Debug/net9.0-ios/iossimulator-arm64/linker-cache/***.a[arm64][2](**)) built for 'iOS'
      clang++: error: linker command failed with exit code 1 (use -v to see invocation)

### Steps to Reproduce

1. Add any Binding library to MAUI application and build the project

**Comment by ArunaYarra** [comment]
Here is the sample app for your reference: https://github.com/ArunaYarra/AXAiOSBindingsApp

**Comment by rolfbjarne** [comment]
The problem is that the native library `libCAMobileAppAnalytics.a`, shipped inside the `AXAiOSBindings_MAUI` NuGet, does not support the arm64 simulator (it does not contain code for the arm64 version of the simulator).

The technical reason for this is a limitation in the .a file format: it can't contain arm64 code for both device and simulator.

The fix is to create an XCFramework bundle instead, which can contain code for all variations of all platforms (and then use the .xcframework bundle in the binding project instead of the .a file). More more information see Apple's documentation about XCFrameworks: https://developer.apple.com/documentation/xcode/creating-a-multi-platform-binary-framework-bundle

A workaround would be to not target the arm64 simulator. If you're using an IDE, this can be accomplished by setting `ForceSimulatorX64ArchitectureInIDE=true` in the project file:

```xml
<PropertyGroup>
    <ForceSimulatorX64ArchitectureInIDE>true</ForceSimulatorX64ArchitectureInIDE>
</PropertyGroup>
```

For a bit more details, see https://github.com/xamarin/xamarin-macios/wiki/.NET-8-release-notes#default-runtimeidentifiers.
