### ISSUE TITLE
Call Directory Extension

### ISSUE THREAD

**Issue by pooran** [xamarin/xamarin-macios#3087]
We followed steps provided https://developer.xamarin.com/guides/ios/platform_features/callkit/#Implementing-a-Call-Directory-Extension to create a call directory extension. We have shared a file group, that has less than 1000 phone numbers written from parent iOS app, which the app will read and load it to its directory.

It deploys along with iOS project. But when we try enabling the extension from Settings > Phone > Call Blocking and Identification, we get error 'An error occurred while attempting to enable app.

In device log, we found this error.

Error (188) / suggestd: Received a connection without suggestions entitlement, rejecting; pid: 801, name: com.apple.Preferences, entitlementKey: com.apple.private.suggestions.contacts, protocol: SGDSuggestManagerContactsProtocol

Any idea where to put this entitlement? What we have been doing wrong.

**Comment by VincentDondain** [comment]
Hi,

We now added a template for new GitHub issues but we need a bit more information in order to help.

Please include your full build logs, crash reports (if any), test case (to reproduce) and all your version information.

The test case is especially useful in this case this I couldn't reproduce the issue you're experience with "potentially" missing entitlement when creating a new CallKit extension.

To get full build logs just set the log verbosity to diagnostic at the following locations:
- On Visual Studio for Mac: Preferences > Projects > Build
- On Visual Studio for Windows: Tools > Options > Projects and Solutions > Build and Run

On Visual Studio Windows you also want to add `-v -v -v -v` to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting `Properties`.
Note: this is done automatically on Visual Studio for Mac when the log verbosity is set to diagnostic.

The easiest way to get exact version information:
- On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
- On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.
Then copy/paste the version information (you can use the "Copy Information" button).

Thanks,

Vincent.

**Comment by pooran** [comment]
Got it .. will do

**Comment by mandel-macaque** [comment]
@pooran  please provide the logs so that we can follow up with you, thanks in advance!

**Comment by timrisi** [comment]
We have not received the requested information. If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button. Thanks!
