### ISSUE TITLE
[XI]LookInside sample fails with build error "error : Unexpected character ']' with d15-6

### ISSUE THREAD

**Issue by GouriKumari** [xamarin/xamarin-macios#3195]
### Steps to Reproduce

1. Open LookInside sample, ios-samples/ios8/LookInside
2. Build it

### Expected Behavior
App should build successfully

### Actual Behavior
App fails to build with an error "error : Unexpected character ']'. This issue occurs with d15-6 builds and not with d15-5  (11.6.X builds)

### Environment
```
=== Xamarin.iOS ===

Version: xamarin.ios-11.8.0.8 (Visual Studio Community)
Branch: xcode9.2

```
### Build Logs

Build Log with Stable: https://gist.github.com/GouriKumari/be22288e296816c93308cd9895563291
Build Log with error: https://gist.github.com/GouriKumari/8ecb3da1d10744d46c35f8f726cfaa8d

**Comment by rolfbjarne** [comment]
It looks like this is a problem with the sample, the jSON here is invalid: https://github.com/xamarin/ios-samples/blob/master/ios8/LookInside/LookInside/Resources/Images.xcassets/BigFlower.imageset/Contents.json

IIRC we report this now, because we changed the jSON parser.

The big question is how this invalid jSON was generated in the first place; if VSfM creates it (and still does), we need to fix the generation as well, otherwise this will be quite annoying to users.

@jstedfast @VincentDondain could you verify that VSfM generates valid jSON now?

**Comment by jstedfast** [comment]
I verified last time that we generated valid json and we do. I suspect someone edited the file manually.

**Comment by rolfbjarne** [comment]
@GouriKumari ok, this is an issue with the sample, which needs to be updated (the invalid jSON must be fixed).

**Comment by mandel-macaque** [comment]
Created an issue in the right project:

https://github.com/xamarin/ios-samples/issues/204

Will close this one, both issues have a ref to each other.

**Comment by Blankys** [comment]
@GouriKumari Hi! I'm getting the same error, my jSON is valid but I don't know how to solve it :(, any ideas?

**Comment by bradumbaugh** [comment]
Hi @Blankys – let's discuss this over on https://github.com/xamarin/ios-samples/issues/204. Thank you!
