### ISSUE TITLE
iOS project PropertyGroup element references automatically removed

### ISSUE THREAD

**Issue by dbrevitt** [xamarin/xamarin-macios#3283]
### Description
MSBuild PropertyGroup elements cannot be referenced within the `<AssemblyName>` element of a Xamarin Forms iOS .csproj file as the '$', '(' and ')' are automatically removed.

There appears to be some special processing that removes illegal characters from the assembly name when loading Xamarin Forms iOS projects. The merits of this are mentioned in a similar issue here: https://bugzilla.xamarin.com/show_bug.cgi?id=32414

Can this illegal character processing be removed? Or, can this processing be postponed until after referenced PropertyGroup elements have been resolved within the `<AssemblyName>` element?

### Steps to Reproduce

1. Edit a Xamarin Forms iOS .csproj file by hand to reference a PropertyGroup element from within the `<AssemblyName>` element e.g. `<AssemblyName>MyProject$(Configuration)</AssemblyName>`
2. Load a solution that contains this project

### Expected Behavior
1. The Xamarin Forms iOS .csproj file remains unchanged
2. 'iOS Project -> Properties -> Application -> Assembly name' reflects the configuration that was loaded. In this case, for a Debug configuration the Assembly name should read 'MyProjectDebug' 
### Actual Behavior
1. The Xamarin Forms iOS csproj file has the `<AssemblyName>` element updated to remove special characters e.g.  `<AssemblyName>MyProjectConfiguration</AssemblyName>`
2. In the project properties, for a Debug configuration the Assembly name reads 'MyProjectConfiguration'

### Basic Information
Xamarin.Forms   2.5.0.122203

Xamarin   4.8.0.757
Xamarin Designer   4.8.188
Xamarin.Android SDK   8.1.3.0
Xamarin.iOS and Xamarin.Mac SDK   11.6.1.2

*** Previously raised as https://github.com/xamarin/Xamarin.Forms/issues/1545

**Comment by VincentDondain** [comment]
Hi,

`xamarin-macios` is only for issues against the SDK and this seems (I confirmed internally with @emaf) to be an issue with the Xamarin VS Extension on Windows.

Please report a **new issue** with Visual Studio 2017 directly within the IDE. Simply use **Help > Send Feedback > Report a Problem** to file your issue.

I believe @hartez redirected you here because he thought the issue was against the iOS MSBuilds tasks / targets but the issue you reported works fine in Visual Studio for Mac and it's definitely not something that our tasks would do (csproj string replacement).

Sorry to redirect you again but we really won't be able to help with this here, the Xamarin VS team will (:
