### ISSUE TITLE
`SceneKit.SCNPhysicsWorld.ConvexSweepTest` method doesn't work properly

### ISSUE THREAD

**Issue by mykyta-bondarenko-gl** [xamarin/xamarin-macios#3383]
### Steps to Reproduce

1. Download a project
2. Open a `Fox2.Shared/Character.cs` file and look at the line 787. Put a breakpoint to the line 789.
3. Run the project
4. Run forward using control on the bottom left corner. 

### Expected Behavior
The `ConvexSweepTest` method return collision contacts.

### Actual Behavior
The `ConvexSweepTest` method doesn't return anything. Output is empty.

### Environment

- https://gist.github.com/mykyta-bondarenko-gl/eb7a5511ea20a0de790cb582da3b0768

### Build Logs

- Device log (when method should returns collisions)
 https://gist.github.com/mykyta-bondarenko-gl/3d8d97263787d6503ea008bb6272f286

### Frequency of Reproduction

Happens every time

### Example Project 

[Link to the project](https://github.com/mykyta-bondarenko-gl/private-samples/tree/fox-2-scenekit/ios11/Fox2)

**Comment by spouliot** [comment]
@dalexsoto can you have a look ? I thought that was back ported to 15.6

**Comment by dalexsoto** [comment]
@spouliot I do not see anything specific to `SceneKit.SCNPhysicsWorld.ConvexSweepTest` in master that needs to be back ported, its been the same since forever, do you recall anything else that needed to be back ported ?. That being said, will have a look at the sample.

**Comment by dalexsoto** [comment]
Hello @mykyta-bondarenko-gl, `SceneKit.SCNPhysicsWorld.ConvexSweepTest` is working fine, the issue lives inside your helper class `SimdExtensions.SetPosition` it seems your matrix positions are a little off 🙂

<img width="410" alt="screen shot 2018-02-02 at 6 38 58 pm" src="https://user-images.githubusercontent.com/204671/35760970-aaac78e0-0849-11e8-901e-36291d6d5a69.png">

vs

<img width="182" alt="screen shot 2018-02-02 at 6 40 21 pm" src="https://user-images.githubusercontent.com/204671/35760980-b57d6946-0849-11e8-812c-09d8de6b1741.png">

so if you change your code from

```csharp
public static void SetPosition(ref SCNMatrix4 matrix, SCNVector3 value)
{
    matrix.M14 = value.X;
    matrix.M24 = value.Y;
    matrix.M34 = value.Z;
}
```

to:

```csharp
public static void SetPosition(ref SCNMatrix4 matrix, SCNVector3 value)
{
    matrix.M41 = value.X;
    matrix.M42 = value.Y;
    matrix.M43 = value.Z;
}
```

Everything works as expected 👍 

Closing this issue as invalid due to it is not an issue with Xamarin.iOS.

Cheers!!

**Comment by mykyta-bondarenko-gl** [comment]
@dalexsoto thank you very much! Sorry for that :(
