### ISSUE TITLE
Callkit extension doesn't work for xamarin iOS

### ISSUE THREAD

**Issue by jyndrkhole** [xamarin/xamarin-macios#3665]
I tried call identification for iOS using CallKit extension, but it didn't work. I followed each steps mentioned in https://developer.xamarin.com/guides/ios/platform_features/callkit/ also created respective certificates. But it never invokes my app against my phone numbers.

**Comment by VincentDondain** [comment]
Investigation by the Xamarin team for an issue like this would usually require additional background info that hints it is a Xamarin specific bug (e.g: Xamarin.iOS behaving differently compared to Xcode).

For questions on how to use a specific framework or to clarify our documentation, the broader developer community is usually the best and quickest place for additional troubleshooting help.
Posting a question on Stack Overflow [0] or the Xamarin Forums [1][2] would be the best next step.

[0] https://stackoverflow.com/questions/tagged/xamarin
[1] https://forums.xamarin.com/categories/ios
[2] https://forums.xamarin.com/categories/mac

In case it might also be a helpful reference, you can find some general recommendations on the best places to ask various kinds of questions about Xamarin on:

https://developer.xamarin.com/guides/cross-platform/troubleshooting/support-options/

Otherwise if you do believe that it is a **Xamarin specific bug** please include your **full build logs, crash reports (if any), test case (to reproduce) and all your version information**.

To get full build logs just set the log verbosity to diagnostic at the following locations:
- On Visual Studio for Mac: Preferences > Projects > Build
- On Visual Studio for Windows: Tools > Options > Projects and Solutions > Build and Run

On Visual Studio Windows you also want to add `-v -v -v -v` to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting `Properties`.
Note: this is done automatically on Visual Studio for Mac when the log verbosity is set to diagnostic.

The easiest way to get exact version information:
- On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
- On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.
Then copy/paste the version information (you can use the "Copy Information" button)

**Comment by dalexsoto** [comment]
We have not received the requested information. If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button. Thanks!
