### ISSUE TITLE
How to get iPad model number programmatically

### ISSUE THREAD

**Issue by SaravananWipro** [xamarin/xamarin-macios#3822]
### Steps to Reproduce

Please provide Xamarin.iOS API to read iPad/iPhone Model Number programattically.

Model number (on the back cover):
**A1670** on the iPad Pro
**A1671** on the iPad Pro Wi-Fi + Cellular

### Expected Behavior
API to read iPad/iPhone Model Number programattically.
### Environment

```
```

**Comment by therealjohn** [comment]
@SaravananWipro 

Thanks for reaching out! I couldn't find an iOS API that provides this specific information. Is there an API that you are referring to that is available from Apples SDK which is missing in Xamarin.iOS?

**Comment by SaravananWipro** [comment]
In apple we have below option to get Model name, do we have similar way in Xamarin.iOS?

struct utsname systemInfo;
uname(&systemInfo);
NSString* code = [NSString stringWithCString:systemInfo.machine encoding:NSUTF8StringEncoding];

**Comment by VincentDondain** [comment]
Not quite sure what the Xamarin.iOS equivalent of that code would be. It's the `struct utsname systemInfo;` and `uname(&systemInfo);` part that's unknown to me.

I see Xamarin.Android has the equivalent:
https://developer.xamarin.com/api/type/Android.Systems.StructUtsname/ (we might be facing an iOS restriction here).

There's a forum post asking about a way to use that: https://forums.xamarin.com/discussion/13017/mono-posix-dll-not-available-in-mobile-profiles-ios-and-android

A workaround could be to create a binding project that uses a native library with the Objective C code you want: https://docs.microsoft.com/en-us/xamarin/ios/platform/binding-objective-c/walkthrough?tabs=vsmac

I'll let other team members provide more info if they have any but I'm not sure there's much Xamarin.iOS can do since there's simply no public API offering this capability.

**Comment by migueldeicaza** [comment]
To use uname, you can copy paste this code:

https://github.com/mono/mono/blob/master/mcs/tools/mkbundle/mkbundle.cs#L1427

**Comment by SaravananWipro** [comment]
Thanks
