### ISSUE TITLE
MTOUCH : error MT4116: Could not register the assembly '*': error MT4118: Cannot register two managed types ('*, *' and '*, *') with the same native name ('*').

### ISSUE THREAD

**Issue by kdubau** [xamarin/xamarin-macios#3832]
### Steps to Reproduce

It's a MS internal application in our regression protection program that recently started to fail with XI master and 15.7.

### Environment

Master failed build http://build.devdiv.io/1534764

|Product|Version|
|---|--|
| Xamarin.iOS | 11.11.0.101 |
 | Mono | 5.10.1.16|

15.7 failed build http://build.devdiv.io/1534766

|Product|Version|
|---|--|
| Xamarin.iOS | 11.10.0.50 |
 | Mono | 5.10.1.16|

### Regression Status
It is a regression since 15.6.

15.6 successful build http://build.devdiv.io/1534854 (only observe the macOS build, ignore failed Windows build as it's an unrelated issue)

|Product|Version|
|---|--|
| Xamarin.iOS | 11.8.1.28 |
 | Mono | 5.8.1.0|

### Build Logs

Available in the CI build links, the failed job can be rebuilt with `/v:diag` if needed.

**Comment by rolfbjarne** [comment]
This happens because we started registering models in the static registrar, and there are two different binding libraries binding the same protocol (whose model thus has the same Objective-C name).

I've implemented (see #3875) a way to specify the Objective-C name of the model [1], and the solution to the build problem is to update one of the two binding libraries to use the new syntax in the api definition:

`[Model ("MyCustomName")]` or `[Model (AutoGeneratedName = true)]` (the latter option will generate a unique name based on the assembly and the full type name)

@kdubau can we somehow get in contact with the team for the app and tell them about this so that they can fix it?

[1] Changing the Objective-C names of models should usually not have any effects; but in order to avoid running into unexpected side effects we've decided to not automatically generate a unique name, and instead made it opt-in (at least for now).
