### ISSUE TITLE
Xamarin.iOS API reference for iOS 11.3

### ISSUE THREAD

**Issue by SaravananWipro** [xamarin/xamarin-macios#3902]
### Steps to Reproduce

Please provide Xamarin.iOS API reference for iOS 11.3 release and samples

### Expected Behavior

API available from Xamarin to support iOS 11.3

### Actual Behavior

No API available from Xamarin to support iOS 11.3

### Environment

```
```

**Comment by dalexsoto** [comment]
Hello, you can follow our releases blog at https://releases.xamarin.com, we published Xcode 9.3 support [since April the 3rd](https://releases.xamarin.com/service-release-15-6-5/) so make sure you have your Xamarin installation up to date using the stable channel.

You can find the release notes here https://developer.xamarin.com/releases/ios/xamarin.ios_11/xamarin.ios_11.9/

Also you can go to our wiki where you will find continuous builds for the most up to date work like Xcode 9.4 support here https://github.com/xamarin/xamarin-macios/wiki
