### ISSUE TITLE
ObjCRuntime.RuntimeException: Wrapper type 'BusinessChat.BCChatButton' is missing its native ObjectiveC class 'BCChatButton'

### ISSUE THREAD

**Issue by SaravananWipro** [xamarin/xamarin-macios#3903]
### Steps to Reproduce

I am using below code in ViewController of Xamarin.iOS app to add BCChatButton from iOS11.3 API

            BCChatButton businessChatButton = new BCChatButton(BCChatButtonStyle.Light);
            businessChatButton.TranslatesAutoresizingMaskIntoConstraints = false;
            View.AddSubview(businessChatButton);

Getting below exception. Please let me know how to resolve.

ObjCRuntime.RuntimeException: Wrapper type 'BusinessChat.BCChatButton' is missing its native ObjectiveC class 'BCChatButton'.

### Expected Behavior

Should show BCCChatButton

### Actual Behavior

Exception
[App7.zip](https://github.com/xamarin/xamarin-macios/files/1889728/App7.zip)
[App7.zip](https://github.com/xamarin/xamarin-macios/files/1889730/App7.zip)

### Environment

```
```

**Comment by dalexsoto** [comment]
Hello @SaravananWipro thanks for reaching us, yes that is a known issue for our current stable and is meant to be fixed in our next major release which we call 15-7 (you can find [continuous-builds here]( https://github.com/xamarin/xamarin-macios/wiki#continuous-builds)) or Xcode 9.4 whatever happens first.

That being said you can add `--weak-framework BusinessChat` to your **Additional mtouch arguments** inside `project options > Build > iOS Build` and also **disable** the `Enable Incremental Builds` option, this should get you unblocked in the meantime.

<img width="963" alt="workaround" src="https://user-images.githubusercontent.com/204671/38509295-1c417b60-3be7-11e8-89f1-c74279a7beaf.png">
