### ISSUE TITLE
[RFC] Ideas for GitHub comment file

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#3904]
Last week I merged support for producing nicer comments on GitHub for PR builds:

![screenshot 2018-04-09 17 34 31](https://user-images.githubusercontent.com/249268/38507230-462505f2-3c1c-11e8-817a-4255a0dc4992.png)

The initial support adds information about a few steps done in the PR build, but I'd like input about how this can be improved (without making the whole thing too overwhelming).

A few points I'd like to keep [1]:

* Should be as concise as possible, so that it doesn't become overwhelming. It's not supposed to show all the possible information (for that we link to somewhere else).
* Should use colors / images / emojis when it makes sense.
* Should be as easy as possible for external contributors (either MS or not) to understand.

Ideas I know about:

* [ ] Include link to the xtro report (maybe only if any failures or .todo are present)
* [x] There's no need for **Provisioning succeeded**, we only need to know if it fails
* [ ] There's no need for **Build succeeded**, we only need to know if it fails
* [x] Api diffs should show if they're empty or not.
* [x] Generator diff should show if it's empty (or only show if not empty).
* [ ] State if a partial or complete test run was executed.
* [x] State which bot (private/public) created the results.
* [x] Links to packages [#5301].

Anything else?

[1] The surrounding text ("Build comment file:", horizontal lines, etc), can't be changed easily, because those come from the [Jenkins plugin](https://github.com/jenkinsci/ghprb-plugin/blob/c15d5106e78f7f028c6305dccf01b77cc9a724b3/src/main/java/org/jenkinsci/plugins/ghprb/extensions/comments/GhprbCommentFile.java#L63-L65)

**Comment by spouliot** [comment]
Ideally reviewing a PR should not require getting inside Jenkins UI. This means xtro results should be available - even if green since there can be .todo to verify (just like API diffs). We could make this smarter and have xtro append itself only if failures or .todo are present (not sure it's worth it).

There's no need for **Provisioning succeeded**, we only need to know if it fails [1].

There's no need for **Build succeeded**, we only need to know if it fails [1].

When a package is created (not in PR / public jenkins [2]) it would be nice to have links to them (both XI and XM), including the version numbers (something that requires an extra click in wrench);

The text **Test run succeeded** can be misleading since not every tests is executed (at least for public jenkins [2]). Not sure how to show this effectively, maybe "Test subset succeeded" ?

IMO the most interesting cases will be when tests fails and how to report them. 

* Ideally this should ease (and maybe lead to partial automation) identifying known, random test failures so we can green'ify such build. Right now our results (colours) do not match reality and this confuse people consuming those builds;

* We need to identify/link reported failures back to some instructions on how to duplicate it locally and, whenever possible, how to run a subset of the test (some are very long to run); 

* We need to have separate results for XI and XM. One can be green while the other is not. I don't think we can have GitHub show the duality but someone reading that text should know if one, both or no package is considered green.

[1] details are still available in Jenkins if reviewing the (green) results is required - but that's quite uncommon and I don't think we need this UI to reflect such level of details;

[2] we need to be able to identify which bot (public or private) created the file, since the output of public/private jenkins will be quite similar but the steps can differ a lot;

**Comment by rolfbjarne** [comment]
Things have changed a lot since this was filed... so no longer relevant.
