### ISSUE TITLE
Issue a warning if the Xcode version is too new

### ISSUE THREAD

**Issue by mvirkkunen** [xamarin/xamarin-macios#3921]
I just spent many frustrating hours debugging why a project stopped building with completely nonsensical error messages such as:

```
ArgumentException: Failed to parse PList data type: 
ArgumentException: Must specify valid information for parsing in the string.
```

Further investigation revealed that `ibtoold` kept segfaulting on the Mac build host, and I assume that caused something to generate an invalid plist file, which Xamarin's tools then failed to parse. In the end it turned out that somebody had turned on auto-updates on the Mac host and Xcode had been updated to version 9.3 which broke everything. The installed version isn't immediately obvious either, so even if you open Xcode you might not notice what version you're actually running. Everything started working after updating all Xamarin tools.

If a minor version update to Xcode can break things this badly, I think it'd be nice if the build tools checked the installed version of Xcode and issued a big fat warning if the version is newer than what is known to be compatible!

**Comment by dalexsoto** [comment]
Hello @mvirkkunen we have acknowledge a similar case to what you are describing here https://github.com/xamarin/xamarin-macios/issues/3908 so in order to keep a single thread about this issues I'll close you issue in favor of https://github.com/xamarin/xamarin-macios/issues/3908 and I'll add your experience there, feel free to continue the discussion over there.
