### ISSUE TITLE
"-framework NetworkExtension" not added by users of that API in XM

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#3976]
### Steps to Reproduce

1. Create new XM project and add this code somewhere `NEVpnManager manager = NEVpnManager.SharedManager` 
2. Build
3. Note lack of -framework NetworkExtension anywhere in mmp's clang invocation

### Expected Behavior

Just like other frameworks reference the framework 

### Actual Behavior

No reference. This causes app store rejection - https://forums.xamarin.com/discussion/comment/328499

### Environment

Stable

### Build Logs
https://gist.github.com/chamons/713b9c70026b2d851355833e9fedd75d

> VS bug [#627721](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/627721)

**Comment by spouliot** [comment]
Yup, something of a.similar design. This one was XM specific (and for a XM specific issue so that was fine). 

This problem can happen on any platform, even more if binding already exists (in another platform) and code works since the framework can be loaded dynamically. Introspection could do that (since it's not linked) with (or without) re-using `Framework.cs` from the tools directory (pros and cons to each).
