### ISSUE TITLE
The contents of response files aren't taken into account when determining whether the cache is still valid or not

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#4033]
Repro:

0. Enable diagnostic build log.
1. Create a new project.
2. Add something to the additional mtouch arguments (for instance `-gcc_flags -v`).
3. Build
4. Change the additional mtouch arguments (for instance to `-gcc_flags -v -v`).
5. Build again. The build log should state that the cache was cleared:

> A full rebuild has been forced because the cache for ... is not valid.

Support for response files was added in d15-7, and since we changed the MSBuild tasks to write arguments into response files, this is a functional regression.

> VS bug [#611119](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/611119), VS bug [#611121](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/611121)

**Comment by spouliot** [comment]
`mmp` response file is only in master (15.8) not in 15.7

**Comment by spouliot** [comment]
oops... **msbuild support** did not support response file (in `mmp`) for 15.7, but response file support was present

**Comment by spouliot** [comment]
That's still less an issue for `mmp` unless a response file is manually used (as msbuild/IDE won't be using it)

**Comment by rolfbjarne** [comment]
The cache never worked properly in `mmp` in the first place (see #4034), so this is only a regression in `mtouch`.

**Comment by rolfbjarne** [comment]
Reopening since we'll try to get this in d15-7 SR1.

**Comment by spouliot** [comment]
note: there seems to be a bug (c.c. @slluis) when re-opening an issue that is sync'ed to both XI and XM (two VSTS issues). The `xamarin-release-manager` close it (likely because it cannot be in sync with both, it's done sequentially, and a race makes it close again before the 2nd open is re-opened)

**Comment by spouliot** [comment]
@GouriKumari can you validate this fix in master ? 
@rolfbjarne will be back porting the fix to 15.7 in the meantime

**Comment by GouriKumari** [comment]
Validated with build Version: 11.11.0.296 (Visual Studio Community)
Hash: 4ccd4482. Build Log didn't contain the message, A full rebuild has been forced because the cache for ... is not valid.

## Steps followed
Created a single view template project and added mtouch extraargs: "-gcc_flags -v".
Build the project (command+B). Build Log: https://gist.github.com/GouriKumari/90358e365554156366dff8b9c6ef6c8d
Added  mtouch extraargs: "-gcc_flags -v -v" and build again ((^+command+B).

## Actual behaviour:
Build Log: https://gist.github.com/GouriKumari/e1b21948c61771aac8c35f5c6cefa9b9. I couldn't find the message "A full rebuild has been forced because the cache for ... is not valid in the log.
