### ISSUE TITLE
Crash linked to becomeFirstResponder : Failed to marshal the Objective-C object 0x1124818b0 (type: UIView)

### ISSUE THREAD

**Issue by Bouncaaa** [xamarin/xamarin-macios#4254]
### Steps to Reproduce

1. Have  a uipopover and a textfield on the same screen
2. make sure becomeFirstResponder is called on the textfield
3. open the uipopover -> crash.

### Expected Behavior

UIPopover opens without a crash

### Actual Behavior

App crashes immediately after the popover opens with following error:

Failed to marshal the Objective-C object 0x1124818b0 (type: UIView). Could not find an existing managed instance for this object, nor was it possible to create a new managed instance (because the type 'UIKit.UIView&' does not have a constructor that takes one IntPtr argument).

### Environment

```
=== Visual Studio Community 2017 for Mac ===

Version 7.5.2 (build 40)
Installation UUID: f20e1583-d3a8-4309-a11b-11e33062b785
Runtime:
	Mono 5.10.1.57 (2017-12/ea8a24b1bbf) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 510010057

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.7
	2.0.5
	2.0.0
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.1.105/Sdks
SDK Versions:
	2.1.105
	2.1.4
	2.0.0
	1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.4.1 (14161)
Build 9F2000

=== Xamarin.Mac ===

Version: 4.4.1.193 (Visual Studio Community)

=== Xamarin.iOS ===

Version: 11.12.0.4 (Visual Studio Community)
Hash: 64fece5f
Branch: d15-7
Build date: 2018-05-29 20:00:44-0400

=== Xamarin.Android ===

Version: 8.3.3.2 (Visual Studio Community)
Android SDK: /Users/bounce/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)
		7.1 (API level 25)

SDK Tools Version: 25.1.2
SDK Platform Tools Version: 24.0.0
SDK Build Tools Version: 23.0.2

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 705020040
Git revision: cfe2fc0566bc4db990242959de40505a13f58352
Build date: 2018-05-30 11:24:18-04
Xamarin addins: 3ac7413ef51a88e06367313c27aec8f7292752a6
Build lane: monodevelop-lion-d15-7

=== Operating System ===

Mac OS X 10.13.4
Darwin 17.5.0 Darwin Kernel Version 17.5.0
    Fri Apr 13 19:32:32 PDT 2018
    root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Internet of Things (IoT) development (Preview) 7.5

```

### Build Logs

[buildlog.txt](https://github.com/xamarin/xamarin-macios/files/2101776/buildlog.txt)

**Comment by mandel-macaque** [comment]
@Bouncaaa could you please provide a small example to reproduce the issue. Just so that we are all in the same page regarding the code.

**Comment by PKDataGreece** [comment]
Hello. I hope I'm not out of context here. I get the same message when clicking an EntryElement in a DialogViewController.

_Failed to marshal the Objective-C object 0x107bc8310 (type: UIView). Could not find an existing managed instance for this object, nor was it possible to create a new managed instance (because the type 'UIKit.UIView&' does not have a constructor that takes one IntPtr argument)._

I'm using Visual Studio 2017 with Xamarin.iOS 11.12.0.4 and the problem occurs on physical devices (when running on simulator everything is OK)

I attach a simple project where the problem occurs. I got the sample project https://github.com/xamarin/ios-samples/tree/master/Popovers#popovers and added by DialogViewController that is displayed. The problem occurs after selecting the navigation and the clicking on an EntryElement.

[Sample.zip](https://github.com/xamarin/xamarin-macios/files/2144656/Sample.zip)

Thank you very much.

**Comment by rolfbjarne** [comment]
I can reproduce; I'll have a look.

**Comment by rolfbjarne** [comment]
It's a regression, the test case works fine in `11.9.1.24 (xcode9.3: f62de472)` and fails in `11.10.1.177 (d15-7: 7e782c1e)`.

**Comment by Ekki** [comment]
Hi all,

am using Xamarin.iOS 11.14.0.14 and still face this issue.

   Ekki

**Comment by rolfbjarne** [comment]
@Ekki This is not fixed in the current stable release (`d15-8`), it will be fixed in our next release (`d15-9`), currently scheduled for some time in late fall.

**Comment by Ekki** [comment]
Facing serious trouble in the markets with my Apps. Was also unable to find out a work around. Anything you have to offer? Maybe using something from Beta channel? If so, which version? Thx

**Comment by rolfbjarne** [comment]
@Ekki the fix is included in version available the Alpha channel.

**Comment by Ekki** [comment]
can we at least have this in a Beta release? If I release production Apps based on Alpha Channel releases they can put me in jail I guess

**Comment by rolfbjarne** [comment]
Most likely this will reach the Beta channel, but I have no idea when (it needs coordinating with other teams/products, which makes it much more complicated).

**Comment by Ekki** [comment]
Rather than building a production App on Alpha channel, I rolled back to Xamarin.iOS 11.9.1.24 and rebuilt the App to avoid business penalties...

I'm a Convinced Xamarinian for now and for ever but how the Hell, it can take that long to have a fix in the Release channel for such a critical issue? In my App there are a few different scenarios where the issue happens, plus the workarounds I tried - all of them showing the same behavior - immediate shutdown of the App... Am I the only user worldwide, using text fields in popups in production Apps... Great honor I must say.......

**Comment by PKDataGreece** [comment]
@Ekki I' m sure you are not the only one (I'm using it, too). I've tried rolling back to 11.9.1.24, however it seems I cannot run the app in the simulator. I get the following message which strikes me as a problem with using latest Visual Studio with old Xamarin.iOS.

_Could not resolve type with token 01000002 (from typeref, class/assembly ObjCRuntime.BindingImplAttribute, Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065)_

You say you rebuilt your app, but have you managed to run your app after the rollback?

**Comment by Ekki** [comment]
yes, the App works fine. neither me nor QA found issues

**Comment by PKDataGreece** [comment]
Are you using latest Visual Studio for Mac 7.6.3 (build 1)?

**Comment by PKDataGreece** [comment]
Is it possible that I'm using a nuget package that is built with the newest version of Xamarin.iOS?

**Comment by rolfbjarne** [comment]
> Is it possible that I'm using a nuget package that is built with the newest version of Xamarin.iOS?

Yes, that's possible. It might work to use an older version of such nugets.

**Comment by PKDataGreece** [comment]
Hello, again. I see that there is a new version for Xamarin iOS 12.0. However the problem "_Failed to marshal the Objective-C object..._" is still here, although the fix is included in the 11.16. Am I missing something? Xamarin iOS 12.0 doesn't include the fixes of version 11.16? Was 12.0 based entirely on 11.14?

The problem now is even worse since after installing XCode with support for iOS 12.0 and updating Visual Studio for Mac, I can't even compile my project using the previous version Xamarin iOS 11.9.1.24, which was the proposed workaround (I'm getting an error message "Could not locate SDK bin directory")

Any suggestions?

**Comment by rolfbjarne** [comment]
> Xamarin iOS 12.0 doesn't include the fixes of version 11.16? Was 12.0 based entirely on 11.14?

Yes, this is correct, Xamarin.iOS 12.0 was based on 11.14 (which was the stable release when Apple released iOS 12).

The 11.16 release will now be called 12.2 (unless Apple releases the next iOS version before we can release our next major version, in which case the version numbers bump yet again).

Our versioning is a bit more complex than normal, because we have to adapt to both Visual Studio's and Apple's releases.

> The problem now is even worse since after installing XCode with support for iOS 12.0 and updating Visual Studio for Mac, I can't even compile my project using the previous version Xamarin iOS 11.9.1.24, which was the proposed workaround (I'm getting an error message "Could not locate SDK bin directory")

This is because Xamarin.iOS 11.9.1.24 is not compatible with Xcode 10. Download and install Xcode 9.4 from Apple, and you'll be able to use Xamarin.iOS 11.9.1.24 again.

**Comment by eamiguinho** [comment]
@rolfbjarne Any news when this is going to stable? It's been a while since this happening and definitely was release versions to stable? Can I get some ETA if possible? 

Thanks

**Comment by rolfbjarne** [comment]
@eamiguinho this will be in our d15-9 release, which is planned for mid-November (it's already in the Alpha/Beta channels).

**Comment by PKDataGreece** [comment]
Hello. Just to be sure : is the fix included in the release channel now?
Thank you

**Comment by rolfbjarne** [comment]
@PKDataGreece yes, the fix for this bug is included in the release available in the stable channel now.
