### ISSUE TITLE
[tvOS] Non-public API usage (IOSurface.framework)

### ISSUE THREAD

**Issue by mykyta-bondarenko-gl** [xamarin/xamarin-macios#4257]
I tried to upload a tvOS archive to the `iTunesConnect` but it was failed on dashboard processing step. 
`MinOSVersion` is `10.0`. It works properly if `MinOSVersion` is `11.0`
Link behavior is `Don't Link`

_I suppose that it started fail between 20.05 and 30.05._

### Steps to Reproduce

1. Download a [project](https://github.com/xamarin/SubmissionSamples/tree/master/UICatalog_DontLink)
2. Switch to `Release` + `Device` configuration
3. Open project options and check that `Link behavior` is set to `Don't Link`
4. Open `Info.plist` and check that `Deployment Target` is set to `10.0`
5. Tap `Build` -> `Archive for Publishing`
6. Upload a `.ipa` file to the `iTunesConnect` and wait until processing will finish

### Expected Behavior
Processing fails. You receive next email:
```
Dear Developer,

We identified one or more issues with a recent delivery for your app, "UICatalogtvapp II". Please correct the following issues, then upload again.

**Non-public API usage:**

- The app links to non-public libraries in UICatalog: /System/Library/PrivateFrameworks/IOSurface.framework/IOSurface
If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed.

If you think this message was sent in error and that you have only used Apple-published APIs in accordance with the guidelines, send the app's nine-digit Apple ID, along with detailed information about why you believe the above APIs were incorrectly flagged, to appreview@apple.com. For further information, visit the Technical Support Information page.

Best regards,

The App Store Team
```

### Actual Behavior
Processing finish successfully. 

### Environment

1. VSfM. Also it was checked with XI: 11.10.1.178, 11.12.0.5, 11.11.0.320
https://gist.github.com/mykyta-bondarenko-gl/f963481d4bd18f24ae58e623b8f87b3b

### Build Logs

1. Archive output
https://gist.github.com/mykyta-bondarenko-gl/cc9a40533e7d6350d3dd114f28555d44

### Example Project
[Project](https://github.com/xamarin/SubmissionSamples/tree/master/UICatalog_DontLink)

**Comment by spouliot** [comment]
I don't get that result on other projects.
@mandel-macaque how did you confirm this ?

**Comment by spouliot** [comment]
Oh, seems I forgot to reply (to myself) since I could repro it.

@mandel-macaque IIRC it's _normal_ due to how Apple's native linker works. What you can try is to use Xcode to build an app that use `IOSurface` and set the target to 10.0. Next use `otool` to list the framework (from the main binary) and check the location of `IOSurface.framework`, if it's inside `PrivateFrameworks` then Apple will reject it.

One can _probably_ argue with Apple about it (if the use is under a version check) but it's simpler to enable the linker.

**Comment by rolfbjarne** [comment]
This was at first a bit puzzling, because we have logic to rewrite references to PrivateFrameworks, and the logic works and kicks in as shown in Mykyta's build log: https://gist.github.com/mykyta-bondarenko-gl/cc9a40533e7d6350d3dd114f28555d44#file-archiving-output-L2523

The catch is bitcode: that `install_name_tool` command does not change the result of compiling bitcode to arm64 on Apple's servers, and it's this post-compiled binary that is referencing the private version of IOSurface:

```
$ /Applications/Xcode94.app/Contents/Developer/usr/bin/bitcode-build-tool -v -v -v -o UICatalog.arm64 "$HOME/Library/Developer/Xcode/Archives/2018-09-11/UICatalog 9-11-18 5.51 PM.xcarchive/Products/Applications/UICatalog.app/UICatalog"
[...]
$ otool -l UICatalog.arm64 | grep IOSurface
         name /System/Library/PrivateFrameworks/IOSurface.framework/IOSurface (offset 24)
```

Unfortunately I don't think we can fix this, I couldn't find any options to `ld` that does what `install_name_tool` does (and we can't run any custom commands after linking on Apple's servers).

This means there are two possible solutions:

* Enable the managed linker to remove any usage of IOSurface
* Set the minimum deployment target to iOS 11+.
