### ISSUE TITLE
MM4162 should have explain text from 0135 

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#4286]
MM4162's error message should be longer and contain the same info as this one

https://github.com/xamarin/xamarin-macios/blob/master/docs/website/mmp-errors.md#mm0135-did-not-link-system-framework-0-referenced-by-assembly-1-because-it-was-introduced-in-2-3-and-were-using-the-2-4-sdk

as the issue can be the same.

**Comment by VincentDondain** [comment]
@chamons I can't find MM4162 and it's not documented in `mmp-errors` either. Can you please link to the code to make it easier to work on this issue?

**Comment by chamons** [comment]
https://github.com/xamarin/xamarin-macios/blob/master/src/ObjCRuntime/Registrar.cs#L1460

https://github.com/xamarin/xamarin-macios/blob/master/docs/website/mtouch-errors.md#mt4162-the-type--used-as--2-is-not-available-in---it-was-introduced-in---please-build-with-a-newer--sdk-usually-done-by-using-the-most-recent-version-of-xcode

**Comment by VincentDondain** [comment]
@chamons so to clarify you want to add the MM4162 error to the mmp-errors document and update both MT4162 and MM4162 documents to feature the long description of https://github.com/xamarin/xamarin-macios/blob/master/docs/website/mmp-errors.md#mm0135-did-not-link-system-framework-0-referenced-by-assembly-1-because-it-was-introduced-in-2-3-and-were-using-the-2-4-sdk since those are similar issues right?

You do not want to update the error message in the code itself correct?

**Comment by chamons** [comment]
This issue is really asking for "135" and any other error that you can hit when using a too-old Xcode to have some of the delightful error message text found here:

https://github.com/xamarin/xamarin-macios/blob/master/docs/website/mmp-errors.md#mm0135-did-not-link-system-framework-0-referenced-by-assembly-1-because-it-was-introduced-in-2-3-and-were-using-the-2-4-sdk

which is actionable (Upgrade Xcode, enable linking, downgrade XM/XI).
