### ISSUE TITLE
[arkit/test] Add test to ensure all subclass of 'ARAnchor' implement 'initWithAnchor'

### ISSUE THREAD

**Issue by VincentDondain** [xamarin/xamarin-macios#4497]
Similar to https://github.com/xamarin/xamarin-macios/blob/master/tests/introspection/ApiCtorInitTest.cs#L286-L327. We need an intro test that will ensure all subclasses of 'ARAnchor' implement 'initWithAnchor'.

**Comment by spouliot** [comment]
I think we should expose `ARAnchorCopying` [1] (even if empty) and base the intro test on it.

Right now it's identical, `ARAnchorCopying` is only used on `ARAnchor`, but that might change in the future (does not make much sense to add the protocol otherwise).

[1] We could also add an `[Advice]` on the protocol to mention the extra requirement for conformance.

**Comment by VincentDondain** [comment]
Fixed in https://github.com/xamarin/xamarin-macios/pull/4551
