### ISSUE TITLE
[ARKit] different 'Transform' matrix presentation

### ISSUE THREAD

**Issue by mykyta-bondarenko-gl** [xamarin/xamarin-macios#4525]
After I set the `Position` property `Transform` matrixes look differently. Position vector is located under different indexes:
- xamarin - position is under `Row3`
- swift - position is under `Column3`

It looks like the same matrix, but one of them isn’t transposed. 

### Steps to Reproduce

1. Open attached projects (swift and xamarin)
2. Run them and looked to the output 

Test code is located:
- xamarin - `GameViewController.cs` - between 30 and 46 lines of code
- swift -  `ViewController.swift` - between 22 and 35 lines of code

### Expected Behavior
The `Transform` matrixes are the same.

### Actual Behavior
The `Transform` matrixes look differently. 

### Environment

1. VSfM 7.6 Preview (7.6 build 2109)
https://gist.github.com/mykyta-bondarenko-gl/aa42dcf103eb3a9b1259d6d67e0de428

### Example Project 

1. [Xamarin](https://github.com/xamarin/xamarin-macios/files/2241190/XamarinGame.zip)
2. [Swift](https://github.com/xamarin/xamarin-macios/files/2241204/SwiftGame.zip)

**Comment by spouliot** [comment]
@VincentDondain it sounds like the wrong type might have been used for the transform (please double check if other ARKit API might be in the same situation)

**Comment by lobrien** [comment]
This definitely applies to other ARKit and SceneKit vectors and matrices. For instance, 

```
var node = new SCNNode { Position = new SCNVector3(2, 3, 4) };  
var xform = node.Transform;
Console.WriteLine(xform);
// Output is: "(1, 0, 0, 0)\n(0, 1, 0, 0)\n(0, 0, 1, 0)\n(2, 3, 4, 1)"
xform.Column3
// Output is ""(0, 0, 0, 1)"
```

**Comment by lobrien** [comment]
Note that in Swift: 

```
let t = float4x4([float4(1, 1, 1, 0), float4(2,2,2,0), float4(3,3,3,0), float4(4, 4, 4, 1)])
let v = float4(1, 0, 0, 0)
let v2 = t * v
// v2 == float4(1.0, 1.0, 1.0, 0.0)
```

**Comment by VincentDondain** [comment]
The native and managed matrices are identical.

```
(1, 0, 0, 0)
(0, 1, 0, 0)
(0, 0, 1, 0)
(0.25, 0.33, 0.44, 1)
```

However Apple think columns are rows and rows are columns (because I'm sorry but in my world `Column3` is (0, 0, 0, 1). That's what Xamarin does.

So yea our [code](https://github.com/xamarin/xamarin-macios/blob/master/src/SceneKit/SCNMatrix4.cs#L190-L193) is doing the **right thing** but it's not matching the native behavior which I understand can be confusing.

I do not believe we can or should change the behavior of our code. Let's reopen if we think it's necessary.

**Comment by EgorBo** [comment]
Column major matrices (where the matrix is basically a set of vectors=columns) is more efficient (or SIMD friendly) than traditional row major matrices in some popular scenarios like
`var foo = mat * vec`

**Comment by VincentDondain** [comment]
Fair point.

Unfortunately if we swap rows and columns under the hood it will break everyone's assumptions. The only we could do is XAMCORE-ify everything for the "next" breaking change. Not even sure that is worth it.

**Comment by spouliot** [comment]
@VincentDondain let's add an `[Advice ("This is a row major matrix representation.")]`

**Comment by lobrien** [comment]
Not changing it will confuse every single person doing SceneKit work. At the very least, I think we should have conversions to/from `SCNMatrix4`.

**Comment by migueldeicaza** [comment]
@lobrien What do you suggest the cast to/from should be?

**Comment by VincentDondain** [comment]
@lobrien I'm confused, why do we need conversions for? This issue is about native going for a column major `SCNMatrix4` and us going for a row major `SCNMatrix4`. The "conversion" method is `Transpose`. That will move from row major to column major.

> Not changing it will confuse every single person doing SceneKit work

I agree it's confusing (though mostly for people porting stuff or reading Apple's doc) and annoying to have to transpose (if you want it the same way as native) but again if we change the behavior of `SCNMatrix4` under the hood even though the APIs won't break customers' apps who were expecting rows instead of columns or were transposed will break.

**Comment by VincentDondain** [comment]
@spouliot I added the advice attribute: https://github.com/xamarin/xamarin-macios/pull/4605

**Comment by rolfbjarne** [comment]
This is something we should fix for XAMCORE_4_0, it's a difference between Swift/ObjC that doesn't make sense (but which we can't change now due to backwards compatibility concerns)
