### ISSUE TITLE
libvlc for tvOS

### ISSUE THREAD

**Issue by mfkl** [xamarin/xamarin-macios#4561]
Hi guys,

It's me again :D

So now that libvlc runs on Xamarin.iOS and Xamarin.Mac, the last Apple platform I plan to target is naturally Xamarin.tvOS. And I have questions.

`TVVLCKit.framework` supports 2 arch (`x86_64` and `ARM64`) and weights a whooping 1.4GB, because of the bitcode requirement of tvOS, I believe.

When building a tvOS app which references the `.framework` as a `NativeReference`, the build outputs this [message](https://github.com/xamarin/xamarin-macios/blob/master/tools/mtouch/Application.cs#L1636) `The framework is a framework of static libraries, and will not be copied to the app.`.

If I'm not mistaken, referencing `.a` files is not allowed by the App Store because the lib needs to be inside a `.framework` container.

Why is copying a framework of static libraries not a thing?
If I'm going at this wrong, what options do I have to work around this with Xamarin?

Thanks again for your insights.

[TVVLCKit build script](https://github.com/videolan/vlckit/blob/master/compileAndBuildVLCKit.sh)

**Comment by spouliot** [comment]
> TVVLCKit.framework supports 2 arch (x86_64 and ARM64) and weights a whooping 1.4GB, because of the bitcode requirement of tvOS, I believe.

Yes, bitcode is very verbose and it's required to submit to the Apple TV App Store. IOW it's only needed for `arm64` (not `x86_64` which you never publish).

> `The framework {0} is a framework of static libraries, and will not be copied to the app.`

Some `.framework` are not not _real_ frameworks, just directories of files. Useful to ensure all related files as kept together but most documentation assume it's more than that.

> If I'm not mistaken, referencing .a files is not allowed by the App Store because the lib needs to be inside a .framework container.

Not quite. You cannot ship (publish) a static library, i.e. `*.a` file, within the application or even inside a `.framework` directory. A _real_ framework should includes dynamic libraries (`.dylib`) and support files (e.g. resources, headers).

> Why is copying a framework of static libraries not a thing?

Static libraries must be given to the (native) linker and the code will be merged (not copied) into the final application executable. They are not meant to be loaded dynamically, like `.dylib` files so they have no value being copied, as is, in the app bundle.

> If I'm going at this wrong, what options do I have to work around this with Xamarin?

Are you using a framework for iOS ? it should work just the same (just need to be compiled against tvOS libraries... and bitcode).

Right now it seems you're not producing a _real_ framework, just a container (directory) that looks like one. Still it's detected as such (it's not a build error) so that might work... unless there are other issues later in the build ?

Can you attach complete, verbose build logs ? or better share the code with us ? Thanks!

**Comment by mfkl** [comment]
Thanks for the info!

> Can you attach complete, verbose build logs ? or better share the code with us ? Thanks!

Yes I will publish a test nuget soon and post the link here. In the meantime, here is the build log: https://gist.github.com/mfkl/b4694d4ebd6018b9f3d2b378732bddff

I used
```
<MtouchExtraArgs>-cxx -gcc_flags "-L${ProjectDir} -lTVVLCKit -force_load ${ProjectDir}/libTVVLCKit.a" -v</MtouchExtraArgs>
```
To link statically this time.

Looks like I'm hitting https://code.videolan.org/videolan/VLCKit/issues/69 
```
ld : warning : URGENT: building for tvOS simulator, but linking in object file (/Users/Martz/Projects/tvos/tvos/libTVVLCKit.a(emms.asm.o)) built for (unknown). Note: This will be an error in the future.
```
which seems to appear as errors in VS even though they're actually warnings? Hmmm still looking.

> Are you using a framework for iOS ? it should work just the same (just need to be compiled against tvOS libraries... and bitcode).

I asked the maintainer and he tells me loading as many dylib dynamically on tvOS is not a good idea. My build output has 2 folder `Release-appletvos` and `Release-appletvsimulator` containing `libTVVLCKit.a` files. There is also a `.framework`, which I assume (unlike for vlckit iOS) is not a "real" dynamic framework, like you mentioned.

```
TVVLCKit.framework Martz$ file TVVLCKit
TVVLCKit: Mach-O universal binary with 2 architectures: [x86_64] [arm64:current ar archive]
TVVLCKit (for architecture x86_64):	current ar archive
TVVLCKit (for architecture arm64):	current ar archive
```

**Comment by spouliot** [comment]
Thanks for the logs!

With `-lTVVLCKit -force_load ${ProjectDir}/libTVVLCKit.a` there should be no need to add a reference to the VLC framework (it's not a real one and might confuse the tooling, depending on its content) as you are linking statically.

From https://gist.github.com/mfkl/b4694d4ebd6018b9f3d2b378732bddff#file-tvvlckit-link-L2999 you can see the reason(s) the build fails.

Your library requires other frameworks to be linked in the application (since it's linked statically). E.g.

* `AUGraphAddNode` -> `-framework AudioUnit
* `AVAudioSessionCategoryPlayback` -> `-framework AVFoundation`
* `CMBlockBufferCopyDataBytes` -> `-framework CoreMedia`
* `VTCompressionSessionCompleteFrames` -> `-framework VideoToolbox`
...

```
ld : warning : URGENT: building for tvOS simulator, but linking in object file (/Users/Martz/Projects/tvos/tvos/libTVVLCKit.a(emms.asm.o)) built for (unknown). Note: This will be an error in the future.
```
^ the compilation of `emms.asm.o` did not mention `tvOS`. That's not a big deal for the simulator, but it should be fixed. The warning comes from Apple's `ld` so I do not know when it will become an actual error - but you have been warned ;-)

> I asked the maintainer and he tells me loading as many dylib dynamically on tvOS is not a good idea.

Frameworks are great for sharing (e.g. between an application and an extension) or copying around code and assets (at development time). They do require dynamic linking, so there's a penalty at runtime (that static linking would solve at build time).

**Comment by mfkl** [comment]
I have not forgotten about this, but was busy with other things.

Using 
```
    <MtouchExtraArgs>-cxx -gcc_flags "-L${ProjectDir} -lTVVLCKit -force_load ${ProjectDir}/libTVVLCKit.a -framework AudioToolbox -framework AVFoundation -framework CoreMedia -framework VideoToolbox" -v</MtouchExtraArgs>
```

I have many duplicate symbols
`ld: 1547 duplicate symbols for architecture x86_64` which I'm looking into (issue on libvlc build side).

Additionally, it does seem `ld` warnings such as 
```
    ld : warning : URGENT: building for tvOS simulator, but linking in object file (/Users/Martz/Projects/tvos/tvos/libTVVLCKit.a(emms.asm.o)) built for (unknown). Note: This will be an error in the future.
```
End up as errors in VS
```
error MT5209 : Native linking error : warning: URGENT: building for tvOS simulator, but linking in object file (/Users/Martz/Projects/tvos/tvos/libTVVLCKit.a(emms.asm.o)) built for (unknown). Note: This will be an error in the future.
```
Which they shouldn't?

I'll keep you posted on that duplicate symbols issue.

**Comment by rolfbjarne** [comment]
> Additionally, it does seem ld warnings such as ... end up as errors in VS

If ld fails, anything it outputs is assumed to be errors (including warnings). Just focus on the errors ld reports, and once those are fixed the warnings won't be reported as errors anymore.

**Comment by rolfbjarne** [comment]
It's been over a month since your last reply, so I'm closing this.

Feel free to reopen if you have any further problems.
