### ISSUE TITLE
`CoreNFC.framework` is not loaded on some devices

### ISSUE THREAD

**Issue by mykyta-bondarenko-gl** [xamarin/xamarin-macios#4628]
### Steps to Reproduce

1. Create `Single View App`
2. Set `Don't Link` to the linker option
3. Deploy to the iPad

### Expected Behavior
It is deployed successfully 

### Actual Behavior
It crashes on the launch. But it runs on iPhone 7

### Environment

1. VSfM
https://gist.github.com/mykyta-bondarenko-gl/b3294ef4ff75875def2d0479fa36506a
2. Xcode 10.0 beta 6 (10L232m)
3. Devices:
   - iPhone 7 -  12.0 (16A5357b) (beta 8)
   - iPad Pro -  12.0 (16A5357b) (beta 8)

### Build Logs

1. Device Log
https://gist.github.com/mykyta-bondarenko-gl/fa9cf201ff6b62314e6641ec3fe85973
2. Ide Log
https://gist.github.com/mykyta-bondarenko-gl/06cae1e395fcd9dbad393a24e04ef8bc

**Comment by spouliot** [comment]
That sounds like only (recent) devices with NFC have the framework (which might be new in iOS 12).

@mykyta-bondarenko-gl does XI stable gives you the same results on the **same** iPad Pro ?

**Comment by spouliot** [comment]
Doing the same on my iPad Pro (on iOS11) works correctly, using XI 11.99.

and it does link with CoreNFC

```
Sebastiens-MacBook-Pro:xamarin-macios poupou$ otool -l ~/Projects/bugz/sva/bin/iPhone/Debug/device-builds/ipad6.7-11.0/sva.app/sva | grep CoreNFC
         name /System/Library/Frameworks/CoreNFC.framework/CoreNFC (offset 24)
```

**Comment by spouliot** [comment]
```
			if (NFCNdefReaderSession.ReadingAvailable)
				Console.WriteLine ("NFC is Available");
			else
				Console.WriteLine ("NFC is not Available");
```
shows
```
2018-08-16 15:50:47.876 sva[338:59639] NFC is not Available
```
as expected.

I'll update my device to iOS 12 to continue.

**Comment by spouliot** [comment]
```
Incident Identifier: D9A6ACCF-5AA8-4C03-AD92-BB13A13FCEC8
CrashReporter Key:   45da90365913a850e63566c0038767744ba54cba
Hardware Model:      iPad6,7
Process:             sva [342]
Path:                /private/var/containers/Bundle/Application/A041FC79-2724-4B0B-97F8-F8F5540376C7/sva.app/sva
Identifier:          com.companyname.sva
Version:             1.0 (1.0)
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           com.companyname.sva [480]


Date/Time:           2018-08-16 16:51:22.8122 -0400
Launch Time:         2018-08-16 16:51:22.7422 -0400
OS Version:          iPhone OS 12.0 (16A5357b)
Baseband Version:    n/a
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Description: DYLD, Library not loaded: /System/Library/Frameworks/CoreNFC.framework/CoreNFC | Referenced from: /var/containers/Bundle/Application/A041FC79-2724-4B0B-97F8-F8F5540376C7/sva.app/sva | Reason: image not found
Triggered by Thread:  0
```

Both the existing app (before iOS update) and a new build gets the same behaviour.

Which means existing applications using CoreNFC will crash on iOS 12 devices that does not support NFC. I'll file.a rdar with Apple since this affects existing applications, including ones with a check like the above.

**Comment by spouliot** [comment]
merged

**Comment by Kortdag** [comment]
Can we do anything but wait for next release of xamarin?

**Comment by Kortdag** [comment]
Thanks. We´re not using CoreNFC
 
We have disabled linking du to a bug report I filed some time ago that you and the .NET.Core community talket about. The fact that linking threw away some of the LINQ classes. I believe it was something with stuff beeing handled by reflection.

I we turn on linking did you have som Monotouch params that could keep the LINQ stuff from beeing removed?

**Comment by Kortdag** [comment]
This one on EF Core
https://github.com/aspnet/EntityFrameworkCore/issues/10963#issuecomment-370475286

**Comment by spouliot** [comment]
@Kortdag do not completely disable the manager linker (unless you're testing if the linker has an impact on something). IOW it should not be done for release builds.

Instead continue to use the default **Link SDK** option and add something like `--linkskip=mscorlib` to the **Additional mtouch arguments** in your project's options. It can be added more than once if the LINQ type(s) you need are across several assemblies.

This will limit the **size** impact of disabling the linker to only one (or few) assemblies, which will be beneficial overall for your application. This will also solve your CoreNFC issue.

**Comment by Kortdag** [comment]
Exelent.
I will try adding the linkskip options and enable link sdk. Sounds like its the forbi we need => get rid of CoreNFC while shortlisting the .NET core assemblies that is removed by mistanke. 

Only reason we disabled linking was to not having to figure out every possible .NET core assembly that was removed due to internal use og reflection. 

Full aware that this will reduce app size. This just didnt have any priority since our app is in house distributed, so we know every user, their network awailability, hardware etc. 

Now its a Big problem of course. Thanks for your linkskip hint.

**Comment by Kortdag** [comment]
Exelent.
I will try adding the linkskip options and enable link sdk. Sounds like its the forbi we need => get rid of CoreNFC while shortlisting the .NET core assemblies that is removed by mistanke. 

Only reason we disabled linking was to not having to figure out every possible .NET core assembly that was removed due to internal use og reflection. 

Full aware that this will reduce app size. This just didnt have any priority since our app is in house distributed, so we know every user, their network awailability, hardware etc. 

Now its a Big problem of course. Thanks for your linkskip hint.

**Comment by Kortdag** [comment]
Exelent.
I will try adding the linkskip options and enable link sdk. Sounds like its the forbi we need => get rid of CoreNFC while shortlisting the .NET core assemblies that is removed by mistanke. 

Only reason we disabled linking was to not having to figure out every possible .NET core assembly that was removed due to internal use og reflection. 

Full aware that this will reduce app size. This just didnt have any priority since our app is in house distributed, so we know every user, their network awailability, hardware etc. 

Now its a Big problem of course. Thanks for your linkskip hint.
