### ISSUE TITLE
ContentOffset only available in iOS 12 or newer

### ISSUE THREAD

**Issue by jzeferino** [xamarin/xamarin-macios#4893]
### Steps to Reproduce

1. Create a `UIScrollView` and access `ContentOffset` property.

### Expected Behavior

Don't show any IDE hint.

### Actual Behavior
Shows IDE hint saying that `ContentOffset` property is only available in iOS 12 or newer.

<img width="399" alt="screen shot 2018-09-29 at 12 23 15 am" src="https://user-images.githubusercontent.com/10722952/46237670-f2678900-c37d-11e8-931b-dbb5f14ba9a0.png">

### Environment

VS for mac Version 7.6.7 (build 49)

Xamarin.iOS
Version: 12.0.0.15 (Visual Studio Community)
Hash: 84552a46
Branch: xcode10
Build date: 2018-09-17 21:54:33-0400

<img width="959" alt="screen shot 2018-09-29 at 12 18 23 am" src="https://user-images.githubusercontent.com/10722952/46237642-b7655580-c37d-11e8-9f78-6849125345ea.png">

**Comment by VincentDondain** [comment]
Indeed this should be iOS 12+ it was removed, probably by mistake, in https://github.com/xamarin/xamarin-macios/pull/4253. A new protocol (`UIFocusItemScrollableContainer`) was introduced but `contentOffset` has always been available and should remain so: https://developer.apple.com/documentation/uikit/uiscrollview/1619404-contentoffset.

**Comment by spouliot** [comment]
`UIFocusItemScrollableContainer` is new in iOS 12, so the attribute is _somewhat_ correct.

What Apple did is to **move** existing members, like `ContentOffset` to this new protocol. However we can't follow that _move_ since the availability attribute won't reflect reality. Keeping duplicate bindings solves this (but creates compiler warnings unless `new` is used).
