### ISSUE TITLE
Xamarin Mac Mojave/XCode 10 SDK Not In 'Stable' Channel. 'XCode 10 Preview' channel no longer exists

### ISSUE THREAD

**Issue by projectgoav** [xamarin/xamarin-macios#4896]
### Steps to Reproduce
1. Visual Studio for Mac was on 'XCode 10 Preview' channel
2. Channel no longer exists, I was prompted to update to 'Stable'
3. Installed stable but doesn't contain the updated Xamarin Mac SDK

How would I go about getting a copy of the Xamarin Mac SDK with XCode 10 support?

### Expected Behavior
'Stable' channel should contain the updated Xamarin Mac SDK like it has with iOS.

### Actual Behavior
Xamarin Mac found: v4.6.0.14
Expected: v4.99.xx.xx (I think that is what was used in the 'Preview' channel)

Xamarin iOS 12 is available but not the latest Xamairn Mac. Release notes for v4.6.0.14 don't mention anything about supporting XCode 10/Mojave. 

Indeed, building our app  with Xamarin Mav v.4.6.0.14 shows the same issues which were fixed by using the Xamarin Mac v4.99.xx SDK. 

### Environment

```
VS Mac: 7.6.7.49
Xamarin iOS: 12.0.0.15
Xamarin Mac: 4.6.0.14

Mac OSX: 10.14.0
Darwin 18.0.0 Darwin Kernel Version 18.0.0
```

**Comment by VincentDondain** [comment]
Hi,

We unfortunately removed the Xcode 10 Preview channel a bit too soon but this is because we're releasing Xamarin.Mac 5.0 (with Xcode 10 support) today to **stable**.

I apologize for the inconvenience.

Here is the build we will push later today: https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/xcode10/b40230c09d557991b776de918b047442cd41533f/211/package/xamarin.mac-5.0.0.0.pkg
