### ISSUE TITLE
Cannot build app with scanbot nuget with don't link linker behaviour

### ISSUE THREAD

**Issue by michaelgobbers** [xamarin/xamarin-macios#4972]
### Steps to Reproduce

1. Clone following repo: https://github.com/doo/scanbot-sdk-example-xamarin.git
2. Put iOS linker behaviour to don't link
3. build.

### Expected Behaviour
iOS Project should build correctly

### Actual Behaviour
iOS Project doesn't build and throws native linking errors. Errors can be found in build log below.

### Environment

```
=== Visual Studio Enterprise 2017 for Mac ===

Version 7.6.9 (build 22)
Installation UUID: 168e1467-49ef-4a4e-9c41-e7c3f60701e5
Runtime:
	Mono 5.12.0.309 (2018-02/39d89a335c8) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 512000309

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.1.1
	2.0.5
	2.0.0
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.301
	2.1.4
	2.0.0
	1.0.1
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.3
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 10.0 (14320.25)
Build 10A255

=== Xamarin.Mac ===

Version: 5.0.0.0 (Visual Studio Enterprise)
Hash: b40230c0
Branch: 
Build date: 2018-09-27 11:41:37-0400

=== Xamarin.iOS ===

Version: 12.0.0.15 (Visual Studio Enterprise)
Hash: 84552a46
Branch: xcode10
Build date: 2018-09-17 21:54:33-0400

=== Xamarin.Android ===

Version: 9.0.0.20 (Visual Studio Enterprise)
Android SDK: /Users/michaelgobbers/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.1 (API level 16)
		4.2 (API level 17)
		4.3 (API level 18)
		4.4 (API level 19)
		5.0 (API level 21)
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.3

Java SDK: /Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 706090022
Git revision: 0a0ba3c4593e9adb1c6ff6324e641036146af376
Build date: 2018-10-05 16:38:51+00
Build branch: release-7.6
Xamarin extensions: f7856b13f2c03a58e08381d3a5970bba18f5c7d7

=== Operating System ===

Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Thu Jun 21 22:53:14 PDT 2018
    root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

MvvmCross Template pack 2.0.1
Straight8's SpecFlow Integration 1.11.2.0


```

### Build Logs

https://gist.github.com/michaelgobbers/b525c2f1c892c886ffbd9fd0dabed812

### Example Project (If Possible)

https://github.com/doo/scanbot-sdk-example-xamarin.git

**Comment by VincentDondain** [comment]
Hi,

I could confirm the issue with the following environment: https://gist.github.com/VincentDondain/4d4b1674d466a1b1c94c911ffef8d540 (internal builds) only on simulator | don't link (building for device works fine).

**Comment by VincentDondain** [comment]
However if you take a look at https://docs.microsoft.com/en-us/xamarin/ios/troubleshooting/mtouch-errors#mt5214-native-linking-failed-undefined-symbol--this-symbol-was-referenced-the-managed-member--please-verify-that-all-the-necessary-frameworks-have-been-referenced-and-native-libraries-linked you can see some suggested solutions for this situation. Not that "Enable the managed linker" is one of them.

Otherwise I'd suggest contacting the package owner to see if they can provide a fix.

In any case I do not believe this is an issue with Xamarin.iOS as we have no control on the 3rd party package.

**Comment by tailsu** [comment]
Thanks for the support. The problem was indeed caused by incorrectly DllImport-ed functions.

We had used Sharpie to auto-generate the bindings for the framework. The problem was caused first when Sharpie generated bindings to inline functions, and second to functions with C++ name mangling.

In the first case, we simply deleted the DllImport-ed functions and in the second case we had to explicitly add an `EntryPoint` property to the DllImport with the properly mangled name.

I hope this helps someone.
