### ISSUE TITLE
please give a document about how to use interpreter

### ISSUE THREAD

**Issue by juepiezhongren** [xamarin/xamarin-macios#5001]
said above

**Comment by spouliot** [comment]
It's not _yet_ documented because it's not complete (it's a work in progress so not everything works) nor in a final state (expect many changes in future release). IOW it's not supported and it might be broken in some releases (it's not in the test plan until the features are set in stone - or at least a bit more rigid than today).

You can enable the interpreter by giving the `--interpreter` to the **Additional mtouch arguments** in the project options.

From `mtouch` help:
```
--interpreter          Enable the *experimental* interpreter.
```

If you want to try the latest pieces then you should build your own Xamarin.iOS package from source based on the latest mono integration branches (e.g. [2018-10](https://github.com/xamarin/xamarin-macios/pull/4904) or [2018-08](https://github.com/xamarin/xamarin-macios/pull/4596)). The mono used in master (and release branches) are stable and older (2018-06 today) and won't get backports of interpreter fixes.
