### ISSUE TITLE
[XI] F# app doesn't build

### ISSUE THREAD

**Issue by mykyta-bondarenko-gl** [xamarin/xamarin-macios#5070]
### Steps to Reproduce

1. Open VSfM 
2. Create `iOS -> App -> Single View App (F#)`
3. Build it

### Expected Behavior
Build is successful 
 
### Actual Behavior
Build is failed 
```
***/FSC: Error FS1108: The type 'BigInteger' is required here and is unavailable. You must add a reference to assembly 'System.Numerics, Version=2.0.5.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. (FS1108) (Test)
```

### Workaround
Edit project file (`.fsproj`). Change
```
<Reference Include="System.Numerics, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e" />
```
to
```
<Reference Include="System.Numerics" />
```

### Environment

1. VSfM
https://gist.github.com/mykyta-bondarenko-gl/3b1727cf900bb96ca0483980543c9f1a

### Build Logs

1. Build Output
https://gist.github.com/mykyta-bondarenko-gl/f861844e82bc3941487ba7c960a25fd2

### Example Project 
[Sample](https://github.com/xamarin/xamarin-macios/files/2538885/Test-F.zip)

> VS bug [#721664](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/721664)

**Comment by spouliot** [comment]
It happens at compilation time, i.e. before reaching the SDK tools, but it does refer to what we ship...

```
Reference
    FSharp.Core
        HintPath = ../packages/FSharp.Core.4.3.3/lib/netstandard1.6/FSharp.Core.dll
    mscorlib
    System
    System.Core
    System.Numerics, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
    System.Xml
    Xamarin.iOS
```

but it seems to be the only assembly that has a full qualified name.

I strongly suspect it's a template issue but it's not clear to me when it last changed (it ships with the IDE).

**Comment by mandel-macaque** [comment]
Closing this issue since it does not longer happen in the following env:

=== Visual Studio Enterprise 2017 for Mac ===

Version 7.7.4 (build 1)
Installation UUID: 8d12e55e-3489-463f-ac52-8cb4573c5a81
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 516000221

=== Mono Framework MDK ===

Runtime:
	Mono 5.16.0.221 (2018-06/b63e5378e38) (64-bit)
	Package version: 516000221

=== NuGet ===

Version: 4.8.0.5385

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.8
	2.1.2
	2.1.1
	2.0.5
	2.0.0
	1.1.2
	1.0.5
	1.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.504/Sdks
SDK Versions:
	2.1.504
	2.1.302
	2.1.301
	2.1.4
	2.0.0
	1.0.4
	1.0.0-preview2-003121
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.4
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 9.1.8.0 (Visual Studio Enterprise)
Android SDK: /Users/mandel/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.0.3 (API level 15)
		4.3   (API level 18)
		4.4   (API level 19)
		5.0   (API level 21)
		6.0   (API level 23)
		7.0   (API level 24)
		7.1   (API level 25)
		8.1   (API level 27)

SDK Tools Version: 25.2.5
SDK Platform Tools Version: 28.0.1
SDK Build Tools Version: 25.0.1

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/mandel/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.9
openjdk version "1.8.0-9"
OpenJDK Runtime Environment (build 1.8.0-9-microsoft-b00)
OpenJDK 64-Bit Server VM (build 25.71-b00, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 7.7.5.0
Hash: 06ceaea1

=== Apple Developer Tools ===

Xcode 10.1 (14460.46)
Build 10B61

=== Xamarin.Mac ===

Version: 5.2.1.15 (Visual Studio Enterprise)
Hash: d60abd198
Branch: 
Build date: 2019-02-01 12:23:30-0500

=== Xamarin.iOS ===

Version: 12.2.1.15 (Visual Studio Enterprise)
Hash: d60abd198
Branch: d15-9
Build date: 2019-02-01 12:23:29-0500

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 707040001
Git revision: 2a4679454f31c8bb887cfd181ea133c9149d3cad
Build date: 2019-01-30 16:18:21+00
Build branch: release-7.7.4
Xamarin extensions: c8b4305fd4c60b9c25947072eb150fdc3a5aa2b5

=== Operating System ===

Mac OS X 10.14.4
Darwin 18.5.0 Darwin Kernel Version 18.5.0
    Wed Jan 16 00:04:52 PST 2019
    root:xnu-4903.250.305~71/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

WakaTime 3.0.5
Vim 0.64.5.76
