### ISSUE TITLE
[ImageCaptureCore] Add managed handler to Request methods

### ISSUE THREAD

**Issue by dalexsoto** [xamarin/xamarin-macios#5093]
The following methods from `ICCameraDevice`:

* [RequestDownloadFile](https://github.com/xamarin/xamarin-macios/pull/5074/files#diff-4d8009902b7464e6d3cc4f5a992a7462R542)
* [RequestUploadFile](https://github.com/xamarin/xamarin-macios/pull/5074/files#diff-4d8009902b7464e6d3cc4f5a992a7462R548)
* [RequestReadDataFromFile](https://github.com/xamarin/xamarin-macios/pull/5074/files#diff-4d8009902b7464e6d3cc4f5a992a7462R551)
* [RequestSendPtpCommand](https://github.com/xamarin/xamarin-macios/pull/5074/files#diff-4d8009902b7464e6d3cc4f5a992a7462R554)

Can have a better signature like the following example:

```csharp
delegate void DidSendPtpCommand (NSData command, NSData inData, NSData response, NSError error);
public void RequestSendPtpCommand (NSData command, NSData outData, DidSendPtpCommand callback)
{
    // Magic goes here
}
```

**Comment by rolfbjarne** [comment]
Pseudocode of how to implement this:

I'm looking at the RequestReadDataFromFile method: https://developer.apple.com/documentation/imagecapturecore/iccameradevice/1508079-requestreaddatafromfile?language=objc

The documentation says that "The readDelegate must implement a function with the signature `- (void)didReadData:(NSData)data fromFile:(ICCameraFile)file error:(NSError)error contextInfo:(void)contextInfo`, to be called when the request is completed." 

Translated to C# that's:

```cs
[Export ("didReadData:fromFile:error:contextInfo:")
void DidReadData (NSData data, ICCameraFile file, NSError error, IntPtr contextInfo);
```

This gives a user-visible delegate like this (C# users shouldn't have to care about the contextInfo parameter, so we'll skip that):

```cs
delegate void DidReadDataDelegate (NSData data, ICCameraFile file, NSError error);
```

And then the function signature we want to expose is:

```cs
class ICCameraDevice {
    void RequestReadDataFromFile (ICCameraFile file, long offset, long length, DidReadDataDelegate callback);
}
```

The way to put this all together is to create a custom type with the given selector, and that calls the managed delegate, like this:

```cs
class DidReadDataFromFileAction : NSObject {
    DidReadDataDelegate Callback;
    public const string CallbackSelector = "didReadData:fromFile:error:contextInfo:";

    public ReadReadDataFromFileAction (ReadReadDataFromFileAction callback)
    {
        Callback = callback;
        IsDirectBinding = false;
    }

    [Export (CallbackSelector)
    void DidReadData (NSData data, ICCameraFile file, NSError error, IntPtr contextInfo)
    {
        Callback (data, file, error);
    }
}
```

and then it's all connected in the new method overload, where we create an instance of the custom type, and pass it to native code, with the selector implemented in the custom type. We pass IntPtr.Zero as the context, because we don't have a need for it.

```cs
class ICCameraDevice {
    public void RequestReadDataFromFile (ICCameraFile file, long offset, long length, DidReadDataDelegate callback)
    {
        var actionObject = new DidReadDataFromFileAction (callback);
        RequestReadDataFromFile (file, offset, length, actionObject, Selector.GetHandle (DidReadDataFromFileAction.CallbackSelector), IntPtr.Zero);
    }
}
```

Finally this needs manual tests!
