### ISSUE TITLE
NSProxy can not found 

### ISSUE THREAD

**Issue by Wenfengcheng** [xamarin/xamarin-macios#5276]
I am working on an FLAnimatedImage binding for iOS and I have come across a binding issue I have not seen before, from [FLAnimatedImage.h](https://github.com/Flipboard/FLAnimatedImage/blob/master/FLAnimatedImage/FLAnimatedImage.h):
```
@interface FLWeakProxy : NSProxy

+ (instancetype)weakProxyForObject:(id)targetObject;

@end
```
Apparently Xamarin.iOS does not have NSProxy.

Can anyone out there help me to figure out the best way to implement NSProxy, or maybe someone have experience to do that?

**Comment by VincentDondain** [comment]
Hi,

Indeed we currently do not support `NSProxy`. This would break assumptions in our runtime since it doesn't derive from `NSObject`.

See related issue: https://bugzilla.xamarin.com/show_bug.cgi?id=22940, https://bugzilla.xamarin.com/show_bug.cgi?id=26845 (those might be private).

Could you try binding this as `NSObject` and see if it works?

An other workaround you could use is to define your own managed NSProxy wrapper:

``` C#
[Register ("NSProxy", true)]
class NSProxy : NSObject
{
}
```

I'll close this issue as it's tracked elsewhere but feel free to still respond here (:

**Comment by Wenfengcheng** [comment]
@VincentDondain 
Hi, 
Thanks for your reply, this related issues are private, and I have tried second workaround:
```
 [Register ("NSProxy", true)]
 abstract class NSProxy : NSObject
 {
 }
```
But it doesn't work, 
> NSProxy is inaccessible due to its protection level.

**Comment by Wenfengcheng** [comment]
@VincentDondain 
I try binding `NSProxy` as `NSObject`, and it worked. 
Thanks for you reply!
