### ISSUE TITLE
Issue with mono version when running F# on ARM64, related to struct types

### ISSUE THREAD

**Issue by RyanBuzzInteractive** [xamarin/xamarin-macios#5279]
This entire issue and all the relevant details and history are already posted here:

https://github.com/mono/mono/issues/12073

It's a nasty bug and one that is crippling our app.

It seems there was a bug with mono which caused this issue on Android, which I also experienced. It was fixed and newer Xamarin.Android releases apparently do not display the issue any more.

I have been told that I need to use a Xamarin.iOS version that is built against mono 5.16 or later, but looking at the upcoming Xamarin.iOS 12.3 release it uses mono 5.14.

I can see that the repo master has bumped to mono 5.18, but I guess it is going to be a long time before this shows up as an update in VS.

**Comment by spouliot** [comment]
@marek-safar mentions it's fixed in https://github.com/mono/mono/issues/12073#issuecomment-447796759 but it requires mono 2018-08 which is, for now, only available using a build from master.

Link to a recent build: 
https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/master/b51e8ecfc8bfb8713559c70072a167800819aa8f/281/package/xamarin.ios-12.6.0.9.pkg

**Comment by RyanBuzzInteractive** [comment]
Brilliant, thanks :)

**Comment by RyanBuzzInteractive** [comment]
I can happily confirm that the recent build provided above did indeed fix the issue. Thanks so much for your help :)

**Comment by spouliot** [comment]
Thanks for confirming the fix! It should be published along with 16.0 preview 2 in early 2019.
