### ISSUE TITLE
[Question] NSArray<T> and covariance

### ISSUE THREAD

**Issue by Therzok** [xamarin/xamarin-macios#5331]
Should `NSArray<T>` support covariance? That is, given the code below, should it compile?

```
NSArray<NSScrollView> specific = ...;
NSArray<NSView> generic = specific;
```

I guess that opens a whole can of worms with what type is registered and runtime when marshalled back and could probably hide issues at runtime.

The fix for it would be to add the `out` generic modifier to `NSArray<T>`:
```
class NSArray<out T> : ...
```

**Comment by spouliot** [comment]
I do not think it would be an issue for the runtime since it already needs to handle cases where types are not what it expects to be (objective-c model being weaker). @rolfbjarne ?

However I think this could be a breaking change and code compiled with the updated type could become unusable with older XI/XM (e.g. XF). Still worth considering if we break compatibility in the future.

**Comment by rolfbjarne** [comment]
Objective-C implemented generics by type erasure, so for the Objective-C runtime there's no difference between `NSArray`, `NSArray<NSScrollView>` or `NSArray<NSView>`.

Also, the actual type of the managed instance doesn't change, which means that I can't see how this will change anything on our side (and I can't come up with a sample that breaks).

This of course raises the equivalent question: should we support contravariance anywhere in our bindings?

**Comment by spouliot** [comment]
keeping this to covariance: I was thinking of a 3rd party built with XI `x` and shipped (as source) to people using `< x`. I do not think it's common enough and since it allows more (not a restriction) then it won't contradict any written documentation.

note: I recall mention of _possible_ compatibility issues when the feature was added - but I can't recall a single _actual_ case reaching my ears...

**Comment by Therzok** [comment]
Closing this.
