### ISSUE TITLE
Handle broken NSApplication.SharedApplication.Windows API (Rename + Advice? Remove in XAMCORE_4_0?)

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#5350]
NSApplication.SharedApplication.Windows has caused many developers pain and suffering. 

https://forums.xamarin.com/discussion/comment/296033#Comment_296033

```NSApplication.SharedApplication.Windows is EVIL. It hooks into the alloc/dealloc of windows, and when you reference it in C# will make bridged objects to everything in the list. Which means if you have windows that are going to dealloc, and then look at the list, you now poked them again to stay alive a bit longer.```

We should [Advice] it now and remove from XAMCORE_4_0 (or rename to DangerousWindows)?

**Comment by spouliot** [comment]
That sounds like the old issue around UIKit `UIApplication.Window`. We added `[Transient]` to minimize its lifetime (but it's probably not needed since we switched to newrefcount). 

My guess here is the (managed) array keeping a (strong) reference to each `NSWindow` instance, blocking the OS from disposing them. Maybe an `NSArray<NSWindow>` would reduce this (and be more like ObjC would behave).

**Comment by chamons** [comment]
That's not a terrible idea at all.

**Comment by alanmcgovern** [comment]
I specialise in non-terrible ideas!

**Comment by chamons** [comment]
Implemented [this idea](https://github.com/xamarin/xamarin-macios/issues/5350#issuecomment-464761475).
