### ISSUE TITLE
[XI] Error MSB4064: The "UseInterpreter" parameter is not supported by the "MTouch" task

### ISSUE THREAD

**Issue by mykyta-bondarenko-gl** [xamarin/xamarin-macios#5354]
It fails with mono 5.18 and XI 15-9.

### Steps to Reproduce

1. Download a [sample](https://github.com/xamarin/ios-samples/tree/master/ios10/IceCreamBuilder)
2. Build it

### Expected Behavior
Build is successful

### Actual Behavior
Build is failed

```
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets(4,4): Error MSB4064: The "UseInterpreter" parameter is not supported by the "MTouch" task. Verify the parameter exists on the task, and it is a settable public instance property. (MSB4064) (MessagesExtension)
```

### Environment

1. VSfM
https://gist.github.com/mykyta-bondarenko-gl/e74e0fc1a60c9a816b60f4de86bdd446

### Build Logs

1. Build Output
https://gist.github.com/mykyta-bondarenko-gl/f95832a79325a63b3d3462f03e92c798

### Example Project (

[IceCreamBuilder](https://github.com/xamarin/ios-samples/tree/master/ios10/IceCreamBuilder)

**Comment by spouliot** [comment]
@mykyta-bondarenko-gl this often happens if you don't restart VS4M between mono updates (since msbuild files are loaded cached from the original mono and XI). I've used this config without issue (but it might not be the exact same version of mono).

Can you please restart VS4M to confirm this ?

It's possible there's a compatibility issue between the newer (and still moving target) mono 5.18 and XI from 15.9 (which is frozen). However because of their respective state it's might not be fixable (15.9 being frozen).

**Comment by mykyta-bondarenko-gl** [comment]
@spouliot you are right. Restart of VSfM didn't help but after restarting a local machine it started working
