### ISSUE TITLE
Feature request: Dialog to run VS Update on MAC

### ISSUE THREAD

**Issue by taori** [xamarin/xamarin-macios#5449]
Sometimes my build fails on MAC and i am sitting there, puzzled - It says something about connection refused and whatnot - but the actual issue is just that there are updates for VS on mac.

It would be great if VS prompted me to update VS on mac, instead of just displaying the stack trace, if an available update is the reason i am getting that stack trace in the first place

> VS bug [#774381](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/774381)

**Comment by mauroa** [comment]
The VS experience in Windows with iOS is totally unrelated and independent of VS for Mac. You can uninstall VS for Mac and continue working with VS in Windows without any problem.
We only require Mono, Xamarin iOS and Xamarin Mac installed on the Mac to be able to work on VS with iOS apps and connected.
Having VS for Mac just make that part easier because it takes care of the Mono, Xamarin iOS and Xamarin Mac installation for you.
However, in VS in Windows we are already tracking and providing auto provisioning of Mono and Xamarin iOS, so we can install and update it directly from Windows.
For this reason, updates on VS for Mac shouldn't be the reason of your build failures.
It would be good if you can provide more detailed information about the build errors, stack traces, build output (with detailed verbosity), logs, etc. so we can understand better what is blocking you.
Thanks in advanced.

**Comment by mauroa** [comment]
Closing this issue given that we haven't received the requested logs to investigate, because VS already provides auto-provisioning feaures to get the Mac ready without needing VS for Mac or without needing to take care of it. Please feel free to re open it if you still experience issues or have the required information. As an alternative, please be sure to update to the latest VS version and see if the issue persists.
