### ISSUE TITLE
Xamarin.Mac Full needs to set new TFI to allow nuget targetting of Full

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#5480]
Today there are three ["target frameworks"](https://developer.xamarin.com/guides/mac/advanced_topics/target-framework/) that Xamarin.Mac can target. However, you can only target two of them in nuget packages. This causes libraries that want to support Full but need platform specific libraries\native libraries significant pain.

After the discussion [here](https://github.com/NuGet/NuGet.Client/pull/2572#issuecomment-456964130) and one with @mrward I believe the following are true:

- Nuget needs a new Target Framework Identifier (TFI) set for Full projects instead of the current one to be able to to handle targettinging
- However, we have many projects in the wild with existing tags.
- A migration will be painful and likely "not worth it".

And that the following plan is feasible:

- When `UseXamMacFullFramework` is true [here](https://github.com/xamarin/xamarin-macios/blob/master/msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.props#L91) we can change the TargetFrameworkIdentifier at build time. 
- Then nuget should see the new TFI and use those bits, or fall back as described in the [PR](https://github.com/NuGet/NuGet.Client/pull/2572)

This change would add yet _another_ bit of complication to the already non-trivial target framework system, and the chance for regressions and complications is non-trivial. However, it is the only viable path forward to allow nuget targetting.

> VS bug [#778613](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/778613), VS bug [#779016](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/779016)

**Comment by chamons** [comment]
The change itself is trivial but the testing implications are frightening. How many interconnected parts (0? many?) depend on the TFI to be set as it is for Xamarin.Mac full? We could run our full auto test suite and a number of samples and yet break the world upon release.

So my current plan is to make this change like this:

- Create a new MigrateToNewXMTFI property that that defaults to false
- If XM Full and MigrateToNewXMTFI is true, then we change the TFI to the new style
- Release with this (opt-in) version, let nuget and some users test it out
- If it is solid, then flip MigrateToNewXMTFI to default to true. This gives us an opt-out flag for projects we break.

**Comment by chamons** [comment]
I've filed https://github.com/xamarin/xamarin-macios/issues/5691 to track that we need to change this to opt-out at some point.

I'm going to close this and track additional work, including IDE integration later, in that task.

**Comment by Odirb** [comment]
@chamons I have the trick given by @mrward here https://github.com/NuGet/NuGet.Client/pull/2572 to be able to support Xamarin.Mac.NET in Visual Studio mac, and try to compile a project using the MigrateToNewXMIdentifier flag.

Unfortunately, it seems an additional patch in Xamarin-macos is necessary in file Xamarin.Mac.ObjCBinding.CSharp.targets because I have this compilation error :

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Mac/Xamarin.Mac.ObjcBinding.CSharp.targets(92,3): error : BTouch doesn't know how to deal with TargetFrameworkIdentifier: Xamarin.Mac.NET
BTOUCH : error BI0086: bgen: A target framework (--target-framework) must be specified.

Do you think you can re-open this issue to fix this problem?

**Comment by chamons** [comment]
@Odirb  - filed as https://github.com/xamarin/xamarin-macios/issues/7588

**Comment by Odirb** [comment]
Thanks Chris
