### ISSUE TITLE
Make ObjCRuntime.Runtime.Arch a constant for the AOT compiler

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#5518]
Suggestion:

* Tell the AOT compiler that the ObjCRuntime.Runtime.Arch field is a constant value (since for the AOT compiler it will always be `ARCH.Device = 0`), which will allow the AOT compiler to skip a lot of dead code (all the simulator-only code can be optimized away).

Requirements:

* The [ObjCRuntime.Runtime.Arch](https://github.com/xamarin/xamarin-macios/blob/742f0df45971ed8837bd65c76e5ad7ada572bd36/src/ObjCRuntime/Runtime.iOS.cs#L46) field [must be readonly](https://github.com/mono/mono/blob/434ec4110d27fb0e5720adc6060d3963a2484af1/mono/mini/method-to-ir.c#L9400). We can't change this now, since it would be a breaking change, but could for XAMCORE_4_0.

POC: https://github.com/rolfbjarne/xamarin-macios/commit/84f35cf916f97fd13170b91e49c8e621a8d98d3d

POC result: The don't link app compiled for iOS/arm64 is ~175kb smaller.

**Comment by spouliot** [comment]
Where are the savings coming from ? 

The linker optimize that (at least in bindings) before it reach the AOT compiler (so the field should not be present). If the saving comes from elsewhere then we could _expand_ on this (linker) optimization.

Or maybe we can shadow the current field with a 2nd (read-only) one ? and make sure the platform assemblies (and generated code?) use this field.

Of course existing (3rd party) bindings won't make use of the new field and won't have this optimizations. Recompiling them would make them incompatible with earlier versions too :|

Now It could be `internal` since our platform bindings already have special case / awareness of their unique situation. OTOH that would mean re-compiling 3rd party bindings won't help.

**Comment by rolfbjarne** [comment]
> The linker optimize that (at least in bindings) before it reach the AOT compiler

This is `dont link` 😄 That said, the linker will only optimize this for methods with `[BindingImpl (Optimizable)]`, the AOT optimizes everywhere.

> Or maybe we can shadow the current field with a 2nd (read-only) one ? and make sure the platform assemblies (and generated code?) use this field.

That's an intriguing idea.

**Comment by spouliot** [comment]
Ok, still make sense for **Don't link** wrt the interpreter, at least until we revisit all the _linker_ optimizations :)
