### ISSUE TITLE
Delegate will return null on ObjC classes not bound in managed code

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#5723]
### Steps to Reproduce

1. Unzip attached projects
2. Build objc project (MakeAWindow) and place libMakeAWindow.dylib in managed project (copy already exists)
3. Build and run managed project (XMDelegateRepro)
4. Note output:

```
1) From ObjC
2) True
3) 
4) False
5) Foundation.NSObject
6) 
MyDelegate
2019-03-05 11:38:15.270 XMDelegateRepro[13657:2238180] Delegate = 0x6000014085a0
```

`x.Delegate`  is null but `x.WeakDelegate`is not, as the ObjC type MyDelegate is not bound in managed code.

### Expected Behavior \ Actual Behavior

I'm unsure if this is a bug or a limitation, but it has strange interactions with delegate stomping checks (will be filed as another issue)

### Environment

Master macios

### Example Project (If Possible)

[MakeAWindow.zip](https://github.com/xamarin/xamarin-macios/files/2932202/MakeAWindow.zip)
[XMDelegateRepro.zip](https://github.com/xamarin/xamarin-macios/files/2932203/XMDelegateRepro.zip)

**Comment by spouliot** [comment]
I'd say it's not a bug but a feature ;-)

The same situation can happen with only managed code. Any `NSObject` can be assigned to a `WeakDelegate` but it cannot be _casted_ of a strongly-typed, interface-based, `Delegate` property.

Whether we could or should (not a small behaviour change) return a `*Wrapper` in such case is a possibility - but it might crash (or cause weird behaviour) at runtime since required/optional is not _really_ enforced by Apple (so it might not match our interfaces)

**Comment by chamons** [comment]
Yeah, I wasn't sure if it was a bug or a gotcha or nothing. I just filed it since it interacts with #5724

**Comment by chamons** [comment]
After thinking about this, I agree with past-Sebastien that this is a feature. Closing.
