### ISSUE TITLE
Expanding NSColor in debugger crashes app

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#5738]
### Steps to Reproduce

1. New XM App
2.  `	NSColor color = NSColor.Red;` and set breakpoint on line after
3.  Expand color in debugger
4. Boom - https://gist.github.com/chamons/be71ccd1b887a7e246bd3b42910bef7b

### Expected Behavior

We don't expand unsafe properties by default in IDE.

### Environment
macios master

**Comment by spouliot** [comment]
weird, the binding is annotated correctly

```csharp
[Export ("blackComponent")]
nfloat BlackComponent { [MarshalNativeExceptions] get; }
```

and the right `xamarin_*` function was called

```
	2   CoreFoundation                      0x00007fff3bd0dc77 +[NSException raise:format:] + 193
	3   AppKit                              0x00007fff39822481 -[NSColorSpaceColor blackComponent] + 44
	4   NSColorCrash                        0x000000010206516d xamarin_nfloat_objc_msgSend + 29
```

but it did crash... maybe mono intercepted it before the native catch handler we generate ?

**Comment by rolfbjarne** [comment]
We caught the NSException, and then decided to rethrow it:

	0x7fff66e5a507 - /usr/lib/libobjc.A.dylib : objc_exception_throw
	0x1020931f1 - [...]/NSColorCrash.app/Contents/MacOS/NSColorCrash : xamarin_process_nsexception_using_mode

which means we hit this case: https://github.com/xamarin/xamarin-macios/blob/99e727c90b73804be3ab4ad08bc02fb2de867870/runtime/runtime.m#L2355-L2359

and that crashes because there are no other Objective-C catch handlers further up the stack.

I suspect that passing `--marshal-objectivec-exceptions=throwmanagedexception` to mmp will fix the problem. Admittedly this should probably be the default when debugging.

**Comment by chamons** [comment]
Nice idea Rolf - that fixed it and is a sensible default.

**Comment by chamons** [comment]
This was fixed back in https://github.com/xamarin/xamarin-macios/pull/7667 and never closed.
