### ISSUE TITLE
[msbuild/template] ConcurrentGC default option inconsistency

### ISSUE THREAD

**Issue by VincentDondain** [xamarin/xamarin-macios#5786]
There is a difference between [VSMac's default](https://github.com/xamarin/xamarin-templates/blob/master/ios/content/single-view/NewApp.csproj#L13) for `ConcurrentGC` and the Xamarin.iOS [msbuild default](https://github.com/xamarin/xamarin-macios/blob/master/msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.props#L53).

Before turning that into an issue and decide if it's `external-visual-studio-for-mac` or not, we need to know which default we want. We need to know if the template is wrong or if the msbuild task is wrong.

In addition this is an opportunity to reinstate that we should have checkboxes but 3 way combo boxes with a "default" state that can be changed automatically by our team.

**Comment by spouliot** [comment]
A two-states checkbox makes this impossible to change without _potentially breaking_ existing code - because we cannot know if it was implicitly and explicitly disabled by the developer.

Now I'm not sure it's inconsistent ?!? Does not `msbuild` always get a value from new (or old) templates ? if that's the case then we _obey_ the input and the output is directly consistent with the input. 

That's pretty much what we can do with a checkbox, i.e. update template for future projects.

A better approach would be to add an analysis rules to suggest developers to enable this feature (if not already enabled).

**Comment by rolfbjarne** [comment]
It seems the ConcurrentGC was enabled in the templates only 2 months ago (https://github.com/xamarin/xamarin-templates/commit/5d002345dbcb89f32009d0be19859ff033bbfa5f), which means it hasn't reached any stable releases yet. 

I think the current situation is fine: new projects will default to ConcurrentGC, while we won't change behavior for existing projects. Once it's been thoroughly tested, we can consider enabling it for existing projects.

**Comment by rolfbjarne** [comment]
Closing, this is not an issue in .NET.
