### ISSUE TITLE
marksweep-conc is now non-experimental, should update text (change default?)

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#5909]
@BrzVlad informed me that the options that `--sgen-conc` enable are no longer experimental. 

We should update the text for sure. Maybe we consider changing the default if that is safe and reasonable.

> VS bug [#935384](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/935384), VS bug [#936141](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/936141)

**Comment by chamons** [comment]
Heads up @rolfbjarne

**Comment by spouliot** [comment]
The UI text can be updated. In fact it should query the feature .plist to see if it's experimental (or not) and adjust the text accordingly.

As for changing defaults i't, again, the _old_ UI checkbox/boolean issue :( We can't know if it was
- never tried, i.e. the default **off** value was unchanged;
- tried, but disabled/unchecked later - e.g. because it did not work as expected

As long as we keep checkbox/bool UI configuration we'll keep having this issue to allow developers to _automatically_ adopt new features (unless they do not _explicitly_ want them).

We need tri-state (default, on, off) or a list of options (including *default*) in order not to break existing applications (that made a conscious decision against using a feature).

**Comment by rolfbjarne** [comment]
> In fact it should query the feature .plist to see if it's experimental (or not)

Sadly we used `sgen-concurrent-gc` as the plist string for the experimental feature, which makes things ugly now. `sgen-concurrent-gc-non-experimental` just doesn't sound very well, but does anyone have a better idea?

**Comment by chamons** [comment]
What about `concurrent-gc`?

**Comment by spouliot** [comment]
or `sgen-concurrent` :)

**Comment by rolfbjarne** [comment]
`sgen-concurrent` sounds good, this will be added in PR #6394.

IDEs should check for this new feature flag and if present, remove the experimental text in the UI to not be experimental anymore.

Adding the `vs-sync` label to that effect.

**Comment by chamons** [comment]
Both VS-sync issues were resolved, closing.
