### ISSUE TITLE
[xcode11-support] Verify support when running on macOS 10.15

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#6234]
macOS 10.15 has a number of changes which could possibly break Xamarin.iOS, Xamarin.Mac, or other Xamarin products. In particular:

- [x] Gatekeeper changes
    - [x] Applied to non LaunchService apps (e.g. console apps, libraries) (per bundle)
    - [x] Self-updating app must “fix” their signature (likely delta updates only)
- [x] Notarization
- [x] Removal of 32-bit subsystem
- [x] System Volume Read Only
- [x] Removal of Application Loader

We need to at minimum be able to
- [x] Able to build xamarin-macios and mono from 10.15
- [x] Able to build "Hello World" in Xcode 11 & macOS 10.15 for XI and XM

**Comment by ivanicin** [comment]
Just to note that for me there are some problems.

At first I've changed my old Mac Mini to XCode 11 / Visual Studio XCode 11 Preview. That worked. After updating further to macOS Catalina there seems to be serious problems:
- Visual Studio for Windows couldn't connect anymore
- Project can't be even opened as it gets to the 'Updating Resources' and keeps there indefinitely.

I haven't gone too much into details on exact causes and it could be that part of the problem is that this Mac Mini has only 4 GB of RAM, but still it is not just that it is slow, but rather it never completes.

**Comment by chamons** [comment]
At this point in the preview cycle, all of these have been handled at some level in our stack.

@ivanicin Please consider reporting the issue with 

https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019

if the build listed here:

https://docs.microsoft.com/en-us/xamarin/ios/platform/ios13/get-started

is not working.
