### ISSUE TITLE
[XM]Quitting installer app is throwing an exception when built with preview XM build (5.14)

### ISSUE THREAD

**Issue by GouriKumari** [xamarin/xamarin-macios#6490]
Steps to Reproduce

1. Install visual studio for mac 8.2 preview builds, https://gist.github.com/GouriKumari/da8e68f8327706f2269dafa001877eb4
2. Execute the installer from this link, https://xamarin-downloads.azureedge.net/uploads/apkgozqezsw/VisualStudioforMacInstaller.dmg
3. Click "Quit" in License Dialog

### Expected Behavior
No exception 
### Actual Behavior
An exception is thrown " Event registration is overwriting exisitng delegate". This issue isn't reproducible with stable XM build. 

### Environment

https://gist.github.com/GouriKumari/da8e68f8327706f2269dafa001877eb4

### Build Logs
Exception Log: https://gist.github.com/GouriKumari/d32f6d21da4224bc116aca5f4688755c. Checked also with latest XM - 5.14.0.109.
Installer Log: https://gist.github.com/GouriKumari/4afb8f1bd2d94eba0a16946177371cb4

### Additional Info:
This issue is not occurring with mono 5.18.1.28 and XM 5.10.0.57. Is the exception a bug in XM or installer code needs an update to build with XM 5.14.0.x? Currently installer is build with https://github.com/xamarin/installer/blob/master/bot-provisioning/provisionator.csx from bots.

**Comment by spouliot** [comment]
That code has not changed for a long while. It detects when people mix the `*Delegate` and the events (which use a custom `*Delegate`) together - since one would overwrite the other.

@GouriKumari Can you point me where the code is (on slack) ?

**Comment by spouliot** [comment]
Ok, that's likely related to https://github.com/xamarin/xamarin-macios/issues/5350
where `NSApplication.Window` was changed (because the managed array would keep them alive longer than expected).

Not quite sure how (it did not fail before) but it seems you have a custom `NSWindowDelegate` in the windows you're iterating - and that conflicts with the _event_ version.

The _safe_ way would be to iterate using the `Delegate` property (and not the `event`) so the code will work in every case. E.g. something like

```csharp
var shouldClose = window?.Delegate?.WindowShouldClose (window) ?? true;
```

**Comment by GouriKumari** [comment]
Thanks, this solves the issue.

**Comment by spouliot** [comment]
I'm not fully sure why it worked before (strange things happens when `dealloc` does extra work) but the current behaviour is the correct one - so your fix is correct (not just a workaround).
