### ISSUE TITLE
[tvOS] "Enable incremental builds" causes build error

### ISSUE THREAD

**Issue by TheSpydog** [xamarin/xamarin-macios#6670]
### Steps to Reproduce

1. Using Visual Studio for Mac, create a new Single-View Xamarin.tvOS project.
2. In AppDelegate.cs, add the following at the class level:
```
using System.Runtime.InteropServices;
...
[DllImport("__Internal")]
private static extern void MyExtern();
```
(It doesn't matter whether you actually have a native library with the symbol MyExtern. The problem occurs regardless.)

3. Build the project for Generic Device. Notice the build error:
`
Error MT5216: Native linking failed for '/Users/calebcornett/Projects/tvIncrementalBuildTest/tvIncrementalBuildTest/obj/iPhone/Debug/mtouch-cache/arm64/libtvIncrementalBuildTest.exe.dylib'. Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new (MT5216) (tvIncrementalBuildTest)
`

4. In Project Options > tvOS Build > iPhone configuration, un-check the "Enable incremental builds" option.

5. Build again. Notice the expected behavior.

### Expected Behavior

Using DllImport should either display a "native linking failed, symbol not found" error (if there is no native library with the specified symbol), or should build without issue (if the symbol does exist).

### Actual Behavior

DllImport gives a build error that suggests submitting an issue to this repo, regardless of whether the symbol exists or not.

### Environment

```
=== Visual Studio Community 2019 for Mac ===

Version 8.2 (build 1105)
Installation UUID: d67ff5a7-669b-462a-a6c4-c138ddfaf1bf
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.14.0.85 (d16-2-fix-mac-updates / 86973979)

	Package version: 600000311

=== Mono Framework MDK ===

Runtime:
	Mono 6.0.0.311 (2019-02/494641b300c) (64-bit)
	Package version: 600000311

=== NuGet ===

Version: 5.1.0.6013

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.2.4
	2.1.9
	2.1.8
	2.1.6
	2.1.5
	2.1.2
	2.1.1
SDK: /usr/local/share/dotnet/sdk/2.2.203/Sdks
SDK Versions:
	2.2.203
	2.1.505
	2.1.504
	2.1.500
	2.1.403
	2.1.302
	2.1.301
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/msbuild/Current/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Not Installed

=== Microsoft Mobile OpenJDK ===

Java SDK: Not Found

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.58
Hash: d03e3ea
Branch: remotes/origin/d16-2~1
Build date: 2019-07-16 17:37:14 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Apple Developer Tools ===

Xcode 10.3 (14492.2)
Build 10G8

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 12.14.0.110 (Visual Studio Community)
Hash: a8bcecce
Branch: d16-2
Build date: 2019-06-28 07:31:42-0400

=== Xamarin Designer ===

Version: 16.2.0.354
Hash: 5f80a14f8
Branch: remotes/origin/d16-2
Build date: 2019-07-11 17:28:26 UTC

=== Build Information ===

Release ID: 802001105
Git revision: a187f6852ae62ba52b944b47e53702957edfcf7b
Build date: 2019-07-22 18:20:10+00
Build branch: release-8.2
Xamarin extensions: 34bd2378d8d707df25989727c23ce68d9a232a67

=== Operating System ===

Mac OS X 10.14.5
Darwin 18.6.0 Darwin Kernel Version 18.6.0
    Thu Apr 25 23:16:27 PDT 2019
    root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64


```

### Build Logs

https://gist.github.com/TheSpydog/27aa12173ce2474ccdf8a3f997c7ca10

### Example Project (If Possible)

[tvIncrementalBuildTest.zip](https://github.com/xamarin/xamarin-macios/files/3438540/tvIncrementalBuildTest.zip)

**Comment by chamons** [comment]
FYI: @rolfbjarne  (this looks like your area)

**Comment by rolfbjarne** [comment]
This is expected, but unfortunately not very well documented.

When you enable incremental builds, we compile each managed assembly into its own dynamic library. This means that if an assembly has a DllImport function, we must link (natively) that particular dynamic library with the native library that provides the native function for the DllImport. A requirement for this is that we can match an assembly with the native library, and this is not possible if you manually link with the native library by adding linker flags to the additional mtouch arguments in the project's iOS Build options (I'm guessing this is how you tried to link with the native library).

The solution is to create a binding project, add the native library to it, and then add the DllImports there (you can delete anything related to binding Objective-C libraries). This way we're able to match the assembly where the DllImport is with the matching native library, and we do the right thing at build time.

**Comment by TheSpydog** [comment]
Not sure I understand. This test case works as expected when compiling for iOS. It only displays this error on tvOS. What’s the difference here?

**Comment by rolfbjarne** [comment]
> It only displays this error on tvOS. What’s the difference here?

Technically it's possible to delay the lookup of the native function until runtime. Due to historical reasons, this is the default on iOS, but with tvOS (and watchOS) we changed the default so that you get a build error instead of runtime exception if there are missing native functions ([1]). In some scenarios (such as this one), it could be that on iOS things would still work, if the apparently missing native function was loaded due to some other means (in this case it would be because the main executable would have it). If you want to try looking up the function at runtime instead, you can try adding `--dlsym:true` to the additional mtouch arguments in the project's iOS Build options (this won't work for tvOS release builds, and I'm not sure it'll work for debug builds either, but it's easy enough to try it out).

[1] There's another benefit of requiring native functions to exist: the native linker is then able to figure out which native functions are *not* used, and can remove those. This can result in some very significant size decreases, depending on the native library in question and exactly what is used from it.

**Comment by flibitijibibo** [comment]
> There's another benefit of requiring native functions to exist: the native linker is then able to figure out which native functions are not used, and can remove those.

That's kind of the reason this report exists; we _don't_ reference the functions in question, so they _should_ be removed, instead of having them generate erroneous linker errors. We can take the `--dlsym=true` route on FNA's end, but at the absolute minimum this should be documented for others who run into this on platforms that are otherwise pretty much identical.

**Comment by rolfbjarne** [comment]
> That's kind of the reason this report exists; we _don't_ reference the functions in question, so they _should_ be removed, instead of having them generate erroneous linker errors.

If there's a P/Invoke in managed code to a native function, we must somehow make sure the native linker doesn't remove that native function (a P/Invoke counts as a reference to it). The problem arises when the native function doesn't exist: you get linker errors.
