### ISSUE TITLE
Xamarin.Mac application randomly hangs completely

### ISSUE THREAD

**Issue by SergioLuis** [xamarin/xamarin-macios#6708]
Hi, I don't know if this is the right place to report this issue - but we were directed here for a faster response when asking to someone at Microsoft.

We have a Xamarin.Mac application that stalls at different points in its lifecycle. The cursor beachballs, and when we try to do a call stack dump of its threads using `kill`, we got nothing. We have several customers reporting this issue, and it was not until yesterday that we got a clean Mojave machine to reproduce this stall issue consistently (although we can't determine the root issue - that's why I'm comming here for help).

Our logs are irrelevant as well, as we were not able to determine a pattern or a given point in the code where the application freezes, it just seems to happen "randomly".

What we got is the dumps retrieved through the Activity Monitor, but we can't make any sense out of them.

### Steps to Reproduce

1. Launch the application from a terminal executing `/Applications/OurApp.app/Contents/MacOS/OurApp`
2. Use the application normally - it might or might not stall.
3. When the application stalls, find out its PID, and execute the following line to try and get the call stack of its threads:

`$ kill -QUIT OurApp_PID`

### Expected Behavior

The application doesn't freeze at all, or when it does, at least we can get the call stack dump using the `kill` command (which works just fine when the application does not freeze)

### Actual Behavior

The application freezes, it never becomes responsive again (even after several hours), and using the kill command to get the stack dump does absolutely nothing.

### Environment

```
Xamarin.Mac 4.4.99.193 git-rev-head:64fece5
```

### Example Project (If Possible)

We do not have an example project we can share, sorry. We however have a "Sample process" generated using Activity Monitor, but we can't make any sense out of it:

[Sample of PlasticSCM.txt](https://github.com/xamarin/xamarin-macios/files/3461253/Sample.of.PlasticSCM.txt)

**Comment by SergioLuis** [comment]
We have generated a build upgrading to Xamarin.Mac 5.14 and the application hangs again (although less frequently). Here is the process sample as Activity Monitor provided it:

[Sample of PlasticSCM-new-version.txt](https://github.com/xamarin/xamarin-macios/files/3461259/Sample.of.PlasticSCM-new-version.txt)

**Comment by chamons** [comment]
Have you considered [AOT](https://docs.microsoft.com/en-us/xamarin/mac/internals/aot)ing your application? You will get _significantly_ better native stack traces, which might help you sort this out.

You could also consider adding [this hack](https://gist.github.com/chamons/68c6eddbde1fe1e32593) in the version you are debugging. It will force a garbage collection every second, which can shake out "random" failures due to garbage collection.

**Comment by miryamGSM** [comment]
Hi,

The application hang appears with much less frequently using Xamarin.Mac 4.4.
Here is the Spindump as Activity Monitor provided it when it froze.

[Spindump.txt](https://github.com/xamarin/xamarin-macios/files/3472630/Spindump.txt)

The relevant info is the following one, where maybe a deadlock occurs:

```
Thread 0x431a0            DispatchQueue 1           Thread name "tid_307"     1000 samples (1-1000)     priority 47 (base 47)
  1000  ??? [0x110fa98bf]
    1000  mono_reflection_get_custom_attrs_by_type_handle + 87 (PlasticSCM + 1829495) [0x10b659a77]
      1000  mono_custom_attrs_construct_by_type + 233 (PlasticSCM + 1822009) [0x10b657d39]
        1000  mono_array_new_specific_checked + 99 (PlasticSCM + 2350515) [0x10b6d8db3]
          1000  mono_gc_alloc_vector + 108 (PlasticSCM + 2459132) [0x10b6f35fc]
            1000  sgen_gc_lock + 61 (PlasticSCM + 2887005) [0x10b75bd5d]
              1000  _pthread_mutex_firstfit_lock_slow + 226 (libsystem_pthread.dylib + 5319) [0x7fff644b84c7]
                1000  __psynch_mutexwait + 10 (libsystem_kernel.dylib + 14450) [0x7fff64403872]
                 *1000  psynch_mtxcontinue + 0 (pthread + 10095) [0xffffff7f829f876f] (blocked by pthread mutex owned by PlasticSCM [7420] thread 0x431b6)
```
				 
```
Thread 0x431b6            Thread name "Threadpool worker"                     1000 samples (1-1000)     priority 47 (base 47)
  1000  ??? [0x110f88276]
    1000  ves_icall_System_String_InternalAllocateStr + 35 (PlasticSCM + 2589891) [0x10b7134c3]
      1000  mono_string_new_size_checked + 110 (PlasticSCM + 2319982) [0x10b6d166e]
        1000  mono_gc_alloc_string + 119 (PlasticSCM + 2459591) [0x10b6f37c7]
          1000  sgen_alloc_obj_nolock + 959 (PlasticSCM + 2839055) [0x10b75020f]
            1000  sgen_perform_collection + 131 (PlasticSCM + 2884547) [0x10b75b3c3]
              1000  sgen_stop_world + 61 (PlasticSCM + 2897709) [0x10b75e72d]
                1000  sgen_client_stop_world + 1295 (PlasticSCM + 2497359) [0x10b6fcb4f]
                  1000  mono_profiler_raise_gc_event + 64 (PlasticSCM + 2384592) [0x10b6e12d0]
                    1000  gc_event_callback(_MonoProfiler*, MonoGCEvent, int) + 75 (PlasticSCM + 187467) [0x10b4c8c4b]
                      1000  _pthread_mutex_firstfit_lock_slow + 226 (libsystem_pthread.dylib + 5319) [0x7fff644b84c7]
                        1000  __psynch_mutexwait + 10 (libsystem_kernel.dylib + 14450) [0x7fff64403872]
                         *1000  psynch_mtxcontinue + 0 (pthread + 10095) [0xffffff7f829f876f] (blocked by pthread mutex owned by PlasticSCM [7420] thread 0x431a0)

```
 
Any help is welcome!
Meanwhile, we are going to check the AOT compilation and the garbage collection issue.

Thanks in advance

**Comment by chamons** [comment]
So
```Xamarin.Mac 4.4.99.193 git-rev-head:64fece5``` is a **preview** of a build from over a **year ago**? Is it a custom build you've created?

Have you tried rebuilding against a build from this year?

There have been a lot of changes over the last year, including a number from our runtime, so rebuilding against our stable would be a good step.

**Comment by spouliot** [comment]
I had a quick look at the attached spindump file. It might be a deadlock but I doubt it.

My _guess_ is that garbage collection becomes more frequent and longer over time (the stacks shows threads doing allocations, which can trigger the GC). 

There _might_ be leaks or retention (intentional or not) that could explain this. Before checking for them you should really update to the latest stable XM (since anything you find, if in XM/mono code, might be fixed or very different today).

You can also set environment variables (check `man mono`) to get some additional data from the GC itself. That might tell you how often it collects and how much work is being done.

**Comment by psantosl** [comment]
Thanks for all the answers.

Some more info:

- We tried with latest Xamarin on Friday, but it freezed even faster.
- The freeze is extremely hard to reproduce. Sometimes it takes a second to consistently reproduce, sometimes we need to try for 45 minutes.
- When it is frozen, it seems it doesn't respond to the regular requests to stackdump in Mono.

Questions:

1. We are building on Windows (our .net assemblies + exes), then packaging (creating the native package) on macOS. Do you expect it to work better if fully built on macOS?
2. Is there a way to port a Xamarin.Mac (Cocoa) to .NET Core, even if experimental, we'd love to try.

Just FYI, this is how Plastic on macOS looks like (developing since 2012):

![image](https://user-images.githubusercontent.com/380766/62580935-ee629c80-b8a7-11e9-8118-0bb71dfb216e.png)


https://www.plasticscm.com/gallery#macplastic

**Comment by BrzVlad** [comment]
The dump from 4.4 looks like gc_lock - framework_peer_lock deadlock that was fixed https://github.com/xamarin/xamarin-macios/issues/3943

The 5.14 dump looks completely unrelated and it is not clear what is going on there.

**Comment by psantosl** [comment]
Ok, we are going to try to reproduce with 5.14 again.

**Comment by psantosl** [comment]
Anyone could answer these?

1. We are building on Windows (our .net assemblies + exes), then packaging (creating the native package) on macOS. Do you expect it to work better if fully built on macOS?
2. Is there a way to port a Xamarin.Mac (Cocoa) to .NET Core, even if experimental, we'd love to try.

**Comment by chamons** [comment]
1. In theory that shouldn't matter. In practice, it isn't a combination we've ever tested.
2. Xamarin.Mac integrations with mono in a number of places. There has been discussion of experiments in that area, but I know of nothing concrete to report on.

**Comment by rolfbjarne** [comment]
You'll usually get a better stack trace if you attach lldb:

1. Make the app hang.
2. Find the app's pid (maybe execute something like `ps aux | grep PlasticSCM` in a terminal)
3. Attach lldb to the process in a terminal, and get a stack trace for all threads:

        lldb -p PID
        ...
        (lldb) thread apply all bt

4. Attach the result here.

**Comment by chamons** [comment]
We have not received the requested information.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!
