### ISSUE TITLE
[Category] doesn't work if the assembly is linked

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#6846]
### Steps to Reproduce

Test case: https://github.com/rolfbjarne/TestApp/commits/test-case-6846

Run test case on device (Debug configuration).

```
2019-08-26 09:39:21.219 unifiedtestapp[770:469271] -[NSTaggedPointerString uppercaseStringWithLocaleEx:]: unrecognized selector sent to instance 0xc97b5069e49ad946
2019-08-26 09:39:21.220 unifiedtestapp[770:469271] Xamarin.iOS: Received unhandled ObjectiveC exception: NSInvalidArgumentException -[NSTaggedPointerString uppercaseStringWithLocaleEx:]: unrecognized selector sent to instance 0xc97b5069e49ad946
2019-08-26 09:39:21.266 unifiedtestapp[770:469271] Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: -[NSTaggedPointerString uppercaseStringWithLocaleEx:]: unrecognized selector sent to instance 0xc97b5069e49ad946
Native stack trace:
	0   CoreFoundation                      0x00000001b79159a4 <redacted> + 252
	1   libobjc.A.dylib                     0x00000001b6aee9f8 objc_exception_throw + 56
	2   CoreFoundation                      0x00000001b78321c8 <redacted> + 0
	3   CoreFoundation                      0x00000001b791b1d4 <redacted> + 1408
	4   CoreFoundation                      0x00000001b791ce6c _CF_forwarding_prep_0 + 92
	5   unifiedtestapp                      0x0000000100e2edbc wrapper_managed_to_native_Messaging_IntPtr_objc_msgSend_IntPtr_intptr_intptr_intptr + 236
	6   unifiedtestapp                      0x0000000100e2d4ac AppDelegate_Tapped + 444

```

It works fine if the linker setting is changed to `Link SDK` or `Don't link`.

Original reporter: VSTS #[962321](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/962321)

**Comment by rolfbjarne** [comment]
The problem is that the linker completely removes the class with the `[Category]`.

This means that simply adding a `[Preserve (AllMembers = true)]` attribute to the type is a viable workaround:

```csharp
[Category (typeof (NSString))]
[Preserve (AllMembers = true)]
public static class NSStringExtension {
	[Export ("uppercaseStringWithLocaleEx:")]
	public static string toUpperEx (this NSString s, NSLocale locale)
	{
		return "NSStringExtension.toUpper";
	}
}
```

**Comment by spouliot** [comment]
I don't see this as a bug (more a support/question). There's no reference to the managed symbol so the linker is removing it. In fact the test case is quite similar to reflection usage, which would also require `[Preserve]`.

The same thing could happen in non-category code. It's uncommon because most selectors are virtual so the linker will keep them (in marked subclasses).

**Comment by rolfbjarne** [comment]
@spouliot can't we fix/improve this by simply treat `[Category]` as `[Preserve]` in the linker (like we already do for NSObject subclasses)? I'd say that it's expected that categories are not referenced from managed code.

**Comment by spouliot** [comment]
While it would be possible and easy I don't think it's right thing to do. 

* It happens when the linker is enabled on an assembly. That means the developer (of the library or the application) is looking to reduce the application size more than what we can achieve by default. Preserving more, unused code is counter productive to their goal;

* It's very easy to `[Preserve]` but you can't (at least easily) un-preserve code.

E.g. Using a small feature in a binding project w/lots of categories would become a lot more costly for (existing) applications. The linker is recursive so everything preserved in the category will preserve more code, which preserve more... (iterate a bit) which then tell the native linker to keep more code in the final app :(

* The crash (selector) makes it easy to find what was missing (and easy to add preserve to the code or a xml file). In fact it's even easier than most managed issues (e.g reflection where the stack trace is `Invoke(...)`).

As for `NSObject` subclasses that's a historical decision (before Xamarin) that has its own set of issues. We get complaints about it (got a meeting this week about that). I wanted to change that many years ago but it broke a few things (including every apps because of `UIApplication.Main (args, null, "AppDelegate");`)

**Comment by rolfbjarne** [comment]
> including every apps because of `UIApplication.Main (args, null, "AppDelegate");`

For a [long, long time](https://github.com/xamarin/maccore/commit/adccbf7fcccc9c8cafc614495fbb90493ba025a4) it's been possible to do `UIApplication.Main (args, null, typeof (AppDelegate));`, but we never updated the templates...

> * The crash (selector) makes it easy to find what was missing

There won't be a crash if the category is replacing an existing method (which was the case in the related VSTS issue), you'll just get the behavior of the existing method. It took me a while to figure out what was going on, and I don't think we can expect customers to do so without help.

In any case I've added some documentation about this: https://github.com/xamarin/apple-api-docs/pull/159.

**Comment by spouliot** [comment]
> For a long, long time...

That specific case would have been possible, even trivial with your additional API, to fix. It would still have required every app to update their code :( (with more work we could have detected that case too) but it was not the only reason - only the simplest and so common that I still remembered it without looking back to the code.

But I wish I had (time to) do this, a long time ago :)

> There won't be a crash if the category is replacing an existing method...

That's different from the attached test case and I agree it would be more difficult to debug.

We could get fancy and track type type being extended and see if it (the selector) replaced an API being used - but that will only work if it's used from managed code, which is likely the simplest case.

Still if you expect to change some runtime behaviour _kind of dynamically_, based on not-directly called code presence, then I think adding `[Preserve]` (and some comments) is an appropriate requirement.
