### ISSUE TITLE
Solution will not rebuild

### ISSUE THREAD

**Issue by aperel66** [xamarin/xamarin-macios#7052]
dd

### Steps to Reproduce

1. Rebuild the solution
2. 
3. 

### Expected Behavior
Rebuild Succeeded
### Actual Behavior
Severity	Code	Description	Project	File	Line	Suppression State
Error		Failed to compile the generated registrar code. Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new	GlassGrabIOSApp			

### Environment
![Annotation 2019-09-22 113549](https://user-images.githubusercontent.com/54277456/65390462-2aa16d80-dd2d-11e9-98c5-406c5dff5800.png)

```
```

### Build Logs

Not sure
### Example Project (If Possible)

Nor sure

Not sure

**Comment by rolfbjarne** [comment]
The problem is that your Mac auto-upgraded Xcode to the new Xcode 11, and our current version of Xamarin.iOS is not compatible with Xcode 11.

We'll release a version of Xamarin.iOS that is compatible with Xcode 11 later today. A more immediate solution is to install our preview version of Xamarin.iOS with support for Xcode 11.
