### ISSUE TITLE
xamarin.iOS/MTOUCH: Error MT4109: Failed to compile the generated registrar code. Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new (MT4109) (xamarin.iOS)

### ISSUE THREAD

**Issue by Cloudtrackers** [xamarin/xamarin-macios#7057]
### Steps to Reproduce

1. 
2. 
3. 

### Environment

```
```

**Comment by Cloudtrackers** [comment]
After the updations of xcode getting this error in xamarin forms.

**Comment by rolfbjarne** [comment]
The problem is that your Mac auto-upgraded Xcode to the new Xcode 11, and our current version of Xamarin.iOS is not compatible with Xcode 11.

We'll release a version of Xamarin.iOS that is compatible with Xcode 11 later today. A more immediate solution is to install our preview version of Xamarin.iOS with support for Xcode 11.
