### ISSUE TITLE
Xcode 11.2 FINAL Support

### ISSUE THREAD

**Issue by dalexsoto** [xamarin/xamarin-macios#7349]
Xcode 11.2 Final dropped on October 31st Xamarin prepared support for it and it is due to be released soon. In the meantime if you need need the packages right away feel free to use:

- [xamarin.ios-13.6.0.12.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/xcode11.2/e3c2b406de425d7b757dfb57b852ef4ad39598e3/47/package/notarized/xamarin.ios-13.6.0.12.pkg)
- [xamarin.mac-6.6.0.12.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/xcode11.2/e3c2b406de425d7b757dfb57b852ef4ad39598e3/47/package/notarized/xamarin.mac-6.6.0.12.pkg)

**Comment by joehanna** [comment]
HEADS UP: Latest VS Mac stable channel includes Xamarin iOS 13.6.0.12, which requires Xcode 11.2. However, there is a known critical bug in Xcode 11.2, which is fixed in 11.2.1 (still in beta) but can be downloaded from https://developer.apple.com/download/.  You can't run Xamarin apps on devices built using Xcode 11.2 (works ok in the simulator).

REFERENCES:
https://forums.developer.apple.com/thread/125287
https://forums.developer.apple.com/thread/125274
https://stackoverflow.com/questions/58657087/after-upgrading-to-xcode-11-2-from-xcode-11-1-app-crashes-due-to-uitextlayoutv

**Comment by matteopiccioni** [comment]
> HEADS UP: Latest VS Mac stable channel includes Xamarin iOS 13.6.0.12, which requires Xcode 11.2. However, there is a known critical bug in Xcode 11.2, which is fixed in 11.2.1 (GM Seed but not released) but can be downloaded from https://developer.apple.com/download/. You can't run Xamarin apps on devices built using Xcode 11.2 (works ok in the simulator).
> 
> REFERENCES:
> https://forums.developer.apple.com/thread/125287
> https://forums.developer.apple.com/thread/125274
> https://stackoverflow.com/questions/58657087/after-upgrading-to-xcode-11-2-from-xcode-11-1-app-crashes-due-to-uitextlayoutv

Hello,
uploading ipa using xcrun return me this error:
`ERROR ITMS-90534: "Invalid Toolchain. Your app was built with an unsupported version of Xcode or SDK. If you plan to submit this build to the App Store, make sure you are using the GM version of Xcode 10.1 and the SDK for iOS 12.1 and watchOS 5.1, Xcode 7.1 and the SDK for tvOS 9, or Xcode 6 and the SDK for macOS 10.9 or later. If you are using an Xcode beta version to test your app, make sure you are using the latest supported version. For more information about supported beta versions, view the App Store Connect What's New page (https://developer.apple.com/app-store-connect/whats-new/)."`
Ofc I have all latest stable version of tools

Maybe should I download and try with 11.2.1 version of xcode? 
Thanks

**Comment by chamons** [comment]
These builds are in stable everywhere now.
