### ISSUE TITLE
Interlocked is inefficient when using non-native type

### ISSUE THREAD

**Issue by Therzok** [xamarin/xamarin-macios#7523]
### Steps to Reproduce

1. Look up usages of Interlocked https://github.com/xamarin/xamarin-macios/search?q=interlocked&unscoped_q=interlocked
2. If the receiver is int/long it must match the CPU word size, otherwise the runtime will generate inefficient code 
3. See https://michaelscodingspot.com/array-iteration-vs-parallelism-in-c-net/

The important one using integer types is:
https://github.com/xamarin/xamarin-macios/blob/af9645410f4576d5d7a156e724f029a2002552b4/src/ObjCRuntime/Blocks.cs#L58

The less important ones:

https://github.com/xamarin/xamarin-macios/blob/6f2ebedb74fe8da250c8f53b61ffae2eb86fc711/src/Compression/Compression.cs#L30

https://github.com/xamarin/xamarin-macios/blob/e32731cb3d541dbf96dd1f601fece1511b4f9145/tests/sampletester/ProcessHelper.cs#L18

**Comment by filipnavara** [comment]
I don't think it's inefficient for `int` since that's something that is implemented natively for both 32-bit and 64-bit CPUs. The referenced article talks about 64-bit `long` manipulated using 32-bit code, ie. wider than native type. Even in that case the conclusion about the cause could be wrong because that is also natively implemented in x86 processors, albeit it may result in register pressure that degrades performance.

**Comment by Therzok** [comment]
I've just checked the compiled ASM, and you are right! The generated code is identical.
