### ISSUE TITLE
uikit.uinavigationbar

### ISSUE THREAD

**Issue by Evelinios** [xamarin/xamarin-macios#7994]
### Steps to Reproduce

1. 
2. 
3. 

### Environment

```
```

**Comment by mojazu** [comment]
Not sure about what your problem is since there is not a description, but in my case I am having problems when assigning the Appearance to UINavigationBar on my AppDelegate.cs, nothing is working as expected and the NavigationBar is being loaded with the default appearance it seems.

Everything worked perfectly yesterday and I started having this issue as soon as I updated to **Xamarin.Forms 4.5.0.356** 

This is my AppDelegate.cs on my iOS project.
```
        public override bool FinishedLaunching(UIApplication app, NSDictionary options)
        {
            global::Xamarin.Forms.Forms.Init();
            LoadApplication(new App(new IOSInitializer()));
            SetUpStyles();

            return base.FinishedLaunching(app, options);
        }

        private void SetUpStyles()
        {
            ResourceDictionary res = Xamarin.Forms.Application.Current.Resources;
            UINavigationBar.Appearance.BarTintColor = ((Color)res["PrimaryThemeColor"]).ToUIColor();
            UINavigationBar.Appearance.TintColor = ((Color)res["NavigationBarTextColor"]).ToUIColor();
            UINavigationBar.Appearance.TitleTextAttributes = new UIStringAttributes()
            {
                ForegroundColor = ((Color)res["NavigationBarTextColor"]).ToUIColor(),
                Font = UIFont.BoldSystemFontOfSize((float)res["NavigationBarTitleFontSize"])
            };
        }
```

**Comment by Evelinios** [comment]
This is my issue,Attempting to JIT compile method 'void Xamarin.Forms.Platform.iOS.NavigationRenderer:UpdateBarBackgroundColor ()' while running in aot-only mode.

**Comment by chamons** [comment]
@mojazu - Please file a new issue.

@Evelinios - That sounds like an AOT bug. Please file an issue with the template actually filled out and a sample showing that issue.
