### ISSUE TITLE
CLLocationManager Events and Memory Management

### ISSUE THREAD

**Issue by cosminstirbu** [xamarin/xamarin-macios#8305]
Hello,

Today I've been chasing down some memory leaks and I have found an unexpected behavior that I'd like to confirm with you guys that it's by design and that there aren't some hidden bugs caused by this.

If you create a view controller that has a reference to a `CLLocationManager` instance and registers some methods to `LocationsUpdated` and `UpdatedHeading` events and maybe others (therefore causing a reference cycle) then despite the reference cycle, the view controller is properly deallocated - which is unexpected.

### Steps to Reproduce

1. Checkout iOS sample https://github.com/cosminstirbu/xamarin-memory-demo/tree/cllocationmanager
2. Profile it and notice that `ItemNewViewController` is deallocated (when leaving the screen using Back) when there is an obvious circular reference between `ItemNewViewController` and `_locationManager` due to the events 

### Expected Behavior

`ItemNewViewController` should leak.

### Actual Behavior

`ItemNewViewController` doesn't leak.

### Environment

```
Visual Studio Enterprise 2019 for Mac (Preview)
Version 8.6 Preview (8.6 build 3437)
Installation UUID: c377e901-73d6-47a0-91ce-f5c291a9b0fb
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.21 (d16-6 / a87d63c06)

	Package version: 610000095

Mono Framework MDK
Runtime:
	Mono 6.10.0.95 (2019-12/f2379f2d665) (64-bit)
	Package version: 610000095

Roslyn (Language Service)
3.6.0-2.20164.4+923b4bdbbd33307456464f4c90222a61af278972

NuGet
Version: 5.4.0.6315

.NET Core SDK
SDK: /usr/local/share/dotnet/sdk/3.1.200/Sdks
SDK Versions:
	3.1.200
	3.1.102
	3.1.101
	3.1.100
	3.0.101
	3.0.100
	2.1.701
	2.1.700
	2.1.505
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.10.0/lib/mono/msbuild/Current/bin/Sdks

.NET Core Runtime
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.2
	3.1.1
	3.1.0
	3.0.1
	3.0.0
	2.1.16
	2.1.15
	2.1.14
	2.1.13
	2.1.12
	2.1.11
	2.1.9

Xamarin.Profiler
Version: 1.6.13.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 11.4 (16134)
Build 11E146

Xamarin.Mac
Version: 6.18.0.21 (Visual Studio Enterprise)
Hash: a87d63c06
Branch: d16-6
Build date: 2020-03-02 11:17:04-0500

Xamarin.iOS
Version: 13.18.0.21 (Visual Studio Enterprise)
Hash: a87d63c06
Branch: d16-6
Build date: 2020-03-02 11:17:05-0500

Xamarin.Android
Version: 10.3.0.33 (Visual Studio Enterprise)
Commit: xamarin-android/d16-6/e9fa8c4
Android SDK: /Users/cosminstirbu/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.1 (API level 22)
		7.1 (API level 25)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.5
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: d90665a
Java.Interop: xamarin/java.interop/d16-6@2cab35c
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.31.1@49232bc
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-6@bfb66f3

Microsoft Mobile OpenJDK
Java SDK: /Users/cosminstirbu/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 16.6.0.46
Hash: f6bfa7b
Branch: remotes/origin/d16-6
Build date: 2020-03-13 00:13:30 UTC

Android Device Manager
Version: 16.6.0.75
Hash: 4509c53
Branch: remotes/origin/d16-6
Build date: 2020-03-13 00:13:52 UTC

Xamarin Designer
Version: 16.6.0.267
Hash: fa27dc7ce
Branch: remotes/origin/d16-6
Build date: 2020-03-19 20:26:14 UTC

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Build Information
Release ID: 806003437
Git revision: b6e23a27c18a3e6f8eb620ff1814fb76b3f47921
Build date: 2020-03-20 11:39:40-04
Build branch: release-8.6
Xamarin extensions: b6e23a27c18a3e6f8eb620ff1814fb76b3f47921

Operating System
Mac OS X 10.15.4
Darwin 19.4.0 Darwin Kernel Version 19.4.0
    Wed Mar  4 22:28:40 PST 2020
    root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

Enabled user installed extensions
DeepClean 1.2.5
Straight8's SpecFlow Integration 1.11.3.0
NuGet Package Management Extensions 0.21
Code Distribution Extension 1.1
FileNesting 0.1.2
Code Coverage 2.0-alpha
EssentialsAddin 1.6.4
```

**Comment by cosminstirbu** [comment]
Also, I have a secondary observation, which I guess is by design.

If I set the view controller as a delegate to a MapView via the storyboard the there is no "strong circular reference" in the managed world and the view controller is deallocated as expected (since the circular reference is weak on the Obj-C side).

On the other side if I set the delegate programatically from C#, then the view controller isn't deallocated due to the "strong circular reference" from the managed world.

**Comment by chamons** [comment]
So I reviewed the code in question, and I think some confusion is due to the differences between ObjC's ARC (Automatic Reference Count) and C#'s GC (Garbage Collector).

1.

    // it doesn't leak for LocationsUpdated and UpdatedHeading (when it actually should leak)
In ObjC, having two items have a strong reference to each other will leak, but not necessarily in C#. If no one is referencing the ItemNewViewController instance from a root (or in native code, which we do work to make roots), then it is disposable. The instance variable inside the ItemNewViewController that points to itself is not a problem. 

Being able to do the "right thing" in this case is one of the nice things about GCs.

2. 

     // If you set the delegate from C# then in causes a circular reference, but if you set it from the storyboard, it doesn't.
     // I guess that's expected since the delegate was set only in Obj-C runtime

Yes, this is actually a circular reference between two items and will stay into memory until BOTH are disposable, if ever. 

However, if you set it in storyboard then the ObjC Runtime / you are responsible for the lifetime. I believe it does the right thing here, but you have to be careful.

I want to caution that you need to keep the garbage collector in mind when looking for "leaks". [GC.Collect](https://docs.microsoft.com/en-us/dotnet/api/system.gc.collect?view=netframework-4.8) can be helpful in "forcing" a GC, but the results can sometimes be surprising.

It's a bit overly technical but https://www.mono-project.com/docs/advanced/garbage-collector/sgen/ might have some useful info. https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/ is more windows focused, but also could be useful.

GH issues aren't necessarily the best place for questions, so I'm going to close this, but please reopen if you have concerns or if I'm misunderstood your issue.

**Comment by cosminstirbu** [comment]
I know this isn't an actual issue so thanks for taking the time to look into it.

Related to 1. there seems to be a difference in the way the objects are deallocated for the following two scenarios:

a. A view controller has a reference to a `CLLocationManager` and registers to `LocationsUpdated`. Both objects are collected by the GC when dismissing the view controller.
b. A view controller has a reference to a `UIButton` and registers to `TouchUpInside`. Both objects leak when dismissing the view controller.

I'm assuming that's because of how the events are implemented under the hood:

a. The events exposed `CLLocationManager` are implemented by using an internal `_CLLocationManagerDelegate` to leverage the native [delegate](https://developer.apple.com/documentation/corelocation/cllocationmanager/1423792-delegate) (which is a weak reference in the native world).
b. The events exposed by `UIButton` are implemented by using `Dictionary<EventHandler, Dictionary<UIControlEvent, UIControlEventProxy>> ()` to leverage the native `[addTarget(_:action:for:)](https://developer.apple.com/documentation/uikit/uicontrol/1618259-addtarget)` (which keeps a weak reference to the target in the native world)

I guess I'll need too dig deeper into the source code of Xamarin.iOS.dll to understand why that happens.

**Comment by chamons** [comment]
Let me try to understand/explain:

in a)

View Controller  -> CLLocationManager 
         ^------------------------|

You have a view controller have a reference to a CLLocationManager. When you use the event we create a private CLLocationManagerDelegate that has a reference to the controller so it can call LocationsUpdated.

From the garbage collector's POV, this looks like a a view controller "clump", and since the location manager doesn't outlive the view controller they can die at the same time. No leak. if the location manager came from other places and had a different lifetime, different story.

b. View Controller -> UI Button

View Controller  -> UI Button <-------- Visual Tree 
         ^------------------------|


You have a view controller have a reference to a UIButton When you use the event we create a private UIButtonDelegate that has a reference to the controller so it can call TouchUpInside. This is very different because the UIButton itself is in the visual tree. That means the visual tree can have references to it as well, so from our garbage collector's perspective it's used in two different lifetimes.

A bit of general advice:

- The C# events are easy to use, but getting lifetime correctly is hard. Consider implementing interfaces and using the "Delegate/WeakDelegate" properties for callbacks. They are a lot easier to get right consistently, without leaks.

**Comment by cosminstirbu** [comment]
The explanations for point a) and b) make sense, thank you.

I'd say that even with "Delegate/WeakDelegate" we should be cautious (depending on how they are set), because in the same sample I've linked I have the following example(s):

c. A view controller has a reference (outlet) to a MapView and the delegate of the MapView is set via the storyboard. Both objects are collected by the GC when dismissing the view controller (which is expected because there is no reference from the managed MapView to the managed view controller).
d. A view controller has a reference (outlet) to a MapView and the "Delegate" is set programatically in ViewDidLoad in C#. Both objects leak when dismissing the view controller (which I think happens because besides setting the native view controller as a weak delegate to the native MapView, the managed MapView also keeps a reference to the managed view controller).

So I would expand your advice and I would say that in general we should unsubscribe from events, use [Weak] / WeakReference where possible and null-out  "Delegate/WeakDelegate" and other references that are not under our control. (most of this advice is captured in the docs which is nice).
