### ISSUE TITLE
[CoreMIDI] Device name is empty

### ISSUE THREAD

**Issue by defcon8** [xamarin/xamarin-macios#8373]
Hi,

I noticed that CoreMIDI does not return the names of the MIDI devices, consider the following repro-code:

```
Console.WriteLine("CoreMIDI: Enumerating MIDI Destinations..");

var count = 0;
for(UInt16 deviceIndex = 0; deviceIndex < Midi.DeviceCount; deviceIndex++)
{
    MidiDevice device = Midi.GetDevice(deviceIndex);
    Console.WriteLine(count + ": " + device.Name);
    count++;
}

Console.WriteLine("CoreMIDI: Total MIDI Destinations: " + count);
```

Result (device.Name did not return anything):

<img width="317" alt="Schermafbeelding 2020-04-13 om 21 42 28" src="https://user-images.githubusercontent.com/3636349/79154358-af3e0100-7dcf-11ea-8d37-7d0ccc181c75.png">

**MacOS:** 10.15.3 Catalina
**Mono:** Mono JIT compiler version 6.8.0.123 (2019-10/1d0d939dc30 Thu Mar 12 23:19:08 EDT 2020)
**Xamarin.Mac:** 6.16.0.11; git-rev-head:aa73e412540e0c3b2a4f11b1c76eca2db77912f8; git-branch:d16-5-xcode11.4)

Seems like a bug or am I missing something?

Kind regards,
Bastiaan

**Comment by chamons** [comment]
I ran this locally and got:

**Comment by defcon8** [comment]
@chamons 
Hi Chris, I really appreciate your time and findings. In my situation both the _Name_ and _DisplayName_ properties have the value _null_ like most of the properties As you can see here, when I break at the first iteration.

<img width="1000" alt="Schermafbeelding 2020-04-15 om 22 51 34" src="https://user-images.githubusercontent.com/3636349/79387777-89019800-7f6c-11ea-9c30-642e2e1b8930.png">

And also in the Midi device panel of MacOS shows 2 devices with names.

<img width="529" alt="Schermafbeelding 2020-04-15 om 22 56 19" src="https://user-images.githubusercontent.com/3636349/79387792-91f26980-7f6c-11ea-9a31-37ce6a6fc5dc.png">

So I don't quite understand what is happening here.. I will do some more debugging a.s.a.p...

**Comment by chamons** [comment]
Given the fact that CoreMidi is CoreFoundation, I could also see Apple returning semi-initialized things because you didn't register/setup correctly.

There isn't much documentation I could find, but http://goodliffe.blogspot.com/2010/10/using-coremidi-in-ios-example.html looks interesting.

**Comment by defcon8** [comment]
@chamons 
Thanks Chris, I also suspect something not being initialized property. However I find it quite noticeable that I am in fact able to send and receive MIDI. So some parts work.

Btw. do you know where I can find the latest (Mono) build/binaires of Xamarin Mac?

**Comment by chamons** [comment]
Released Xamarin.Mac builds are linked on the [README.md](https://github.com/xamarin/xamarin-macios/blob/master/README.md). 

If you want something from a development branch, see [the documentation](https://github.com/xamarin/xamarin-macios/wiki#downloading-a-build).

If you are using a Xamarin.Mac project, which references Xamarin.Mac.CSharp.targets at the bottom, then that should be handled for you. If not, you are running a custom configuration and then things get complicated. :)

**Comment by whitneyschmidt** [comment]
@defcon8 I'm closing this issue as it is over a month old.

If you run into the same CoreMIDI weirdness, feel free to reopen. 

For future bugs, you know where to find us :)

**Comment by mbmleone** [comment]
In my Xamarin.Mac project I'm seeing the same issue.
@defcon8 did you find find a solution for the issue?

**Comment by maestrocoder** [comment]
@whitneyschmidt Request re-open. This is still an issue in some use case for us.

We also get null on Model property.

However, it is only on first time run of the application, and only if the midi device is unplugged before reading from CoreMidi.Midi.GetDevice.  

So imagine a first time user of an application, they install the application but do not know or have their keyboard plugged in or turned on, so they run the program, get a notice that says ""no keyboard found please check" they realize its not plugged in or powered on, they plug in or power on... sadly this bug happens and because Model property is null in Xamarin MAC / CoreMIDI weirdness, no keyboard can be added to the list because even though we can respond to the DeviceAdded event, we cannot get a name for the device.  

We have tried CoreMidi.Midi.Restart() but still any call to GetDevice(int) has Model = null, which is a bug.

If we close the application and start it with the device powered on and plugged in, it works fine.

Is it possible that someone did not test the edge case and since the MAC OS Midi Studio/ Audio MIDI Setup, shows the device illuminated when we toggle power on/plugged in, it seems more probably this is a Microsoft SDK bug and not an IOS issue?  I assert this because Xamarin.MAC cannot properly use the MidiEntity with Model property is null while MAC OS appears to handle it just fine and highlight the correct device, so please re-consider this as an active bug, it's live in our production.

![image](https://user-images.githubusercontent.com/2679210/101283778-810f9600-3791-11eb-909f-adb0b8b0254c.png)

and in that same moment, MAC OS shows it has device added (V25 in pic below) and active in Audio MIDI Setup

![image](https://user-images.githubusercontent.com/2679210/101283860-02ffbf00-3792-11eb-905c-007f8efd86fb.png)

So with Model = null, we cannot put any name into the input dropdown, or can you kindly suggest how we can overcome getting the name, if Model property is null?

![image](https://user-images.githubusercontent.com/2679210/101283927-53771c80-3792-11eb-8a74-930a88f9fe99.png)

I can link you production build to run so you can realize this is a real bug?

**Comment by rolfbjarne** [comment]
There isn't much to our bindings for CoreMidi, they basically just call straight into macOS' CoreMIDI framework, so it seems strange that there would be a bug in the bindings that manifests in this particular way. That said, I'd be delighted to be proven wrong :) 

Could you please attach a sample project that shows your code to listen for added devices, and how you try to get information about them? That way we can be sure to run the same code when testing it.

**Comment by spouliot** [comment]
I'm closing the issue since we have not received the requested sample project in the past month.
This issue can be re-opened if/when a sample test case is provided. Thanks!
