### ISSUE TITLE
Running introspection tests on old macOS bots for PR

### ISSUE THREAD

**Issue by spouliot** [xamarin/xamarin-macios#8437]
# Situation

Adding older API is made using the documented (web, headers) availability version, which is often incorrect. This leads to test failures after the merge (and a new PR to fix it).

# Solution

We have internal bots with older macOS versions that runs the tests - after the merge. Those are bots are (or were) not in very high demand, so they could be used to tests PR. What's missing is a public-to-private trigger.

Minimally introspection, but other tests could be enabled too

**Comment by rolfbjarne** [comment]
The tests we run on older macOS bots don't take long to run (4-5 minutes), so running all of them for PRs won't be a problem.

One way to get around the public-to-private trigger is to move the whole older macOS setup to a new Azure Devops, and run it for both normal commits in the origin repo and pull requests (and remove it from Jenkins).

Pros:

* Should be fairly simple and self-contained to implement.
* It's a step in the right direction (towards Azure Devops).

Cons:

* There would be two reporting comments on PRs/commits instead of one.
* The Azure Devops macOS agent requires macOS 10.12+, and we need to run on macOS 10.9, which means we can't run the agent on at least some of the older macOS bots. One way to get around this would be to have the agent (and pipeline) run on a single newer bot, which uses ssh to copy and run the tests on each older macOS bot.

**Comment by rolfbjarne** [comment]
We've implemented this.
