### ISSUE TITLE
tvOS AVMetadataItem.set_MetadataIdentifier throws NotImplementedException

### ISSUE THREAD

**Issue by dgyesbreghs** [xamarin/xamarin-macios#8480]
### Steps to Reproduce

1. Create an new AVMetadataItem object
2. Set the `MetadataIdentifier`
3. Launch app
4. Exception is triggered

### Expected Behavior

`set_MetadataIdentifier` is implemented.

### Actual Behavior

`MetadataIdentifier` is read only.

### Environment

https://gist.github.com/dgyesbreghs/0a455aaefb2b9ff309774c46fe63c5ec

### Build Logs

https://gist.github.com/dgyesbreghs/c47e04a4cebda87f1279e915425dd526

### Example Project (If Possible)

[Sample.zip](https://github.com/xamarin/xamarin-macios/files/4556978/Sample.zip)

**Comment by rolfbjarne** [comment]
The `AVMetadataItem` class is immutable, if you want a mutable version you need to create an instance of the `AVMutableMetadataItem` class.

The reason the setter is there in the first place is because the property is virtual, and the `AVMutableMetadataItem` class provides both a getter and a setter, which it couldn't do unless the base class also provided a getter and a setter.
