### ISSUE TITLE
NSTextField: Formatter does not work when EditingEnded is assigned

### ISSUE THREAD

**Issue by GT85** [xamarin/xamarin-macios#8871]
### Steps to Reproduce

1. Create a new Cocoa app
2. Add it the code below
3. Run the app

### Expected Behavior
Do not allow to quit Tbx1 when it contains a letter (NSNumberFormatter does not accept letters)
### Actual Behavior
Formatter seems to be ignored
### Environment
MacOS 10.14.6

```
=== Visual Studio Community 2019 for Mac ===

Version 8.6.4 (build 14)
Installation UUID: 82cedb76-2ce7-439d-9752-1fa6fe3a5e1e
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 610000104

=== Mono Framework MDK ===

Runtime:
	Mono 6.10.0.104 (2019-12/5d03a6fe116) (64-bit)
	Package version: 610000104

=== Roslyn (Language Service) ===

3.6.0-3.20210.9+4eafdcb1bcbd8d3573f2ba6065e56d9b9ce4f8a3

=== NuGet ===

Version : 5.6.0.6591

=== Kit SDK .NET Core ===

SDK : /usr/local/share/dotnet/sdk/3.1.301/Sdks
Versions du SDK :
	3.1.301
	3.1.300
	3.1.200
	3.1.102
SDK MSBuild : /Library/Frameworks/Mono.framework/Versions/6.10.0/lib/mono/msbuild/Current/bin/Sdks

=== Runtime .NET Core ===

Runtime : /usr/local/share/dotnet/dotnet
Versions du runtime :
	3.1.5
	3.1.4
	3.1.2
	2.1.19
	2.1.18
	2.1.17
	2.1.16

=== Xamarin.Profiler ===

Version : 1.6.13.11
Emplacement : /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version : 11

=== Xamarin Designer ===

Version: 16.6.0.329
Hash: d4f8bcd13
Branch: remotes/origin/d16-6
Build date: 2020-04-24 02:16:02 UTC

=== Apple Developer Tools ===

Xcode 11.3.1 (15715)
Build 11C504

=== Xamarin.Mac ===

Version: 6.18.2.1 (Visual Studio Community)
Hash: 29c4ea731
Branch: d16-6
Build date: 2020-05-26 17:03:04-0400

=== Xamarin.iOS ===

Version: 13.18.2.1 (Visual Studio Community)
Hash: 29c4ea731
Branch: d16-6
Build date: 2020-05-26 17:03:05-0400

=== Xamarin.Android ===

Non installé

=== Microsoft OpenJDK for Mobile ===

Java SDK: Introuvable

Code EPL d'Android Designer disponible ici :
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.6.0.50
Hash: 5901879
Branch: remotes/origin/d16-6
Build date: 2020-05-15 00:43:06 UTC

=== Android Device Manager ===

Version: 16.6.0.95
Hash: 45d17b5
Branch: remotes/origin/d16-6
Build date: 2020-05-15 00:43:26 UTC

=== Build Information ===

Release ID: 806040014
Git revision: b22fa17f4309e67d2f254d93f02d17613cf6ef6c
Build date: 2020-06-15 10:43:44-04
Build branch: release-8.6
Xamarin extensions: b22fa17f4309e67d2f254d93f02d17613cf6ef6c

=== Operating System ===

Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Mon Apr 27 20:09:39 PDT 2020
    root:xnu-4903.278.35~1/RELEASE_X86_64 x86_64

```

### Example Project (If Possible)

using AppKit;
using CoreGraphics;
using Foundation;
using System;

namespace NSTextFieldValidation
{
public partial class ViewController : NSViewController
{
NSTextField Tbx1, Tbx2;
public ViewController(IntPtr handle) : base(handle)
{
}

    public override void ViewDidLoad()
    {
        base.ViewDidLoad();

        var fm = new NSNumberFormatter { Maximum = 999, Minimum = 0 };
        Tbx1 = new NSTextField(new CGRect(10, 50, 100, 30));
        View.AddSubview(Tbx1);
        Tbx1.PlaceholderString = "Tbx1";
        Tbx1.Formatter = fm;
        //Tbx1.EditingEnded += Tbx1_EditingEnded;

        Tbx2 = new NSTextField(new CGRect(150, 50, 100, 30));
        View.AddSubview(Tbx2);
        Tbx2.PlaceholderString = "Tbx2";
        Tbx2.Formatter = fm;
        Tbx2.EditingEnded += Tbx2_EditingEnded;
    }

    private void Tbx1_EditingEnded(object sender, EventArgs e)
    { Console.WriteLine("Tbx1"); }

    private void Tbx2_EditingEnded(object sender, EventArgs e)
    { Console.WriteLine("Tbx2"); }
}
}

**Comment by chamons** [comment]
I did some research, and this turns out to not be a bug. 

## Short version:

Using C# events defaults the `DidFailToFormatString` method to return true. That overrides the default logic that checks NSNumberFormatter, and it gets ignored.

This is one of **many reasons** you should use the actual delegate class support, and not the C# events.

Example Fixed Code:
```
	public partial class ViewController : NSViewController, INSTextFieldDelegate
	{
		public ViewController (IntPtr handle) : base (handle)
		{
		}

	        NSTextField Tbx1, Tbx2;
        	public override void ViewDidLoad ()
        	{
	            base.ViewDidLoad ();

	            var fm = new NSNumberFormatter { Maximum = 999, Minimum = 0 };
	            Tbx1 = new NSTextField (new CGRect (10, 50, 100, 30));
	            View.AddSubview (Tbx1);
	            Tbx1.PlaceholderString = "Tbx1";
	            Tbx1.Formatter = fm;

        	    Tbx2 = new NSTextField (new CGRect (150, 50, 100, 30));
	            View.AddSubview (Tbx2);
        	    Tbx2.PlaceholderString = "Tbx2";
        	    Tbx2.Formatter = fm;
        	    Tbx2.Delegate = this;
        	}

        	[Export ("controlTextDidEndEditing:")]
        	public void EditingEnded (NSNotification notification)
        	{
        	    Console.WriteLine ("Done");
        	}
	}
```

See the documentation for more details:

- https://docs.microsoft.com/en-us/xamarin/mac/app-fundamentals/patterns#data-source--delegate--subclassing
- https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/delegates-protocols-and-events
- https://docs.microsoft.com/en-us/xamarin/mac/app-fundamentals/mac-apis


## Technical Details 

Here's the [code](https://gist.github.com/chamons/3483c5daf2702d87c5d1811c58c3925a) if you want to follow along. 

I first converted the sample to Objective-C, and validated that it works there.

So there must be some difference in samples, or a bug in Xamarin.Mac. Reviewing the samples again led me to the C# events in use.

Under the hood, use of those events create a C# delegate and assigns it to listen for each event you may attach yourself to. 

Unfortuntely, this means we respond to every selector the protocol supplies (else we couldn't listen and bubble up if you subscribed), and many of them require returning a bool/array.

Converting the sample to more closely match my Obj-C version, with a NSTextFieldDelegate and it started working. I then started overriding methods and returning the default value until I figured out which one was at fault.

We handle this [in our bindings](https://github.com/xamarin/xamarin-macios/blob/main/src/appkit.cs#L10719) with the `DefaultValue (true)]`, which means by default if not subscribed to, return true. 

We can't return false here or the standard case would of no formatter would start breaking.

Thus, if you want to use a NSTextField with a Formatter, you need to use the actual Delegate for events.
