### ISSUE TITLE
No teams in dropdown for auto provisioning

### ISSUE THREAD

**Issue by airpaulg** [xamarin/xamarin-macios#8936]
### Steps to Reproduce

1. Get a paid Apple Developer Account (Individual)
2. Add the account to VS for Mac 8.6.2 (build 6)
3. Go to Info.plist > Application tab

### Expected Behavior
See teams in the dropdown

### Actual Behavior
No teams in the dropdown. See thread [here](https://forums.xamarin.com/discussion/comment/414930#Comment_414930) for details. I did confirm that I see the team in XCode. 

### Environment
macOS Catalina Version 10.15.5 (19F101). MacBook Air (13-inch Early 2015). VS for Mac 8.6.2 (build 6)

```
```

### Example Project (If Possible)

> VS bug [#1145681](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1145681), VS bug [#1149661](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1149661)

**Comment by emaf** [comment]
Hi @airpaulgl,
I just wanted to confirm if you're still facing this problem since this issue was closed by mistake a couple of weeks ago.

Thanks!

**Comment by airpaulg** [comment]
I actually gave up on the project - it was too cumbersome to set it up.

**Comment by terriblememory** [comment]
In case it helps I just ran into the same issue. In my case it seemed to happen because my developer account had just expired and I had to renew it on the developer.apple.com site and it takes around 30 minutes after you have renewed before the developer account is full provisioned - this is visible on the Apple site too, some pages don't work properly for a while after you renew. I suspect the same would be true of new accounts.

Anyway I was left in a state where Visual Studio showed my Apple ID but no teams. To make things worse I was also unable to remove my Apple ID with the "Remove Account" button (it was greyed out). To fix this I tracked down the place where VS was storing these details and found it in ~/Library/VisualStudio/8.7/DeveloperStorage8.7.json. I opened the json file and sure enough there were my Apple ID details with an empty teams array. I just deleted the line, relaunched VS and re-added my Apple ID. This time it worked.
