### ISSUE TITLE
App crash on launch

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-macios#9282]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1102532/app-crash-on-launch.html)._

---
With the latest Xamarin.Forms 4.7 in combination with the latest VS for Mac Stable version, my app always crashes at launch (no other change involved, it works with Forms 4.6 without any problem and did work with 4.7 as well before the latest update). This crash only happens on Release Build while Debug runs fine. 

The only message I get when trying to run this app in release is the following: 
dyld: Library not loaded: @rpath/Mono.framework/Mono
  Referenced from: /Users/sebastian/Library/Developer/CoreSimulator/Devices/F9AECBD1-5630-4236-99BF-DD72415098E2/data/Containers/Bundle/Application/BBC8B3D3-6D9C-4968-A5C3-CD0766F3AF8C/MyApp.iOS.app/BreathCompanion.iOS
  Reason: image not found

---
#### Visual Studio Feedback System on 7/5/2020, 11:03 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by PureWeen** [comment]
@rolfbjarne mentioned that this look like a Xamarin.iOS bug so I'm moving here for now

But, not sure if they'll be able to pin it down without a reproduction

**Comment by rolfbjarne** [comment]
> But, not sure if they'll be able to pin it down without a reproduction

Yes, we'll need a test project to reproduce this in order to fix it.

**Comment by Sebastian1989101** [comment]
This project does not 100% recreate the base issue but it shows already that the widget is not submitted to the device in a release build to a device. I'm not sure why it does not crash in this case like my real app does but it already shows that it is getting removed. Btw. this is with a fresh new project so I don't know why you need a test project if this can be recreated with the a new fresh project... 
[XamarinIssue9282.zip](https://github.com/xamarin/xamarin-macios/files/5046213/XamarinIssue9282.zip)

**Comment by rolfbjarne** [comment]
> This project does not 100% recreate the base issue but it shows already that the widget is not submitted to the device in a release build to a device.

I don't quite understand the behavior you're seeing. Do you mean that the today extension doesn't show up in the list of today extensions on the device?

> I'm not sure why it does not crash in this case like my real app
> Btw. this is with a fresh new project so I don't know why you need a test project if this can be recreated with the a new fresh project...

We ask for a test project that can be used to reproduce the reported issue, because it's very common that there's something else going on (according to yourself it's not possible to reproduce the reported crash using a new fresh project), and then there's a lot of wasted time on both sides going back and forth trying to re-create the exact conditions that trigger the problem.

> XamarinIssue9282.zip

I just tried this project, and both the extension and the app showed up when executed in release mode.

Then I upgraded the projects to Xamarin.Forms v4.7.0.1260, but both the app and the extension continued to work fine.

**Comment by Sebastian1989101** [comment]
@rolfbjarne I tested it with this project on 3 devices - all the same. The today extension is not included in a release build on a device (it works on the simulator for some reason). I also asked in my team others to test it and so far it is the same for all 5 who tested with it yet. The today extension is always just not commited to the device (3D-Touch / Force Touch just makes the background blur and wiggle once and the today extension is not accessable on the widget page). I still don't know why this app does not crash as our real app does but it seems like the today extension is just removed there as well. 

All who tested it from my team are using the latest stable release of Visual Studio for Mac as of today.

**Comment by rolfbjarne** [comment]
@Sebastian1989101 one thing you can do to narrow it down is to compare the build options between Debug and Release (the Build/iOS* project option pages), and try to figure out which option causes the project to fail (either by making the Debug configuration look like the Release configuration one option at a time, or the other way around).

**Comment by donaldashworth** [comment]
What's going on with this?  I have had the same problem after upgrading to Xamarin 4.8.  After upgrading, suddenly I began receiving the iOS depreciated UIWebView warning from App Store Connect.  After finding zero help on this I opted to change a few compilation options until I was able to create a warning-less build...and then this happens when I switch to "Link All" instead of "Link Framework SDKs Only".

I got Xamm'ed twice in one day.  A new record.

In all seriousness, I have never seen so many problems with a technology.  Russian Roulette would render better results.

**Comment by donaldashworth** [comment]
These additional mtouch arguments ridded the App Store Connect depreciated UIWebView warning...

--optimize=experimental-xforms-product-type --optimize=+force-rejected-types-removal

**Comment by donaldashworth** [comment]
Sadly, I just discovered this causes an app crash when my UIWebView screen is accessed.

**Comment by rolfbjarne** [comment]
@donaldashworth I'm sorry you're having such a hard time with out product. From what I understand you were able to find a solution to the UIWebView warning, but your app is still crashing? If that's the case, please open a new issue and describe your the problem there, since it might be something different that what's reported here, and having two separate problems in a single issue will lead to a lot of unnecessary confusion.

**Comment by Sebastian1989101** [comment]
@donaldashworth This issue is related to the today extension in iOS. The app crashes right away when a today extension is included. If you still use a UIWebView you should switch to a WkWebView because UIWebView is obsolete.

**Comment by donaldashworth** [comment]
We are Xamarin.Forms.WebView … nothing exotic going on.  When using Xarmin 3.3.1 we encountered this App Store Connect warning.  We develop on a Windows 10 PC Professional connecting to a MacBook Pro and were advised to use mtouch arguments “--optimize=experimental-xforms-product-type" in our Xamarin iOS project.

This muted the App Store Connect warning message until recently upgrading to Xamarin 4.8.0 in which the message returned, this time with a drop dead date of December 2020.

Nothing in our code has changed on the two screens we have that use Xamarin.Forms.WebView.

We are not using “UIWebView” by choice.  Its usage is embedded in Xamarin.Forms.WebView.  WebView is the only wed view available in Xamrin.Forms…no WkWebView. The class, itself, is not marked depreciated or obsolete (see below).

With all of this said, Xamarin 4.8 broke a few things for us, this warning is one of them.


namespace Xamarin.Forms
{
    //
    // Summary:
    //     A Xamarin.Forms.View that presents HTML content.
    //
    // Remarks:
    //     The following example shows a basic use.
    [RenderWith(typeof(_WebViewRenderer))]
    public class WebView : View, IWebViewController, IViewController, IVisualElementController, IElementController, IElementConfiguration<WebView>

**Comment by tj-devel709** [comment]
We have not received the requested information.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!
