### ISSUE TITLE
mtouch --optimize multiple options

### ISSUE THREAD

**Issue by bijington** [xamarin/xamarin-macios#9355]
To be clear I am not raising a real issue but more asking for direction as I am unable to find documentation that covers this. Also sorry if this is not the right place for this.

I currently have an app that makes use of the `mtouch` extra arguments option in Visual Studio. We use it based on recommendations from a framework that we consume (you can see it below).

> ```--optimize=-remove-dynamic-registrar -gcc_flags "-L${ProjectDir}/libs/native -lvpxfm-iOS -lopusfm-iOS -lyuvfm-iOS -force_load ${ProjectDir}/libs/native/libvpxfm-iOS.a -force_load ${ProjectDir}/libs/native/libopusfm-iOS.a -force_load ${ProjectDir}/libs/native/libyuvfm-iOS.a"```

Now with the `UIWebView` deprecated issue (yes we have put it off for a while as we have been releasing updates to existing apps) is now causing us an issue with attempting to release a new app.

As per this Microsoft blog post at: https://devblogs.microsoft.com/xamarin/uiwebview-deprecation-xamarin-forms/ we have attempted to include this in the `--optimize` switch. Sadly whatever we try seems to result either in a build error or an error when uploading to the App Store.

What is the correct way to include more options in the `--optimize` switch?

I have tried:

1. Results in build failure:

**Cannot resolve reference: emove-dynamic-registrar (MT2002).** This looks like the info is not correctly formed.

> ```--optimize=experimental-xforms-product-type -remove-dynamic-registrar -gcc_flags "-L${ProjectDir}/libs/native -lvpxfm-iOS -lopusfm-iOS -lyuvfm-iOS -force_load ${ProjectDir}/libs/native/libvpxfm-iOS.a -force_load ${ProjectDir}/libs/native/libopusfm-iOS.a -force_load ${ProjectDir}/libs/native/libyuvfm-iOS.a"```

2. Compiles but fails to upload:

> ```--optimize=experimental-xforms-product-type -optimize=-remove-dynamic-registrar -gcc_flags "-L${ProjectDir}/libs/native -lvpxfm-iOS -lopusfm-iOS -lyuvfm-iOS -force_load ${ProjectDir}/libs/native/libvpxfm-iOS.a -force_load ${ProjectDir}/libs/native/libopusfm-iOS.a -force_load ${ProjectDir}/libs/native/libyuvfm-iOS.a"```

**Comment by spouliot** [comment]
On a terminal you can do
```
/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch --help
```
and it will tell you all options and how to use them.

In general you can use options like `--optimize` multiple times (your 2nd attempt) or separate them with commas (`,`), e.g.
```
--optimize=experimental-xforms-product-type,-remove-dynamic-registrar
```

What happens, in four first attempt, is that the `-r` (first part of `-remove-dynamic-registrar`) is confused with the `-r` option to add a reference. That's why you get an error that `emove-dynamic-registrar` could not be found.

Also with the latest XI stable `--optimize=experimental-xforms-product-type` is a no-op, IOW it's always true (and not an experiment anymore). 

Sadly it also _seems_ to be broken (under investigation), at least it does not do what it did before (removing `UIWebView`) but there can be different reasons from that (it must be _link'able_). To be clear that option was not to remove `UIWebView` but to allow the linker to remove more things from Xamarin.Forms (and treat that assembly like we would treat `Xamarin.iOS.dll`). That made it possible (at least back then) to remove `UIWebView` from most XF applications that did not require it elsewhere.

You can try the **nuclear** option `--optimize=force-rejected-types-removal`. Unlike the previous one, where the linker does a _normal_ job on _product_ (not user) code, this option will remove **managed** (only) references to `UIWebView`, even if it's used (which means code will break, throw or crash if you try to execute something that needs `UIWebView`).

This should fix all references to `UIWebView` unless they come from a **native** library/framework that your application includes.

>  but fails to upload:

You'll need to provide additional details about that failure.

**Comment by bijington** [comment]
@spouliot great thank you for the in depth response!

I think I will play around with the nuclear option for now then as we really have no need to use `UIWebView`.

> but fails to upload:

Sorry this is a little bit of Chinese whispers at this stage. A dev on my team gave me that much so far. I will attempt to dig deeper and see what we get back from Apple.

**Comment by bijington** [comment]
@spouliot I believe you have answered my original question and I think it is safe to ignore the Apple rejection statement as it is likely an issue on our end. Feel free to close this unless you think there is a reason to keep it open.

**Comment by bijington** [comment]
Just to confirm the rejection (failed upload) came about because of a corrupted `Info.plist` file.

**Comment by spouliot** [comment]
@bijington thanks for confirming!
