### ISSUE TITLE
iOS 14 Streaming using AVPlayer only has sound in the first second

### ISSUE THREAD

**Issue by motoko89** [xamarin/xamarin-macios#9435]
### Steps to Reproduce

1. run on real iOS 14 beta device https://github.com/motoko89/test-ios14-bg
2. wait a bit for AVPlayer to load the URL
3. hit Play

### Expected Behavior

Streaming audio is played continuously with sound

### Actual Behavior

Only the first second has sound

### Environment

I'm on Big Sur 20A5354i and my phone has the latest iOS 14 beta 5

=== Visual Studio Enterprise 2019 for Mac ===

Version 8.7.2 (build 9)
Installation UUID: 257fe6ec-087a-49a4-b31c-0204ff79fe4e
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000090

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.90 (2020-02/d3daacdaa80) (64-bit)
	Package version: 612000090

=== Roslyn (Language Service) ===

3.7.0-6.20371.12+917b9dfae12e3b6cb266a3c062fb20a1e9d5fb06

=== NuGet ===

Version: 5.7.0.6702

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.401/Sdks
SDK Versions:
	3.1.401
	3.1.302
	3.0.103
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.7
	3.1.6
	3.0.3
	2.1.21
	2.1.20

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.0 (17210.1)
Build 12A8189h

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 13.99.0.179 (Visual Studio Enterprise)
Hash: 8abd3ebbc
Branch: xcode12
Build date: 2020-08-12 21:56:11-0400

=== Xamarin Designer ===

Version: 16.7.0.492
Hash: f5afe667d
Branch: remotes/origin/d16-7-vsmac
Build date: 2020-07-10 18:42:54 UTC

=== Xamarin.Android ===

Version: 11.0.0.3 (Visual Studio Enterprise)
Commit: xamarin-android/d16-7/aca845b
Android SDK: /Users/admin/Library/Android/sdk
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: 83105ba
Java.Interop: xamarin/java.interop/d16-7@1f3388a
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@017078f

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/admin/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.7.0.13
Hash: 8380518
Branch: remotes/origin/dev/jmt/d16-7readconfig~2
Build date: 2020-07-23 22:38:02 UTC

=== Android Device Manager ===

Version: 16.7.0.18
Hash: 4b44bc1
Branch: remotes/origin/d16-7
Build date: 2020-07-23 22:38:26 UTC

=== Build Information ===

Release ID: 807020009
Git revision: 76b8ecb8cde5f8fc9347bd87919c303832633e50
Build date: 2020-08-13 09:10:10-04
Build branch: merge
Xamarin extensions: 76b8ecb8cde5f8fc9347bd87919c303832633e50

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.0.0 Darwin Kernel Version 20.0.0
    Fri Aug 14 00:25:13 PDT 2020
    root:xnu-7195.40.44.151.1~4/RELEASE_X86_64 x86_64

```
```

**Comment by whitneyschmidt** [comment]
@motoko89 Thank you for your feedback and patience!

A few questions:

1. Does playback only fail on device or does it also fail on the simulator?
2. In the past, with older OSX or older VS for Mac, did playback work correctly? If it did, then this is likely a regression.
3. If it's possible to recreate the project in Xcode using ObjC or Swift, do you encounter the same issue? If this is the case, then it's possible this is an Apple bug.

We look forward to hearing back from you.

**Comment by whitneyschmidt** [comment]
I was able to reproduce this behavior locally on OSX Catalina with VSMac 8.7.5. However, it's not evident that the issue is related to Xamarin specifically.

The broader developer community would be the best and quickest place for additional troubleshooting help on this issue.
Posting a question on Stack Overflow [0] or the Xamarin Forums [1][2] would be the best next step.

[0] https://stackoverflow.com/questions/tagged/xamarin
[1] https://forums.xamarin.com/categories/ios
[2] https://forums.xamarin.com/categories/mac

(Investigation by the Xamarin team in the bug tracker for an issue like this would usually require that the reporter include additional background info to hint that Xamarin is behaving differently compared to Xcode.)

**Comment by motoko89** [comment]
So you were able to reproduce the issue but considered that no evidence?

**Comment by whitneyschmidt** [comment]
@motoko89 One challenge we face when triaging issues in the SDK is that they could be:

- A bug in the Xamarin specific binding or runtime code
- A bug in Apple's implementation itself
- A subtle mis-use of the API in question, which is triggering undefined behavior in Apple's implementation. 

Only the first category actually belong as issues here, thought sometimes it is hard to tell which a given issue actually is.

Historically Apple’s audio APIs are some of the most difficult to correctly use, and many audio issues end up being API misuse.

A second complicating factor here is that iOS 14 beta’s have had made more than a few sharp edges, and the bug was a bit unclear if this specific issue was introduced by iOS 14 or not.

Looking back at the issue more closely, it may have been closed a bit early, but we need more information to continue.

1. Under what circumstances does the failure occur? Does it fail with iOS 13 / Xcode 11.x? Only with the beta?
2. Would it be possible to trim your sample audio code into a more concise version?

If this fails only on iOS 14, it is very likely a bug with Apple, and the next step would be reproducing your sample in Objective C to compare behavior. This is dramatically simpler with a smaller sample.

I expect however that this is not a Xamarin bug, which is why I pointed you to the wider developer community.  We are not specialists with the audio APIs, and there may be a simpler API or set of calls you can make to solve your problem and bypass this completely.

**Comment by motoko89** [comment]
@whitneyschmidt I got back to non beta and the issue went away for a while but it's back again. I have created a Swift sample at https://github.com/motoko89/test-ios14-bg/tree/master/TestApp and a Xamarin iOS app at https://github.com/motoko89/test-ios14-bg/tree/master/TestNative. The 2 projects are equivalent, AVPlayer streaming the same remote URL.

The Xamarin iOS stops working after a few seconds but I can still see progress observer updated

This is Catalina 10.15.7 Xcode Version 12.1 (12A7403). Both runs on the same simulator

Can you please take a look at this?

=== Visual Studio Enterprise 2019 for Mac ===

Version 8.7.8 (build 4)
Installation UUID: 33ba9349-a2e6-4f41-b8f4-0ead5fc49e6e
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000093

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.93 (2020-02/620cf538206) (64-bit)
	Package version: 612000093

=== Xamarin Designer ===

Version: 16.7.0.495
Hash: 03d50a221
Branch: remotes/origin/d16-7-vsmac
Build date: 2020-08-28 13:12:52 UTC

=== Roslyn (Language Service) ===

3.7.0-6.20427.1+18ede13943b0bfae1b44ef078b2f3923159bcd32

=== NuGet ===

Version: 5.7.0.6702

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.402/Sdks
SDK Versions:
	3.1.402
	3.1.401
	3.1.302
	3.1.301
	3.1.300
	3.1.202
	3.1.200
	3.1.102
	3.1.101
	3.1.100
	3.0.101
	3.0.100
	2.1.810
	2.1.701
	2.1.700
	2.1.505
	2.1.504
	2.1.503
	2.1.302
	2.1.301
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.8
	3.1.7
	3.1.6
	3.1.5
	3.1.4
	3.1.2
	3.1.1
	3.1.0
	3.0.1
	3.0.0
	2.1.22
	2.1.21
	2.1.20
	2.1.19
	2.1.18
	2.1.17
	2.1.16
	2.1.15
	2.1.14
	2.1.13
	2.1.12
	2.1.11
	2.1.9
	2.1.8
	2.1.7
	2.1.2
	2.1.1
	2.0.5
	2.0.0

=== Xamarin.Profiler ===

Version: 1.6.12.26
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.1 (17222)
Build 12A7403

=== Xamarin.Mac ===

Version: 6.20.2.2 (Visual Studio Enterprise)
Hash: 817b6f72a
Branch: d16-7
Build date: 2020-07-18 18:44:59-0400

=== Xamarin.iOS ===

Version: 14.0.0.0 (Visual Studio Enterprise)
Hash: 7ec3751a1
Branch: xcode12
Build date: 2020-09-16 11:33:15-0400

=== Xamarin.Android ===

Version: 11.0.2.0 (Visual Studio Enterprise)
Commit: xamarin-android/d16-7/025fde9
Android SDK: /Users/admin/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)
		7.1 (API level 25)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 29.0.3

Build Information: 
Mono: 83105ba
Java.Interop: xamarin/java.interop/d16-7@1f3388a
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@017078f

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/admin/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.7.0.13
Hash: 8380518
Branch: remotes/origin/d16-7~2
Build date: 2020-09-16 05:12:24 UTC

=== Android Device Manager ===

Version: 16.7.0.24
Hash: bb090a3
Branch: remotes/origin/d16-7
Build date: 2020-09-16 05:12:46 UTC

=== Build Information ===

Release ID: 807080004
Git revision: 9ea7bef96d65cdc3f4288014a799026ccb1993bc
Build date: 2020-09-16 17:22:54-04
Build branch: release-8.7
Xamarin extensions: 9ea7bef96d65cdc3f4288014a799026ccb1993bc

=== Operating System ===

Mac OS X 10.15.7
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Mon Aug 31 22:12:52 PDT 2020
    root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64

**Comment by chamons** [comment]
Reopening and adding to myself to review the new samples.

**Comment by motoko89** [comment]
@chamons did you get a chance to take a look at the samples?

**Comment by chamons** [comment]
I took a look today. There are some differences between your Swift and C#, and fixing one of them "fixes" your sample.

See

https://github.com/motoko89/test-ios14-bg/pull/1

**Comment by motoko89** [comment]
Thanks @chamons ! It works again. Not sure why it used to work before
